### ISSUE TITLE
Refactor Recurring Event Edit/Create page

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#1041]
### Overview
The design of the update recurring event functionality needs to be refactored to more closely align with the design from V.4.

### Action Items
-[ ] Add a list of recurring events to the project edit page - Below the project items to edit (name, description, etc) list all of the current recurring events.  (it does not need to list past events)
-[ ] Add an edit button/link to each of the events.  When the event is clicked, the user will be directed to a page with the option to edit the event.  That functionality currently exists on the editable meeting component. 
-[ ] Add a link to create new event at the bottom of the page 

### Acceptance Criteria
The new Project edit page will list the current recurring events with a link to edit each one.  There will also be a link to create a new recurring event. The page will be styled to look like the Figma. 

### Resources/Instructions
Project Edit Component
client/src/components/manageProjects/editProject.js
<details>
<summary>Project Edit Component</summary>
<img width="565" alt="Screen Shot 2022-01-31 at 1 31 40 PM" src="https://user-images.githubusercontent.com/68244054/151877463-eba4beab-eb74-460f-aab8-bd43269ea4a9.png">
</details>

Editable Meeting Component
client/src/components/manageProjects/editableMeeting.js
<details>
<summary>Editable Meeting Component</summary>
<img width="548" alt="Screen Shot 2022-01-31 at 1 39 52 PM" src="https://user-images.githubusercontent.com/68244054/151877721-8db87fc7-ab32-4d35-a01c-d3fe113f820b.png">
</details>

Create New Event Component
client/src/components/manageProjects/createNewEvent.js

Figma Design Detail
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23726%3A2254

<details>
<summary>FIgma Detail 1</summary>
<img width="275" alt="Screen Shot 2022-01-31 at 1 15 10 PM" src="https://user-images.githubusercontent.com/68244054/151877537-d13b11b8-1d02-47fe-8011-768d3c3915ca.png">
</details>

<details>
<summary>Figma Detail 2</summary>
<img width="423" alt="Screen Shot 2022-01-31 at 1 14 29 PM" src="https://user-images.githubusercontent.com/68244054/151877575-55335e1f-3f90-469b-be49-1fb055070171.png">
</details>

<img width="423" alt="Screen Shot 2022-01-31 at 1 14 29 PM" src="https://user-images.githubusercontent.com/68244054

**Comment by drubgrubby** [comment]
### Progress:
So far the only progress is assigning myself this issue today. 

### Blockers:
Taxes.  Having to do them.  Having to pay them is annoying, but not really a blocker. 

### Availability:
Whenever I'm not sleeping, or working on taxes.

### ETA:
TBD after I get into it, but let's say two weeks.

**Comment by drubgrubby** [comment]
### Progress:
None.  Nada. Zip. Zero

### Blockers:
I have a job interview tomorrow for a really cool PHP job.  So I spent the week re-learning PHP.  The interview is tomorrow and the blocker will be removed.  Then the only blocker is finishing my taxes, but who cares about that. 

### Availability:
Abundant

### ETA:
Next Monday

**Comment by FoxShaunR** [comment]
Progress:
Completed refactoring pass of existing components. Still need to address the action items above

Blockers:
None

Availability:
Available

ETA:
2/28

**Comment by FoxShaunR** [comment]
Progress:
Complete

Blockers:
None

Availability:
Available

ETA:
Awaiting approval
