### ISSUE TITLE
Dynamically name recurring events

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#1045]
### Overview
The recurring event "name" field is now being filled with boilerplate, not very useful, information. We want to create a dynamic naming of the event.  This will provide consistency, and reduce mistakes. 

### Action Items
- [ ] The 'create new event' component has a drop-down selector for 'Meeting Type' with the options of 'Team Meeting' and 'Onboarding'.  If the user selects "Team Meeting" they will be presented with a second drop-down with the following: 
All Team
Data Science
UI/UX Design
UI/UX Design & Research
UI/UX Research
Engineering All
Engineering Front End
Engineering Back End
PM
PM & Org
Other
- [ ] Once those two selections are made, create logic to fill the "name" and "description" fields.  The logic will be something like: 
Team Meeting -> All Team = VRMS All Team meeting 
Food Oasis -> Engineering All = Food Oasis Engineering All
- [ ] Remove the ability to edit the event name directly. The name can only be filled in the manner described above. 
- [ ] Add validation so that the new event cannot be created until both of these drop-downs have been selected. 

### Acceptance Criteria
The 'name' field in the event will be filled dynamically using dropdowns and business logic described above. 

### Resources/Instructions
Create New Event
client/src/components/manageProjects/createNewEvent.js

Note: The description field is currently being used as the name of the event for the display on the HfLA site: https://www.hackforla.org/events/.  We will currently fill the description field with the name of the meeting, but ultimately this field will be used to add further description to the meeting, e.g. Meets alternate Tuesdays

**Comment by jbubar** [comment]
@juliagab56 @JackHaeg is this issue irrelevant? Do we already have something tracking this?

**Comment by JackHaeg** [comment]
This issue will be handled via an alternate method described in this issue: https://github.com/hackforla/VRMS/issues/1404

**Comment by JackHaeg** [comment]
This issue will be handled via an alternate method described in this issue: https://github.com/hackforla/VRMS/issues/1404
