### ISSUE TITLE
Style Project Management Component

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#1049]
### Overview
The component was built with minimal styling.  There were styles created for vrms that, while not for these exact pages, can be used as a model for styling these pages. 

### Action Items
-[ ] Style the page to more closely resemble the figma (see below). (The figma was built for showing all of the events, not just the recurring events, so the page doesn't need to look exactly like this, but rather in this style).

### Acceptance Criteria
The styling of this component will be aligned with that in the figma file below

### Resources/Instructions
Project Edit Component
client/src/components/manageProjects/editProject.js
<details>
<summary>Project Edit Component</summary>
<img width="565" alt="Screen Shot 2022-01-31 at 1 31 40 PM" src="https://user-images.githubusercontent.com/68244054/151877463-eba4beab-eb74-460f-aab8-bd43269ea4a9.png">
</details>

Editable Meeting Component
client/src/components/manageProjects/editableMeeting.js
<details>
<summary>Editable Meeting Component</summary>
<img width="548" alt="Screen Shot 2022-01-31 at 1 39 52 PM" src="https://user-images.githubusercontent.com/68244054/151877721-8db87fc7-ab32-4d35-a01c-d3fe113f820b.png">
</details>

Create New Event Component
client/src/components/manageProjects/createNewEvent.js

Figma Design Detail
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23726%3A2254

<details>
<summary>FIgma Detail 1</summary>
<img width="275" alt="Screen Shot 2022-01-31 at 1 15 10 PM" src="https://user-images.githubusercontent.com/68244054/151877537-d13b11b8-1d02-47fe-8011-768d3c3915ca.png">
</details>

<details>
<summary>Figma Detail 2</summary>
<img width="423" alt="Screen Shot 2022-01-31 at 1 14 29 PM" src="https://user-images.githubusercontent.com/68244054/151877575-55335e1f-3f90-469b-be49-1fb055070171.png">
</details>

<img width="423" alt="Screen Shot 2022-01-31 at 1 14 29 PM" src="https://user-images.githubusercontent.com/68244054

**Comment by jbubar** [comment]
Finally started on this!
What i did: got vrms running and started styling
What I still have to do all the styling

**Comment by jbubar** [comment]
Whats the plan with this josh?

**Comment by jbubar** [comment]
will look at this at the next dev meeting

**Comment by jbubar** [comment]
Issue is no longer relevant
