### ISSUE TITLE
Meeting time change request for [Civic Tech Jobs]

### ISSUE THREAD

**Issue by sdimran** [hackforla/VRMS#1058]
### Overview
We need to add/change the team meeting time for [Civic Tech Jobs] so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

- Civic Tech Jobs, Team Meeting, Tuesday 5pm, 1 hour
- Civic Tech Jobs, UX/UI Meeting, Tuesday 6pm, 1 hour
- Civic Tech Jobs, Developer Meeting, Tuesday 6pm, 1 hour
- Civic Tech Jobs, Management Meeting, Sunday 12pm, 1hour

### What is your project page URL?
https://www.hackforla.org/projects/civic-tech-jobs

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #civictechjobs
Slack @handle: @s.danish.imran
<hr />

**Comment by drubgrubby** [comment]
@sdimran -> I have added the CTJ team meetings to the database.  Can you please check and confirm that they are correct?  Thanks. 

https://www.hackforla.org/events/

**Comment by drubgrubby** [comment]
Hearing no response I assume they are correct and am closing the ticket.
