### ISSUE TITLE
Make user.email field unique in production database

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#1065]
### Overview
The user.email field in the Production database is not a unique field, which allows duplicate accounts to be created. (That is, two accounts with identical email addresses).  

### Action Items
- [x] Make like 17 backups of the production database. (One will probably be enough, but you get my point I hope). \

Option 1 (if it's not too much of a pain)
- [ ] Append something to the duplicate users' email addresses so that they are now all unique, but only one is a functional email address. ex. g@google.com, g@google.com.dup1, g@google.com.dup2, etc

Option 2
- [x] Make a copy of the users table (users.copy).  This will allow us to go back and look at the data from duplicate users later if we need. 
- [x] Remove duplicate users (that is, users with the same email address) from the database. 

Then...
- [x] Make that field unique

### Resources/Instructions
Production database login: 
mongodb+srv://testuser2:Riy4gVoo3RYzLJEB@cluster0-haogu.mongodb.net/db?retryWrites=true&w=majority

**Comment by FoxShaunR** [comment]
Created a backup of the users table "users_with_dupes", deleted all duplicates, and created a unique index based on the email field.
