### ISSUE TITLE
Project name should be non-null and shouldn't be empty string or whitespace; UX is affected

### ISSUE THREAD

**Issue by evanyang1** [hackforla/VRMS#1069]
In `[URL]/projects`, projects with empty strings or white space are camouflaged 

See `/backend/models/project.model.js` and probably `client/src/components/manageProjects/ManageProjects.js`

**Comment by drubgrubby** [comment]
This may be fixed in https://github.com/hackforla/VRMS/issues/1041 .  If so, we can delete this issue.

**Comment by drubgrubby** [comment]
Fixed in #1041
