### ISSUE TITLE
Stay logged in for longer

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1080]
### Overview
As an admin you have to log in using the magic link (email), and then 10 minutes after you have to log in again. Could we investigate why this is happening and make it so that the admin can be logged in for longer?

### Action Items
- [ ] investigate why we get signed out
- [ ] discover a solution to have the browser remember the user for longer

**Comment by FoxShaunR** [comment]
Closing since we're going to move to v.4. Still nice to have for v.3 if Tim decides to reopen.
