### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by tmshkr** [hackforla/VRMS#1086]
### Overview
There are some serious security issues with the backend that make it so, e.g., anyone can make themselves an admin.

### Action Items
* Research security issues with backend.
* Determine whether to attempt to resolve the issues with the current backend, or choose another security strategy.

### Resources
* [NextAuth.js](https://next-auth.js.org/) could be used to easily add a secure and well-supported authentication strategy.
  * This approach would also require migrating to [Next.js](https://nextjs.org/).
* See this [Slack thread](https://hackforla.slack.com/archives/C0208S0GDFD/p1647721910266019) for more context

**Comment by JackHaeg** [comment]
@Spiteless & @jbubar Can we discuss this during our Monday meeting?

**Comment by trillium** [comment]
Hey @tmshkr , can you detail where the issue is happening here. We're trying to close this security flaw.
