### ISSUE TITLE
Create Roster component

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#109]
### Overview
As a project manager, I want to see a roster component on my homepage, so that I can see my team members and initiate onboarding for new team members.

### Action Items
- [x] Rachel to create Figma mockup & link to this issue
- [x] Create roster component
- [x] Issue #98 is about adding the component to the project manager dashboard

### Resources/Instructions
- When a team leader logs in during an active meeting, they see a list of who has checked in and whether those people are on the roster. For people not on the roster, they see a button "Start Onboarding" to kickoff the onboarding process for that person.
    - Might also be nice to show a % of team members in meeting, or something at the top
- When a team leader logs in NOT during a meeting, they see a list of project team members (can toggle between current/active, pending, and inactive).

**Comment by rachelwhaley** [comment]
@MasterBirdy - here's an initial (VERY rough) [mockup](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23345%3A98) of the Roster component for the during an active meeting piece. The NOT during a meeting piece would be similar, just having the Team Member Status be active, pending, or inactive.

**Comment by MasterBirdy** [comment]
Looks good! I updated my components accordingly.

**Comment by ExperimentsInHonesty** [comment]
@sarL3y mat needs to review.
