### ISSUE TITLE
Add Deployment info to readme

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1093]
### Overview
We have a bunch of open questions about deployment and if we could put all the information in one place, it would make it easier for everyone.

What we do know
- Development v0.3 frontend and api are on AWS through the github hub actions deployment written by @jasonwong26 and @darpham 
- our db is on MongoDB Atlas

What we believe but has not yet been confirmed
- current production is on someones heroku instance...

### Action Items
- [x] Find out more information about our deployment - done @FoxShaunR now has access to the aws account
    - [x] Get in touch with @ExperimentsInHonesty , or @alex-anakin 
- [x] figure out who has and can give access to the VRMS deployment on **AWS**
- [x] figure out who owns [Mongo db atlas](https://www.mongodb.com/atlas) account _***we think its hack for la_
- [x] Add mongo db atlas login info to 1password, if possible
- [x] Add current prod heroku info to 1password, if possible
- [x] How are the emails being sent? _***probably vrms.signup@gmail.com_ 
- [x] Who is the keeper of Mailhog? appears to be deployed to heroku

### Resources/Instructions
[Mongo db atlas](https://www.mongodb.com/atlas)
- one way to get in touch with bonnie is through the #admin channel on the slack with an explanation

**Comment by FoxShaunR** [comment]
Added as much info as I've discovered so far to the readme and wiki. Blocked as I currently need more info about the prod heroku account (or we just need to deploy prod to so we can not worry about it). And need to find out what the login info for mongodb atlas is.
