### ISSUE TITLE
Meeting name change request for Hackforla.org Website

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/VRMS#1098]
### Overview
We need to change the name for a team meeting for Hackforla.org Website so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

- Hackforla.org Website, Development Office Hours, Thursday 7pm, 1 hour 
(Note: The current name of the meeting on the live website is `Back-end Meeting` but I want it changed to `Development Office Hours`. This name change is the only change I want.)

### What is your project page URL?
https://www.hackforla.org/projects/website

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: hfla-site
Slack @handle: Jessica Cheng (she/her) 
<hr />

### Instructions
- [ ] For `Hackforla.org Website, Back-end Meeting, Thursday, 7pm, 1 hour`, change the name of the meeting to `Development Office Hours`

**Comment by FoxShaunR** [comment]
Updated name for the meeting. Meeting duration is actually 1.5 hours, not 1, but I left the duration as-is based on the other info in this ticket.
