### ISSUE TITLE
Build user profile page 

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#110]
### Overview
As a user, when I log in to VRMS, I want to see my profile information and edit/add info, so that I can be onboarded to a Hack for LA project. 

### Action Items
- [x] Rachel to complete Figma mockup of this & add link to this issue
- [x] Build user profile page
- [ ] ~~User should be directed to profile page after they check in or log in, if they are not a project manager~~
- [ ] ~~If user is a project manager, user should see an option to toggle to their profile page from their project dashboard~~

### Resources/Instructions
- User homepage should have 3 buckets/sections: profile info, "journey questions", and data (total # hours, etc.). This ticket is ONLY focused on the first bucket, profile info.

Fields on the user profile page should be (all should be editable unless stated otherwise):
- email 
- first name / last name / pronouns
- Github handle (and link to create a github if needed)
- Slack handle (link to instructions to join slack)
- Roles interested in (use list from the [survey](https://docs.google.com/forms/d/e/1FAIpQLScXnJSyCXgO_RCAuCyOkG4sqGILpAepTlJ0HOaK4H_ccEVmNw/viewform))
- Availability (use same format from the survey)
- Which hack night(s) they can attend (DTLA, Westside, South LA, and/or Remote)
- Team(s) where the user is an active project team member, and the next scheduled meeting for each of those teams (this part is not editable)
- Team(s) where the user is in the process of being onboarded, aka "pending" (this part is not editable)

Profile info should display everything they've entered in the onboarding survey, and make it editable for updates. (Or maybe this replaces the onboarding survey?)

**Comment by rachelwhaley** [comment]
Here's my initial (very rough) [Figma mockup](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23330%3A6)! @clockwerkz let me know if you have any trouble accessing that link.

**Comment by clockwerkz** [comment]
@rachelwhaley Yep, I can access it fine, thanks!

**Comment by clockwerkz** [comment]
Here's my first take on the mock up - I created a UserProfile component and did straight html. I'll add in some temp data and refactor it into components:
![user-profile](https://user-images.githubusercontent.com/11682523/79162585-6a47a980-7d92-11ea-9046-e600121a6f2a.PNG)

**Comment by ExperimentsInHonesty** [comment]
@clockwerkz 
1. Progress : going to break out into components.
2. Blocks: none other than availability
3. Availability: free next couple of days
4. ETA: done in a few days

**Comment by clockwerkz** [comment]
I went ahead and created the User Profile page component, and implemented a separate context to save the user. The Component is using temp data at the moment, will need to link up to the User Model in the future.

**Comment by ExperimentsInHonesty** [comment]
Closing this issue.  Will create a new issue for wiring it up.
