### ISSUE TITLE
When adding a project redirect to the project edit page

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1104]
### Overview
Currently when you add a project you can only add the name, then you have to go into the projects page, find the project and edit it. It would make more sense to immediately go to the project edit page

### Action Items
- [ ] Improve Routing so you can route to a specific project on the projects page
- [ ] After saving a new project on the add projects interface, redirect the user to the newly created project

**Comment by FoxShaunR** [comment]
Closing this as it will be included in v.4
