### ISSUE TITLE
Add an 'add a project' button on the projects page

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1105]
### Overview
It would make sense to have add a project button on the project page. currently, there is not add a project button on the project list page

### Action Items
- [ ] Add a button that goes to the create project page on the project page

**Comment by chukalicious** [comment]
@jbubar
Discussed with Shaun a problem I was having with this issue and we agreed that creating a button that links to the useradmin component will be enough for now. I will experiment another method at a later time. Maybe an issue can be created for that, too
