### ISSUE TITLE
Add Events Page Edit Button for Each Event

### ISSUE THREAD

**Issue by FoxShaunR** [hackforla/VRMS#1109]
### Overview
Add Events Page Edit Button for Each Event

### Action Items
- [ ] Add an edit button to each event (may be a separate issue)
    - [x] Pass a query parameter to project page indicating project id to open
    - [x] Update project page to check for query parameter and open corresponding project

**Comment by jbubar** [comment]
Future routing can be url/projects/:projectId?event=:eventId
