### ISSUE TITLE
Meeting time change request for UX Design in Hack for LA Website

### ISSUE THREAD

**Issue by phuonguvan** [hackforla/VRMS#1113]
### Overview
We need to add/change the team meeting time in Hack for LA Website so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Hack for LA Website, UX Design, Wednesday 2:30 PM, 1 hour

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

### What is your project page URL?
https://www.hackforla.org/projects/website

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: [hfla-site-ux](https://hackforla.slack.com/archives/C018FMQTWMT) 
Slack @handle: [```@Phuong Van```](https://hackforla.slack.com/team/U031MRNSLNS)
<hr />

**Comment by FoxShaunR** [comment]
Reached out to team to find out if they still need this updated
