### ISSUE TITLE
Use the Enter Key to sign in

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1118]
### Overview
Currently, if you click enter after typing in your email, it does not sign you in, you have to click the 'LOGIN' button

### Action Items
- [ ] figure out what happens when the button is clicked
- [ ] figure out what happens when the enter is pushed
- [ ] fix the logic for the enter
- [ ] maybe add some regex validation if there is not one

**Comment by evanyang1** [comment]
pressing "enter" has something to do with form submission (see HTML forms) and its default action. This is why we have `e.preventDefault()`

**Comment by evanyang1** [comment]
tried everything but couldn't fix it :(

**Comment by FoxShaunR** [comment]
Josh reached out to Evan to suggest ways to approach this
