### ISSUE TITLE
Automated deploy to dev

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1125]
### Overview
It would make sense to run our deployment gh-action when someone merges a pr into dev

### Action Items
- [ ] try out the gh-action
- [ ] change the trigger to be on pr being merged to dev

**Comment by FoxShaunR** [comment]
Reading through the existing deploy github action, it occurs to me that it would have been much easier to make this automatic by default. I messaged @darpham on Slack to find out the rationale behind the manual deployment before moving forward with this task

**Comment by jbubar** [comment]
This has already been done
