### ISSUE TITLE
Create an api endpoint to create a new github issue with the description in the request body.

### ISSUE THREAD

**Issue by FoxShaunR** [hackforla/VRMS#1129]
We would like to be able to create new issues by calling the github api from our own.

Here's documentation on getting started with the github api: https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api#repositories

Here's a library that may meet our needs: https://www.npmjs.com/package/@octokit/rest

Here's the documentation on authentication https://octokit.github.io/rest.js/v18#authentication We probably want to use the github apps auth method

**Comment by jbubar** [comment]
https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D


This is where we need the github issue to go

**Comment by jbubar** [comment]
No longer relevant
