### ISSUE TITLE
Meeting time change request for Access the Data

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/VRMS#1131]
### Overview
We need to add/change the team meeting time for Access the Data so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

Can we instead embed our Google calendar so that it is always up-to-date?
<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FLos_Angeles&title=Access%20the%20Data%20calendar&showPrint=0&showCalendars=1&src=YWNjZXNzdGhlZGF0YUBoYWNrZm9ybGEub3Jn&src=Y19kZHM1YjJlaTRuOTYxcHM0ajUwbGc1NXY1OEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&src=Y190ZDFqc2dvdm9kc25pcmd2dTk1aWk4ZWJob0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t&src=Y18ycmxjbzJmcTRiNXJqNGZrM2k0Mmw0b3Iyc0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t&src=Y18wc2NmZHFqa2ZzNjVwbmk2dGViaTN0YTc4MEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%234285F4&color=%23F6BF26&color=%2333B679&color=%239E69AF&color=%23E67C73" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>

### What is your project page URL?
https://www.hackforla.org/projects/access-the-data

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #access-the-data-leads
Slack @handle: @ajPrice
<hr />
### Instructions
Our calendar changes week-to-week.  If we could embed the calendar above instead that would be more helpful.

**Comment by AmandaGlover-PM** [comment]
Reached out to AJ to see if help is needed or if we can close the ticket.
