### ISSUE TITLE
Meeting time change request for [Project Name]

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#1137]
### Overview
We need to add/change the team meeting time for various projects so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Home Unite US, Management, Saturday 12:30pm, 1 hour
- Home Unite US, Team meeting, Tuesday 6pm, 2 hours

**Remove the following meeting times**
MONDAY
6:30 pm - 6:40 pm
[Not Today](https://www.hackforla.org/projects/not-today) (updates)

TUESDAY
7:00 pm - 7:50 pm
[Write for All™](https://www.hackforla.org/projects/writeforall)

WEDNESDAY
6:30 pm - 9:00 pm
[Undebate](https://www.hackforla.org/projects/undebate) Team Meeting

THURSDAY
4:00 pm - 5:00 pm
[Civic Opportunity Project](https://www.hackforla.org/projects/civic-opportunity-project) Meeting

SATURDAY
2:00 pm - 4:00 pm
[New Schools Today](https://www.hackforla.org/projects/new-schools-today)

SUNDAY
9:00 am - 10:00 am
[Civic Opportunity Project](https://www.hackforla.org/projects/civic-opportunity-project)
12:00 pm - 2:00 pm
[Hack for LA Marketing Team](https://www.hackforla.org/projects/website)

### What is your project page URL?
see links above

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: VRMS
Slack @handle: ```@Bonnie```
<hr />

**Comment by FoxShaunR** [comment]
Remove the following meeting times
MONDAY
6:30 pm - 6:40 pm
[Not Today](https://www.hackforla.org/projects/not-today) (updates)
Done

TUESDAY
7:00 pm - 7:50 pm
[Write for All™](https://www.hackforla.org/projects/writeforall)
Done

WEDNESDAY
6:30 pm - 9:00 pm
[Undebate](https://www.hackforla.org/projects/undebate) Team Meeting
Done

THURSDAY
4:00 pm - 5:00 pm
[Civic Opportunity Project](https://www.hackforla.org/projects/civic-opportunity-project) Meeting
Done

SATURDAY
2:00 pm - 4:00 pm
[New Schools Today](https://www.hackforla.org/projects/new-schools-today)
Done

SUNDAY
9:00 am - 10:00 am
[Civic Opportunity Project](https://www.hackforla.org/projects/civic-opportunity-project)
Done

12:00 pm - 2:00 pm
[Hack for LA Marketing Team](https://www.hackforla.org/projects/website)
Done
