### ISSUE TITLE
Meeting Descriptions not Displayed in Check-In Dropdown

### ISSUE THREAD

**Issue by JRHutson** [hackforla/VRMS#1141]
### Overview
Meeting times were updated but are all displaying with the same title in VRMS.
Is it possible to have the meetings distinguished in VRMS>

### Is your team meeting team already displayed on hackforla.org?
- [X] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
Home Unite US, Product Team, Monday 5:00pm, 30 min
Home Unite US, Team meeting, Tuesday 6:30pm, 30 min
Home Unite US, Engineering Team meeting, Tuesday 7:00pm, 1 Hour
Home Unite US, Design Team meeting, Tuesday 7:00pm, 1 Hour
Home Unite US, Product Owner Meeting, Friday 4:30pm, 30 min

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

What is your project page URL?

https://www.hackforla.org/projects/home-unite-us

Who should we contact on your team (via Slack) for user acceptance testing

Slack Channel #home-unite-us:
Slack @JRHutson:

**Comment by JRHutson** [comment]
Example of how meetings are currently being displayed.

![](https://user-images.githubusercontent.com/10876900/168946395-22ebeed7-6896-413c-8ae0-003474668950.png)

**Comment by FoxShaunR** [comment]
This is not a meeting time change request, it's an enhancement. The dropdown for checkins needs to display the description for the meeting as well as the event name to make it clear which meeting is being checked into

**Comment by JackHaeg** [comment]
This is no longer an issue with the current VRMS PROD build. Closing as unplanned.
