### ISSUE TITLE
'Close' button on "meeting details" needs to redirect user back to events page/"meetings list"

### ISSUE THREAD

**Issue by juliagab56** [hackforla/VRMS#1142]
### Overview
The button on the "meeting details" page doesn't work and when pressed it only toggles from the word 'open' and 'close' but isn't actually functioning. This button needs to take the user back to the events page where all the meetings are listed.

### Action Items
- [ ] Fix 'close' button to redirect user back to events page

REPLACE THIS TEXT - If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues or assigning it as a pair programming task.

### Resources/Instructions
REPLACE THIS TEXT - If there is a website that has documentation that helps with this issue provide the link(s) here.

**Comment by juliagab56** [comment]
https://user-images.githubusercontent.com/80308705/172936573-940aa301-83b9-445b-902e-8bbf6fdcc273.mov

**Comment by FoxShaunR** [comment]
Just need to remove close button. We have a back button now after a recent change
