### ISSUE TITLE
Locate user role documentation in the repo

### ISSUE THREAD

**Issue by chukalicious** [hackforla/VRMS#1147]
### Overview
The team needs clarification on the existing roles, their function and permissions granted

### Action Items

- [ ] Look for the roles in the documentation
- [ ] if they don't exist, create it

### Resources/Instructions
https://github.com/hackforla/VRMS/projects/6
https://github.com/hackforla/VRMS/projects/8
https://docs.google.com/document/d/1BlhtbYBbSBlwSKNFupqUwdtKiUluCErIt0Mr4vNzxlA/edit#

**Comment by juliagab56** [comment]
This could be resolved and closed after our meeting today with Adam and Bonnie.
