### ISSUE TITLE
Add a category of "project leads/admins" on the project details page

### ISSUE THREAD

**Issue by juliagab56** [hackforla/VRMS#1152]
### Overview
We want to display the leads/admins of a specific project in the details page of that project. It will be a field that the main admin can edit to add/remove leads.

### Action Items
- [x] figure out how to get the project admins (ideally in the back end) 
- [x] display a list of these project admins on the project page by creating an editable field that will hit the managedByUsers endpoint in the projects API
- [x] apply same user validation in the editable field as the rest of the editable fields (only authorized users can edit the field)
- [x] apply the comma separated format for these values

**Comment by chukalicious** [comment]
Hello team! This comment is regarding the first action item.

A call to the `api/projects` endpoint returns this project object: 

>         id: this._id,
>         name: this.name,
>         description: this.description,
>         githubIdentifier: this.githubIdentifier,
>         // owner: this.owner,
>         projectStatus: this.projectStatus,
>         location: this.location,
>         //teamMembers: this.teamMembers,
>         createdDate: this.createdDate,
>         completedDate: this.completedDate,
>         githubUrl: this.githubUrl,
>         slackUrl: this.slackUrl,
>         googleDriveUrl: this.googleDriveUrl,
>         googleDriveId: this.googleDriveId,
>         hflaWebsiteUrl: this.hflaWebsiteUrl,
>         videoConferenceLink: this.videoConferenceLink,
>         lookingDescription: this.lookingDescription,
>         recruitingCategories: this.recruitingCategories,
>         partners: this.partners,
>         managedByUsers: this.managedByUsers

I believe that last value, `managedByUsers` would provide an array of the project manager by project ID, but none of the projects in the database have any items in this array. So, I'm concluding for now that the project leads names are not in the database. At least not in this endpoint. 
I also looked in the users database to see the `managedProjects` value in the user schema and this array is also empty.

**Comment by FoxShaunR** [comment]
The projects api does not currently return a list of users managing the project. This fix requires updating the projects endpoint to return users assigned to it:  `users.managedProjects` (the managedByUsers field in the projects table does not appear to ever contain any user ids).
