### ISSUE TITLE
Meeting time change request for [Civic Tech Index]

### ISSUE THREAD

**Issue by kevindphan** [hackforla/VRMS#1160]
### Overview
We need to add/change the team meeting time for [Civic Tech Index] so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

-Civic Tech Index, Team Meeting, Monday 6pm, 1 hour
-Civic Tech Index, Team Meeting, Thursday 6pm, 1 hour
-Please delete Wednesday 12:30-1:30
Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

### What is your project page URL?
https://www.hackforla.org/projects/civic-tech-index

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: civic-tech-index
Slack @handle: Kevin Phan
<hr />

**Comment by ExperimentsInHonesty** [comment]
This project is on hold, so I have deleted all the meetings and am closing this issue
