### ISSUE TITLE
Get in touch with adam spar

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1161]
### Overview
We have a new design team who are ready to help us build v0.4 (our mvp for the vrms app)!!

Adam spar ([adamspar@gmail.com](mailto:adamspar@gmail.com)) is one of the og product people to have created v0.4 and we could use his guidance when filling the gaps for getting started on v0.4

### Action Items
- [x] Create a list of things to talk about with him
- [x] send him an email
    - [x] inform him of our meeting times 
    - [x] tell him about the team we have right now

### Resources/Instructions
REPLACE THIS TEXT - If there is a website that has documentation that helps with this issue provide the link(s) here.

**Comment by juliagab56** [comment]
An email was sent to Adam today.

>  Hi Adam, 
I am one of the UX designers on the Hack for LA VRMS project. I got your email from Josh who suggests that the design team speaks with you to get more information about VRMS.
Julia (cc’d here) and I just joined the team as UX designers. There are questions about the project that the development team cannot answer (e.g. needs, goals, features, etc.) We are hoping that we can schedule a chat with you so you can help us move the project from v3 to v4. Please let us know if you can help and when we can schedule this call.

**Comment by juliagab56** [comment]
We got in touch with Adam and had a meeting with him and Bonnie. The video recording can be found in the VRMS drive. High-level planning>Videos with stakeholder
