### ISSUE TITLE
Clean up dev folders on google drive

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1170]
### Overview
There's a lot of old files and we're not sure which ones are still relevant. We need to clean it up.

### Action Items
- [  ] Review google drive folder and archive old files

### Resources/Instructions
- [ ] https://drive.google.com/drive/u/0/folders/1uxCkpcPtDjrhftBO-axU2g8hjXsxiLiS

**Comment by FoxShaunR** [comment]
Done. Other than our environment variables, the development folder mostly just contained half-finished notes about features that have either been completed or abandoned.
