### ISSUE TITLE
User can type text into GitHub handle field

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1179]

**Comment by JackHaeg** [comment]
Evaluate if this is a duplicate of another issue, or if it needs to be rewritten.

**Comment by JackHaeg** [comment]
@heyitsalexander Hi Alex, did you mean to make this a separate issue for #1174? If not, can we remove / close this issue?

**Comment by JackHaeg** [comment]
Closing issue per discussion with Alex.
