### ISSUE TITLE
As a returning volunteer, I need to be able to check-in using VRMS, so that HforLA can keep track of my involvement and attendance.

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1182]
### Overview
As a volunteer, I need to be able to check-in using VRMS, so that HforLA can keep track of my involvement and attendance.

### Acceptance Criteria

- [ ] User can select project or event (e.g. onboarding, CoP) from drop-down list
- [ ] User can "check-in" to project selected.

### Action Items

- [x] #1200
- [x] #1213
- [x] #1214
- [ ]

**Comment by fyliu** [comment]
Looking at the figma file under "... v4 - final", the check-in process looks to be a notification displayed in the user's interface with a green button to check in. That design makes checking in very fast and convenient. It also assumes that users can only check in to events for projects/COPs they're members of, and maybe that's exactly what we want.

![2022-09-13 11 13 33 www figma com 45e2d3dfe103](https://user-images.githubusercontent.com/1160105/189979059-ca4dc9bd-e0dc-4ded-adff-ae079a4c1136.png)

Maybe clicking the Check In button will cause a new tab to open with the meeting's zoom link?

Okay, I just realized this is from the old v4 figma file. But it still clearly shows the user is meant to be logged in before they can check in to a meeting.

**Comment by ExperimentsInHonesty** [comment]
This issue needs to be re written to have requirements

**Comment by juliagab56** [comment]
@JackHaeg no updates since last comment

**Comment by JackHaeg** [comment]
This issue has a mix of conflicting comments. We, the product team, are determining that this was meant to be about checking in on the homepage of VRMS to meetings, which is not currently working.

**Comment by JackHaeg** [comment]
Issue #1411 details the bug, we are closing this issue as a duplicate.
