### ISSUE TITLE
Bring over the backend for meeting times from v0.3 to v0.4

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1183]
### Overview
It is time to port over our backend from v0.3 to v0.4. We are going to start with the meeting times endpoint

### Action Items
- [ ] Router
  - v0.3: https://github.com/hackforla/VRMS/blob/development/backend/routers/events.router.js
  - v0.4
- [ ] Model
  - v0.3: https://github.com/hackforla/VRMS/blob/development/backend/models/event.model.js
- [ ] Controller
  - v0.3: https://github.com/hackforla/VRMS/blob/development/backend/controllers/event.controller.js
- [ ] Add it to our https://github.com/hackforla/VRMS/blob/development-0.4/backend/src/app.js
   - _app.use().. etc._
- [ ] Test the endpoint using postman or insomnia
- [ ] Copy over the test files. 
- [ ] run the tests

### Resources
Nice little article to dip your toes in: https://www.bezkoder.com/node-express-mongodb-crud-rest-api/
^^ this is essentially what we are doing

**Comment by jbubar** [comment]
Closed this issue because we are not sure if we are going to do this or not...
