### ISSUE TITLE
Design Lo-fi User flow for User Story #1

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1193]
### Overview
As a Project Level Admin, I need to be able to create and edit meeting times, so that I can keep HackforLA events page up-to-date. 

### Action Items
- [ ] Create user flow to visualize user story #

### Resources/Instructions
- [Figma](https://www.figma.com/file/VlsfGn1qZOAzpDymDQoTiy/VRMS-V4-Old-Files-(this-page-is-for-reference-only)?node-id=23823%3A2353)
- [Style Guide](https://www.figma.com/file/2cwgCTKnLYl7OXhqsRZJsg/VRMS-Team-Library-%2B-Style-Guides?node-id=0%3A1)

**Comment by ExperimentsInHonesty** [comment]
There is another issue that is very similar to this.  So we are closing this #1197
