### ISSUE TITLE
Design lo-fi user story flows

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1195]
### Overview
User Story 1: As a Project Level Admin, I need to be able to create and edit meeting times, so that I can keep HackforLA events page up-to-date. 

User Story 2: As Bonnie, I need to be able to edit user access levels to different projects, so that different volunteers have different admin permissions.

User Story 3: As Bonnie, I need to be able to add a new project, so that I can manage all the activities going on within HforLA.

User Story 4: As a volunteer, I need to be able to check-in using VRMS, so that HforLA can keep track of my involvement and attendance.

### Action Items
- [x] Create user flow to visualize user story 1
- [x] Create user flow to visualize user story 2
- [x] Create user flow to visualize user story 3
- [x] Create user flow to visualize user story 4

### Resources/Instructions
[Figma](https://www.figma.com/file/VlsfGn1qZOAzpDymDQoTiy/VRMS-V4-Old-Files-(this-page-is-for-reference-only)?node-id=23823%3A2353)
[Style Guide](https://www.figma.com/file/2cwgCTKnLYl7OXhqsRZJsg/VRMS-Team-Library-%2B-Style-Guides?node-id=0%3A1)

**Comment by juliagab56** [comment]
https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?node-id=11%3A19
