### ISSUE TITLE
Design wireframe for user story 3

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1199]
### Overview
As Bonnie, I need to be able to add a new project, so that I can manage all the activities going on within HforLA

### Acceptance Criteria

- [ ] New user can create an account
- [ ] Returning user can enter login and password or email link (?)
- [ ] User can add new project

### Action Items

- [ ] Check Figma files to see if previous design can be recycled
- [ ] Sketch key screens
- [ ] Lo-fi Design
- [ ] Apply style guide to Lo-fi
- [ ] Design Hi-fi

### Resources/Instructions
[Figma](https://www.figma.com/file/VlsfGn1qZOAzpDymDQoTiy/VRMS-V4-Old-Files-(this-page-is-for-reference-only)?node-id=25405%3A2253)

**Comment by juliagab56** [comment]
Related to project form validation? Since it deals with the 'create a project' screens.

**Comment by juliagab56** [comment]
@JackHaeg is my understanding that project creation is a current feature Bonnie has access to. This issue can probably be closed or re-written as needed to include other UAL (User Acces Levels)

**Comment by juliagab56** [comment]
This feature is deployed and we are closing this issue
