### ISSUE TITLE
Design wireframe user story 4

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1200]
### Dependency

- [ ] #1411 

### Overview
As a volunteer, I need to be able to check-in using VRMS, so that HforLA can keep track of my involvement and attendance.

### Acceptance Criteria

- [x] New user can create an account
- [x] Returning user can enter login and password or email link (?)
- [x] User can select project or event (e.g. onboarding, CoP) from drop-down list
- [x] User can "check-in" to project selected.

### Action Items

- [ ] Check Figma files to see if previous design can be recycled
- [ ] Sketch key screens
- [ ] Lo-fi Design
- [ ] Apply style guide to Lo-fi
- [ ] Design Hi-fi

### Resources/Instructions
[Figma](https://www.figma.com/file/VlsfGn1qZOAzpDymDQoTiy/VRMS-V4-Old-Files-(this-page-is-for-reference-only)?node-id=25405%3A2253)

**Comment by juliagab56** [comment]
@JackHaeg These "User story" issues have become a bit complicated/entangled. I'm having a hard time discerning from all the info and multiple issues. 

This issue has irrelevant resources, the Figma file links to an archived file.

**Comment by juliagab56** [comment]
This is not working, we should be able to check-in to People Depot meeting but it's not showing up for us. Update resources.

**Comment by juliagab56** [comment]
As soon as the bug issue gets resolved this user story should be rechecked and if at a satisfactory level should be closed.

**Comment by JackHaeg** [comment]
Confirmed that check in is currently working.
