### ISSUE TITLE
Make the development-0.4 branch our main branch!

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1206]
_note: This can only be done by the owner of the repo.. or anyone who can see the settings tab on their github_

### Dependencies
https://github.com/hackforla/VRMS/issues/1205 - need to wait for this issue to be resolved

### Overview
We are making the transition to 0.4 and it will be time to make it our main branch very soon!!
We want to make it our main branch so that we can get those awesome dependabot pr's and so that new devs can have an easier time working on it. 

### Action Items
- [ ] Follow the guide below in the resources 

### Resources/Instructions
[guide](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch)

**Comment by JackHaeg** [comment]
I believe this is complete and can be closed, correct @jbubar ?

**Comment by jbubar** [comment]
We will not be doing this
