### ISSUE TITLE
Rename development to development-0.3

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1207]
#### Dependency
https://github.com/hackforla/VRMS/issues/1206 - need to wait for this issue to be completed

### Overview
Need change the name of the development branch to development-0.3, because we are switching our main branch to development-0.4

### Action Items
- [ ] follow the guide and rename the branch

### Resources/Instructions
[guide](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch)

**Comment by JackHaeg** [comment]
No longer required
