### ISSUE TITLE
Is Bonnie using v3 right now?

### ISSUE THREAD

**Issue by juliagab56** [hackforla/VRMS#1208]
### Overview
This is a question for devs or whoever knows the answer. 

### Action Items
- [x] Is Bonnie using v3 right now and to what extent?

### Resources/Instructions
REPLACE THIS TEXT - If there is a website that has documentation that helps with this issue provide the link(s) here.

**Comment by heyitsalexander** [comment]
Assigning @jbubar to best answer this question.

**Comment by heyitsalexander** [comment]
We found out that the current version of VRMS is not being used the way it should be given all the usability issues we discovered during our usability testing with Bonnie. The prioritized issues that we are fixing will address these.
