### ISSUE TITLE
Migrate Github Actions to Development v0.4 Branch

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1212]
### Overview
We need to migrate the existing Github Actions to Development v0.4 Branch. They are currently in the development branch.

### Action Items

- [ ] [New-issue-create-card.yml](https://github.com/hackforla/VRMS/blob/development/.github/workflows/New-issue-create-card.yml)
- [ ] [aws-backend-deploy.yml](https://github.com/hackforla/VRMS/blob/development/.github/workflows/aws-backend-deploy.yml)
- [ ] [aws-frontend-deploy.yml](https://github.com/hackforla/VRMS/blob/development/.github/workflows/aws-frontend-deploy.yml)

### Resource
Example on how to run on a single branch:
- [ ] https://github.com/hackforla/VRMS/blob/development-0.4/.github/workflows/v0.4-pull-requests.yaml

**Comment by JackHaeg** [comment]
Closing - in regard to v4 which we are not implementing.
