### ISSUE TITLE
Functions for mock user check-in

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1214]
### Overview
Functions for mock user check-in.

### Action Items
From Front-End:
- [ ] Create a function that will be replaced with People Depot eventually to create a check-in function (Parameters: Event_id, User_id)
- [ ] Create a function to return get all events mock response 
- [ ] Create a function to return get user by id mock response 

Resource:
https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/view?page=0_0#

**Comment by JackHaeg** [comment]
This currently has not been completed and a new issue will be made when People Depot database is available.
