### ISSUE TITLE
Meeting time change request for Food Oasis 

### ISSUE THREAD

**Issue by yiminng** [hackforla/VRMS#1216]
### Overview
We need to add/change the team meeting time for Food Oasis so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

ADD Food Oasis, Developer Meeting, Monday 6.30pm, 30 mins
ADD Food Oasis, PM Meeting, Tuesday 5pm, 1 hour
ADD Food Oasis, UXR Meeting, Tuesday 6:30 pm, 1 hour
DELETE Thu 6:00 pm - 7:00 pm Team Meeting
ADD Food Oasis, Leads and PM Meeting, Thursday 6pm, 1 hour
ADD Food Oasis, All Team Meeting, First Thursday of the month 6pm, 1 hour
ADD Food Oasis, Design Meeting, Thursday 7pm, 1 hour
Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

### What is your project page URL?
https://www.hackforla.org/projects/food-oasis 

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: fola
Slack @handle: Erin Dean
<hr />

**Comment by heyitsalexander** [comment]
@jbubar Could you take a look at this please?

**Comment by jbubar** [comment]
@yiminng for some reason, I cannot find food oasis in the data base. Is there any chance that it used to have a different name?

**Comment by heyitsalexander** [comment]
@jbubar Food Oasis may be under FOLA. Can we check that?

**Comment by itserindean** [comment]
For anyone working on this moving forward. @yiminng  has off boarded from Food Oasis so direct any questions for our team to me...

**Comment by staceyrebekahscott** [comment]
Food Oasis or FOLA's Meeting schedule is as follows: 

- Mon 6:30-7PM Development Team Meeting
- Every Other Tues 6:30-7:30PM UX Research Team Meeting
- Wed 5-6PM Product/ Project Team Meeting
- Thurs 10-11AM Content Team Meeting
- Thurs 6-7PM Leads/ PM Team Meeting
- Thurs 7-8PM Design Team Meeting
- 1st Thurs of Each Month All Hands Team Meeting

tagging @jbubar. Josh I don't think we're able to find Food Oasis in VRMS still. We might need to do this manually still. Could you take a look when you get a moment?

**Comment by jbubar** [comment]
Just added Food Oasis to the app. This will be done tonight

**Comment by jbubar** [comment]
![Screen Shot 2023-03-02 at 8 16 54 PM](https://user-images.githubusercontent.com/53061723/222630127-21909372-edea-4900-a8de-5f5fc319d1a6.png)

**Comment by MattPereira** [comment]
> Just added Food Oasis to the app. This will be done tonight

@jbubar is this issue completed?

**Comment by jbubar** [comment]
This is done
