### ISSUE TITLE
Removal of Fields of Project Information

### ISSUE THREAD

**Issue by AmandaGlover-PM** [hackforla/VRMS#1220]
### Overview
The following fields need to be removed from the front end so nobody can edit. 

- [x] googleDriveId
- [x] lookingDescription
- [x] recruitingCategories
- [x] videoConferenceLink

#### Potential Removal
- [ ] githubIdentifier

**Comment by JackHaeg** [comment]
All of these fields have been removed and are no longer available on the project management screen.
