### ISSUE TITLE
Update Flow for New Project Creation

### ISSUE THREAD

**Issue by AmandaGlover-PM** [hackforla/VRMS#1222]
### Overview

- [x] Confirm that users that can't add projects don't have a project button
- [x] Add project button when clicked by admin
- [x] On submission - they need to navigate to the new project page (already implemented)

### Question
What is the likelihood that you would need to batch multiple projects?
- unlikely because each project has a different description, most likely create a single project, click save and then create a new project separately.

**Comment by JackHaeg** [comment]
Issue needs cleanup (screenshots, create a new account add PM to People Depot shouldn't show add project button if not admin user level access, also move "on submission..." task to new issue - what should happen after submitting a new project - also check if screens are available from @juliagab56.)

**Comment by JackHaeg** [comment]
Closed as completed - current functionality meets these specifications already.
