### ISSUE TITLE
Add edit icon to each users' name on user search page

### ISSUE THREAD

**Issue by AmandaGlover-PM** [hackforla/VRMS#1225]
### Overview

As an Admin Level user (Bonnie), I want to know where to click after searching for a volunteers name, so I don't have to guess where to click to progress

When searching for a volunteer through the user management search function, there are no icons to guide the user through the process of selecting or adding the user. A simple icon next to name/email would help guide the user here.

### Action Items
- [ ] Add [icon] next to user management search results

### Acceptance Criteria
Scenario: Admin level user is searching for a particular volunteer to add to a project
GIVEN that the admin level user is on the User Management page
AND the volunteer has been successfully been onboarded
WHEN the user searches for a volunteer's information by name or email
THEN user should see corresponding volunteer information with an icon next to each search result indicating that it is clickable.

### Resources/Instructions

- [Zoom timestamp: 15:05]

<img width="553" alt="Screen Shot 2023-07-06 at 4 51 55 PM" src="https://github.com/hackforla/VRMS/assets/53061723/822373f4-ed96-43b3-a8e8-7aeaa08c6050">

- Usability Testing recording: https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq

**Comment by trillium** [comment]
- Pull request #1229 resolves this issue

**Comment by bkmorgan3** [comment]
I think better than placing an icon next to each returned result, The list of names should be more prominent.  The HTML needs to be restructured but that can make each list item bigger and give it hover states to indicate an item is clickable.  Reducing button size would be good too, to let users see a list has been rendered - but this can be its own issue.

@heyitsalexander  @MattPereira  @jbubar   @AmandaGlover-PM  Thoughts on this approach.

**Comment by juliagab56** [comment]
Redundant issues:
- #1237
- #1244

**Comment by JackHaeg** [comment]
- Closed issue #1244. 
- #1237 is not redundant to this issue.
- The PR referenced above #1229 is for a totally different issue

**Comment by JackHaeg** [comment]
There are tickets already prepared to manage the new user search page design.
