### ISSUE TITLE
Create a survey for Bonnie to gather more info about pain points and satisfaction level

### ISSUE THREAD

**Issue by juliagab56** [hackforla/VRMS#1227]
### Overview
We want to create a survey to ask Bonnie about pain points and what features she finds important to be able to prioritize those first.

### Action Items

- [x] Create a survey

### Resources/Instructions
REPLACE THIS TEXT - If there is a website that has documentation that helps with this issue provide the link(s) here.

**Comment by JudyLee533** [comment]
Survey is completed and results are recorded.
