### ISSUE TITLE
As a Admin-level user (Bonnie), I want to know where to click to edit meeting times, so that I can quickly make changes to meeting times

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1234]
### Overview
When tasked with editing meeting time, it wasn't clear to the user that "Recurring Events block" was clickable. The only way for user to know that it was a clickable item, was to hover over it. However, during testing, our user didn't hover over the block, so they had no idea how to edit the meeting time and needed guidance from VRMS team.

### Action Items
- [ ] Add a [edit icon] next to each meeting time. For example, if project has multiple events, each event should have an edit hyperlink next to it.
- [ ] Size and color should be consistent with existing [edit icon] hyperlinks

### Acceptance Criteria
Gherkin Syntax:
    Scenarios: All the actions a user could take (including bad input)
    GIVEN: Sets the context. What page are we on and what state are we in? Is the user an admin? Signed-in? Has created a campaign?
    WHEN: What actions the user is performing. What event occurred?
    THEN: What should the system do in response? What is the expected outcome?

Scenario: Admin level user is tasked to edit existing project meeting time
GIVEN: That the admin level user is on the Projects page
AND there is an existing meeting time
WHEN they go to edit existing meeting time
THEN there should be a clear [edit icon] next to corresponding meeting time that the user can click to edit meeting time.

### Resources/Instructions

- [Zoom timestamp: 20:54]

- <img width="453" alt="Screen Shot 2022-10-17 at 10 51 01 AM" src="https://user-images.githubusercontent.com/39230947/199864840-6158f4e4-d3a6-4bd7-851d-6ec313be7e36.png">

- Usability Testing recording: https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq

**Comment by jbubar** [comment]
@JudyLee533 do you want to provide evan with an icon to use?

**Comment by JudyLee533** [comment]
@jbubar See if you can download it.

![Edit_Icon](https://user-images.githubusercontent.com/107373945/205219056-6dd4e4ec-af2b-4f89-9f8c-8091f908edf4.svg)
