### ISSUE TITLE
As a Admin Level User (Bonnie), I want to know be able to tell what each tab on the navigation tab means, so I don't have to guess each time.

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1235]
### Overview
The existing navigation bar currently has 4 tabs: 1) Home, 2) Events, 3) Admin, 4) Projects. It is not very clear on what each tab provides for our users. To improve usability and simplify navigation, we need to rethink the nav bar.

The Home tab currently displays a "donut report" that is not very valuable to our user. This information under Home tab is not being actively used and is taking up valuable real estate on the nav bar.
The Events tab leads to a search function. While this feature is somewhat valuable, in its current form, it's not usable because it's taking too long to load. We will hide the Events tab for now.
The Admin tab leads to a page with two links: a) User Management, b) Projects. Clicking on User Management leads to page with an email search function, to then add a volunteers to a project. The Projects link is redundant as there is a separate tab just for Projects. To simplify our nav bar, we should rename the Admin tab to User (Management) tab that takes user directly to email search function.
Projects tabs is clear and functional. This should remain

### Action Items
- [ ] Hide Home Tab
- [ ] Hide Events Tab
- [ ] Rename Admin to User (Management) tab
- [ ] New User (Management) tab should lead directly to email search function

### Acceptance Criteria
Gherkin Syntax:
    Scenarios: All the actions a user could take (including bad input)
    GIVEN: Sets the context. What page are we on and what state are we in? Is the user an admin? Signed-in? Has created a campaign?
    WHEN: What actions the user is performing. What event occurred?
    THEN: What should the system do in response? What is the expected outcome?

Scenario: Admin level logs into VRMS
GIVEN: That the user has Admin level access
WHEN they log on to their VRMS account
THEN the navigation bar should have a) User (Management) tab and b) Projects tab
AND User (Management) tab should lead directly to emails search function

### Resources/Instructions
Zoom time stamp [20:57]
Zoom recording - https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq
<img width="508" alt="Screen Shot 2022-11-02 at 5 38 27 PM" src="https://user-images.githubusercontent.com/39230947/199867396-36600111-1099-47a0-a473-b1f2bec9888a.png">

**Comment by JudyLee533** [comment]
@Spiteless See new designs

<img width="1920" alt="Issue 1235 - Fonts" src="https://user-images.githubusercontent.com/107373945/203166488-c5506558-80ed-4699-81a8-a836167464ea.png">
<img width="1920" alt="Issue 1235 - Original vs  Updated" src="https://user-images.githubusercontent.com/107373945/203166495-96f2f5df-bf23-4daf-b9a0-f0e48b93f882.png">

**Comment by trillium** [comment]
I've been working on this over the past two days. Excited to show it off!

**Comment by heyitsalexander** [comment]
@Spiteless Excited to see it! Let me know when it's ready to go so we can reserve some time during a Monday meeting.

**Comment by juliagab56** [comment]
@JackHaeg @jbubar I believe this has already been implemented thus we can QA this issue and close it. I put it in the correct column on the board for PMs

See current
<img width="516" alt="Screenshot 2023-07-05 at 11 41 47 AM" src="https://github.com/hackforla/VRMS/assets/80308705/e43713d9-18a0-48ad-aa24-0054620b8e29">
