### ISSUE TITLE
As a Admin-Level User (Bonnie), I want to minimize the number of misclicks and errors, so that I can use VRMS for efficiently

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1237]
### Overview
Currently, some of the buttons that are not critical for a particular user task are oversized and prominent, while critical icons/buttons are very small. This mismatch between the sizes and importance of buttons is leading to a lot of user errors and misclicks. 
Specifically, in [16:10], the buttons for [Add Project], [Back to search], [Admin Dashboard] seem oversized compared to the text size for Name, Email, Projects.

### Action Items
- [x] UX/UI to rethink size:importance ratio of icons
- [x] Make size consistent throughout VRMS to reflect new parameters

### Acceptance Criteria
Scenario Admin level logs into VRMS
GIVEN that the user has Admin level access and is on the [Admin] tab
WHEN they go to either [add] or [remove] a volunteer from a project
THEN user shouldn't be any confusion on which buttons to click to perform those tasks.    

### Resources/Instructions

<img width="341" alt="Screen Shot 2022-11-09 at 2 54 51 PM" src="https://user-images.githubusercontent.com/39230947/200959695-5f1601c0-5647-4e93-8e91-ca43e63a2361.png">

Zoom time stamp [16:10]
Zoom recording - https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq
<img width="508" alt="Screen Shot 2022-11-02 at 5 38 27 PM" src="https://user-images.githubusercontent.com/39230947/199867396-36600111-1099-47a0-a473-b1f2bec9888a.png">

**Comment by JudyLee533** [comment]
<img width="1920" alt="Issue 1237 - Original vs  Updated" src="https://user-images.githubusercontent.com/107373945/215602335-e3c2c00d-e8f5-4319-93d0-2477ae59bfd8.png">

**Dev Team to Review**

**Comment by juliagab56** [comment]
This is done and functional
