### ISSUE TITLE
Connect and populate Projects and Team Members

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#124]
### Overview
We recently added Projects and Project Team Members to the data model - need to connect them to the live database and populate with real data.

### Action Items
- [ ] @ExperimentsInHonesty to get us the spreadsheet of projects and project leaders
- [ ] @MasterBirdy and @rachelwhaley to connect on creating the routes and uploading the project data to MongoDB
- [ ] Upload spreadsheet to MongoDB and ensure that everything populates correctly - need to make sure project leaders have user records and are linked to their projects

### Resources/Instructions
- List of project data that Bonnie will get us in spreadsheet form is located [here](https://github.com/hackforla/website/tree/gh-pages/_projects)
- Do all project leaders have user records?

**Comment by sarL3y** [comment]
Progress: @sarL3y is populating the project collection in the DB and testing the `.populate() ` functionality.
ETA: ASAP/tomorrow 5/19
Blocks: n/a
Availability: Yes

**Comment by sarL3y** [comment]
Progress: Projects collection has been populated. Next step is to "join" events with their associated project

**Comment by ExperimentsInHonesty** [comment]
@rachelwhaley 
1. Progress - partial ready 
2. Blockers - needs time with Matt
3. Availability - time this week
4. ETA - a couple of hours after blocker resolved.

**Comment by ExperimentsInHonesty** [comment]
@rachelwhaley
1. Progress - partial ready
2. Blockers - needs @sarL3y to make @rachelwhaley @ExperimentsInHonesty have admin access to Mongo DB
3. Availability - time this week
4. ETA - a couple of hours after blocker resolved.

**Comment by sarL3y** [comment]
Admin access granted

**Comment by ExperimentsInHonesty** [comment]
1. Progress: none this week
2. blocks - no avail
3. availability - some this week
4. ETA, a couple of hours

**Comment by rachelwhaley** [comment]
1. Progress: Completed test load of 11 users/project team members for the TDM project, for demo purposes. 
2. Blocks:  Waiting for feedback from devs - before I do a real load, want to make sure the data in the testdb is working as expected.
3. Availability: weekend
4. ETA: once the test load looks good, will probably take a few hours to clean data to do the full real load, connect to existing users, etc., so we'll need to schedule that when we're ready.

**Comment by ExperimentsInHonesty** [comment]
Let's go live with HomeUniteUs and HfLA website team.  - @ExperimentsInHonesty will clean the roster.

**Comment by ExperimentsInHonesty** [comment]
1. Progress: None
2. Blocks: time
3. Availability : Monday night after meeting
4. ETA: By end of monday night.

**Comment by alex-anakin** [comment]
This task is obsolete now.
