### ISSUE TITLE
As an Admin Level User (Bonnie), I want my forms to have validation when filling out project details, so that they're more accurate - UI

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1245]
### Overview
Currently, the projects details form doesn't have any validation. It increases onboarding time because user needs to go back and frequently correct typos (UI)
**Validation will be made into a separate issue

The project’s form fields need data validation, as opposed to them being free text fields.
Updated form should look as follows:    

- [ ] Name: Add validation with criteria - no duplicates, minimum 4 characters, allowable symbols: "- , ' " numbers, letters"

- [ ] Description: criteria - Max 250 characters

- [ ] Location: dropdown to preselected options
    a) Remote: links will be provided on the events of each project
    b) In-person: a field appears to add an address

- [ ] Github identifier: add in validation - developers to find out the best way to validate (good question, but edge case -- What if there’s multiple repos?) 

- [ ] Github URL: add in validation -- https://www.github.com/[example or project name] - this will be a placeholder that will allow the user to copy and paste the final URL.  Placeholder will be red if it is incorrect. Developers to find the best way to validate. 
- [ ] Slack URL: add in validation -- https://www.slack.com/[          ]  - this will be a placeholder that will allow the user to copy and paste the final URL.  Placeholder will be red if it is incorrect. Developers to find the best way to validate. 

- [ ] Google Drive URL: add in validation -- https://drive.google.com/[          ] - this will be a placeholder that will allow the user to copy and paste the final URL.  Placeholder will be red if it is incorrect. Developers to find the best way to validate. 
- [ ] HFLA Website URL: add in validation -- https://www.hackforla.org/[          ] - this will be a placeholder that will allow the user to copy and paste the final URL.  Placeholder will be red if it is incorrect. Developers to find the best way to validate. 

- [x] Google Drive ID: Needs to be removed

- [x] Video Conference Link: Needs to be removed

- [x] Looking for description: Needs to be removed

- [x] Recruiting Categories: Needs to be removed

### Discussion 
- Error message: Generic error message "Doesn't fit criteria"
- 
### Resources/Instructions
REPLACE THIS TEXT - If there is a website that has documentation that helps with this issue provide the link(s) here.

**Comment by JudyLee533** [comment]
<img width="2730" alt="Issue1245 Updated Screens with Annotations" src="https://user-images.githubusercontent.com/107373945/214715448-023223ad-0574-4eb2-9c58-458d5a61f55b.png">

Dev Team - please review

**Comment by heyitsalexander** [comment]
@JudyLee533 Dev team is asking if there's a good reason we need an edit button next to every field? @bkmorgan3 noted that it would be easier if we just had one edit button to toggle in between an "edit mode" vs "publish mode".
Maybe there can be a global edit button on the top right where the "+ Add New Project" is? Thoughts?

**Comment by JudyLee533** [comment]
@heyitsalexander I kept the edit icons because I was not sure the original intention behind the edit links next to each field since there were no previous design documentations. I left them for now in case there is an important reason from previous discussions before my time. We should ask Bonnie / PMs at the next round of user testing to determine whether they have true values. 

From a UX perspective, I don't see why because users should be able to edit any of the fields while they are in that page and type over the information. Once they updated the desired fields, they simply click "save" and all information will be updated.
