### ISSUE TITLE
Meeting time change request for Design Systems team

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/VRMS#1248]
### Overview
We need to add/change the team meeting time for Design Systems project so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

- Design Systems, All-hands meeting, Monday 5:30 pm, 1 hour and 15 minutes 
- Design Systems, UX/UI Design meeting, Thursdays 10:30 am, 1 hour (The previous meeting time must be deleted.)
- Design Systems, UX Research meeting, Wednesday 5 pm, 1 hour (The previous meeting time must be deleted.)

### What is your project page URL?
https://www.hackforla.org/projects/design-systems

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name:  Yas Roostaeian
Slack @handle: Yas Roostaeian
<hr />

**Comment by heyitsalexander** [comment]
@jbubar Hey Josh, I know we're off but could you take a look if you get a chance? Hope your holiday season is off to a good start!

**Comment by juliagab56** [comment]
Closing this issue since DS team is on hiatus and need time reorganizing their team/meetings
