### ISSUE TITLE
Add users to Google Drive

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#125]
### Overview
Project Leaders and Admins should be able to add a user to a project-specific Google Drive

### Action Items
- [x] Create button to grant access to a Google Drive
- [x] Create route on backend to hit Google API
- [x] Add Google Drive field to Project collection
- [ ] Update hard-coded email and google drive file id to test if front end is communicating with back end properly
- [ ] Wire up click handlers
- [ ] Send dynamic project info (email, googleDriveId) in props, test
- [ ] Move credentials into environment variables

### Dependencies
#124

**Comment by ExperimentsInHonesty** [comment]
@Jonathanko52 doing research on routes right now.
@MasterBirdy is doing the button (screen shots)

**Comment by MasterBirdy** [comment]
![screenshot](https://user-images.githubusercontent.com/1127804/79817552-976bfd00-833a-11ea-93f1-4fc16ef78cf2.jpg)

Picture of component for Project Leader Dashboard onboarding.

**Comment by ExperimentsInHonesty** [comment]
@sarL3y @rachelwhaley @switchzer0 lets talk about the separate buttons for checkin (which is really onboarding).

**Comment by Jonathanko52** [comment]
Progress: Tool: Working on sharing access to google drive of a given project. No access to github or google doc yet.
Blocks: Issues regarding authentication.
Availability: Pretty much every day.
ETA: Wednesday evening.

**Comment by Jonathanko52** [comment]
Progress: Figured out how to share files to users
Blocks: Access to vrms/hack for LA gmail account is necessary to set up the API and grant permissions to the drive.
Availability: Pretty much every day.
ETA: 5/11

**Comment by ExperimentsInHonesty** [comment]
will setup vrms-bot@hackforla.org and give @Jonathanko52 access.

**Comment by Jonathanko52** [comment]
Progress: Project leaders can now give users access to folders and files that VRMS bot has access to.
Blocks: ID's need to be set up in the collection/database
Availability: Pretty much every day.
ETA: ?

**Comment by sarL3y** [comment]
Progress: Requirements: Move credentials into environment variables. Receive dynamic project info in query (currently hard-coded).

**Comment by Jonathanko52** [comment]
Progress: Credentials moved to environment. 
Blocks: PR needs to be merged.
ETA: ?

**Comment by ExperimentsInHonesty** [comment]
update from @Jonathanko52 
1. Progress: pretty much done except for blocker
2. Blockers: Need to receive email address from backend (@sarL3y ??? or @rachelwhaley ???)
0
3. Availability: pretty much free
4. ETA: unknown due to blocker

**Comment by ExperimentsInHonesty** [comment]
@patrickgus will help @Jonathanko52 resolve blocker above.

**Comment by patrickgus** [comment]
Blocker is due to dummy data in db so @rachelwhaley can help resolve it when she has admin access.

**Comment by ExperimentsInHonesty** [comment]
@Jonathanko52 will provide more detail about blocker.

**Comment by Jonathanko52** [comment]
Progress: Need to find exact problem with issue: Whether front end call needs to be changed, router changed, env changed
Blocks: None
Availability: 24/7
ETA:  7/20

**Comment by Jonathanko52** [comment]
Progress: roster fetch call is being made with a hard-coded userId to a dummy group in the database
Blocks: Need to know what userId to be using instead, what group I SHOULD be showing on the roster board. Are we sticking to the dummy group for demo purposes? The actual VRMS group? Or jumping to using the project leader's ID when they sign in to the dashboard?
Availability: 24/7
ETA: ?

**Comment by rachelwhaley** [comment]
@Jonathanko52 I just uploaded a full team of users and project team members to the testdb in Mongo (for the TDM project, which I also added to the testdb). All the object IDs are in there so if you query for them you should get a list of 11 people with actual data (I edited all their emails to end in ".demo" so we can easily see that these are the tester records). So as long as we're demo'ing as one of the leaders of that project, should be able to use this "live" data.

**Comment by Jonathanko52** [comment]
Can now give access to roster members with google drive.

**Comment by alex-anakin** [comment]
#224 will help with this

**Comment by alex-anakin** [comment]
Obsolete
