### ISSUE TITLE
Meeting time change request for 311

### ISSUE THREAD

**Issue by EchoProject** [hackforla/VRMS#1253]
### Overview
We need to add/change the team meeting time for **311-Data.org** so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- 311-Data, Product Planning meeting, 1st Wednesday of the month 7 PM, 1 hour
- 311-Data, Team meeting, Wednesday 7 PM, 1 hour

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

- Fri 5:00 pm - 6:00 pm
Product Meeting

- Thu 6:30 pm - 7:30 pm
Team Meeting

### What is your project page URL?
https://www.hackforla.org/projects/311-data

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #311-Data 
Slack @handle: @eric Cho
<hr />
### Instructions
Please update 311-Data's project page with the new meeting time and delete the older times.

**Comment by AmandaGlover-PM** [comment]
Reached out to Eric to see if help is needed or if we can close this ticket.

**Comment by JackHaeg** [comment]
Complete - spoke with Edwin (311-Data Engineering Lead), and we confirmed & updated 311 meeting times on VRMS.
