### ISSUE TITLE
Meeting time change request for Access the Data (AtD)

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/VRMS#1262]
### Overview
We need to add the team meeting time for AtD so it will appear correctly on hackforla.org

### Is your team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

- Access the Data, PM, Tuesdays 2:00pm PT, 50 min
- Access the Data, Team, Wednesdays 5:00pm PT, 50 min

I don't currently see any meeting times listed on our page, but let me know if there is somewhere else on the HfLA site it would be and I can check it for updates needed.

### What is your project page URL?
https://www.hackforla.org/projects/access-the-data.html

### Who should we contact on your team (via Slack) for user acceptance testing
NOTE: AtD is on break until 2023.  Lucy and I will be back first on 3 January.

Slack @handle: @ajPrice and @LucyChang

**Comment by AmandaGlover-PM** [comment]
Reached out to AJ to see if they need help updating the meeting time or if we could close the ticket.

**Comment by AmandaGlover-PM** [comment]
Closing the ticket - note back from AJ - #1262 can be closed.   It was created last year and I have since used the new system to update the meeting times.
