### ISSUE TITLE
Request to add Content meeting for Expunge Assist

### ISSUE THREAD

**Issue by jamesshin27** [hackforla/VRMS#1269]
### Overview
Currently the content meeting for Expunge Assist doesn't show up on the project page. We need to add the team meeting title and time for Content so it will appear on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [X] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
Expunge  Assist, Content, Thursday 11:00 am PT, 60 min

### What is your project page URL?
https://www.hackforla.org/projects/expunge-assist

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #expunge-assist-pm-and-leads
Slack @handle: @James Shin

### Instructions
Please add Content meeting to Expunge Assist project page with its relevant information

**Comment by AmandaGlover-PM** [comment]
Reached out to James to see if help is needed or if we can close this ticket.

**Comment by JackHaeg** [comment]
Issue is closed after speaking with new PM, Analicia, who has updated the meeting times for Expunge Assist on VRMS.

**Comment by amejiamesinas** [comment]
Done.
