### ISSUE TITLE
Request to add Team Planning meeting for [Expunge Assist]

### ISSUE THREAD

**Issue by jamesshin27** [hackforla/VRMS#1271]
### Overview
Currently the Team Planning meeting for Expunge Assist doesn't show up on the project page. We need to add the team meeting title and time so it will appear on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [X] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

Expunge Assist, Team Planning, Monthly First Friday 10:30 am PT, 60 min

### What is your project page URL?
https://www.hackforla.org/projects/vrms

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #expunge-assist-pm-and-leads
Slack @handle: @James Shin
<hr />
### Instructions
Please add Team Planning meeting to Expunge Assist project page with its relevant information. It's a monthly meeting that happens on every first Friday of the month.

**Comment by AmandaGlover-PM** [comment]
Reached out to James to see if there is still help needed for this ticket.

**Comment by JackHaeg** [comment]
Issue is closed after speaking with new PM, Analicia, who has updated the meeting times for Expunge Assist on VRMS.

**Comment by amejiamesinas** [comment]
Done.
