### ISSUE TITLE
Update Admin Level Sign-in Flow - UI

### ISSUE THREAD

**Issue by JudyLee533** [hackforla/VRMS#1278]
### Overview
This issue relates to the UI update to the current user sign-in screens. The current process of signing in stays the same.

### Action Items

- [ ] Update all sign-in screens to the new fonts(and sizes) and top navigation bar.
- [ ] Replace the current landing page (after user signed-in) to the updated Project Management page. 

### Resources/Instructions
<img width="2882" alt="Sign-in Update_ Issue 1236" src="https://user-images.githubusercontent.com/107373945/214632542-a8d3d0d7-57e8-469c-97b1-cc3ac43a5273.png">

**Comment by JackHaeg** [comment]
We have users going to a landing page that does not have any data on it.
