### ISSUE TITLE
Update Event Data Model

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#128]
### Overview
As an admin, I want to be able to add an event start time and ensure that the event data model is clearly documented, in order to have a clear API for communication with the website team.

### Action Items
- [x] Confirm and clarify all event attributes
- [x] Clearly document attributes of event data model

### Resources/Instructions
Coordinate with website team to ensure that all needed attributes are present.

**Comment by ExperimentsInHonesty** [comment]
Current thinking
working with VRMS team on calendar. Waiting for data model from @sarL3y
template so farIdentification: (this is a number of the project)
Start Time: YYYY-MM-DDTHH:mm:ss.sssZ
End Time: YYYY-MM-DDTHH:mm:ss.sssZ
Meeting Name:
Meeting Description:
Meeting Type:
Meeting Location: (online, DTLA, SM, soLA)
Zoom Link:

https://github.com/hackforla/website/issues/385#issuecomment-609463483
