### ISSUE TITLE
Meeting time change request for Home Unite Us

### ISSUE THREAD

**Issue by randelbrot** [hackforla/VRMS#1284]
### Overview
We need to add/change the team meeting time for Home Unite Us so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [X] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

- Home Unite Us, Product Team Meeting, Monday 5:40pm, 30 minutes
- Home Unite Us, All Team Meeting, Tuesday 6:30pm, 30 minutes
- Home Unite Us, Design Team Meeting, Tuesday 7:00pm, 1 hour
- Home Unite Us, Engineering Team Meeting, Tuesday 7:00pm, 1 hour
- Home Unite Us, Product Owner Meeting, Friday 4:30pm, 30 minutes

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

### What is your project page URL?
https://www.hackforla.org/projects/home-unite-us

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: home-unite-us-pm
Slack @handle: Bryce Lednar
<hr />

**Comment by AmandaGlover-PM** [comment]
Reached out to Bryce to see if help is needed, if he could change the meeting time in VRMS or if help is needed.

**Comment by randelbrot** [comment]
I updated the meeting time via VRMS. I'll confirm that the change is reflected accurately on the HfLA website tomorrow and will close this issue then if it's no longer needed. Thanks!

**Comment by randelbrot** [comment]
The meeting time updates that I made via VRMS were reflected correctly on the HfLA website this morning so this issue is all set.
