### ISSUE TITLE
VRMS research Human Capital

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#129]
### Overview
Identify career development tools that may be of use to HfLA community members.  Tools to search for should be able to be used at various career life stages covering 7 decades. (Teens/20s/30s/40s/50s/60s/70s).

### Action Items
Perform Discovery into various career and skill building tool space to identify tools that may be of use.

### Resources/Instructions
post findings to VRMS Research board 
https://github.com/hackforla/VRMS/projects/1

**Comment by Rankazze** [comment]
Progress:  Tool: Job Posting Board.  I have been introduced to Code for America staff that have and are currently managing their Job Posting Board.  I have let them know that VRMS team is interested in using and customizing their code base if it is available to us.
Blocks:  None.
Availability:  Nightly after 6p
ETA: Ongoing

**Comment by Rankazze** [comment]
Progress: Tool: Job Posting Board. I have been introduced to Code for America staff that have and are currently managing their Job Posting Board. I have let them know that VRMS team is interested in using and customizing their code base if it is available to us.
Blocks: The two Code for America staff have not returned my email.  Giving them a bit of space since they announced new CEO.  The lead manager of the Job Posting Board is the Chief of Staff (he may be a bit busy with an on-boarding).  I follow up with them on Wed.
Availability: Nightly after 6p
ETA: Ongoing

**Comment by ExperimentsInHonesty** [comment]
@Rankazze  will follow up with Tom Dooner on CfA slack.

**Comment by Rankazze** [comment]
Progress: Tool: Job Posting Board. Gave them the benefit of the doubt with on-boarding a new CEO.  I reached out to the two staff members previously mentioned.  

I again reiterated that VRMS team is interested in using and customizing their code base if it is available to us.
Blocks: The two Code for America staff have not returned my second email. 
Future action:  I will now reach out to Tom Dooner as Bonnie has previously suggested.
Availability: Nightly after 6p
ETA: Ongoing

**Comment by Rankazze** [comment]
Progress: Tool: Job Posting Board. Reached out (DM) to Tom Dooner on the CfA slack letting him know of my previous attempts at contacting the people to whom I was referred within CfA.

I again reiterated that VRMS team is interested in using and customizing their code base if it is available to us.

Blocks: I have not yet heard back from Tom Dooner.  Additionally, neither of the the two Code for America staff have not returned my second email.

Future action: I will now reach out to Tom Dooner as Bonnie has previously suggested.

Availability: Nightly after 6p
ETA: Ongoing

**Comment by Rankazze** [comment]
Progress: Tool: Job Posting Board. Heard back from Tom Dooner, CfA.  Here is his reply to the request: "It’s not currently open source. We built it ourselves but it’s currently the code is not in a place where it’s possible for us to publish."

Blocks:  No blocks.

Future action: I will now conduct research to identify potential tool candidates for use.

Availability: Nightly after 6p
ETA: Ongoing

**Comment by juliagab56** [comment]
Outdated issue
