### ISSUE TITLE
Home page looks broken when no meetings happening

### ISSUE THREAD

**Issue by fyliu** [hackforla/VRMS#1292]
### Overview
As a volunteer, I get a confusing/uninformative page when I go to vrms.io at a time when there's no meeting scheduled. I would expect it to tell me there's no meeting right now. Maybe even include a link to the [Hack for LA meeting schedule](https://www.hackforla.org/events/) that I use to check my meeting time.

Anything is better than just showing a "CREATE NEW PROFILE" button. I actually went to fill in the form thinking maybe I need to re-register. But it tells me that the user already exists, so that leaves me with no possible action to do in the app and I'm not told that I should check back later when my meeting is actually happening.

### Action Items
- [x] #1515

### Resources/Instructions

Screenshots taken Thursday 11:39AM. There's no schedule meeting until 4PM
![2023-02-16 11 39 12 vrms io d4d177aad481](https://user-images.githubusercontent.com/1160105/219470353-ad295390-f495-4356-a899-14900db608ff.png)
![2023-02-16 11 39 30 www hackforla org b08c373f91e7](https://user-images.githubusercontent.com/1160105/219470364-7ee2dba9-73ed-486b-a57b-4ceb20a6aabf.png)

**Comment by juliagab56** [comment]
Issue needs to be rewritten and prioritized by PMs @JackHaeg @jbubar

**Comment by JackHaeg** [comment]
Issue broken down in: #1515. Closing current issue.
