### ISSUE TITLE
Update-navbar

### ISSUE THREAD

**Issue by plang-psm** [hackforla/VRMS#1307]
### Overview
We need to update the nav bar to the new layout displayed in #1236.

### Action Items
- [x] Update the nav bar to the new design.
- [x] Check off the issue in the epic.

<details open>
<summary>Proposed design:</summary>
<br>

![Nav bar desgin](https://user-images.githubusercontent.com/101952500/222876995-feaa5baa-5fc7-4041-919c-6b03351b517f.png)

</details>

### Resources/Instructions
#1236

**Comment by trillium** [comment]
This comment was meant to be added to #1308 
___

Pretty sure we're still on the 'working out the kinks' phase of integrating MUI, but MUI has a button type 'outlined' that fits the style guide without having to specifiy a new variant. Needs similar updating for border pixel thickness:

```js
variants: [
  {
    props: { variant: 'outlined' },
    style: {
      border: '2px solid',
      "&:hover": {
      border: '2px solid'
      },
    },
  },
],
```

```jsx
<Button color="secondary" variant="outlined">
```

<img width="495" alt="image" src="https://user-images.githubusercontent.com/5898009/223489614-1d633194-b236-4a97-85ac-ea602b036c28.png">

**Comment by MattPereira** [comment]
Hey @Spiteless 

I hear what you are saying and am open to discussing use of the `outlined` variant

The reason I named the custom button variant "secondary" was to match the style guide from the Figma

![image](https://user-images.githubusercontent.com/73561520/223597016-87526827-a6ab-413b-a59f-41c300404066.png)


https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?node-id=803-788

**Comment by trillium** [comment]
My bad, I added this comment to the wrong issue. Meant to comment on Pull Request #1308. Moving disuccion there.
