### ISSUE TITLE
Add color variables to MUI theme instead of hardcoding color values

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1327]
### Overview
Create a color palette within MUI's theme so that the dev team can use a color variables.

### Action Items
- [ ] Create a color variables file 
- [ ] Import color variables into MUI's theme
- [ ] Replace existing hard coded color values with variables from the color palette

### Resources/Instructions
* [theme.js example file](https://github.com/CollectiveFocus/CFM_Frontend/blob/dev/src/theme/index.js)
* [palette.js example file](https://github.com/CollectiveFocus/CFM_Frontend/blob/dev/src/theme/palette.js)
* [VRMS Style Guide](https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?node-id=5%3A3&t=zYXaUQyikZOpNk12-0)

**Comment by MattPereira** [comment]
@Spiteless I added a link in the Resources section of this issue to the figma so whoever works on this issue can find the colors

You should also add `size`, `feature`, and `role` labels when you create an issue. The labels will help us identify issues quickly and allow for more granular data analysis for future features. (I'm hoping to eventually build a points leaderboard feature that can be filtered by week/month/year/project ect. )

Maybe you could also include instructions for how we might go about naming our color variables? "Other" would be funny...

![image](https://user-images.githubusercontent.com/73561520/224452114-ed301ef8-55ea-4cb0-8410-459df880d924.png)

**Comment by trillium** [comment]
MUI has designations already for success and error, I interpreted the red and green to go along with those. Hopefully that's the right choice!
