### ISSUE TITLE
Usability Testing #2 with Bonnie

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1335]
Here you go @bonniewolfe 
   
   - [ ] Usability Testing Video (https://drive.google.com/file/d/1KBcMbdwVtjXTlIf3P6j0ecvHSc7i1vWt/view?usp=share_link)
   
   - [ ] Post Test Survey (https://forms.gle/BnDNHKyDZB4Aw6PT8)

**Comment by ExperimentsInHonesty** [comment]
I have finished taking the survey.
