### ISSUE TITLE
Adding new welcome page and allowing admin dashboard access from navbar

### ISSUE THREAD

**Issue by MattPereira** [hackforla/VRMS#1353]
### Overview
Our stakeholder has requested that we create a new welcome page for users to land on after clicking the magic link sent to their email. Additionally, we will add the admin dashboard page component to the nav-bar.

### Action Items
- [x] Create a new welcome page component in the `src/pages/` folder called `UserWelcome.js`
- [x] Greet the user with a friendly message and offer them this link to the vrms User Guide wiki `https://github.com/hackforla/VRMS/wiki/User-Guide`
- [x] Add another button to the `Navbar.js` component that links to the `/admin` route ( follow same pattern as other buttons )
- [x] Add a link to the logo so that it navigates users to `/` path if not logged in or `/weclome` if they are authenticated

### Instructions
- When a user clicks the magic link, it should take them directly to the new welcome landing page
- This is the only time the user will have access to the welcome page

### Resources
- https://github.com/hackforla/VRMS/blob/development/client/src/components/Navbar.js

**Comment by trillium** [comment]
A common pattern on other sites is that the logo is also a link to wherever the user lands after login.

Suggest we link to the new UserWelcome page when HFLA logo is clicked.

**Comment by MattPereira** [comment]
@Spiteless not a bad idea

I set it up so that if a user is logged in, clicking the hfla logo will take them to the welcome page as you suggested

If a user is not logged in, clicking the logo will take them to the root "/" path
