### ISSUE TITLE
Form Validation - Event Link

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1364]
### Overview
Currently, the Recurring Event add/edit screen does not have any validation for the Event Link. Zoom or Google Meet links must be validated so that users know what to insert into the field and inputs are uniform across all projects. 

### Action Items:
- [x] Add validation and error messages to Event Link field.
- [x] Error message should be in red below the field
- [x] #1513

### To replicate:
1. Go to a project
2. Under Recurring Events, click "Create New Event"
3. See "Event Link"
4. Try adding a test event (don't forget to name it "test")
     1. Event name required
     2. Event Type required
     3. Day of the Week required
     4. Start Time required
     5. Duration required
     6. Description is optional
     7. Event link required

### Validation:
- https://
- [x] #1511
   - meet.google.com/
   - zoom.us/

### Placeholder message: 
- User should be changed from "Enter meeting url..." to: "Insert Zoom or Google Meet Link" 

### Error message: 
- "Your link must start with https://" (if link does not include "https://")
- "This does not look like a valid Zoom or Google Meet link" (if link does not include: "meet.google.com/" or "zoom.us/")

<img width="612" alt="Screenshot 2023-08-03 at 6 43 10 PM" src="https://github.com/hackforla/VRMS/assets/134463646/d033aa12-69e7-4694-aa10-f639b0ca9e35">

**Comment by heyitsalexander** [comment]
@MattPereira not sure what the best way to add in some form of validation here for zoom links would be?
Sample Zoom link: https://us02web.zoom.us/j/87300266029?pwd=OUc0NFRoV2piWmp6TWZMMVE2Nk9NQT09

Could we add in a requirement so that the link has to start with https://us02web.zoom.us/* ?
If validation for all these fields is going to be too complicated, we can just stick with the placeholder text to help guide our users.

**Comment by MattPereira** [comment]
> Could we add in a requirement so that the link has to start with https://us02web.zoom.us/* ?

@heyitsalexander Yes this is possible but im not sure if zoom moves around the `02` or some other part of the url so it could potentially cause problems down the road if zoom changes url or another org has meetings that are like `https://us06web.zoom.us`

Off top of my head safest option zoom link might be just making sure the string entered contains `zoom.us`

**Comment by jbubar** [comment]
Here is a pr that is not going to be merged that has some useful code on it for this validation
- https://github.com/hackforla/VRMS/pull/1425

**Comment by JackHaeg** [comment]
Still need to add validation for: 
- meet.google.com/  either/or zoom.us/

**Comment by JackHaeg** [comment]
Closing as planned, covered by other tickets.
