### ISSUE TITLE
Update /secretpassword

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1365]
### Overview

Update /secretpassword

### Action Items

 - [ ] Make validation not case sensitive
 - [ ] Do not show word
 - [ ] Remove copy button
 - [ ] Update instrucitons wording
   - [ ] Add second paragraph

**Comment by ExperimentsInHonesty** [comment]
Great job! You found the secret password

You can now return to the onboarding instructions.

When later asked for the password, in the onboarding form, use the password you just validated.

**Comment by Rabia2219** [comment]
![image](https://user-images.githubusercontent.com/75643389/228360084-17661207-eff5-49ed-bbe3-ac226cc441c6.png)
