### ISSUE TITLE
Add an "isActive" field to the user model

### ISSUE THREAD

**Issue by MattPereira** [hackforla/VRMS#1374]
### Overview
Our stakeholder has requested that we implement a feature that allows admin users to mark other users as inactive. For this issue, we will update the database schema and add a button that toggles a user's `isActive` status.

### Action Items
- [x] Add the new key/value pair to the `userSchema` in the `user.model.js` file
    - `isActive: { type: Boolean, default: true }`
- [x] Show the active status of a user on the user details page 
- [x] Add a button on the user details page that toggles the active status between `true` and `false`
- [ ] Notify people depot about this modification to the database schema

### Details
- The default state of a newly created user will be `isActive: true`
- Allow admin users to manage the `isActive` status of a user via the user details page

### Resources
- https://github.com/hackforla/VRMS/blob/development/backend/models/user.model.js
- https://github.com/hackforla/VRMS/blob/development/client/src/pages/UserAdmin.js
<details><summary>See screenshot of user details page</summary>

![image](https://user-images.githubusercontent.com/73561520/228350977-22c028af-5cf1-4e90-80da-ac1197d104c4.png)

</details>

**Comment by ExperimentsInHonesty** [comment]
@bkmorgan3 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by bkmorgan3** [comment]
@ExperimentsInHonesty 
I haven't gotten to this but I can pick it up soon.  
I had another PR up and another PR I reviewed that brought up a lot of questions with the team. I also just got my computer back from a repair so getting everything re installed and up and running.
