### ISSUE TITLE
Rearrange order of Add New Project Form

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1379]
Background-
Bonnie would like to see the add new project fields in the following order: 

1. Project name
2. Project description
3. Location (remote radio button default)
4. Github URL
5. Github Identifier
6. Slack Channel Link (previously Slack URL)
7. Google Drive URL
8. HFLA Website URL

**Comment by MicahBear** [comment]
- #1325 completes this issue.
- And #1325 fixed the original issue #1245.
- labels added to this issue that matched 1325. size label adjusted to reflect this one issue versus the size of 1325.
- [This comment explains why GitHub identifier is not on the project form now](https://github.com/hackforla/VRMS/pull/1325#issuecomment-1465307269)
- #1383  Meets the Rename Slack Channel Link -> Slack Channel Url
