### ISSUE TITLE
Protected Routes

### ISSUE THREAD

**Issue by MasterBirdy** [hackforla/VRMS#138]
### Overview
Users should only be able to see routes authorized for user level, project leaders should be able to see both user level and project leader routes, and admins should be able to see all routes.

### Action Items
- [ ] Move conditional rendering logic out of individual components
- [ ] Create Auth Context that stores current user access level
- [ ] Create protected routes through a component that wraps routes and checks for auth level

**Comment by ExperimentsInHonesty** [comment]
@MasterBirdy can you move this issue to the appropriate column on the project board?

**Comment by sarL3y** [comment]
Progress: Protected routes will affect other features that are currently in development. Pieces will be falling in place shortly. 
Blocks: Project Leader Dashboard, User Profile, Admin dashboard
Availability: N/A
ETA: Waiting for other features first

**Comment by sarL3y** [comment]
Progress: Carlos looked into the implementation and we'll be moving in a different direction for now. Going into backlog.

**Comment by switchzer0** [comment]
@alex-anakin is this made redundant/obsolete due to revised MVP PRD and database schema, as well as new issues?

**Comment by alex-anakin** [comment]
@switchzer0 It's obsolete. UALs are designed and will be implemented in the v0.4 release.
