### ISSUE TITLE
When Adding New Project, User should be able to save first before adding meeting time.

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1381]
Background-
In the usability testing, Bonnie wanted to make sure that she would be able to save the project before adding a recurring meeting time. We need to make sure this is possible with the current live version of VRMS, since the usability test was done in Figma.

A/C-
When adding new project, user should be able to save project first before adding recurring meeting time.

### Resources
- #1335  - video

**Comment by MicahBear** [comment]
- #1325  completes this issue.
- labels added to this issue that matched 1325. size label adjusted to reflect this one issue versus the size of 1325.
- [This comment refers to what is stated in issue Background](https://github.com/hackforla/VRMS/pull/1325#issuecomment-1465307269)
