### ISSUE TITLE
Add New Project Field Location Default Value -- Remote

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1382]
When adding new project, the default value for Location should be Remote.
Currently, the default value in In-Person

A/C-
When adding new project, under location, the Remote radio button should be selected by default.

**Comment by MicahBear** [comment]
- #1325   completes this issue of remote location being selected by default.  
- And #1325 fixed the original issue #1245.
- labels added to this issue that matched 1325. size label adjusted to reflect this one issue versus the size of 1325.
