### ISSUE TITLE
Add New Project Form Validation - Location

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1387]
Under Location, we should add validation to this field so that it requires a string that contains "zoom.us"

     
AC1:
GIVEN that a user adds a new project
WHEN they enter a url that contains the string "zoom.us" under location
THEN the field will not reject the entry
AND allow the user to save as long as all other required fields are entered

AC2:
GIVEN that a user adds a new project
WHEN they enter a url that does not contain the string "zoom.us" under location
THEN text box will turn red
AND error message underneath box will read "please enter valid zoom link"
AND user will not be able to save

**Comment by jbubar** [comment]
@bkmorgan3 are you actively working on this?
If so could you put it in progress?

**Comment by bkmorgan3** [comment]
@jbubar 
Theres a PR up for it.  I moved it over on the board.

**Comment by JackHaeg** [comment]
- @bkmorgan3 Hi Brad, please link the PR that you have open for this issue. I see that you referenced a PR above #1400 but it seems like it was closed unmerged, is that what you were referencing?
