### ISSUE TITLE
Prompt user to consent to discarding form info on Close click

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1391]
### Overview
Right now, using the Create Project page (and possibly the Edit Project page), the Close button doesn't inform the user they're going to discard the new project information they've entered so far.

The Figma design calls for a confirmation modal that is currently not implemented.
<details>
<summary>Figma Screenshot</summary>
<img width="248" alt="image" src="https://user-images.githubusercontent.com/5898009/236362620-f9f403d8-9ec0-4245-b11f-81188bf1e3ee.png">
</details>

### Action Items
- [ ] Create a new component ChangesModal.js as per the [current figma design](https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?node-id=1258-3890&t=X2VtNC2heHD5mhvQ-0)
- [ ] Activate this modal once the user clicks Close. Modal should:
  - [ ] Keep the user on the current page if No is clicked.
  - [ ] Return the user to the previous page if Yes is clicked

<details>
<summary>Screenshots</summary>
<img width="509" alt="image" src="https://user-images.githubusercontent.com/5898009/236358113-8fbe7a03-ce9d-4c08-ae22-73c330f139c5.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/5898009/236358134-a9c115b3-9c9c-41b7-b36d-c78c2f92987a.png">

</details>

**Comment by JackHaeg** [comment]
Blocked until we have a modal
