### ISSUE TITLE
Add Hack For LA URL to Add Project Page

### ISSUE THREAD

**Issue by AmandaGlover-PM** [hackforla/VRMS#1393]
### Overview
We need to add the website URL to the new project page so the Hack For LA URL can be part of the project.  This form will replace a form submitted on Github to add more usability to VRMS; so this is one of the changes that will get us closer to migrating this activity to VRMS and out of Github.
 
### Action
- [x] Add description and field to allow the Hack for LA web URL for the project to be included
- [x] Description: Hack For LA Project URL:
- [x] Field includes grayed-out text to guide the user on what to fill in here just like the other fill-in fields; an exaxmple URL for this text is https://www.hackforla.org/projects/
- [x] If someone is adding a new project and the web url is not availlable, they can add this later, so it does not have to be a required field 

### Outcome:
The user can see the Hack For LA Project URL description and field and can add in the web url from the Hack For LA website if already established.  It the web URL doesn't exist yet, this can be completed without it and added later. This would be updated so all projects added to VRMS will have this option moving forward.

### Resources
Example project page:
https://vrms.io/projects/5edea7d2ce228b001778fac9

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: Amanda
Slack @handle: Amanda Glover

**Comment by JackHaeg** [comment]
Improve issue: Add screenshots, clean up writing.

**Comment by JackHaeg** [comment]
This has been completed in the prod build of VRMS as of Feb 1, 2023
