### ISSUE TITLE
Create showcase slide deck

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#14]
### Overview
Create a demo presentation on the VRMS project to present more broadly with CfA/HfLA. Useful for recruiting new team members once project has momentum.

### Action Items
* [ ] Create outline 
  * [ ] Get Bonnie to review
* [ ] Create slide deck
  * [ ] Get Bonnie to review
* [ ] Identify dates for presentation

### Resources/Instructions
[Wiki](https://github.com/hackforla/VRMS/wiki)
[TDM Calculator Presentation Example](https://docs.google.com/presentation/d/1djX48CJLJtw0ObDLN9cpVhJEIVsN4dplc4pe_wciUQY/edit#slide=id.p1)
[Figma template needs update](https://www.figma.com/file/Itzbfcwz2mKjttvO6Bfc6t/VRMS-Product-Guide-v1?node-id=0%3A1)

**Comment by rachelwhaley** [comment]
3 slides:

- Screenshots
- Why it's important
- What we've learned

**Comment by ExperimentsInHonesty** [comment]
https://docs.google.com/document/d/1HlsNSQyscOLqFg__vgo0l66xA6aRGIxmbY5B7w4VoVU/edit#heading=h.75fwiint49xn

**Comment by kelseylc** [comment]
This is now in progress. Sent some design prelims to Bonnie. Have basic outline above and next step will be to get basic content outline in slides for Bonnie's review & edits.

**Comment by ExperimentsInHonesty** [comment]
Kelsey's deck s://docs.google.com/document/d/16HGD2Eqv1tiNevI5ws6-9nzMYiH1SPQT1ZeM6wsXU00/edit

**Comment by switchzer0** [comment]
### Update
Rachel away from project and not aware of still upcoming showcase. Should this ticket close?

**Comment by switchzer0** [comment]
### Update
Bonnie explained purpose. Adam to bring up with Bonnie later, once v1.0 design and functionality is finalized and animated demo can be created.

### ETA
1-2 months
