### ISSUE TITLE
Event name validation: Add regex validation so that people cannot submit the wrong event name

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1403]
### Overview
We are having a problem where people are naming the meetings incorrectly. 

When the event name shows up on the website it shows up with the word meeting and the name of the project above it. So if someone puts the name of the project and the word meeting in the event name. We need to check for if they have the project name or the word meeting and gently remind them to not include it in the event name. 

### Action Items
- [ ] Check for the use of the project name, and the word "meeting" or "MTG" in the event name. 
- [ ] If either is present display a gentle reminder "Please do not use the project name or the word 'meeting' in the Event Name"
    - make it look nice.. (feel free to reach out to design @juliagab56 )

### Resources
- #1409

__________________________

Notice in the picture below the meeting name is just "Design" not "VRMS Design Meeting"

<img width="1144" alt="Screen Shot 2023-06-27 at 5 07 06 PM" src="https://github.com/hackforla/VRMS/assets/53061723/9b503824-cc32-41d2-9e0b-deeeb88d54d3">

**Comment by juliagab56** [comment]
- https://github.com/hackforla/VRMS/issues/1404
Mother issue
