### ISSUE TITLE
Meeting name validation, based on practice and UAL of attendees

### ISSUE THREAD

**Issue by juliagab56** [hackforla/VRMS#1409]
### Overview
Meeting names are not standardized. When creating a new meeting, volunteers don't know how to properly name them. This creates confusion because this information is displayed on the HfLA website and volunteers rely on that information to decide what meetings/projects they can join.

#### Reqs

Meeting names need to display meeting type/practice and who attends it. Example:

VRMS (project) 
**DevOps (practice/meeting type)
Leads and Members (who attends)**

### Action Items
- [x] Design possible solutions 
- [x] Get feedback

### Resources
[Figma](https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?type=design&node-id=2021%3A1617&mode=design&t=a5SyVahcEMZ9SyrP-1)

Related issue: 
- #1403

**Comment by juliagab56** [comment]
Part of an epic issue, waiting for feedback to iterate designs [Figma](https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?type=design&node-id=2021%3A1617&mode=design&t=a5SyVahcEMZ9SyrP-1)

**Comment by juliagab56** [comment]
@JackHaeg no updates since last comment!

**Comment by ExperimentsInHonesty** [comment]
name
--
data
pm
design
research
devops
dev (engineering)
content
admin
marketing
fundraising

**Comment by juliagab56** [comment]
> ## name
> data pm design research devops dev (engineering) content admin marketing fundraising

Added this info to the [specs](https://github.com/hackforla/VRMS/issues/1473)
