### ISSUE TITLE
Project Info Page

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#143]
### Overview
A project leader or admin should be able to view a "Project Info" page to see relevant info about their project. 

### Action Items
- [ ] Develop Project page
- [ ] Implement "Edit Project Info" page and/or functionality adjacent to Project Info page

### Resources
https://github.com/hackforla/website/tree/gh-pages/_projects

**Comment by clockwerkz** [comment]
Update: Should be done by tonight (05/18) or tomorrow the latest.

**Comment by clockwerkz** [comment]
Created a project page to display basic project info. Added edit project functionality. Will need to revisit to add back end connection functionality.
