### ISSUE TITLE
/projects/create link is unprotected

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1458]
### Overview
[/projects/create](https://dev.vrms.io/projects/create) link brings the user to the /create page without authentication.

### Action Items
Redirect the user to the login page if the user isn't logged in.

**Comment by JackHaeg** [comment]
@bkmorgan3 I saw that you moved this into Questions/Review, but there is no comment on the issue. Can you please add your question to this issue when you have a moment?
