### ISSUE TITLE
Update validateEventForm validation to better inform the user

### ISSUE THREAD

**Issue by vaidyarohan** [hackforla/VRMS#1466]
### Overview
Update the error message on Meeting Name to be more clear.

Right now, meeting names are not allowed to include `mtg`, `meeting` or the project name.

The error message listed is

```js
"Event name cannot contain `meeting` or `mtg` or the project name"
```

Which can be unclear if the Project Name is something like Onboarding.

The error message should call out specifically what is excluded, eg two separate errors

```js
"Event name cannot contain 'meeting' or 'mtg'"
"Event name cannot contain the Project Name: `${name}"
```

### Action Items
- [ ] update `validateEventForm` function to resolve for the two above errors. 

### Additional Context
- Bonnie sent a message in Slack (VRMS) saying that she was unable to change the name because of https://github.com/hackforla/VRMS/pull/1440.

**Comment by trillium** [comment]
Turns out this is funcitoning as intended. The project name is `Onboarding` and as such the word cannot appear in the meeting name.

**Comment by vaidyarohan** [comment]
@bonniewolfe the app is behaving as intended. The meeting name cannot be the same as the project name. We are going to update the error message to be more clear.
The current error message is: Event name cannot contain 'meeting' or 'mtg' or the project name

The error message on including Project Name will read: 'Event name cannot contain Project Name'.
The error message on including 'mgt' or 'meeting' will read: 'Event name cannot contain 'mgt' or 'meeting'.

**Comment by juliagab56** [comment]
Here are the latest [Figma designs](https://www.figma.com/file/pIxFTL62Nx2XyQdZy1fR6f/VRMS-v.4?type=design&node-id=2024%3A1892&mode=design&t=dvtbUknLzVcv301x-1) for the Events page. I am working on alternative wireframes to present and discuss during Thursday's meeting based on the notes I took from last Monday (Aug 21st)
