### ISSUE TITLE
1396 + Reusable form

### ISSUE THREAD

**Issue by plang-psm** [hackforla/VRMS#1470]
### Overview
Merge the Edit Project issue + create a reusable project form. Edit page will have an edit icon to open "Editing mode".

### Action Items
- [x] Create reusable form
- [x] Add the edit page components
Additional tasks:
- [x] Validation for the edit page
- [x] React Hook Form State
- [x] Including the buttons within the project for + minor styling
- [x] Edit Mode cancel function using React Hook Form reset method

Issue is created to combine issue #1396 and implement the additional requests.

**Comment by vaidyarohan** [comment]
Thank you @plang-psm for the work. Trillium will connect with you slack. It would be great if you can provide some updates here as well.

**Comment by plang-psm** [comment]
Hello @vaidyarohan . Currently running into some blockers with redirecting after a new project is created and optimizing the project form to accept information and functionality of the edit page.
