### ISSUE TITLE
Define and get appropriate access to AWS for VRMS

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1474]
### Overview
VRMS team needs access to VRMS on incubator so that they can troubleshoot bugs and update deployments on an ongoing basis. 

### Action Items

- [x] write up what kind of access does vrms need on an ongoing basis
- [ ] meet with the devops community of practice to setup appropriate accounts
- [ ] unblock this issue #1322

**Comment by angela-lee1** [comment]
@trillium I have a list of AWS services that we are currently using for dev and prod, obtained from reading the Terraform files. Please advise on the next step.

**Comment by JackHaeg** [comment]
Closing issue - @jbubar & @trillium were granted access to the AWS instance. No further steps required.

**Comment by JackHaeg** [comment]
@angela-lee1 Please post the Google Drive link to the document containing the list of the AWS services that we are currently using for dev and prod, obtained from reading the Terraform files. This document should be uploaded to [this "Development" folder](https://drive.google.com/drive/u/3/folders/1m4pS3kidCY2VrcNQWhtpLThSKQSplkax) on the VRMS Google Drive.
