### ISSUE TITLE
add .toLowerCase to front end new account creation

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1479]
### Overview
We need to transform user emails to be lower case during account creation as per #1456.

### Action items
- Transform new user email to lower case before the reuqest for account creation is sent to the db.

**Comment by StephenTheDev1001** [comment]
I can't self assign yet. I'd really like to start off with this issue and I think I'll be able to self assign after I'm fully onboarded. I'll start digging around tonight and hopefully I'll have a pull request before Monday EOD. Thanks

ETA: Monday, Aug 28.
Availability: 10am - 12pm

**Comment by trillium** [comment]
This is already currently handled in the database for account creation
