### ISSUE TITLE
Move simpleInput to it's own data.js object

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1483]
### Overview

The `simpleInput` object exists in two places and has slight variations between the two. Refactor out `simpleInput` from the `addPrject` and `editProject` components.

### Action Items
- [x] Create a data.js object in the same folder as ProjectForm
- [x] Copy the simepleInput version from the `addProject` component into this data object
- [x] import new data object into `addProject`
- [x] Remove version of simpleInput from `editProject`
- [x] import new data object into `editProject`

### Resources/Info
The verion of simpleInput from `editProject` has a value field that is populated with unused data, that version is not needed.

**Comment by trillium** [comment]
@StephenTheDev1001 is working on this

**Comment by StephenTheDev1001** [comment]
@Spiteless I'm unable to find any object named `simpleInput` but there's an array called `simpleInputs` in [ProjectForm.js](https://github.com/hackforla/VRMS/blob/development/client/src/components/ProjectForm.js). Is that the object that's releveant to this issue?

**Comment by trillium** [comment]
That's the right one @StephenTheDev1001

**Comment by trillium** [comment]
You're probably not all the way caught up with the most recent code changes if its in ProjectForm though

**Comment by trillium** [comment]
This is the array in question: https://github.com/hackforla/VRMS/blob/development/client/src/components/manageProjects/addProject.js#L6
