### ISSUE TITLE
Create ability for Admins to promote and demote Admins

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1486]
### Overview
Right now the only avenue to promote a user to admin level is to ping someone with DB access and have them promote the account. Not ideal.

### Action Items
The EditUser accessible by an admin needs the ability to promote and demote admins. Here's the short list:

#### PR Needs
- [ ] Promote a user to an admin
- [ ] Remove a user's admin status
- [ ] Remove self admin status

This will require both front end and back end edits

### Front end edits:
- [ ] Create AdminStatus component rendered on the EditUsers page 
  - [ ] Displays text: "VRMS Admin"  and toggle component.
```js
// client/src/components/user-admin/EditUsers.js
<FormGroup>
  <FormControlLabel control={<Switch checked={isActive} />} onClick={() => handleSetIsActive()} />
</FormGroup>
```

- [ ] Create function within UserApiService:
  - [ ] UpdateUserAdminStatus
  This function edits the user's admin status ~and stores the the user id `_id` of the admin that promoted them.~

#### Back end edits:
- [ ] ~update `user.model.js` to have an `adminPromotedBy` property of type `string`~
- [ ] apply the update to the user model to across the db

### Resources 
This task is fairly similar to #1452 , so feel free to use that PR's code as a model for how to do this PR.
- This issue is part of this epic: #1737

**Comment by JackHaeg** [comment]
This issue has been updated based on more recent requirements from stakeholder Bonnie, with the request that we drop the requirement to track / block edits to a admin's EditUser page based on who promoted them. Instead, we will implement a super admin user approach via the following issue: 
- #1747

Discussed with Nikhil on September 16, 2024. Minor updates required to this existing issue alone (i.e., changing the button text to "VRMS Admin")
