### ISSUE TITLE
Add in all available fields from the vrms database on the project edit page

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1489]
### Overview
bonnie requested to have all available fields in the db editable for admin level users

### Action Items
- [ ] add text inputs on the project page corresponding with the project model

### Resources/Instructions
example part of a json object from get request of vrms db
``` diff
"recruitingCategories": [],
+ "partners": [ ""
],
+ "managedByUsers": [],
"_id": "5eec35...",
"name": "Community of Practice: Data Science",
"description": "",
"githubIdentifier": "",
+ "projectStatus": "Active",
+ "location": "Remote",
"githubUrl": "https://github.com/hackforla/website",
"slackUrl": "",
+ "googleDriveUrl": "",
+ "googleDriveId": "",
"hflaWebsiteUrl": "https://www.hackforla.org/projects/website",

+ "createdDate": "2020-06-19T03:47:56.782Z", (display)
```

**Comment by trillium** [comment]
Confirmed Bonnie wants all these fields available by admin

- `createdDate` viewable but not editable

**Comment by JackHaeg** [comment]
@bkmorgan3 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by JackHaeg** [comment]
@bkmorgan3 can you please provide an update on this issue following the guidelines mentioned in the above comment? I see there is a PR linked.

**Comment by bkmorgan3** [comment]
@JackHaeg  just waiting for @Spiteless to re review.  I pinged him and tagged him here.
