### ISSUE TITLE
Prototype wireframes for admin dashboard

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#15]
### Overview
Propose a new design for the admin dashboard based on data visualizations

### Dependencies 
- See the list of potential metrics in the User Personas project board

### Action Items
* [ ] Review list from the User Personas board and create wireframes based on findings

### Resources
Current draft of wireframes: https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=22881%3A2786

**Comment by kelseylc** [comment]
Kill "Hi, [User]" tile, move to top right corner

Global Filters:
* Location
*** DTLA
*** Westside
*** South LA
* Date Range
*** Last 7 Days
*** Last 30 Days
*** Last 90 Days
*** Last 6 months
*** Last 12 months
*** All Time 

Data tiles:
* Total Volunteers
* Total Hours Volunteered
* Avg. Hours by Location
* Avg. Hours by Volunteer

Leaderboard: (most hours volunteered per person, DESC, LIMIT 10)
* Name
* Events (count)
* Hours (sum)

Tabs: Events, Brigade

Events:
Upcoming, Past

Past Events: (details)
* Event Name
* Event Date & Time (humanize format)
* City, State
* Status: Open/Closed
* Checkins: (count)
* Total Volunteer Hours: (Sum)
* Attendees: (list of check-ins, display first_name last_name)

**Comment by kelseylc** [comment]
Wireframes completed for V1, signed off by Bonnie. We'll create new versions for user personas later.

**Comment by kelseylc** [comment]
d2133d (red)
005a87 (dark blue)
5dafdc (light blue)

Cut Event Details person table (keep chart & total)
