### ISSUE TITLE
Add/Remove PM Admin Access: [Lucky Parking]

### ISSUE THREAD

**Issue by dannycpham** [hackforla/VRMS#1507]
Person who is staying on the team or leaving a team, person adds ticket. 

feature: add/remove admin access

Required information: 
- Name of PM: Danny Pham
- Are they being added or remove Who is being added as a new PM on the team and needs admin access to the project on VRMS? 
    - Slack Handle: Danny Pham
    - Email: dannycpham@gmail.com
    - Add or Remove. Add
    - Who has the access now, who to remove? Danny Pham should have access, Yuting should be removed.

**Comment by JackHaeg** [comment]
Hi @dannycpham I checked and your VRMS account should already have access to Lucky Parking (see below). Yuting as also been removed from Lucky Parking.

I will follow up via Slack with more info. 


<img width="804" alt="Screenshot 2023-09-07 at 5 18 48 PM" src="https://github.com/hackforla/VRMS/assets/134463646/c1dd8162-057c-4909-8e60-e897c1502aaf">

Closing as completed
