### ISSUE TITLE
Add "New User" ability to check-in if no meetings are open

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#153]
### Overview
A new user should be able to create a profile if there are no meetings to check-in for

### Dependency
the database end points and routes will need to be completed for this to be fully functional but some of the interface can be built.

### Action Items
- [ ] If no meetings are open for check-in, replace buttons on homepage with "Join Hack for LA"  and "Log In" 
- [ ] Use the current iteration of the new user form, but with "check-in" functionality removed

**Comment by Jonathanko52** [comment]
Progress: None
Blocks: None
Availability: 24/7
ETA: 7/20

**Comment by Jonathanko52** [comment]
Progress: Completed. Waiting for pull request review.

**Comment by alex-anakin** [comment]
@Jonathanko52 please check out your pull request. I don't see it.

**Comment by alex-anakin** [comment]
@Jonathanko52 please provide your update

**Comment by patrickgus** [comment]
Progress: I believe it is almost completed
Blockers: Need to get in touch with @Jonathanko52 to check progress.
Availability: Weekdays after 3pm
ETA: N/A

**Comment by alex-anakin** [comment]
Obsolete
