### ISSUE TITLE
Issue Cleanup: Review old issues assigned to inactive projects

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1538]
### Overview
Currently, VRMS has a number of old projects that could be closed. Issues assigned to old/outdated projects should be reviewed so that old issues can be cleared out.

### Action Items
- [x] If issues are still relevant, please add them to the current project and remove them from the old one,
- [x] If they are no longer relevant, close issue
- [x] If an issue is relevant, but is entirely unrelated to the current project and needs to remain in another (old) project, feel free to keep them as is. (hopefully there won’t be many of these - our goal is to get any relevant issue into the current active project)
- [x] If you have a question about an issue, add the label “review” to the issue and discuss with relevant team member. 

### Resources/Instructions
Issues can be found here: https://github.com/hackforla/VRMS/issues?q=is:open+is:issue+-project:hackforla/vrms/12+

**Comment by JackHaeg** [comment]
@jbubar Can you please provide an update on this issue?

**Comment by JackHaeg** [comment]
@jbubar Can you please provide an update on this issue?

**Comment by JackHaeg** [comment]
@jbubar Can you please provide an update on the progress of this issue?

**Comment by jbubar** [comment]
Cleaned out a majority of the issues by closing them as unplanned. I attempted to keep the organizational integrity of the [dev 0.4 project board (now depricated)](https://github.com/hackforla/VRMS/projects/10)

**Comment by JackHaeg** [comment]
Completed
