### ISSUE TITLE
Update Home.js Page page to MUI components

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1547]
### Overview

The `Home` page doesn't use our current MUI component system, update the components to the MUI structure

### Action Steps
- Convert components of the login page
  - Div --> Box
  - h1/h2/h3/h4 --> Typography with prop variant="{type}" 
  - disregard `<select/>` `<option/>` `<label/>` 
- Goal is to have very little to no UI change despite moving to `MUI` components

### Resources
 - [MUI Box](https://mui.com/material-ui/react-box/)
 - [MUI Typography](https://mui.com/material-ui/react-typography/)

**Comment by freaky4wrld** [comment]
@Spiteless the `sass properties` in the `index.scss`  used for the heading tags didn't apply to the `<Typography>` tags, so do I have to use `sx` attribute and write all the properties there or, shall I use the `className` attribute and change heading tags as classes like `.h1` ?

**Comment by trillium** [comment]
Please use the `sx` prop to keep the styling the same on the `Home` page eg

```jsx
<Typography variant='h2' sx={{
      // css properties
      }}
/>
```
The `Home` page is the only page at the moment where the blocky extra bold styling is being preserved on the h1, h2, etc tags.

**Comment by freaky4wrld** [comment]
Hey there @Spiteless on using the above mentioned changes of using `sx property` I have one issue, all the properties mentioned in `sx attribute` are valid except the `fontSize` and doesn't look accurate. Here is the code changes I did
```
<Typography variant='h1' sx={{fontSize: '7em', lineHeight: '0.85em', letterSpacing: '0.05em' }}>VRMS</Typography>
```
and it's showing all the changes except the desired `fontSize` and it's showing a warning and an error in the browser which are as follows: 

<img width="1440" alt="Screenshot 2023-12-04 at 12 10 51 PM" src="https://github.com/hackforla/VRMS/assets/134206855/22168aa4-b373-4457-a208-405695f81184">

<img width="1440" alt="Screenshot 2023-12-04 at 12 11 13 PM" src="https://github.com/hackforla/VRMS/assets/134206855/76135b70-fab5-46e1-8ade-18aad7893473">

**Comment by freaky4wrld** [comment]
You can see the changes that I've made on the branch 
https://github.com/freaky4wrld/VRMS/tree/update-front-page-to-MUI-components-1547

**Comment by freaky4wrld** [comment]
Please tell me what desired changes should be made to resolve those errors, warnings and get the desired UI changes.

**Comment by trillium** [comment]
Hey @freaky4wrld, the warning you're experiencing isn't related to the `/Home` page

Looking at this again I am recognizing that changing VRMS h1/h2 on the front page to tpyography elements and restyling them is a pain, sorry to send you on that goose chase.

Go ahead and undo the changes and submit a PR with the other changes provided

**Comment by freaky4wrld** [comment]
@Spiteless please check #1554, I've been able to successfully attain the changes in terms of font, but it doesn't met the changes as per the margins and paddings, can you guide me with that.

I have used the below article to make changes as suggested by you :)
https://mui.com/material-ui/customization/typography/
