### ISSUE TITLE
Convert all .js files that contain JSX components to .jsx

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1548]
### Overview
Use git rename to change all .js components that contain JSX to .jsx

### Action Items
- [x] #1549
- [ ] Use `git mv` to change file extensions

**Comment by pluto-bell** [comment]
@trillium is this issue still needed? Want to double-check with you!

After cross referencing issue #1549, it looks like all files with JSX have already been switched to a `.jsx` extension. 
I did a quick look over  `.js` files in `client/src` and didn't find any missing items. 

Update: brought up in meeting on Nov. 4 to double-check close out.
