### ISSUE TITLE
Determine which files need to be changed from .js to .jsx

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1549]
### Overview

Find all the `.js` files that contain `<SomeComponent></SomeComponent>` or `<SomeComponent/>` syntax within the project so that they can be renamed to `.jsx` with `git mv`

**Comment by trillium** [comment]
Here is the list of files:

```
./src/components/ProjectForm.js
./src/components/Navbar.js
./src/components/auth/Auth.js
./src/components/auth/HandleAuth.js
./src/components/user-admin/EditUsers.js
./src/components/user-admin/AddNewProject.js
./src/components/user-admin/UserManagement.js
./src/components/admin/donutChartContainer.js
./src/components/admin/donutChartLoading.js
./src/components/admin/dashboard/index.js
./src/components/admin/donutChart.js
./src/components/admin/reports/index.js
./src/components/dashboard/AddTeamMember.js
./src/components/dashboard/RosterTable.js
./src/components/dashboard/RosterTableRow.js
./src/components/presentational/CheckInButtons.js
./src/components/presentational/returnUserForm.js
./src/components/presentational/newUserForm.js
./src/components/presentational/profile/UserTable.js
./src/components/presentational/upcomingEvent.js
./src/components/manageProjects/eventForm.js
./src/components/manageProjects/editableField.js
./src/components/manageProjects/editMeetingTimes.js
./src/components/manageProjects/editProject.js
./src/components/manageProjects/addProject.js
./src/components/parts/form/ValidatedTextField.js
./src/components/parts/boxes/TitledBox.js
./src/components/Form.js
./src/components/Leaderboard.test.js
./src/components/Footer.js
./src/pages/Events.js
./src/pages/CheckInForm.js
./src/pages/ProjectLeaderDashboard.js
./src/pages/UserAdmin.js
./src/pages/UserProfile.js
./src/pages/ReturningUser.js
./src/pages/Home.js
./src/pages/ProjectList.js
./src/pages/ManageProjects.js
./src/pages/NewUser.js
./src/pages/SecretPassword.js
./src/App.js
```

**Comment by freaky4wrld** [comment]
> Here is the list of files:
> 
> ```
> ./src/components/ProjectForm.js
> ./src/components/Navbar.js
> ./src/components/auth/Auth.js
> ./src/components/auth/HandleAuth.js
> ./src/components/user-admin/EditUsers.js
> ./src/components/user-admin/AddNewProject.js
> ./src/components/user-admin/UserManagement.js
> ./src/components/admin/donutChartContainer.js
> ./src/components/admin/donutChartLoading.js
> ./src/components/admin/dashboard/index.js
> ./src/components/admin/donutChart.js
> ./src/components/admin/reports/index.js
> ./src/components/dashboard/AddTeamMember.js
> ./src/components/dashboard/RosterTable.js
> ./src/components/dashboard/RosterTableRow.js
> ./src/components/presentational/CheckInButtons.js
> ./src/components/presentational/returnUserForm.js
> ./src/components/presentational/newUserForm.js
> ./src/components/presentational/profile/UserTable.js
> ./src/components/presentational/upcomingEvent.js
> ./src/components/manageProjects/eventForm.js
> ./src/components/manageProjects/editableField.js
> ./src/components/manageProjects/editMeetingTimes.js
> ./src/components/manageProjects/editProject.js
> ./src/components/manageProjects/addProject.js
> ./src/components/parts/form/ValidatedTextField.js
> ./src/components/parts/boxes/TitledBox.js
> ./src/components/Form.js
> ./src/components/Leaderboard.test.js
> ./src/components/Footer.js
> ./src/pages/Events.js
> ./src/pages/CheckInForm.js
> ./src/pages/ProjectLeaderDashboard.js
> ./src/pages/UserAdmin.js
> ./src/pages/UserProfile.js
> ./src/pages/ReturningUser.js
> ./src/pages/Home.js
> ./src/pages/ProjectList.js
> ./src/pages/ManageProjects.js
> ./src/pages/NewUser.js
> ./src/pages/SecretPassword.js
> ./src/App.js
> ```

@Spiteless can't find any instance of `<SomeComponent></SomeComponent>` in `Footer.js` and `Form.js`, can you please tell me the reason of mentioning it there.
