### ISSUE TITLE
Export the HackForLA party user data as a CSV

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1562]
### Overview
Bonnie has asked for a CSV of all the user checkin data for the HackForLA end of year party. Provide Bonnie with the CSV

### Action Items
 - [ ] Develop a method to get the data out of our database and into a CSV format for the Holiday Party event.

**Comment by JackHaeg** [comment]
@jbubar & @Spiteless successfully exported this CSV, which will be shared with Bonnie.

**Comment by JackHaeg** [comment]
@jbubar & @Spiteless successfully exported this CSV, which will be shared with Bonnie.
