### ISSUE TITLE
Provide user a more clear flash message when errors happen

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1569]
### Overview
Change server alert box to be something more friendly and clear to users about the current error.

### Action Items
- [ ] Integrate [MUI Snackbar](https://mui.com/material-ui/react-snackbar/) into our component structure to be able to provide errors to users.
  - [ ] Create a context component `SnackbarContext` for the structure.

### Resources
 - [useContext Docs](https://react.dev/reference/react/useContext)

**Comment by JackHaeg** [comment]
@freaky4wrld Please provide update

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."
- remember to add links to the top of the issue if they are going to be needed again.

**Comment by freaky4wrld** [comment]
@JackHaeg 
- Progress: As per the current scenario the flash messages are executed on updating the events, @Spiteless has to approve it
- The PR #1575 has all the information
