### ISSUE TITLE
Remove project input fields

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1577]
### Overview
We need to comment out a few of the project input fields. Currently, the app requires people to put in junk data if there is no data for specific fields, and the "partners", "projectStatus", "managedByUsers", and "HFLA Website URL" are sometimes empty. This means that users will put whatever they type in those fields with no guard rails. Also, the "Created Date" field can be removed.

### Action Items
- [x] Collect feedback from stakeholder: confirm if these fields are, in fact, still required. If they are not required, continue on to next step.
  -  These fields are NOT required for the current build of the projects page. We will still include the Future versions will include Partners. 
- [x] comment out the field "partners"
- [x] comment out the field "projectStatus"
- [x] comment out the field "managedByUsers"
- [x] comment out the field: "Created Date"
- [x] #1581

**Comment by ExperimentsInHonesty** [comment]
I accept this fix.  It's working as intended.
