### ISSUE TITLE
Define personas for users and group leaders

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#16]
### Overview
Create personas and their user stories.

### Action Items
* [x] Turn each of these user stories into cards on Personas/User Stories project board 
* [x] Merge/streamline the 2 columns of stories on the Personas/User Stories project board 

### Resources
[Potential features/user stories](https://docs.google.com/document/d/1-4q-suCaUKZW2L3UyMvr6EtDZWAh9oaYCY2Ztm_vg_M/edit?usp=sharing)
[project board to add them to](https://github.com/hackforla/VRMS/projects/6)

**Comment by ExperimentsInHonesty** [comment]
I have created cards for all the stories in the Potential features/user stories doc.  The cards are located on the [personas/user stories board](https://github.com/hackforla/VRMS/projects/6)

**Comment by ExperimentsInHonesty** [comment]
1. Progress: none
2. Blocks: lack of available time, and that I keep forgetting, so someone needs to me my butt kicker
3. Availability, ill make time
4. ETA, when someone can meet with me. Post Summit

**Comment by switchzer0** [comment]
personas summarized atop each persona/user-story column
