### ISSUE TITLE
Update HTML components to MUI: ./src/components/ProjectForm.js

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1623]
### Overview
Review all components in`./src/components/ProjectForm.js` and replace all standard HTML components with applicable MUI components.

### Action Items
- [ ] Review components in:`./src/components/ProjectForm.js` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI_
    - [ ] Comment on this issue that all components are already updated to MUI & close the issue. 
    - [ ] move to next [MUI issue](https://github.com/hackforla/VRMS/issues/1617)) 
  - _IF standard HTML components are found in the file:_ 
    - [ ] Replace these standard HTML components with applicable MUI components. 
    - [ ] Make a PR for this file
- If you run into any questions, add a comment to the issue and tag "@Spiteless" 

### Resources
https://mui.com/base-ui/all-components/

**Comment by evanyang1** [comment]
I think the file used Mui already.
