### ISSUE TITLE
Remove ability for PMs to edit Project Information on VRMS

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1630]
### Overview
Currently, Project / Product Managers (PMs) assigned to a project on VRMS can make edits to their project's information. We must remove the ability for PMs to edit project information, while still allowing PMs to add/edit/remove project events on VRMS. Admins are to be the only User Access Level who can make edits to Project Information in the current product.

### Action Items
- [ ] On the "Project Management" screen, only render the "Edit Mode" Button when the user access level = Admin. (see: client/src/components/ProjectForm.js)

### Resources/Instructions
<details><summary>Screenshot</summary>
<p>
<img width="426" alt="Screenshot 2024-04-22 at 7 51 50 PM" src="https://github.com/hackforla/VRMS/assets/134463646/e36d80e3-e509-4bf5-92a1-28b383706929">
</p>
</details> 

*Note that in _future_ versions of the product, we will plan to allow PMs to make edits to project information via an admin review process, however we cannot allow PMs to make these changes without a proper review system in place. This serves as a temporary fix for the current product only, until we can implement the admin review process in the future product.

**Comment by lcchrty** [comment]
client/src/components/ProjectForm.js
Conditionally render based on user access level
