### ISSUE TITLE
Investigate and Block Zoom Links from VRMS API

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1659]
### Overview
Per stakeholder (Bonnie) - the VRMS API that is used by the HfLA website appears to be publishing Zoom links for each event stored on VRMS. For security reasons, it is recommended that these Zoom links are either blocked from being published or hidden from the public API. 

### Action Items
- [ ] Review the VRMS data that the HfLA website is pulling from: [vrms_data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json) and check for Zoom links (look for `videoConferenceLink`)
- [ ] Based on findings, investigate how to block Zoom links from being published on the VRMS API. Zoom links should still remain viewable within the VRMS app. 
- [ ] Block Zoom links from being published on VRMS API.
- [ ] Submit PR. 

### Resources/Instructions
- https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json

**Comment by bkmorgan3** [comment]
@JackHaeg  @Spiteless  

I could either setup permissions on the DB, or make another route for either us or them and on the route i can leave off the zoom links with a .select("-meetinglink"). 

Not sure how far-future-facing we should go on this

**Comment by JackHaeg** [comment]
As discussed during Monday's all team meeting, decision = make a new route.

**Comment by JackHaeg** [comment]
@bkmorgan3  Please provide update:

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

**Comment by bkmorgan3** [comment]
@JackHaeg  
I have most of the work done, I took out the meeting links from the current events call and created a new route.  I just have to  assign the new route to what we are using. 
I'll try to get a PR in today

**Comment by JackHaeg** [comment]
@bkmorgan3 That's great news! Thanks a ton for the update, Brad 👍

**Comment by JackHaeg** [comment]
@bkmorgan3 When you have a moment, can you please provide an update:

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

**Comment by bkmorgan3** [comment]
@JackHaeg 
Sorry, didn't link the issue in the PR.  This is done and approved but not merged.
