### ISSUE TITLE
Update HTML components to MUI: ./src/components/admin/donutChart.js

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1672]
### Overview
Review all components in`./src/components/admin/donutChart.js` and replace all standard HTML components with applicable MUI components.

### Action Items
- [ ] Review components in:`./src/components/admin/donutChart.js` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI_
    - [ ] Comment on this issue that all components are already updated to MUI. 
    - [ ] Close the issue & check the box associated with this issue on the [MUI issue epic](https://github.com/hackforla/VRMS/issues/1617)
    - [ ] Move on to the next [MUI issue](https://github.com/hackforla/VRMS/issues/1617) 
  - _IF standard HTML components are found in the file:_ 
    - [ ] Replace these standard HTML components with applicable MUI components. 
    - [ ] Make a PR for this file

### Resources
- https://mui.com/base-ui/all-components/
- If you run into any questions, add a comment to the issue and tag "@trillium"

**Comment by trillium** [comment]
Closing as unplanned (this component isn't used in our current iteration of the app)
