### ISSUE TITLE
Evaluate VRMS suitability and readiness for internship

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#1697]
### Overview
We need to evaluate whether VRMS can take on 20 new developers inside a structured internship program so that we can decide if we are including it or will be using another project.

### Action Items
- [ ] Review project board
- [ ] Issue Structure
- [ ] Discuss objectives for VRMS during internship
- [ ] Discuss Measurements
- [ ] Define metrics and how we would track them

### Resources/Instructions

- [Project Board, Dev, Icebox with no dependency](https://github.com/orgs/hackforla/projects/72/views/5?filterQuery=label%3A%22role%3A+devops%22%2C%22role%3A+Front+End%22%2C%22role%3A+Back+End%22%2C%22role%3A+Dev+Lead%22%2C%22ready+for+dev+lead%22%2C%22role%3A+Database%22+-label%3A%22Dependency+-+Icebox%22+status%3AIcebox)
- HfLA Website team wiki about reviewing PRs https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests
- https://github.com/hackforla/internship/issues/59
- https://github.com/hackforla/internship/issues/101
- John Darragh is the tech lead on TDM-Calculator and has an environment that allows us to push just the changes that have been approved from dev to prod, instead of all changes sitting on dev.
- Draft of the skills issue from website team https://github.com/hackforla/website/issues/4944#issuecomment-2170595357.  This will replace the current [prework template](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Prework%2C+Feature%3A+Onboarding%2FContributing.md%2C+role+missing%2C+size%3A+1pt&projects=&template=pre-work-template--dev.md&title=Pre-work+Checklist%3A+Developer%3A+%5Breplace+brackets+with+your+name%5D)
- add missing labels to each new issue template ([edit all issue templates](https://github.com/hackforla/VRMS/issues/templates/edit))

**Comment by ExperimentsInHonesty** [comment]
- A full Prioritized Backlog that is sized to the current team
- 8 weeks worth of work for current developers 
- current team size should be no less than 4 developers including dev lead
- ladder system of complexity of issue (2x good first, small, medium, large, x-large)
- ladder system of issue making 
- board organization makes sense 
   - items in icebox have well-defined dependencies
   - new issue approval gets reviewed weekly and issues processed in a timely way
   - prioritized backlog does not have people assigned to the issues and the issues are ready to work
   - in progress, has a person assigned to each issue, and has written weekly updates
   - Questions / Review has who needs to answer questions label
     - `ready for dev lead`
     - `ready for product`
     - `ready for design`
- Epics need to have rules
   - Do all the issues in an epic need to be made before it goes to the epic column?  I don't think it needs to, but all the issues that are made need to indicate that when they are done, the epic needs to be revisited based on up-to-date info. Meaning... sometimes you can't write all the issues, because an issue might change next steps.
   - All issues in an epic, need to have the following text in the Resources section
     ```
     - This issue is part of this epic: #
     ```
   - The last Action item in each issue in an epic, should be to check off the issue as complete in the epic
      - Some issues will have other instructions, such as returning to the epic to make other issues or removing other issues from the icebox because their dependency has been satisfied by the completing of this issue.

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by JackHaeg** [comment]
Trillium & Jack met for a brief kick off call today to begin discussing this project.

**Comment by JackHaeg** [comment]
As discussed with Bonnie during today's PM/Design Lead planning meeting, the grant funding this internship is not going to be approved. Thus, we will be closing this issue as unplanned.
