### ISSUE TITLE
Update HTML components to MUI: ./src/components/parts/form/ValidatedTextField.js

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1705]
### Overview
Review all components in`./src/components/parts/form/ValidatedTextField.js` and replace all standard HTML components with applicable MUI components.

### Action Items
- [x] Review components in:`./src/components/parts/form/ValidatedTextField.js` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI_
    - [x] Comment on this issue that all components are already updated to MUI. 
    - [x] Close the issue & check the box associated with this issue on the [MUI issue epic](https://github.com/hackforla/VRMS/issues/1617)
    - [ ] Move on to the next [MUI issue](https://github.com/hackforla/VRMS/issues/1617) 
  - _IF standard HTML components are found in the file:_ 
    - [ ] Replace these standard HTML components with applicable MUI components. 
    - [ ] Make a PR for this file

### Resources
- https://mui.com/base-ui/all-components/
- If you run into any questions, add a comment to the issue and tag "@trillium"

**Comment by evanyang1** [comment]
updated to MUI already

**Comment by JackHaeg** [comment]
@trillium please take a look at this to confirm MUI is updated already and if so, close issue as completed.

**Comment by trillium** [comment]
Closing as completed :)
