### ISSUE TITLE
GitHub identifier: Needs to be removed

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1728]
### Overview
Remove GitHub Identifyer from project form frields:

<img width="574" alt="image" src="https://github.com/user-attachments/assets/3637d086-5bb8-477b-83d5-4cb3732af98d">

### Action Items
 - [ ] Search codebase for `githubIdentifier`
 - [ ] Remove `githubIdentifier` from api call and from Project Details render

### Resources/Instructions
- #1567 is a similar issue
- Part of Epic #1371

**Comment by JackHaeg** [comment]
Per stakeholder, we want to keep the GitHub identifier within the project details screen, however this field will not be required to create/edit a project, and it will be validated. Closing as unplanned
