### ISSUE TITLE
Generate Comprehensive reports in Admin Dashboard

### ISSUE THREAD

**Issue by Jonathanko52** [hackforla/VRMS#173]
### Overview
Have the dashboard data displayed in a manner more usable to the administrators, rather than as piecharts.

### Action Items
-Mock Report received. Set up router to retrieve data from database and view to display data

**Comment by Jonathanko52** [comment]
Progress: Minimal
Blocks: Need the event/project name to be included in user sign ins, within the database model.
Availability:24/7
ETA:6/29

**Comment by ExperimentsInHonesty** [comment]
@rachelwhaley can you look at this issue and let me know if adding this to the model is your purview or some one else's.

**Comment by ExperimentsInHonesty** [comment]
@Rankazze please identify requirements and then review with Adam and I so that we can add them if applicable to the mock ups.

**Comment by Rankazze** [comment]
Here is the Mock Report

https://drive.google.com/file/d/1fjFvNQkZ2oRW_5P1JkmitspHYJgiCHml/view?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
we will let Rachel know when there are attributes to add.

**Comment by ExperimentsInHonesty** [comment]
Here is the google docs version revised 
https://docs.google.com/document/d/1fjFvNQkZ2oRW_5P1JkmitspHYJgiCHml/edit

**Comment by ExperimentsInHonesty** [comment]
see https://github.com/hackforla/VRMS/issues/69

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty will add spreadsheet to issue

**Comment by ExperimentsInHonesty** [comment]
1. Progress - none
2. Blocks : forgot about it
3. Availability: good
4. ETA - Monday next week.

**Comment by ExperimentsInHonesty** [comment]
Progress - none
Blocks : forgot about it
Availability: good
ETA - Monday next week.

**Comment by ExperimentsInHonesty** [comment]
@OlgaBilogurova  Can you look at what I have put into figma for the admin section and let me know what questions you might have?

**Comment by OlgaBilogurova** [comment]
@ExperimentsInHonesty thanks for providing info and mockups for stats.

As I understand we need to have 2 types of stats:

- Stats by Location- Volunteer Hours  

  should include:  
            donut charts (current stats)
            table stats with filtering by date (need to develop)

- Stats by Project- Volunteer Hours (need to develop)

I have questions regarding Stats by Project- Volunteer Hours.
Table column # Hours Donated includes columns: Current / Historically

1. When a user chooses time range from the dropdown, should we recalculate data for the "Current" column only?   

2. As I understand "Historically" column displays total hours donated by members for the specific project for all time. And this data not sensitive to the data filter. Am I right?

3. By default (when a page loaded), "Stats by Project- Volunteer Hours" displays stats for week / last month or all time? (active members/avg hours/current hours donated)

![Stats](https://user-images.githubusercontent.com/11681030/90169902-19ea5380-dd54-11ea-8d71-3490f4563dd3.png)

**Comment by ExperimentsInHonesty** [comment]
@OlgaBilogurova Does this answer your questions:
![Screen Shot 2020-08-14 at 10 59 36 AM](https://user-images.githubusercontent.com/37763229/90279068-52a22f80-de1d-11ea-9861-7c3f740937e8.png)

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2020-08-14 at 11 15 14 AM](https://user-images.githubusercontent.com/37763229/90280261-79616580-de1f-11ea-9efb-d86b7d7404b3.png)

**Comment by OlgaBilogurova** [comment]
It's clear, now. I will work on it.
Thanks, @ExperimentsInHonesty
