### ISSUE TITLE
Add/Remove PM Admin Access: [Civic Tech Jobs]

### ISSUE THREAD

**Issue by kcoronel** [hackforla/VRMS#1730]
Person who is staying on the team or leaving a team, person adds ticket. 

### Required information
- Name of PM requesting changes (your name): Karen Coronel 
- Slack handle: Karen

#### People you are removing  
- Name:
- Slack Handle:
- Email:

#### People you are adding 
- Name: Nooria Ali
- Slack Handle: @Nooria Ali
- Email: nooria.ali1610@gmail.com

**Comment by JackHaeg** [comment]
Nooria's account has been created on VRMS and Nooria has been added to the Civic Tech Jobs project with PM permissions on VRMS. Closing as completed.
