### ISSUE TITLE
Add/Remove PM Admin Access: 311 Data

### ISSUE THREAD

**Issue by bberhane** [hackforla/VRMS#1735]
Person who is staying on the team or leaving a team, person adds ticket. 

### Required information
- Name of PM requesting changes (your name): Bethlihem Berhane 
- Slack handle: @Bethlehem Berhane

#### People you are removing  
- Name:
- Slack Handle:
- Email:

#### People you are adding 
- Name: Sumit Sharma 
- Slack Handle: @Sumit Sharma 
- Email: sumitsharma8692@gmail.com

**Comment by JackHaeg** [comment]
Created new VRMS account and added Sumit to 311 Data project.
