### ISSUE TITLE
Add/Remove PM Admin Access: PeopleDepot

### ISSUE THREAD

**Issue by shmonks** [hackforla/VRMS#1736]
Person who is staying on the team or leaving a team, person adds ticket. 

### Required information
- Name of PM requesting changes (your name): Sarah Monks
- Slack handle: Sarah Monks, PhD

#### People you are removing  
- Name: Shifra Goldberg
- Slack Handle: Shifra Goldberg
- Email: ShifraG@gmail.com

- Name: Kathleen Francois
- Slack Handle: kathleenfrancois
- Email: kathleenmfrancois@gmail.com

#### People you are adding 
- Name: Sarah Monks
- Slack Handle: Sarah Monks, PhD
- Email: shmonks@gmail.com

- Name: Vanessa Aviles
- Slack Handle: Vanessa Aviles
- Email: vanessaavviles@gmail.com

**Comment by JackHaeg** [comment]
Removed Shifra & Kathleen, and added Sarah & Vanessa to the People Depot project on VRMS.
