### ISSUE TITLE
Add PM Admin Access: 311 Data

### ISSUE THREAD

**Issue by rayneng** [hackforla/VRMS#1738]
Person who is staying on the team or leaving a team, person adds ticket. 

### Required information
- Name of PM requesting changes (your name): Ryan Chase
- Slack handle: @Ryan Chase

#### People you are adding 
- Name: Christopher Cotton
- Slack Handle: @Christopher Cotton
- Email: snr.cotton@gmail.com

**Comment by JackHaeg** [comment]
@ryanfchase It looks like Christopher currently has an account on VRMS with the email: sr.cotton@yahoo.com. 

Would you like for me to add him to the 311 Data project using this email, or would you prefer that I create a new account for him and add him to the 311 Data project on VRMS with the email linked above (snr.cotton@gmail.com)?

**Comment by rayneng** [comment]
Hi @JackHaeg. Can we swap him over so he’s on the 311 project with the gmail account? We can get rid of the account with the yahoo email. Thanks!

**Comment by JackHaeg** [comment]
@ryanfchase Sounds good 👍 
I created the account for [snr.cotton@gmail.com](mailto:snr.cotton@gmail.com) and have added Christopher to the 311 Project on VRMS. Closing issue as complete.
