### ISSUE TITLE
Implement free-level mixpanel analytics

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#176]
### Overview

MixPanel is a frontend analytics tool that allows for product design optimization by tracking user behavior. Implementing the tool requires admin some code to VRMS, which will then allow the product team to identify pain-points in product design, friction, etc.

### Action Items
- [ ] speak with bonnie about the other project using MixPanel. Should we get a separate account for VRMS?
- [ ] open/access mixpanel account
- [ ] add header code to VRMS
- [ ] coordinate with Product Manager/UI/UX on first round of elements to track
- [ ] document implementation in google drive

Resources
[https://mixpanel.com](url)

**Comment by jbubar** [comment]
Closing because there is not a clear stakeholder request. This might be a good thing to implement in the future.
