### ISSUE TITLE
Convert finalized PRD to full list of small tickets

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#177]
### Dependency
Not enough tickets in the prioritized backlog

### Overview

Translate MVP PRD into tickets for development, design, slicing tasks as small as possible and allowing for new team members to dive in

### Action Items
- [ ] brainstorm ticket size and skill differentiation goals by functional area (e.g., dev, design; screen layouts, graphics creation)
- [ ] create tickets
- [ ] categorize tickets as prioritized backlog or icebox (do we want an intermediate category for "if we've got time and its easy" or should that be "icebox"?)

Resources
[MVP PRD](https://drive.google.com/open?id=15LvzFpLPYjQhpMx58P60onh697ww45fgZm-Sg_FGehw)
[Screens overview](https://drive.google.com/open?id=1hDus73QA-HpYbIXyTg-Bhhe-LqunURZc2Ef0-LQIT6U)

**Comment by ExperimentsInHonesty** [comment]
@switchzer0 will update dependency with related issues

**Comment by juliagab56** [comment]
Outdated issue
