### ISSUE TITLE
Add/Remove PM Admin Access: Civic Tech Jobs

### ISSUE THREAD

**Issue by kcoronel** [hackforla/VRMS#1788]
Person who is staying on the team or leaving a team, person adds ticket. 

### Required information
- Name of PM requesting changes (your name): Karen Coronel
- Slack handle: Karen 

#### People you are removing  
- Name: Kanika Chotani
- Slack Handle: Kanika Chotani
- Email: kanika.chotani@gmail.com

#### People you are adding 
- Name:
- Slack Handle:
- Email:

**Comment by JackHaeg** [comment]
Kanika Chotani has been removed from the Civic Tech Jobs project and status has been changed to inactive on VRMS. Closing issue as complete.
