### ISSUE TITLE
Updated documentation for MVP

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#179]
### Overview

Documentation for VRMS should be for current upon completing MVP milestone .

### Dependency
Stable code base - end of mvp dev, before launch

### Action Items
- [ ] data model
- [ ] APIs
- [ ] design conventions

**Comment by ExperimentsInHonesty** [comment]
Data Model : https://github.com/hackforla/VRMS/tree/development/models

**Comment by alex-anakin** [comment]
Done
https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit
