### ISSUE TITLE
Create the framework to conduct user interviews and synthesize the results

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#18]
### Overview
Collect attendee feedback on the initial build of the VRMS.

### Action Items
- [ ] Convert [this template](https://docs.google.com/document/d/19uYILR38PQvVFblgLx5PyUMqnPh-4KFfqCOgWStaJF8/edit) document to Google Form
- [ ] Create bit.ly for survey (called "starfish99")
- [ ] Distribute the survey 
- [ ] Add survey link to wiki
- [ ] Synthesize the notes from all interviews into key points

**Comment by alex-anakin** [comment]
Obsolete
