### ISSUE TITLE
Add/Remove PM Admin Access: Guides Team

### ISSUE THREAD

**Issue by fchan218** [hackforla/VRMS#1807]
Person who is staying on the team or leaving a team, person adds ticket. 

### Required information
- Name of PM requesting changes (your name): France Chan
- Slack handle: @fchan218

#### People you are removing  
- Name: Sarah Edwards
- Slack Handle: @sarahedwards
- Email: sme4027@gmail.com

**Comment by JackHaeg** [comment]
Sarah Edwards is removed from the Guides Team on VRMS, and has been marked as inactive. Closed as completed.
