### ISSUE TITLE
Administrator access level control tool

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#182]
We decided to hardcode access level controls on the rare cases they need to be modified.

Notes leftover from when this tool existed in MVP:

Administrator user access level tool
Accounts with administrator access level will display an additional module for access level administration on the VRMS user account dashboard
Administrators will select individual user accounts and can grant “administrator” access level. An “are you sure” screen will display before the change is recorded in the user object.
Administrators will select individual user accounts 
Administrators will be able to view all administrators in a list with a button in the access level dashboard
“Remove administrator permission” will be clickable on each administrator
All other administrators will receive a “confirm removal” notification in their VRMS dashboard; removal will be marked “pending” until a 2nd administrator account authorizes (m of n security)
The notification will be automatically cleared from all administrator dashboards once a second admin has approved, and the user account of lowered status will have its user object access level lowered to basic user
Administrators will be able to view all project leads in a list with a button in the access level dashboard
“Change project lead” will be clickable on each project lead user listed. Admin can select a new project lead on subsequent screen, which will be saved to the project (or later iteration, project team member) object
need to discuss logic around if projects must have a lead role; i think yes so someone is always driving in the onboarding flows
Administrators will be able to generate a modify user account data link pursuant to “user account administration” feature (below)

**Comment by alex-anakin** [comment]
Obsolete
