### ISSUE TITLE
Fix API endpoint for Hack for LA website.

### ISSUE THREAD

**Issue by ruben1s** [hackforla/VRMS#185]
### Overview
Currently, there are a few project names that do not align with the project names listed on the Hack for LA .md files, and there is a links not resolving properly on the team meeting page.

### Action Items
- [x] Change project titles to match what's on the .md files
   - [x] TDM Calculator
      -  Currently says 'TDM Calculator' 
      -  Change to 'LA TDM Calculator' 
   - [x] HackForLa website 
      -  Currently says 'Hack for LA Website' 
      -  Change to 'Hackforla.org Website' 
- [x] Fix broken Home Unite Us link in API endpoint by correcting the link to refer to home-unite-us.md instead of homeuniteus.md)

### Resources
[website md file](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
[tdm-calculator md file](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md)
[home unite us md file](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)

**Comment by sarL3y** [comment]
@ruben1s Please let me know once you approve the changes and I'll close the issue. Thanks!

**Comment by ruben1s** [comment]
Everything looks good.
