### ISSUE TITLE
Discussion item: Slack invite process DRAFT

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#187]
### Overview
Define the slack processes (manual and technical) and how they fit together so that both UX and development can understand what we are trying to achieve.

### Action Items

- [ ] Review Draft 1
- [ ] If you have changes, copy and paste entire process to a comment and then change the relevant part, so that eventually when we get to the bottom of this issue we have the final version.
- [ ] Add any questions you might have into a comment.

### Draft 1
All user journeys seem to require the same process, which is the user signing up on VRMS and as soon as they have given us their email address and other basic details, they agree to the code of conduct and then...

**Process for new joiners on VRMS for slack by looking up their email in the api**

- **_check to see if they are already a member of slack._**  
   - if no (they are not a member of hfla slack workspace) 
      - **send invite and instructions on accepting**
      - **show "Confirm you have joined slack" and "resend slack invite" buttons**
         - when they click the 'confirm' button if checks to see if they are a member of our slack
            - if no
               - **Display text explaining their need to accept and setup their slack account on our workspace, and  show "Confirm you have joined slack" and "resend slack invite" buttons**
      - if yes (they are a member of hfla slack workspace) 

         - Q: Did they come with with an invite to a specific channel/team? 
            -  if no (they are a member of the hfla slack workspace, and they came to VRMS without a channel/team specific invite)
               - **do nothing**
            - if yes (they came with an invite to a specific channel/team)
               - Q: are they already part of the slack channel associate with that team?
                  - if yes (they are a member of the hfla slack workspace and the channel from the invite)
                  - **_record their membership to channel in data model_**
                 -  if no (they are a member of the hfla workspace but not of the channel), 
                    - **_add them to the channel_**
                    - **_record their membership to channel in data model_**
               - **_add a link to their vrms dashboard that will take them to the channel anytime._**

- This section might get pushed to another iteration
   - if yes, it will be replaced by people just choosing their team  from a drop down
      - if no (they are not a member of hfla slack workspace) 
         - **send invite**
         - **show "Confirm you have joined slack" and "resend slack invite" buttons**
            -  if no (they are a member of the hfla slack workspace, and they came to VRMS without a channel/team specific invite)
                - do nothing
            - if yes (they came with an invite to a specific channel/team)
               - Q: are they already part of the slack channel associate with that team?
                  - if yes (they are a member of the hfla slack workspace and the channel from the invite)
                     - **->_record their membership to channel in data model_**
                 -  if no (they are a member of the hfla workspace but not of the channel), 
                     - **_add them to the channel_**
                    - **_record their membership to channel in data model_**
               - **_add a link to their vrms dashboard that will take them to the channel anytime._**
            

### Resources/Instructions
https://api.slack.com/methods#users
https://api.slack.com/methods/users.lookupByEmail
https://api.slack.com/methods/users.conversations
https://api.slack.com/methods/conversations.members

**Comment by Rankazze** [comment]
Overview

Define the **"To-Be"** slack processes (manual and technical) and how they fit together so that both UX and development can understand what we are trying to achieve.
Action Items

Review Draft 1
If you have changes, copy and paste entire process to a comment and then change the relevant part, so that eventually when we get to the bottom of this issue we have the final **shared understanding** version.

    Add any questions you might have into a comment.

Draft 1

All user journeys **begin with** the user signing up on VRMS and **upon inputting a valid** email address and other basic details, **and** they agree to the code of conduct and then...

Process for new joiners on VRMS for slack by looking up their email in the api

    check to see if they are already a member of slack.
        if no (they are not a member of hfla slack workspace)

            send invite and instructions on accepting

            show "Confirm you have joined slack" and "resend slack invite" buttons
                when they click the 'confirm' button **it** checks to see if they are a member of our slack
                    if no
                        Display text explaining their need to accept and setup their slack account on our workspace, and show "Confirm you have joined slack" and "resend slack invite" buttons

            if yes (they are a member of hfla slack workspace)
                Q: Did they come with with an invite to a specific channel/team?
                    if no (they are a member of the hfla slack workspace, and they came to VRMS without a channel/team specific invite)
                        **then,** do nothing
                    if yes (they came with an invite to a specific channel/team)
                        Q: are they already part of the slack channel associate with that team?
                            if yes (they are a member of the hfla slack workspace and the channel from the invite)
                            **then,** record their membership to channel in data model
                            if no (they are a member of the hfla workspace but not of the channel),
                                **then,** add them to the channel
                                **then**, record their membership to channel in data model
                        **then,** add a link to their vrms dashboard that will take them to the channel anytime.

    This section might get pushed to another iteration
        if yes, it will be replaced by people just choosing their team from a drop down
            if no (they are not a member of hfla slack workspace)
                send invite
                show "Confirm you have joined slack" and "resend slack invite" buttons
                    if no (they are a member of the hfla slack workspace, and they came to VRMS without a channel/team specific invite)
                        do nothing
                    if yes (they came with an invite to a specific channel/team)
                        Q: are they already part of the slack channel associate with that team?
                            if yes (they are a member of the hfla slack workspace and the channel from the invite)
                                ->record their membership to channel in data model
                            if no (they are a member of the hfla workspace but not of the channel),
                                add them to the channel
                                record their membership to channel in data model
                        add a link to their vrms dashboard that will take them to the channel anytime.

Resources/Instructions

https://api.slack.com/methods#users
https://api.slack.com/methods/users.lookupByEmail
https://api.slack.com/methods/users.conversations
https://api.slack.com/methods/conversations.members

**Comment by switchzer0** [comment]
### Update
Should revisit and document pending completion of #255 (roadmap/release-plan phasing for MVP) and in conjunction with crafting #225 (PRD)

**Comment by switchzer0** [comment]
slack requirements have been defined through both v0.4 UI/UX design and PRD.
