### ISSUE TITLE
Update Success page to include Zoom link

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#190]
### Overview
Update the current Success page to show the appropriate project links upon successful check-in

### Dependency
Put Zoom link into the data model and adding to db #214 

### Action
- [ ] Update Success page with new components
- [ ] Pull associated project info with event

**Comment by Jonathanko52** [comment]
Progress: None
Blocks: Need Zoom link to be in database somewhere. Need to know how to find it
Availability: 24/7
ETA: ?

**Comment by Jonathanko52** [comment]
Progress: In Progress
Blocks: None
Availability: 24/7
ETA: 8/17

**Comment by Jonathanko52** [comment]
Progress: In Progress
Blocks: Database issues
Availability: 24/7
ETA: 8/24

**Comment by alex-anakin** [comment]
Obsolete
