### ISSUE TITLE
Develop Authentication model and implement

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#191]
### Overview
Research Auth0 implementation for both front and back end (API) and implement

### Action Items
- [x] Set up Auth0 on the client side.
- [ ] Successfully connect with an API test call that verifies/authenticates through Auth0.
- [ ] Implement authentication and authorization at a global state level using Auth0.
- [ ] Migrate Auth0 credentials over to using a HackForLA account.

**Comment by clockwerkz** [comment]
I looked over Auth0 over the weekend after attending Tyler's presentation on Wednesday. The workflow is interesting - the authentication would occur on the client side, and would package a token to make requests to the back end with. The back end can deserialize a token and check if it's valid or not before responding back with any protected data. 
The last piece of the puzzle I'm currently looking into is how we can extract user info from the token to then query the db for their profile.

**Comment by clockwerkz** [comment]
I currently have Auth0 set up on the client side, I'm currently working on making an API call to a protected test route on the back end that uses Auth0 authentication/verification. 
Currently, I'm using my own Auth0 account for the registration of the service; we'll need to set up a new or use an existing HackForLA account.

**Comment by alex-anakin** [comment]
@alex-anakin will ping Carlos

**Comment by clockwerkz** [comment]
Progress: I have Auth0 working on the client side.
Next Step: Connecting the back end to authenticate/validate the user's Auth0 token.
Blocks: No blocks, but I will need to switch out my personal Auth0 keys to a HackLA account.
ETA: 08/17/2020
Availability: Weekdays 6 PM - 10 PM

**Comment by clockwerkz** [comment]
@alex-anakin  and I discussed this task today; it's a fairly large and complex task to implement at the moment, and there are currently other sections of the project that would be better to focus on atm. So this is going on backlog temporarily, and will be more than likely broken up into smaller incremental tasks in the future.

**Comment by alex-anakin** [comment]
Obsolete
