### ISSUE TITLE
Proposed Feature: Onboarding Select Social Issue

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#193]
**Purpose:** to allow users (e.g., those without a particular skill) to self-categorize around interest or subject matter expertise
**Description:** a field in onboarding/matching/user profile that lets them select (or unstructured data string) an interest area e.g., environment, criminal justice reform
**Proposed Iteration:** second iteration
**Notes:** NA

**Comment by sarL3y** [comment]
@switchzer0 

This feature currently exists for returning users as the question they are required to answer before checking in (if they haven't already answered it), **but** we temporarily removed it to expedite the returning user check-in process and alleviate the multiple button-click process per user feedback. 

We could move this to the live iteration of the new user check-in form. 

My question would be is this a valuable and necessary field to require in the new user process now, or can it wait until the proposed second iteration where a user profile would be provided for self-categorization-types of questions?

**Comment by switchzer0** [comment]
offline discussion with @rachelwhaley was that it would allow subject matter experts and volunteers without skills but who are passionate about certain causes to ID themselves, and aid in matching in later iterations.

Not important for MVP, just didn't want it to get lost

**Comment by juliagab56** [comment]
@juliagab56
