### ISSUE TITLE
Add environment variables to Docker files 

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#2]
### Overview
Environment variables may be needed for local development

### Action Items
Add environment variables to Docker files

**Comment by sarL3y** [comment]
#67 addresses this issue, but will wait to merge until after Summit

**Comment by alex-anakin** [comment]
@alex-anakin check the #67 out

**Comment by nickbeaird** [comment]
I would suggest that this one can be closed. The ticket is no longer relevant with the work done to move all variables to the .env files in the frontend and backend.
