### ISSUE TITLE
AddToRoster component

### ISSUE THREAD

**Issue by patrickgus** [hackforla/VRMS#210]
### Overview
A project leader should be able to add a team member to the roster by their email address.

### Action Items
- [x] develop component

- [x] wire up to the back end

- [x] add function that checks if the user is already on the roster

**Comment by ExperimentsInHonesty** [comment]
@patrickgus 
1. Progress - finished will be merged into master
2. Blocks - none
3. Availability - n/a
4. ETA- n/a

**Comment by patrickgus** [comment]
Need to add function that checks if the user is already on the roster

**Comment by ExperimentsInHonesty** [comment]
1. Progress: One last part: Need to add function that checks if the user is already on the roster
2. Blockers : None
3. Availability: Everyday after 3.
4. ETA: mid week

**Comment by patrickgus** [comment]
1. Progress: Almost done. Just need to test to see if it works.
2. Blockers: Need projects array in user objects to be populated
3. Availability: Weekdays after 3pm
4. ETA: n/a

**Comment by sarL3y** [comment]
@patrickgus @rachelwhaley My understanding from our data expert was that it wouldn't be wise to have an array of projects on the user object directly while also having a separate roster collection. Every time we add someone to a roster (projectTeamMember collection), we would also need to update the array on the user object, which creates a duplication in the database that now must be maintained and accounted for any time the information then needs to be changed/deleted. 

If you query the projectTeamMember collection on the backend using the corresponding project ID and user ID, you should be able to see if someone is already on the roster. This might take a two-step process of first querying the user collection by email to get the user ID (if it exists), then passing the project ID and user ID in parameters to the projectTeamMember collection query.

**Comment by patrickgus** [comment]
1. Progress: Need to add condition that checks if user is already on the roster
2. Blockers: Need help to query projectTeamMember and user collection in the backend
3. Availability: Weekdays after 3pm
4. ETA: n/a

**Comment by ExperimentsInHonesty** [comment]
@alex-anakin will help after reviewing code base.

**Comment by patrickgus** [comment]
1. Progress: Code is finished but it needs to be tested
2. Blockers: Need data on project leader dashboard to test if it works
3. Availability: Weekdays after 3pm
4. ETA: n/a

**Comment by OlgaBilogurova** [comment]
Sorry, closed accidentally

**Comment by patrickgus** [comment]
Progress: Done
Pull Request: #238

**Comment by patrickgus** [comment]
Progress: Done. Resolved all requested changes and fixed bug.
Pull request: #238
