### ISSUE TITLE
Implement a new way how to calculate displaying stats on the admin dashboard

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#213]
### Overview
A lot of the calculations are broken because of moving from 3 events per week to 15.

### Action Items
1. Figure out the correct way of calculating stats
2. Implement calculations 
3. Cover new business logic with tests

### Resources/Instructions
Not available

**Comment by ExperimentsInHonesty** [comment]
1. Progress: identified information missing
2. Blocks: need to talk to @sarL3y to understand which properties will help change the event length, @Jonathanko52 will fix undefined fields.
3. Availability:  between 10-5 minus interviews
4. ETA: unknown because of blockers

**Comment by ExperimentsInHonesty** [comment]
@OlgaBilogurova here are the 5 colors you will need - see issue https://github.com/hackforla/VRMS/issues/218

**Comment by OlgaBilogurova** [comment]
Implemented new calculations for the Admin Dashboard. 
Developed 2 Charts for "all event types" and for "hacknight only" property with displaying locations.

Before:
1. https://monosnap.com/file/bGaSO4i4PgyFepULm8jc7fBMD7VuIS
2. https://monosnap.com/file/qbOUMHR0QZuoxCNzcT2TUo7oelDgI3
3. https://monosnap.com/file/zh96gCmkiPufBKXywUqC61teRFbxOS
4. https://monosnap.com/file/CFxhGrlT07TJNcphVjRmlyeFS6lPjm

After:
1. https://monosnap.com/file/4b3riM2SCyGSPn1V9coBatq6eG2CtJ
2. https://monosnap.com/file/NwWCbfyy9CQsIUzYGSq7O2mfP1KifT
3. https://monosnap.com/file/DF7Mbq4RjEyB2K4nB2Za7XlWv23Tn6

Pull request:
https://github.com/hackforla/VRMS/pull/217

**Comment by OlgaBilogurova** [comment]
> @OlgaBilogurova here are the 5 colors you will need - see issue #218

Great, thanks. I'll update charts using new colors.

**Comment by OlgaBilogurova** [comment]
Updated charts using new colors.

Before:
https://monosnap.com/file/iUv39vM38p8oAb3r0Yc3pc7cEWpek5

After:
https://monosnap.com/file/Bd1pXHUp0RjnKfjRbS9CeJfDhveIxb
https://monosnap.com/file/OySZFCINKDQbM7WGoAZobJ0eisDUUQ

Pull request: https://github.com/hackforla/VRMS/pull/217
