### ISSUE TITLE
Search for experience tech lead

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#215]
### Overview
We need some advice, experience and help

### Action Items
Identify the skills/experience you want them to have.

**Comment by patrickgus** [comment]
Team lead should have extensive proficiency in React, Node, and MongoDB

**Comment by patrickgus** [comment]
Experience working with, building, and documenting APIs

**Comment by Rankazze** [comment]
Advanced skill level in breaking down work tasks into issues that are workable chunks.  Taking into account the current skill level & variability of availability of our volunteer dev team when crafting the issues.

**Comment by Rankazze** [comment]
Passionate about helping the next crop of developers gain the competence and confidence to ship valued quality working code.

**Comment by Rankazze** [comment]
An understanding of the Agile Mindset and how to manage up within a dynamic operating environment.

**Comment by OlgaBilogurova** [comment]
- Leadership and mentorship - helping other developers, sharing technical knowledge, delegating responsibilities
- Software Architecture - designing application structure and API, providing technical solutions for complicated features
- Maintaining codebase quality - introducing clean code best practices, doing code review, approving pull requests

**Comment by ExperimentsInHonesty** [comment]
have potential candidates contact Bonnie@hackforla.org

**Comment by ExperimentsInHonesty** [comment]
@alex-anakin welcome!!!
