### ISSUE TITLE
Document MongoDB Access

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#216]
### Overview
Document access to github for the team 

### Action Items
Need to document: 
- [ ] How to get a user in our mongo instance
- [ ] How to set up test space for testing

### Resources/Instructions
Add this documentation to the wiki

**Comment by sarL3y** [comment]
@ExperimentsInHonesty and @rachelwhaley have been given admin-level access. 

The server root env file that the developers are using contains credentials to access the "testdb" database in the MongoDB dashboard. This has been the persistent testing environment, but it does not reflect the "live" data. The development version in staging on Heroku also uses these test credentials (environment variables are located in the settings tab) to test the app after pushing to development on Heroku. The production version of the app on Heroku uses different a different environment variable in the settings tab for the MongoDB connection to the live database. I can provide the connection string if needed, or it should be available from MongoDB.

**Comment by alex-anakin** [comment]
Need to have protected document for credentials @ExperimentsInHonesty

**Comment by nickbeaird** [comment]
I believe that this can be closed when https://github.com/hackforla/VRMS/pull/264 gets merged.

**Comment by alex-anakin** [comment]
Should be prioritized again when the test database will be moved to the local environment. Blocked by #1
