### ISSUE TITLE
Update Color Palette options for multiple orgs and user preferences

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#218]
### Overview
We need a Color palette and a Style guide both for Product artifacts and a more comprehensive one for Developers. 

### Action Items
- [ ] We need to take the current Palette and identify other complimentary colors asap.  This item is holding up some development work to re-visualize the Stats.  See resources for current pallet.  We need a minimum of 5 colors.  We can always change this later, but we need something now.
- [ ] Please review this deck which manages to capture the feel we are going for https://docs.google.com/presentation/d/1CebVXu6phZ9mx6AF-hrYeV_2981BZkHRKIrWtpR37vo/edit#slide=id.g7e9da59040_0_24
- [ ] The style guide should be in figma.  Here is an example of a style guide for the hack for la website: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1695%3A13302

#### Old stats.  We ran out of colors
![Screen Shot 2020-07-15 at 12 07 30 PM](https://user-images.githubusercontent.com/37763229/87585914-9a099480-c694-11ea-874d-3c8e69c2189a.png)

#### New colors
![Temp color palette](https://user-images.githubusercontent.com/37763229/87597144-24a6bf80-c6a6-11ea-9bb4-6cf94a0c96a0.png)

```
/* CSV */
3f7589,172d47,bd3346,999999,d9d9d9

/* Array */
["3f7589","172d47","bd3346","999999","d9d9d9"]

/* Object */
{"Teal Blue":"3f7589","Prussian Blue":"172d47","French Raspberry":"bd3346","Spanish Gray":"999999","Gainsboro":"d9d9d9"}

/* Extended Array */
[{"name":"Teal Blue","hex":"3f7589","rgb":[63,117,137],"cmyk":[54,15,0,46],"hsb":[196,54,54],"hsl":[196,37,39],"lab":[46,-12,-16]},{"name":"Prussian Blue","hex":"172d47","rgb":[23,45,71],"cmyk":[68,37,0,72],"hsb":[213,68,28],"hsl":[213,51,18],"lab":[18,1,-19]},{"name":"French Raspberry","hex":"bd3346","rgb":[189,51,70],"cmyk":[0,73,63,26],"hsb":[352,73,74],"hsl":[352,58,47],"lab":[44,56,22]},{"name":"Spanish Gray","hex":"999999","rgb":[153,153,153],"cmyk":[0,0,0,40],"hsb":[0,0,60],"hsl":[0,0,60],"lab":[63,0,0]},{"name":"Gainsboro","hex":"d9d9d9","rgb":[217,217,217],"cmyk":[0,0,0,15],"hsb":[0,0,85],"hsl":[0,0,85],"lab":[87,0,0]}]
```

**Comment by switchzer0** [comment]
@cicyhou FYI

**Comment by switchzer0** [comment]
whoever picks this up should discuss current status with @switchzer0 before proceeding since this issue has aged significantly in the icebox

**Comment by juliagab56** [comment]
Outdated issue
