### ISSUE TITLE
Define global styles rules for starting to implement a new UI

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#223]
### Overview
The goal is organizing scss code and making it easy to share common design rules through the project. It's important to do from the beginning when starting to implement a new UI. This will save a lot of time in developing the next components with a new UI.

### Action Items
- Create variables, nested rules, mixins
- Use all superpowers of scss preprocessor to help optimize and organize styles
- Make styles easy to use inside react components 

### Dependencies
A style guide for a new design is good to have for development. 
The style guide should provide the following:
- Primary elements such as the color palette, fonts, headings, type of buttons, icons, and so on
- An overview of the styles for the app and how styles should be used

### Resources/Instructions
Please, take a look at the attached examples.

![1-style-guides](https://user-images.githubusercontent.com/11681030/88115746-bbbebc00-cb6b-11ea-898c-ee3370e96741.png)
![2-ui-style-guide](https://user-images.githubusercontent.com/11681030/88115749-be211600-cb6b-11ea-9db8-c4fec581def8.png)

@cicyhou, please, let me know if you have any questions.

**Comment by OlgaBilogurova** [comment]
Progress: None
Blockers: Need to have a style guide from @cicyhou
Availability: Weekdays 10 am - 5 pm
ETA: n/a

**Comment by alex-anakin** [comment]
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23593%3A2779

**Comment by OlgaBilogurova** [comment]
@cicyhou created the style guide #227 and shared it with me.

**Comment by OlgaBilogurova** [comment]
Progress: in progress
Blocks: none
Availability: weekdays 10am - 5pm
ETA: till next Monday - 8/10

**Comment by OlgaBilogurova** [comment]
Progress: 
New files were created inside the `sass `folder
> /components (a directory which has a .scss file for each React component)

> /pages (a directory which has a .scss file for each page that requires custom styles)

Files:
_variables.scss (this file store any variables (based on the style guide) that will be used throughout styles)
_main.scss (this file store main styles for all app)
_elements.scss (this file store any generic styles for elements in the app)
_mixins.scss (this file store any mixins (style snippets) that will be used over and over)
_keyframes.scss (this file store any keyframes or animations for the app)

Imported all main scss files to App.scss. Commented while the current UI is working.
Created a pull request.

**Comment by OlgaBilogurova** [comment]
Added new directory 'sass-new-ui'. All files regarding new UI moved into this folder. Added fonts, normalize, and local reset. 
Everything described at [UI-Development-Guideline](https://github.com/hackforla/VRMS/wiki/UI-Development-Guideline).
@alex-anakin please, review the pull request.

**Comment by OlgaBilogurova** [comment]
Progress: Done. 
Blocks: Pull request #253 is waiting for code review
Availability: Weekdays 10 am - 5 pm
ETA: -
