### ISSUE TITLE
Create a test DB instance with an actual data set

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#224]
### Overview
Developers need to have a test DB with data that is close to real production DB except for personal data. 
To avoid any issues it is better to prepare the second test DB and start it in parallel with existing test DB. Then completely switch to the second DB and shut down the first instance.
Also, it is a good chance to try a cloud MongoDB instance.

### Action Items

- [ ] Create MongoDB new instance on the MongoDB cloud platform.

- [ ] Develop a script for migrating data from the production DB to the new DB. The script should secure emails and phone numbers. See the instructions for the details.

- [ ] Run the script, check out the personal data securing quality

- [ ] Provide URL and credentials for the new DB in this issue.

### Resources
Cloud hosting for MongoDB: https://www.mongodb.com/pricing
Choose free tier, use HackForLA work email for registration, no credit card required.

### Instructions
The migration script should replace:
* letters in emails username from forth to the last by "*" (don't change emails domain part)
* numbers in phone numbers from the second to 8th by "0"

**Comment by rachelwhaley** [comment]
@alex-anakin I don't have a "HackForLA work email", so if someone else (@ExperimentsInHonesty ?) could do the initial set up the Mongo account, that would be great.

**Comment by alex-anakin** [comment]
The task is done.
