### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#23]
### Overview
Add Authentication. Current model uses role-based selection. We need to decide if that's the correct method for our product and pivot if needed. Ideally, we'll use a combination of magic links for users and 2FA for admins.

### Dependency
Full implementation will require new user roles once they have been added: Implement New User Roles #30 

### Requirements
* [x] Front End Developer
  * [x] Understanding of React Hooks implementation with global state management 

### Action Items
Front End:
* [x] Utilize current React Hooks and Context to implement ~Auth0~ Firebase

**Comment by sarL3y** [comment]
I pivoted from Auth0, and went with Google’s Firebase. After a good amount of research and consideration, this one provided the easiest, most secure implementation for our needs. I also went with passwordless authentication for several reasons:
1) Users of this app may only be logging in once or twice a week to begin with, and remembering a password is frustrating (as well as unsecure, if repeatedly used in their personal suite of apps). By using passwords, we would have been required to use an email service for resets anyway, so this implementation removes that step.
2) Passwordless is essentially token-based, so it gives us a foundation for easily implementing social auth providers.
3) It's simple (relatively) to secure the front end with authentication being managed in global state using React Context and a Firebase class. This also means faster loading because React won’t render components that shouldn’t be shown based on access level.
4) Time to market, we’re nearing the home stretch!

Cons: 
1) I had to build a couple more pages and routes when Auth0 would have provided pre-built components to use.
2) There is a known issue with Safari that prevents Google's auth redirects from doing their job. Clearing your cache and enabling cross site tracking in Safari settings works for now. This also might be fixed by pushing to production, since Heroku adds another redirect with their temporary/subdomain apps. Info here: https://support.securly.com/hc/en-us/articles/360000881087-How-to-resolve-the-too-many-redirects-error-on-Safari- and https://support.apple.com/en-ie/HT203370

Next steps: 
1) Verify that the user is already in the database and has the proper access level (should be done by Monday but wanted to get feedback on the auth flow first). Remember this development site is using fake data, so nothing will be compromised.
2) Move Firebase project to a dedicated VRMS account. This will allow us to use a custom-formatted message when sending the links, as well as an official @vrms.io domain.
No regular members would be allowed to use this feature until member dashboards are ready (they will be turned away at the login screen because of access level), but this provides a great way to get an organizer secured right now.

**Comment by vadzimk** [comment]
@sarL3y @drubgrubby I've noticed a warning that might be related
![image](https://user-images.githubusercontent.com/28674835/128270037-d26d5aad-57b4-46e7-8685-924657743fcc.png)

I suppose that it is coming from all components that call the useAuth() hook, correct me if it is not the case.
Any such component that unmounts for whatever reason before the response form fetch comes back emits this error.
