### ISSUE TITLE
Split Front/Back End files

### ISSUE THREAD

**Issue by Jonathanko52** [hackforla/VRMS#231]
Front end(client) file is nested in back end of the project. Split it into two files.

### Action Items
-See if it's best practice to separate front end and back end into different repositories. 
-Move client file to root
-Fix and break/calls that come from that
     -Make sure back end routes are serving right files.
     -Front end still calling correct routes
     -create one package.json(?)

**Comment by Jonathanko52** [comment]
Progess: Researched best practices. Reorganizing React files.
Blockers: None
Availability: 24/7
ETA: Next week.

**Comment by nickbeaird** [comment]
See https://github.com/hackforla/VRMS/pull/264
