### ISSUE TITLE
revise style guide

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#240]
### overview
initial style guide should be revisited, updated, and fleshed out with more detail once designs for MVP are complete

**Comment by switchzer0** [comment]
### Progress
Underway, waiting on blockers due to PM/Adam's assigned prioritization.

### Blockers
Cicy working through remaining mobile designs for onboarding flow, in order to deliver complete collection of mobile screens for review/approval.

### ETA
1-2 weeks

### Availability
NA

**Comment by juliagab56** [comment]
Outdated issue
