### ISSUE TITLE
One button for event check-in on the home page

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#242]
### Overview
![VRMS check-in buttons](https://user-images.githubusercontent.com/11644789/89260634-88574500-d5e1-11ea-9691-76e1da948dba.png)

Any user should be able to select an event in the drop-down list (1) then enter an email into the input (2) and then click one button "Check-in". If the user performs check-in the first time then the personal info page should be shown. 

### Instructions
1. Remove one button, rename the remaining to "Check-in".
2. Call user API to check out if a user had previous check-ins.
3. If yes then show the success page.
4. I if not then display the page for user to provide personal info, save it and show the success page.

**Comment by dae-hyun-kim** [comment]
1. Progress - Created new email input field and removed one check-in button. Trying to figure out how to utilize checkInForm component functions. (May need to rewrite code completely)
2. Blockers - May need to discuss with other devs if some of the code in checkInForm component is necessary
3. Availability - After 6pm M-F
4. ETA - Possibly 5/24

**Comment by dae-hyun-kim** [comment]
1. Progress - None
2. Blockers - Can't access db on dev environment
3. Availability - After 6pm M-F

**Comment by dae-hyun-kim** [comment]
1. Progress - Deleted commented code, and discussed with devs about previous code. Currently just need to complete conditional to check with backend if email exists.
Blockers - Need help with how to write conditional method while utilizing current code. Will contact Nick or Carlos for help.
Availability - After 6pm M-F

**Comment by switchzer0** [comment]
FYI depending on how implemented may relate to #282 (Swap position of new/returning user buttons)

**Comment by alex-anakin** [comment]
@dae-hyun-kim please provide details about your progress

**Comment by dae-hyun-kim** [comment]
1. Progress - Was unable to complete and got stuck. Asked Jonathan if he could take a look and complete
2. Blockers - Couldn't figure out how to complete existing member login

**Comment by patrickgus** [comment]
Progress: None
Blockers: Need to get in touch with @dae-hyun-kim to see progress and figure out what problems there are.
Availability: Weekdays after 3pm
ETA: N/A

**Comment by patrickgus** [comment]
Progress: Just starting with some planning on how to approach this task.
Blockers: None
Availability: Weekdays after 3pm
ETA: 2-3 days

**Comment by patrickgus** [comment]
Progress: None
Blockers: None
Availability: Weekdays after 3pm
ETA: 2-3 days

**Comment by patrickgus** [comment]
@alex-anakin and I discussed this task and found that there are big differences between the old functionality and new implementation. It is much more complex to complete and we decided to mark this as done so we can focus on more important tasks and revisit this later.
