### ISSUE TITLE
Update Admin Dashboard

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#25]
### Overview
The admin dashboard is the hub for all things related to managing a brigade of volunteers. It should provide data about the brigade, and tools for the admin to create and update events, open check-in time for hack nights, and oversee the human capital development of the organization through project and volunteer management.

### Dependency
Research Admin Dashboard Requirements #31 

### Requirements
* Front End Developer
* Back End Developer

### Action Items
Front End:
* [x] Utilize data fetching and components to display brigade data/stats
* [x] Ensure components are modular so they can be reused for "user" and other dashboards

Back End: 
* [x] Implement queries to database to retrieve the data we need

**Comment by rachelwhaley** [comment]
This epic was split into several smaller tickets:

- @39
- @40
- @41
- @42

**Comment by rachelwhaley** [comment]
This epic has been started and broken down into more granular user stories:
- #39 
- #40 
- #41 
- #42

**Comment by sarL3y** [comment]
Updating styles per https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=22881%3A2844.

Related to #15

**Comment by sarL3y** [comment]
Broke HfLA logo height (Chrome mobile).
Broke "Location:" drop-down styling (Chrome mobile).
