### ISSUE TITLE
Create a "UI Development Guideline" inside the project Wiki

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#254]
### Overview
Confirmed by @alex-anakin that we need to have Development Guidelines for the project. 

Update the project wiki with the new "Development Guidelines" section.
Create a "UI Development Guideline" and write documentation for it. 

### Action Items

- [x] Create a "Development Guidelines" page
- [x] Update the wiki Home page by adding "Development Guidelines" section
- [x] Create a "UI Development Guideline" page
- [x] Update "Development Guidelines" page by adding "UI Development Guideline" section
- [x] Write documentation for "UI Development Guideline" page

**Comment by OlgaBilogurova** [comment]
@alex-anakin please review [UI-Development-Guideline](https://github.com/hackforla/VRMS/wiki/UI-Development-Guideline)

**Comment by OlgaBilogurova** [comment]
Progress: Done
Blocks: Waiting for review
Availability: Weekdays 10am - 5pm
ETA: -

**Comment by alex-anakin** [comment]
Reviewed, no findings. Great work!
