### ISSUE TITLE
Prevent check-in of returning user with empty email

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#258]
### Overview
Check-in button after choosing "returning user" for check-in should be disabled when email input is empty. 

![VRMS check-in bug](https://user-images.githubusercontent.com/11644789/90470132-886e3f00-e0cf-11ea-8a06-4bf4fc8a0b39.png)

### Action Items
Add a simple validation for the email field and disable the button when the field is empty.

**Comment by OlgaBilogurova** [comment]
This task was done, as #376
