### ISSUE TITLE
Change pre-Alpha version number

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#26]
### Overview
pre-Alpha version has reached user milestone of 100+ active users.  Production is stable at that load.  Increment has been earned.

### Action Items

Increase pre-Alpha versioning to 0.2

**Comment by ExperimentsInHonesty** [comment]
updating the package.json file.  and setup relases.  Write up proposal and then review with Kegan.

thanks to Steven for https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by sarL3y** [comment]
Using https://docs.npmjs.com/cli/version as well. 

`npm version major` to increase X.#.#
`npm version minor` to increase #.X.#
`npm version patch` to increase #.#.X

Must be done twice (both package.json files). First in root, second in client.
