### ISSUE TITLE
Create Frontend Component Guideline Template

### ISSUE THREAD

**Issue by Jonathanko52** [hackforla/VRMS#261]
![Current](https://user-images.githubusercontent.com/30099154/92829514-28df1880-f389-11ea-9a0e-c202885b10f0.png)
![After](https://user-images.githubusercontent.com/30099154/92829521-2a104580-f389-11ea-91dc-0c374ba6c651.png)
![Before](https://user-images.githubusercontent.com/30099154/92829525-2b417280-f389-11ea-8e40-f14c7c4c9ebc.png)

### Overview

    Client folder currently lacks structure. Collection of images, fonts, js files, css files pushed up to where individual 
    developers think they best fit.

     Goal is to create a consistent structure and guidelines for everyone to follow so developers have an easier time finding 
     old files and know where to place new files.

### Resources/Instructions

How to Organize Your React + Redux Codebase
https://www.pluralsight.com/guides/how-to-organize-your-react-+-redux-codebase

File Structure
https://reactjs.org/docs/faq-structure.html

VRMS Wiki
https://github.com/hackforla/VRMS/wiki/Development-Guidelines

**Comment by Jonathanko52** [comment]
Progress: In Progress
Blocks: None
Availability: 24/7
ETA: ?

**Comment by OlgaBilogurova** [comment]
Discussed with Jonathan this task and his progress.

Current progress:
- created page [React-Component-Structure](https://github.com/hackforla/VRMS/wiki/React-Component-Structure) inside the Wiki. Described goals and some future required changes.
- no local branch, any changes inside the project

**Comment by OlgaBilogurova** [comment]
Progress: 
- started to organize the `admin `component
- inside the admin component created 2 directives: `dashboard`, `reports `and moved appropriate files there
- created a new directory `common` for reusable components, moved a `datapicker `and `tabs` component inside this folder 

![VRMS – index test js 2020-10-05 18 21 21](https://user-images.githubusercontent.com/11681030/95148222-a6533a00-0737-11eb-8f19-09a12cd6b841.jpg)

Blocks: None
Availability: Weekdays
ETA: N/A

**Comment by OlgaBilogurova** [comment]
This task is obsolete and needs to be closed.
Set up the new app `client-mvp-04`. Task #327.
