### ISSUE TITLE
Add a new event to the recurring events worker

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#262]
### Overview
Add a new event to https://github.com/hackforla/VRMS/blob/master/workers/createRecurringEvents.js worker:
* type: HackNights
* day: Tuesday
* time: 6 pm - 8 pm

This a hotfix so a pull request should be created to `master` branch. The deadline is Monday, before 7 pm.

**Comment by clockwerkz** [comment]
I wrote up a script that will enter in a recurring event into the database. I'm testing it with a test recurring event set for Friday (08/21/2020). If that works out, I'll mod the script for the new recurring event on Tuesdays. In the meantime, There's some additional info I could include when I create the event, such as:
name, hacknight, eventType, description, and if it's tied to any existing projects
This is optional info, but would definitely be helpful.
Something to note: Currently, the recurringEvent model's date property is not required; this *should* be as the backend pulls this date to check if it needs to generate an event from.

**Comment by clockwerkz** [comment]
**Progress** -Pending Complete:  I went ahead and entered in the event into the recurringevent collections. Will close after the cron job runs correctly and creates an event for the meeting on Tues (08/25/2020). 
Also found a bug with the events generator, will submit a PR via the development branch.
**Blockers** - None
**Availability** - After 6pm M-F

**Comment by Rankazze** [comment]
In reviewing/validating the Live HackforLA.org site  we need to fix our typo from "for"  to "or"  in the following: "On boarding for Happy Hour"
@alex-anakin @clockwerkz 
Thanks

**Comment by Rankazze** [comment]
Confirmed the selection loaded in the pick list.
