### ISSUE TITLE
Get rid of Firebase

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#267]
Details will be added later

https://reallifeprogramming.com/how-to-implement-magic-link-authentication-using-jwt-in-node-8193196bcd78
https://medium.com/one-more-thing-studio/how-to-make-magic-links-with-node-1d164c036e29

**Comment by ye-susan** [comment]
SMTP Options: 
- **Twilio's SendGrid**:  free account allows you to send up to 100 emails/day or $15/mo for 50k emails per month
- **SendinBlue**: provides 300 emails/day for free
- **ElasticEmail**: cheap pay as you go plan, 9 cents per 1000 emails
(more options [here](https://www.wpoven.com/blog/free-smtp-servers-sending-emails/))

**Comment by alex-anakin** [comment]
@ye-susan please list open-source solutions

**Comment by nickbeaird** [comment]
Progress: Added two PRs (see associated PRs to this ticket). The first added a backend API point and basic email functionality. I created a gmail account and added the credentials to our 1Password. The second PR adds this work to the frontend. it needs some work still. 

Blockers: Time and context. The functionality pretty much replaces what we had with Firebase and uses a magic link email token. I have deferred to Alex based on security. Also, I am unsure on how to enable a logout method with the solution created. 

Availability: One or two nights this week. 

ETA: If approved, it will be merged, or if there are changes requested by Alex and the team.

**Comment by nickbeaird** [comment]
Progress: 2 PRs are placed. The final one removes Firebase

Blockers: 
* Requires review and feedback. 
* Approval on moving forward without a logout function. If that is out of scope, then this is done. Alex stated that he might have some thoughts on how to make that happen. I will defer to the loudest party at this moment 😆. 
* This story also blocks our Docker work. We need working auth that works with localhost to add tests before refactoring the app to be within a container. If not, we may be working blind on breaking the admin page. 

Availability: Mid day after work 3-430pm

ETA: Upon review and approval/help.

**Comment by alex-anakin** [comment]
@nickbeaird What is the question for this task?

**Comment by nickbeaird** [comment]
@alex-anakin, it revolves around the blockers. The following relates to the posted blockers listed above and the questions that I asked you in a group DM (yourself, Carlos, and Susan).

1. When I sent in this PR in a group DM on Slack, you stated that you would follow up and take over the work. Do you still want to do that, or are you wanting me to follow this through?

2. I am wondering if putting this token in the Cookies is a valid path. Can we use cookies to store this for the long term? And if not, can we use them in the short term?

3. This does not have a super valid logout mechanism. Are we okay with moving this through and adding in a ticket for following up on that?

**Comment by alex-anakin** [comment]
1. PR #290 is the implementation of the task. It is almost done and will be merged soon.
1. We are good at using Cookies.
1. It's completely fine.
