### ISSUE TITLE
Add Project collection to the database

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#27]
### Overview
Build a Projects collection in the database to contain information about each project and its team. 

### Action Items
* [x] Research and propose requirements needed to develop a project collection
* [x] Add Projects collection to database
* [ ] Add necessary project API routes and querying abilities

**Comment by ExperimentsInHonesty** [comment]
Progress: Sent initial design to Matt, setup mongo DB. 
Blocks: Need to discuss with team how to setup with NoSql setting.
Availability: Wed and Thursday evenings
ETA: later this week, on the db stuff and next week on the API stuff

Bonnie will find DB person for Rachel and Matt to review.
