### ISSUE TITLE
Add BallotNav project to the project database

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#271]
### Overview

The meeting times on the hackforla website are driven by an VRMS api. So incoming requests for changes to that page, have to be sent here to be updated manually. We need to add this new project the output.

### Action Items

Add meeting time (in-progress):

- [x] Tuesdays: 6:00pm-8:00pm (Pacific) Team Meeting

- [x] Thursday: 5:30pm-7:30pm (Pacific) Team Meeting (added 09/04/2020) 

- [x] Saturdays: 4:00pm-6:00pm (Pacific) Management Meeting

- [ ] Notify BallotNav team (via their issue below), that this has been added so that they can perform User Acceptance Testing

Resources/Instructions

[Hack for LA team meetings page](https://www.hackforla.org/project-meetings)

**Comment by Rankazze** [comment]
Randall GitHub:  @arjayellis   Slack: @ Randall is the Point of Contact on the BallotNav team for this issue

**Comment by clockwerkz** [comment]
I messaged Randall for some project info and will be adding this project/recurringevent to the vrms database.

**Comment by clockwerkz** [comment]
Status: In-progress
Details: I heard back from Randall; I just need to send him a set of questions to fill out the fields in a new Project entry, and enter the project into the database.
Blockers: None

**Comment by Arjayellis** [comment]
@clockwerkz @ExperimentsInHonesty Following up on this request. Will you be sending over the questions? We are hoping to have everything up on the website by Thursday as that is when we will be pitching to Hack for San Jose. Thank you!

**Comment by clockwerkz** [comment]
@Arjayellis Yep! I'm just having one of our PMs confirm some of the data we'll need and I'll send it over to you promptly.

**Comment by clockwerkz** [comment]
Ok I emailed you those questions - I'll set it up as soon as I get that info back.

**Comment by Arjayellis** [comment]
We currently have a project card open at the website repo for them to add us to the website. I believe it has all the details you are looking for. https://github.com/hackforla/website/issues/703

**Comment by Arjayellis** [comment]
Tuesdays: 6:00pm-8:00pm (Pacific) Team Meeting
**Thursday: 5:30pm-7:30pm (Pacific) Team Meeting**
Saturdays: 4:00pm-6:00pm (Pacific) Management Meeting

Newly created meeting times in bold

**Comment by clockwerkz** [comment]
Ok I'll add in Thursday as a new recurringevent for BallotNav.

**Comment by clockwerkz** [comment]
BallotNav is not showing up in the dropdown list for events today (Saturday). I'll need to look into this and see why the cronjob did not pick up the recurringevent and create a new checkin today.

**Comment by Arjayellis** [comment]
Hi Carlos. How is it coming? Anything I can do to help?

**Comment by clockwerkz** [comment]
@Arjayellis I just added Thursday's meeting. I will be checking around 5 to see if the dropdown shows your meeting on the vrms website tomorrow. :)

**Comment by clockwerkz** [comment]
@Arjayellis did you have your members sign in? It's in the dropdown list on vrms.io. 👍

**Comment by Rankazze** [comment]
Tuesday loaded in the Pick list

**Comment by alexandrastubbs** [comment]
See [this page](https://www.hackforla.org/projects/ballot-nav) - we are getting a problem with 'undefined' under the team meeting times displayed. 

![Screen Shot 2020-09-17 at 4 22 40 PM](https://user-images.githubusercontent.com/66918724/93534296-0d808a00-f902-11ea-8e27-470246326da2.png)

This is also occurring on the team meeting overview page: https://www.hackforla.org/project-meetings

![Screen Shot 2020-09-17 at 4 22 31 PM](https://user-images.githubusercontent.com/66918724/93534338-21c48700-f902-11ea-8f19-f33a193d9013.png)

**Comment by clockwerkz** [comment]
I'll look into it, thanks

**Comment by alexandrastubbs** [comment]
There is a corresponding issue dealing with the above: https://github.com/hackforla/website/issues/735

**Comment by Rankazze** [comment]
Thursday loaded in the Pick list.  Undefined was not there.

**Comment by alex-anakin** [comment]
Done
