### ISSUE TITLE
Attempting to generate a new events from the recurring events collection will cause an exception error if a document does not have a location property.

### ISSUE THREAD

**Issue by clockwerkz** [hackforla/VRMS#273]
### Overview
There is a cron job that periodically scans the recurringevent collections for events to occur on the current day. It then attempts to create new event entries into the events collection. If a given recurrentevent document does not have a location property, it crashes the operation with an exception error.

### Action Items
Include a test for the location property instead of assuming it always exists.

Also, in the short term, make sure all of the recurring events in the production database have a location property.

**Comment by jbubar** [comment]
No progress. was not able to make the time to look over this, in the deep way it needs

**Comment by peteplass** [comment]
@jbubar Please update.

**Comment by maburke09** [comment]
@jbubar please add a role label to this issue
