### ISSUE TITLE
Revise data model

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#278]
### Overview
Data model parameters should match revised 0.4.0 release plan requirements. The existing data model is missing parameters and has vestigial elements, too. Data model should focus on MVP and give at least moderate consideration for requirements through 1.0.0 themes.

### Action Items
- [x] review approved 0.4.0 release plan, existing data model, and 0.5.0 through 1.0.0 requirements
- [x] reconcile needs and draft new non-technical data model
- [x] present and review with engineering team
- [ ] revise and finalize plan
- [ ] implement and approve changes to code

### Resources
[Existing data model code](https://github.com/hackforla/VRMS/tree/master/models)
[Outdated data model relational diagram](https://drive.google.com/drive/folders/1RD3Od4m2EfiGDJQKOjOEcRwZNIqTRB-H)
[Roadmap/Release Plan](https://docs.google.com/document/d/1BlhtbYBbSBlwSKNFupqUwdtKiUluCErIt0Mr4vNzxlA/edit)
[PRD](https://docs.google.com/document/d/15LvzFpLPYjQhpMx58P60onh697ww45fgZm-Sg_FGehw/edit)

**Comment by switchzer0** [comment]
Update: Revisions in progress with reccos and questions/considerations on MVP model parameters.
Blockers: none
Availability: most days
ETA: by next meeting (Mon)

**Comment by switchzer0** [comment]
Update: revisions complete. Overview document posted to Google Drive/Slack.
Blockers: needs team review
Availability: most days
ETA: tentatively next wednesday (after team meeting + revision time)

**Comment by switchzer0** [comment]
Update: still awaiting feedback from dev team
Blockers: initial team review on model components, also #304 (analytics goals)
Availability: most days
ETA: tentatively next wednesday (after team meeting + revision time)

**Comment by switchzer0** [comment]
Update: met with dev team, received input on parameters
Blockers: my general bandwidth as I get the PRD updated first, per direction from @alex-anakin 
Availability: most days
ETA: 2 weeks

**Comment by switchzer0** [comment]
Update: all proposed variables documented for v0.4, documented in [PRD](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#heading=h.hhutmpgbwq8c).
Blockers: meet to review, answer outstanding questions, future-proof, and approve final version with @alex-anakin et al.
Availability: most days
ETA: ~1 week

**Comment by switchzer0** [comment]
Update: finalized `user` and `project`. Next steps to finalize `project team member`, `event`, and `check-in`
Blockers: meeting time with @alex-anakin and dev team members
Availability: most days
ETA: ~1 week

**Comment by switchzer0** [comment]
Update: time spent on resolving database schema, user access level scheme, and some of project team member (now named `ProjectMembership`). Still need to review ProjectMembership, Event, Checkin.
Blockers: meeting time with @alex-anakin and dev team members
Availability: most days except this Friday
ETA: ~1 week

**Comment by switchzer0** [comment]
Finished reviewing all models/values. Drafted dictionaries. Finalized UAL scheme. @alex-anakin reviewing some final relationship issues between projects<->events and GitHub teams questions before we close this out
Blockers: none
Avails: most days
ETA: a few days

**Comment by switchzer0** [comment]
completed review of all models. will review dictionaries and add "event template" model to document in coming few days
Blockers: none
ETA: monday eve after meeting w/ Alex

**Comment by switchzer0** [comment]
Addressed event template and dictionaries this week. Next steps (final odds and ends):
- @alex-anakin tweaking a couple parameters in the recurring portion of event template model.
- @awhig diagramming database schema #437 
- @switchzer0 meeting with @ExperimentsInHonesty to discuss requirements/clarifications/definitions around a few existing matching variables between user and project models
- The implementation action item checkbox for this issue will be made obsolete by specific new issues describing the necessary updates, issues to be created by @alex-anakin once models are finalized.

**ETA to close this issue: 1-2 weeks**

**Comment by switchzer0** [comment]
met with Bonnie to get input on user-project matching variables. can discuss with @alex-anakin when ready

**Comment by switchzer0** [comment]
reviewed outstanding questions w/ @alex-anakin; ready for him to finalize

**Comment by alex-anakin** [comment]
Created the #487 task for fixing the EventTemplate model.
