### ISSUE TITLE
Design onboarding flow screens for mobile

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#279]
### Overview
Deliver designs for onboarding flow mobile-format screens based on Figma wireframes

**Comment by switchzer0** [comment]
### Update
designs reviewed with Bonnie/Adam, Cicy incorporating small feedback items and adding ~2 new screens to flow

### Blockers
none

### ETA
Friday

**Comment by cicyhou** [comment]
update - onboarding screens has been updated based on Adam's feedback. There are a few more things that need to be discussed, plan to do that today during the meeting

**Comment by cicyhou** [comment]
update - onboarding screens are complete and moved to "Approved" section in Figma. Adam had a few additional comments that I still need to address

ETA - next few days

Blockers - none

**Comment by cicyhou** [comment]
update - all except one screen of onboarding are in the final page
Adam will approve one screen

**Comment by cicyhou** [comment]
Update - complete
Will close the issue once Adam signs off this comment

**Comment by switchzer0** [comment]
you're good to go, you have all the approvals you need via figma :) I'll leave you the honor of clicking "close w/ comment" @cicyhou
