### ISSUE TITLE
Modify 1.0.0 designs to create MVP/0.4 screens

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#281]
### Overview
MVP functionality will be limited vs. full 1.0.0 themes contemplated, and so select features will need to be obscured. A few new screens will need to be designed to accomodate intermediate functional needs.

### Action items
- [x] Review front-end technical process with Adam & Olga
- [x] revise sign-in landing screen(s)
- [x] revise onboarding screen(s)
- [ ] revise checked-in screen(s)
- [x] revise main dashboard screen(s)
- [x] revise team roster screen(s)
- [x] revise roster single-user view screen(s)
- [ ] create admin onboarding dashboard -- new screen(s)
- [x] create admin CSV download -- new screen(s)

**Comment by switchzer0** [comment]
Update: Cicy and Adam reviewed assignment, agreed that first step is for Adam to offer comments/wireframes for MVP based on completed v1.0 screens
Blockers: Adam hasn't given direction yet, will unblock Cicy this week
Availability: Adam generally avail throughout week. Cicy N/A
ETA: wireframes to Cicy by next meeting (mon)

**Comment by switchzer0** [comment]
### Update
Unblocked by Adam: new [Figma page](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=24553%3A2603) with MVP-only comments provided. Adam to add additional notes over coming week.
### Blockers
- partial from #300 (co-branding scheme) but shouldn't be too consequential pending convo w/ Olga about SCSS templates
- believe Cicy to be away
### Availability
?
### ETA
? but Adam estimates 2 weeks

**Comment by cicyhou** [comment]
Update - screens that are not finished are admin screens and team roster screens
Blockers - there are a few questions on the completed screens, plan to discuss with Adam today during the meeting
ETA - admin screens and team roster screen should be finished in a week

**Comment by cicyhou** [comment]
Update - need to finalize profile, dashboard, single user and admin screen.
Blockers - not at the moment
ETA - 1 week

**Comment by cicyhou** [comment]
Update - finalized onboarding screens, dashboard, project screen
Blockers - No
ETA - 1 week

**Comment by cicyhou** [comment]
Updated - only screen left is the admin approval screen
Blockers - none
ETA - 2 days

**Comment by cicyhou** [comment]
Update - finished admin/team request screens today. 
Next step - finalize the screens with Adam
Blockers - None

**Comment by cicyhou** [comment]
Update - finalizing and updating the Admin/Team request screens
Blocker - none
ETA - 1 week

**Comment by cicyhou** [comment]
Update - still finalizing the team request screens with Adam.
Blocker - none
ETA - it's complete from my perspective, awaiting for Adam's approval

**Comment by switchzer0** [comment]
approved all designs. once @cicyhou finalizes we'll be done other than a few one-off issues that will be created to correct design errors we caught after finalizing the initial mockups

**Comment by cicyhou** [comment]
Update - finalized the design approved by Adam, coordinating with Olga to make sure all the features are buildable before moving into Final page.

**Comment by switchzer0** [comment]
**Progress:** @cicyhou states all designs are ready for final review; She is resigning from project. Next I will review designs, finalize where appropriate, identify any cures to be completed by next designer, and write tickets for them
**Blockers:** None
**Availability:** tomorrow afternoon/eve after 2pm PST
**ETA:** 3/9 (this ticket will be made obsolete by new individual cure tickets)

**Comment by switchzer0** [comment]
99% done, as discussed the other week, outstanding tweaks on select screens — will make individual tickets for each design change
