### ISSUE TITLE
Slack server conflicts with tests

### ISSUE THREAD

**Issue by nickbeaird** [hackforla/VRMS#283]
Overview: 
The architecture for the Slack integration and how we are integrating it at this time is causing issues with the test infrastructure. We are not able to spin up the tests without purposesfully skipping this section of the application. I worry that this pattern will become worse if we don't take a look at it sooner rather than for more application integrations (i.e. Slack, Google, etc).

Relates to commit: https://github.com/hackforla/VRMS/pull/396/commits/469dff86abf09ab896fcf1f53ee95808f7741e2b

Acceptance Criteria:
[ ] We review our Slack integration and have sign off by Alex and the team. 
[ ] The tests can be run without manually hard coding environment variables. 
[ ] Slack is not hard coded to a port.

**Comment by switchzer0** [comment]
@nickbeaird does this relate only to automating Slack DM/channel messaging or globally including adding/checking users on workspace, channels, etc.?

**Comment by nickbeaird** [comment]
This relates to all things Slack related. The way that we are using the Slack app is a strange work-around and is causing us issues with our development pipelines as well as our tests. This ticket is to address those specific concerns.
