### ISSUE TITLE
RecurringEvents should not be dependent on Projects

### ISSUE THREAD

**Issue by clockwerkz** [hackforla/VRMS#285]
Investigate if fetching a recurringevent that has no project assigned will cause an error on the backend.

**Comment by clockwerkz** [comment]
Status: In-progress
Details: It appears that there is some sort of dependency or required properties in the recurringevents in order to generate new events./checkings. I think I've narrowed it down to either requiring a location or a project property. will continue to look into this this week,.
Blockers: None

**Comment by clockwerkz** [comment]
Status: In-progress
Details: Still looking into this. Didn't have time this week.
Blockers: None

**Comment by alex-anakin** [comment]
@clockwerkz please add a comment here

**Comment by clockwerkz** [comment]
RecurringEvents only require a project if the event type is labeled as a Project Meeting. I believe this is as intended. There does not appear to be any other dependencies between RecurringEvents and Projects.
