### ISSUE TITLE
Define User roles

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#29]
### Overview
Review all of the roles and identify which systems they need access to

### Action Items
* [x] Review current user model in database and propose proper role based authentication
* [x] Review proposals below for additional role identification and hierarchy
* [x] Define hierarchy
* [x] Propose roles (admin, user, project owner, team leads, hack night host)

### Resources/Instructions
* [x] Identify unique roles from [this](https://github.com/hackforla/github-automation/issues/2) and [this](https://github.com/hackforla/github-automation/issues/3) process
* [x] Research and update user stories document [here](https://docs.google.com/document/d/1-4q-suCaUKZW2L3UyMvr6EtDZWAh9oaYCY2Ztm_vg_M/edit?usp=sharing)

Related to
 Issue #91 - currently being worked on

**Comment by switchzer0** [comment]
UALs have been reviewed with architect, defined in PRD, designed into UI/UX, and situated in database schema
