### ISSUE TITLE
Implement New User Roles

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#30]
### Overview
Get the requirements from the user role definition issue

### Dependency 
Define User Roles #29 

### Action Items
Back End: 
* [ ] Add new roles to current model

**Comment by switchzer0** [comment]
@alex-anakin i think this will be superseded by new v0.4 PRD issues and should be closed as obsolete, but please confirm

**Comment by alex-anakin** [comment]
yes, it's outdated
