### ISSUE TITLE
Define VRMS Analytics Goals

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#304]
### Overview
One of VRMS's primary functionalities is an analytics tool to optimize organizational performance. Identifying the organizational choices we want to make down the road and the data required to inform them should dictate how the data model is structured. 

### Acceptance Criteria
- [x] review of strategy and vision
- [ ] data scientist input
- [ ] project sponsor input
- [ ] recommendation of analytics-enabling data model architecture and parameters
- [ ] review with technical team

### Background
- [VRMS strategy and vision](https://docs.google.com/presentation/d/1DLljKCoaoI2JSZUxL6oIOhBBXbSF30uW0EOgtYNSRrs/edit?usp=sharing)
- relates to #278 ([data model review - documentation](https://docs.google.com/presentation/d/17_ucxJ_7uQJwNL8Xc9HimJ73LTTN4Wn_1hYewoOdsLU/edit?usp=sharing)
- [leader persona user stories](https://github.com/hackforla/VRMS/projects/6#column-7873876)

**Comment by switchzer0** [comment]
Update: drafted initial list of needs based on strategy and vision document and personas board. Next up time with. @nickbeaird (technical sanity check), bonnie (sponsor needs interview), data science team (best practices recco), dev team (discussion and technical approval)
Blockers: none
Availability: most days
ETA: 2 weeks

**Comment by switchzer0** [comment]
Update: reviewed with @nickbeaird and dev team. Tentative decision to enable future complex analytics functionality by snapshotting document database at intervals and copying to relational database to facilitate analytics
Blockers: my schedule
Availability: most days
ETA: 3 weeks

**Comment by switchzer0** [comment]
no progress, no blockers, on hold until higher priority items addressed based on insights from initial interviews

**Comment by JackHaeg** [comment]
Plan already exists, no longer a relevant issue
