### ISSUE TITLE
Create VRMS "Home" page

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#306]
### Overview
As a user, I want to see a [page](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=24760%3A2811) after opening https://www.vrms.io
This page displays a choice between 2 options:
- Sign in
- Create account

Clicking buttons should redirect to the next page. 
If the corresponding page is not implemented then use the temporary dummy page from #321 for all redirects.

### Resources/Instructions
Please follow [UI development guideline](https://github.com/hackforla/VRMS/wiki/UI-Development-Guideline). 

### Important info:
The page should be implemented in the client folder client-v-04

**Comment by alex-anakin** [comment]
@switchzer0 please add here a link to the Figma mockup when it will be finished.

**Comment by switchzer0** [comment]
Figma [wireframe](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=24586%3A8) of this screen. @cicyhou will be working on an actual design for it, but functionality will be similar.

**Comment by OlgaBilogurova** [comment]
Blocked by:

- [x] #327

**Comment by OlgaBilogurova** [comment]
The task is blocked because of waiting for the finalized mockup and installing Redux for `client-mvp-04`.

**Comment by OlgaBilogurova** [comment]
Progress: 
- Created the local branch. Preparing app-container, new components, routing, styles.  
- Waiting until the design will move to the "final" screen in Figma according to the new workflow for moving designs into development.

Blocks: Blocked by not finalized design.
Availability: Weekdays 2-4pm
ETA: N/A

**Comment by OlgaBilogurova** [comment]
Progress:
- Added routing and navigation
- Covered existing components with unit tests
- On Friday was unblocked by the finalized v0.4 style guide #360 and need to update UI variables and styles for existing pages

Blocks: Blocked by #360
Availability: Weekdays 2-4pm
ETA: 2-3 days

**Comment by OlgaBilogurova** [comment]
Done
