### ISSUE TITLE
Research Admin Dashboard Requirements

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#31]
### Overview
The admin dashboard is the hub for all things related to managing a brigade of volunteers. It should provide data about the brigade, and tools for the admin to create and update events, open check-in time for hack nights, and oversee the human capital development of the organization through project and volunteer management.

### Action Items
UI/UX:
* [ ] Research popular dashboards and how they display their information
* [ ] Obtain requirements from stakeholders about how to effectively display the information and tools they need
* [ ] Document this

Data Science:
* [ ] Review current data collected and propose how to display it effectively for stakeholders

### Resources/Instructions
Current user model and data that has been collected already
<img width="437" alt="Screen Shot 2020-02-02 at 12 57 04 PM" src="https://user-images.githubusercontent.com/39248174/73615365-13686b80-45bc-11ea-8206-a81a25f6a790.png">

**Comment by alex-anakin** [comment]
Obsolete
