### ISSUE TITLE
Create Project Manager user level work flow

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#32]
### Overview
Create a work flow for how the Project Manager would experience VRMS

### Action Items

- [x] Review the issues in the Github Automation repo to identify automation goals.
   - [ ] Interview Bonnie after you have automation goals list and get validation 
- [ ] Design work flow diagrams
  - [ ] Review with Bonnie
 - [ ] Create low fidelity mock ups
    - [ ] Show to subset of project managers
       - [ ] Revise as appropriate
       - [ ] Once signed off - create new issue for development

### Resources/Instructions
[Github Automation repo](https://github.com/hackforla/github-automation)

**Comment by switchzer0** [comment]
### Status
- wrote up initial project manager role overview
- write up prospective workflow for PM adding contributor to project
### Next Steps
- conduct interviews validating "add contributor" (Bonnie) and technical architecture
- expand overview document to include addition PM paths: mgr. housekeeping, update project description, engage with project dashboard
### No blockers
### Resources
Write-up: https://docs.google.com/document/d/16HGD2Eqv1tiNevI5ws6-9nzMYiH1SPQT1ZeM6wsXU00/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
@switchzer0 @ExperimentsInHonesty need to meet tomorrow.

**Comment by switchzer0** [comment]
### Status
- revised PM role elements overview to match architecture
- revised "add contributor" workflow incorporating Bonnie interview
### Next Steps
- expand overview document to include addition PM paths: mgr. housekeeping, update project description, engage with project dashboard
### Blockers
- confirm roadmap for project before continuing to write up potentially late-phase elements
### Resources
Write-up: https://docs.google.com/document/d/16HGD2Eqv1tiNevI5ws6-9nzMYiH1SPQT1ZeM6wsXU00/edit?usp=sharing

**Comment by switchzer0** [comment]
completed in PRD and UI/UX 1.0
