### ISSUE TITLE
Create temporary dummy page

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#321]
### Overview
Implement [dummy page](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=24897%3A0) for accelerating development process. 
It should be used in cases when any currently developing page redirects a user somewhere else but the destination page is not developed yet.

### Resources/Instructions
The page should be implemented in the client folder client-v-04
Please follow [UI development guideline](https://github.com/hackforla/VRMS/wiki/UI-Development-Guideline).

**Comment by OlgaBilogurova** [comment]
Blocked by:

- [x] #327
- [x] #306

**Comment by OlgaBilogurova** [comment]
Done
