### ISSUE TITLE
Implement "Create account" page

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#322]
### Overview
Implement a [page](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3447) that allows a user to input an email and start the process of creating an account.

### Action Items

- [x] The "Create account" button is disabled by default.
- [x] Enable the "Create account" button when the input value is not empty (consider spaces as empty input).
- [x] After clicking the "Create account" button validate inputted symbols in the client using a regular expression.
- [x] If the inputted value is not valid email then show an [error](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3477).
- [x] If the inputted value is valid then check out if the inputted email is not registered in the VRMS system by sending a request to the back-end.
- [x] If the inputted email is not registered then redirect to the temporary dummy page from #321.
- [x] If the inputted email is already registered then show an [error](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3462). The error should contain a link to the "Sign in" page (or dummy page if it is not implemented).

### Resources/Instructions
* The page should be implemented in the client folder `client-v-04`
* Please follow [UI development guideline](https://github.com/hackforla/VRMS/wiki/UI-Development-Guideline).

**Comment by alex-anakin** [comment]
Blocked by:

- [x] #327 
- [x] #306 
- [x] #321

**Comment by OlgaBilogurova** [comment]
@ChrxsCrxss this task is unblocked. 
Please, pull changes from `development` branch and follow instructions from `client-mvp-04/README.md`.

**Comment by alex-anakin** [comment]
Hey @ChrxsCrxss, Figma mockups for the task were updated. Please take a look.
