### ISSUE TITLE
Remove meeting time for HelloGOV

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#323]
### Overview
We need to remove the meeting times for the HelloGOV team as they are no longer meeting.

### Action Items
Update database to remove meeting times on Monday's 6:30 - 8:30

**Comment by junganthonyy** [comment]
Unless I'm mistaken, I don't see HelloGov's meetings on the site anymore, and when I run a GET on "api/recurringevents" I don't see any entries for HelloGov. Since I don't have access to the production database, @clockwerkz can you confirm that it has been removed?

**Comment by clockwerkz** [comment]
@junganthonyy  Hey Anthony, that was my bad - I didn't see that you had been assigned the ticket. I went ahead and removed the meetings for HelloGov, just forgot to update this ticket.

**Comment by Rankazze** [comment]
Confirmed HelloGov is no longer displaying on PROD Project Meeting page.
