### ISSUE TITLE
Remove meeting time for NewSchoolToday

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#324]
### Overview
We need to remove the meeting times for the NewSchoolToday team as they are no longer meeting.

### Action Items
Update database to remove meeting times on Monday's 6:30 - 8:30

**Comment by clockwerkz** [comment]
I removed the recurringevent for the HellGov team meeting on Mondays 6:30 - 830 - the change will be reflected on the week of 10/19.

**Comment by junganthonyy** [comment]
Hi Everyone. I just noticed that the name of this ticket and the text didn't line up. HelloGov was removed, but New Schools Today's meetings are still there. I can take care of this, but I'll need someone to give me access to the database.

**Comment by Rankazze** [comment]
Transferred request to Newly created Issue template for Meeting Change Requests
