### ISSUE TITLE
Create a separate client application for MVP 0.4 features development

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#327]
### Overview
Set up a new React application for MVP 0.4 features development on the client side.

### Action Items

- [x] Create a separate folder on the project root level and name it `client-mvp-04`.
- [x] Set up a new React application.
- [x] Apply Sass setup from #223 implementation.
- [x] Set up the new client local deployment from the VRMS root folder.

**Comment by OlgaBilogurova** [comment]
Done!

- Created a separate folder on the project root level and name it `client-mvp-04`
- Set up a new React application
- Install all packages from `client package.json`
- Set up the new client local deployment from the VRMS root folder
- Applied Sass setup from #223 implementation
- Added README.md to `client-mvp-04`
- Created the first unit test for `App.js` and runs successfully
- Removed all files from `client` regarding `sass-new-ui`
- Updated root README.md with instructions how to run `client` and `client-mvp-04`

Both client apps  `client` and `client-mvp-04` run successfully.

![MVP-4 0-Home](https://user-images.githubusercontent.com/11681030/95642131-550ab980-0a5b-11eb-8c76-bd7b88afa478.png)
![MVP-4 0-Home-clear-console](https://user-images.githubusercontent.com/11681030/95642134-576d1380-0a5b-11eb-8896-6482f9994f86.png)
![tests-passed](https://user-images.githubusercontent.com/11681030/95642169-900ced00-0a5b-11eb-9235-4a663a194068.png)
