### ISSUE TITLE
Install and set up Redux for `client-mvp-04`

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#329]
### Overview
Install and set up Redux for `client-mvp-04`.

### Resources/Instructions
This is the next step after issue #327 will be finished and merged into `development` 
[Redux documentation](https://redux.js.org/introduction/getting-started)

**Comment by clockwerkz** [comment]
Sounds good - so in regards to our convo last night, do you want me to start on this when 0.4 is merged into dev? This was the issue I'm on: #299

**Comment by OlgaBilogurova** [comment]
Sure, @clockwerkz 
Please, set up Redux during the next few days. Because we should move forward with MVP 0.4.

**Comment by OlgaBilogurova** [comment]
@clockwerkz PR #328 was merged into `development`.
You can move forward to install Redux for `client-mvp-04`.

**Comment by clockwerkz** [comment]
Ok perfect, thanks!

**Comment by clockwerkz** [comment]
Progress: Awaiting PR approval 
Blockers: None
Availability: weekdays after 6 PM

**Comment by alex-anakin** [comment]
Done
