### ISSUE TITLE
Meeting time Change Request BallotNav

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#338]
Overview

We need to change the meeting times for the BallotNav team as they have requested a meeting time change.

Action Items

Update database to change meeting times for BallotNav Tuesday meeting from "6:00PM - 7:30PM" to "5:00PM - 6:30PM"

**Comment by alex-anakin** [comment]
The meeting time was changed. Please check it out the next Tuesday.

**Comment by Rankazze** [comment]
Confirmed it displayed new time on Tuesday.
