### ISSUE TITLE
Clean up Visual Studio Code workspace file

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#344]
### Overview
The project should not contain tool-dependent files.

### Action Items

- [ ] Remove vrms.code-workspace file from the project.
- [ ] Add *.code-workspace to gitignore.

**Comment by awhig** [comment]
Also should also remove .DS_Store file from repository.

**Comment by alex-anakin** [comment]
Visual Studio Code workspace file was not deleted from the repository.

**Comment by awhig** [comment]
@alex-anakin removed vscode file from repository
