### ISSUE TITLE
Use the VRMS host address for building Magic Link

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#346]
### Overview
We need to implement a mechanism for building Magic Link depending on the host of the application.

### Instructions
The easiest way to implement that is by using environment variables. Let's say if there is a variable `APP_HOST` in the `.env` file then the Magic Link mechanism uses its value. If there is no such variable then the default value `localhost:3000` should be used.

If there is a way that can resolve the VRMS host address automatically and it's not hard to implement then let's use it.

**Comment by awhig** [comment]
I believe this is doable by using the request hostname property. 

It would involve modifying the call and function in:

user.controller.js 
email.controller.js

      emailController.sendUserEmailSigninLink(req.body.email, jsonToken);


http://expressjs.com/en/api.html#req.hostname

req.hostname
Contains the hostname derived from the Host HTTP header.

When the trust proxy setting does not evaluate to false, this property will instead get the value from the X-Forwarded-Host header field. This header can be set by the client or by the proxy.

If there is more than one X-Forwarded-Host header in the request, the value of the first header is used. This includes a single header with comma-separated values, in which the first value is used.

Prior to Express v4.17.0, the X-Forwarded-Host could not contain multiple values or be present more than once.

// Host: "example.com:3000"
console.dir(req.hostname)
// => 'example.com'

Let me know if you want me to do this. Seems like an easy first task.

**Comment by alex-anakin** [comment]
@awhig sounds good. I assigned the task to you.
