### ISSUE TITLE
Meeting time Change Request Record Clearance

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#347]
### Changing existing event
Meeting time Change Request Record Clearance

If you are requesting changes for an existing event provide the following details:
* Record Clearance
* Weekly Team meeting
* Event type Project Meeting
* Monday
* Time (start and end)  Update database to change meeting times on Monday's 6:00p - 7:00p

### Creating new event
REPLACE THIS TEXT:
Provide the following details:
* Project
* Event name
* Event type (Project Meeting, Orientation, Workshop, etc)
* Day of week
* Time (start and end)
* Location (can be remote): 
* Use for check-ins (yes or no)

### Contact info
REPLACE THIS TEXT:
Provide your nickname in HackForLA slack   Daniel Lee

**Comment by alex-anakin** [comment]
@Rankazze Done.
