### ISSUE TITLE
Remove meeting time for NewSchoolToday

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#349]
### Changing existing event
REPLACE THIS TEXT
If you are requesting creating a Remove event then remove this topic.

If you are requesting changes for an existing event provide the following details:
* Project  NewSchoolToday (remove)
* Event name  Monday weekly meeting
* Event type Project Meeting
* Day of week  Monday
* Time (start and end)  We need to remove the meeting times for the NewSchoolToday team as they are no longer meeting.

### Contact info
REPLACE THIS TEXT:
Provide your nickname in HackForLA slack  Rankazze

**Comment by alex-anakin** [comment]
@Rankazze Done.
