### ISSUE TITLE
HfLA AWS account configuration

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#35]
### Overview
Hack for L.A. (HFLA) wishes to host all of their services from an AWS account owned by the HFLA organization. In order to do so, we must create and configure an AWS account for the HFLA organization. This issue tracks the work of doing the discovery and initial set-up for this AWS account. 

### Action Items

- [ ] IAM (identity and access management)
   - [ ] discovery
   - [ ] set up account
   - [ ] create groups and users
   - [ ] configure tagging 
- [ ] Networking and Security
   - [ ] discovery
- [ ] Deployment
   - [ ] discovery

### Resources/Instructions
Add link to Yasmin's doc here

**Comment by ExperimentsInHonesty** [comment]
Make sure matt gets invite to aws meeting.

**Comment by ExperimentsInHonesty** [comment]
Progress: set a slack reminder for Matt and assigned issue to him

**Comment by ExperimentsInHonesty** [comment]
Matt will reach out to Joel.

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty @sarL3y to meet to talk about about CfA paying for heroku

**Comment by switchzer0** [comment]
### Update
Is this still relevant in the @Alex era?

**Comment by alex-anakin** [comment]
@switchzer0 It's not relevant anymore. Closing it.
