### ISSUE TITLE
Community of Practice: Software Developers/Front end New Meeting Request

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#350]
### Changing existing event
REPLACE THIS TEXT

### Creating new event
REPLACE THIS TEXT:
Provide the following details:
* Project  Software Developers/Front end Group
* Event name  Weekly meeting
* Event type Community of Practice Meeting 
* Day of week  Monday
* Time (start and end)  8pm - 9pm
* Location (can be remote):  Remote
* Use for check-ins (yes or no)  Yes

### Contact info
REPLACE THIS TEXT:
Provide your nickname in HackForLA slack  Greg Pawin  or Bonnie  @alex-anakin

**Comment by alex-anakin** [comment]
@Rankazze Event created in the database.

**Comment by Rankazze** [comment]
@alex-anakin Can you please add the Meeting title name Community of Practice: Software Developers/Front end

**Comment by alex-anakin** [comment]
@Rankazze Fixed. Please check it out.

**Comment by Rankazze** [comment]
@alex-anakin Confirmed.  Thanks!  I have informed Greg that the ticket has been completed.
