### ISSUE TITLE
Refactor backend for magic link additions

### ISSUE THREAD

**Issue by nickbeaird** [hackforla/VRMS#355]
The recent magic link work was done quickly and requires some follow up. We aim to increase the testing and confidence of the backend and make sure that the methods are well named and communicated. I am making sure that the endpoints work as expected and cleaning up the organization along the way.

**Comment by nickbeaird** [comment]
Do we need the answers Model? It is not being referenced anywhere. Any thoughts @alex-anakin ?

I added a commit to remove the Answer Model as it is not being called and the Question Model looks to have been refactored to house this information.

**Comment by nickbeaird** [comment]
Suggestion # 2: We should get rid of the Checkin model and move the list of attendees over to the event model. That and improve the attendee list in general. We should review what we need, because it seems like two paths. 
 - Path 1 Projects: We need a list of people on the project. Add an array of user IDs on the project. This is likely a smaller list  each person is an active VRMS member. 
 - Path 2 Events: We would want to know a few things. 
  * The count of people at the event
  * The count of people at an event that are not a part of a project. Potentially compute heavy with how we structure our evenst. 
  * A list of emails to reach out to for future follow up who have joined an event, but are not part of a project. 

What are your thoughts to the above Adam (not sure on your github username) and @alex-anakin ?

**Comment by nickbeaird** [comment]
Suggestion # 3: We should move all checkUser api routes over to pathways on Auth, and we should verify the user's permissions when we do.

**Comment by switchzer0** [comment]
@nickbeaird Adam here.
- Question/Answer models: There is no functionality I'm aware of scoped for the next ~year that would require either model.
- Event/Checkin models: there are some reasons that I found to be persuasive for having these models separate, but I don't recall in detail. Coincidentally given your question, there is a meeting proposed to finalize the parameters for both of these models and their relationship within the database schema on this coming Tuesday eve. Would be great if you could attend that in addition to discussing here. I'll bump the RSVP request in our slack channel.

**Comment by nickbeaird** [comment]
Great, once you know what you all hope to have, then I can move things around to organize the data.

**Comment by nickbeaird** [comment]
Progress: This is done. We had a data model checkin this last week, which answered a lot of the questions that I had. 

This will be done as soon after this meeting.
