### ISSUE TITLE
Make API protection consistent

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#356]
### Overview
The application uses CUSTOM_REQUEST_HEADER to protect API from unauthorized use. It's a pretty legacy solution. It should be fixed, but not the way by restricting everything. HackForLA website uses some of our API, so it shouldn't be protected to not make the HackForLA website team add changes to their codebase.

### Action Items

- [ ] Contact @ExperimentsInHonesty to figure out what VRMS APIs are used by the organization website.
- [ ] Protect all APIs except used by the organization website.
- [ ] Check out the CORS behavior of the back-end. Probably now it allows all requests outside. If so then enable CORS and allow requests by specific IP-address only. Implement this by using environment variables for storing IP-addresses.

**Comment by awhig** [comment]
Alex Anakin  1:26 PM
Let's use header scheme for everything that is not used outside. I already found that API for outside users has cors() parameter in methods. Probably CORS is enabled for everything else.

**Comment by awhig** [comment]
I sent a DM to Bonnie   @ExperimentsInHonesty  regarding info of API usage, but have not heard back.

**Comment by awhig** [comment]
@alex-anakin CORS is implemented by the web server. Assuming nginx, you have to modify configuration files for the service. https://enable-cors.org/server_nginx.html. I think it would be difficult to have the app env. files be used to do this. Do you mean to do CORS like behavior in the api code in the router? FYI, I'm still waiting for info in regards to API use from Bonnie.

**Comment by ExperimentsInHonesty** [comment]
These are the apps that are currently approved

![Screen Shot 2020-11-02 at 10 48 50 AM](https://user-images.githubusercontent.com/37763229/97906744-0a4a2d80-1cf9-11eb-9c26-1c252e26555d.png)

**Comment by ExperimentsInHonesty** [comment]
Here are all the apis hackforla.org  uses: https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#api-endpoints

```# 1 ``` is the one from vrms
see the details in this file by searching for api
https://github.com/hackforla/website/blob/gh-pages/project-meetings.html

**Comment by awhig** [comment]
API used by hackforla.org is here:

```

    const API_URL = 'https://www.vrms.io/api/recurringevents';

...
    // GET request 
    let calendarFetch = fetch(API_URL, {
        method: 'GET'
    });
```
