### ISSUE TITLE
Make API HTTP codes and messages consistent across the application

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#357]
### Overview
Currently, there is some inconsistency in HTTP codes, error messages, and success responses for different routers:
https://github.com/hackforla/VRMS/tree/development/backend/routers

### Action Items

- [ ] Use HTTP status codes mentioned in the description for fixing all responses.
- [ ] Make error handling consistent.
- [ ] Make error messages consistent.
- [ ] Clean up mistakes.

### Instructions
Success:
200 OK - Response to a successful GET, PUT, PATCH or DELETE.
201 Created - Response to a POST that results in a creation. Should return created object.

Errors:
400 Bad Request – This means that client-side input fails validation.
401 Unauthorized – This means the user isn’t not authorized to access a resource. It usually returns when the user isn’t authenticated.
403 Forbidden – This means the user is authenticated, but it’s not allowed to access a resource.
404 Not Found – This indicates that the API endpoint is not found.

502 Bad Gateway – This indicates an invalid response from an upstream server.
503 Service Unavailable – This indicates that something unexpected happened on the server side (It can be anything like server overload, some parts of the system failed, database failed, etc.).

**Comment by nickbeaird** [comment]
The PR https://github.com/hackforla/VRMS/pull/361 solves the standard codes. It does not make error handling consistent.
