### ISSUE TITLE
Update all UI Sass-variables based on finalized v0.4 style guide

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#360]
### Overview
@cicyhou has delivered a finalized style guide for v0.4, with updates to tooltip instructions and color scheme. Update UI Sass-variables to match.

### Action Items
- [x] Update all UI Sass variables

### Resources/Instructions
[Finalized v0.4 Style Guide (Figma)](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/?node-id=23471%3A0)

**Comment by OlgaBilogurova** [comment]
Progress: In progress from today
Blocks: None
Availability: Weekdays 2-4pm
ETA: 1-2 days or less

**Comment by OlgaBilogurova** [comment]
Done.
-  Updated all _colors.scss variables based on v0.4 style guide
-  Added Open Sans Italic font, add new font-face
-  Updated _typography.scss variables based on v0.4 style guide
-  Changed _base.scss based on v0.4 style guide
-  Updated App.scss styles
-  Created index.scss file inside sass/variables to export vars 
-  Updated names for UI vars for Home component
-  Updated names for UI vars for Footer component
-  Updated names for UI vars for Error component
-  Updated _buttons.scss vars and styles based on v0.4 style guide
-  Created _links.scss, add styles for Join and Project links
-  Created _menu.scss, add styles for menu item
-  Created _inputs.scss, add styles for default input and input with icon
-  Add new icons for new elements

Developed and updated all elements inside blue borders.
Elements outside borders should be implemented in a separate task. 
![SG-done](https://user-images.githubusercontent.com/11681030/97645999-b646fc80-1a0b-11eb-9c94-6a7d361b6830.png)
![SG-2](https://user-images.githubusercontent.com/11681030/97640713-99f09300-19fe-11eb-9d89-68d65d6cece4.png)
