### ISSUE TITLE
Create EventTemplate data model

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#364]
### Overview
Create a Mongoose schema `EventTemplate` containing the following properties:

```
name: String
description: String
type: String, enum: ['Project Meeting', 'Orientation', 'Workshop', 'Hacknight']
createdDate: Date
weekDay: Number, enum: [0, 1, 2, 3, 4, 5, 6]
startTime: Date
endTime: type: Date
isActive: type: Boolean
project: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Project'
}
isOnline: Boolean
location: {
	addressLine1: String
	addressLine2: String
        city: String
        state: String
	zip: String
}
videoConferenceLink: String
```

### Action Items

- [ ] Create a schema
- [ ] Create the schema test

### Resources/Instructions
https://github.com/hackforla/VRMS/tree/development/backend/models

**Comment by nickbeaird** [comment]
I like that we have simplified a few fields for the event, but there are two observations. 

1. We need a way to associate Projects and Events. We lost that connection. Why are we removing the project from the Event? I would say that the 1:1 mapping before made sense. What is your alternative on this?
2. What fields are required? And what fields are unique? We should figure that out.

**Comment by nickbeaird** [comment]
I like that we have simplified a few fields for the event, but there are two observations. 

1. We need a way to associate Projects and Events. We lost that connection. Why are we removing the project from the Event? I would say that the 1:1 mapping before made sense. What is your alternative on this?
2. What fields are required? And what fields are unique? We should figure that out.
