### ISSUE TITLE
Create ModificationLog data model

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#365]
### Overview
`ModificationLog` stores a history of modification of any object type. We can't use `ObjectId` for a reference but using a String representation of `Id` is Ok here.

Create a Mongoose schema `ModificationLog` containing the following properties:

```
date: Date
authorEmail: String
objectId: String			// modified object id stored as String
objectType: String, enum ['UserProfile', 'EventTemplate', 'ProjectInfo', 'ProjectMembership']
newState: Object			// modified object new state should be saved completely as an object
```

### Action Items

- [x] Create a schema
- [x] Create the schema test
- [x] Define compound index using `objectId` and `objectType`

### Resources/Instructions
https://github.com/hackforla/VRMS/tree/development/backend/models

**Comment by awhig** [comment]
@alex-anakin for this schema, it looks like you want to store arbitrary objects  in the newState field. We have the objectId in another field, do we need to store object type in another field?

**Comment by alex-anakin** [comment]
@awhig This is a good idea. Let's create a field `objectType: String` with enum value `'UserProfile', 'EventTemplate', 'ProjectInfo', 'ProjectMembership'`. Also please define compound index using `objectId` and `objectType`. 
The task description is updated.
