### ISSUE TITLE
Implement "Sign In" page

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#386]
### Overview
Implement [page](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25461%3A3337) for logging in the application.

### Action Items

- [x] The "Sign in" button is disabled by default.
- [x] Enable the "Sign in" button when the input value is not empty (consider spaces as empty input).
- [x] After clicking the "Sign in" button validate inputted symbols in the client using a regular expression.
- [x] If the inputted value is not valid email then show an [error](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25461%3A3429).
- [x] If the inputted value is valid check out if it is registered in the VRMS system by sending a request to the back-end.
- [x] If the inputted email is registered then redirect to the temporary [dummy page](https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/components/dummy/dummy.js).
- [x] If the inputted email is not registered then show an [error](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25461%3A3413). The error should contain a link to the "Create account" page from #322 (or dummy page if it is not implemented).
- [x] Cover implemented component and functionality with tests.

### Resources/Instructions
The feature [description](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#heading=h.r8i1carm5a4p) in the MVP doc.

**Comment by OlgaBilogurova** [comment]
Done.
Next step - cover implemented LoginContainer functionality with unit tests (mock data, test logic).
