### ISSUE TITLE
Streamline readme for new developers

### ISSUE THREAD

**Issue by nickbeaird** [hackforla/VRMS#395]
Update the readme for new developers looking at the project for the first time. 

Goals:
1. Simplify the readme to show how to setup and how to run tests.
2. Move contributing related information to a contributing.md file. 
3. Move all new users to using Docker. Users not using Docker will have already set themselves up for this type of development.

**Comment by nickbeaird** [comment]
Done and the corresponding PR needs to be approved and merged.

**Comment by switchzer0** [comment]
Update/next steps: no progress this week. review text from a copyediting perspective
Blockers: none, just my schedule
Avails: thursday on
ETA: 1 week

**Comment by switchzer0** [comment]
Update/next steps: suggested copyedits, requested clarification on a couple small things
Blockers: feedback from @alex-anakin 
Avails: most afternoons/evenings
ETA: friday, assuming I get feedback on one of Alex's usual available days

**Comment by switchzer0** [comment]
i believe this is completed or superseded per the discussion earlier today. would like to close
