### ISSUE TITLE
Manually Update BallotNav meeting times in VRMS database

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#399]
### Overview
We need to add/change the team meeting times for BallotNav so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (day of week, start time am/pm, duration):
Tuesday, 5:00pm, ~1.5 hours~ 1 hour
Remove the others: Saturday and Thursday

### What is your project page URL?
https://www.hackforla.org/projects/ballot-nav

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #ballotnav 
Slack @handle: @karen
<hr />

**Comment by switchzer0** [comment]
if this hasn't been completed yet, please note that the stakeholder has requested that the meeting length should in fact be 1 hour: 5-6pm

**Comment by alex-anakin** [comment]
Done

**Comment by switchzer0** [comment]
Thanks for handling these. Did karen confirm this is good? if not, I will handle DMing her. Same question for Ray on the other ticket.

**Comment by switchzer0** [comment]
I will be corresponding with stakeholder to confirm user acceptance. ETA this week.

**Comment by switchzer0** [comment]
requested UAT w/ stakeholder

**Comment by switchzer0** [comment]
stakeholder approved. done.
