### ISSUE TITLE
Add start/end times to events table

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#40]
### Overview
Add attributes to the data model for each event to track the number of hours, so that we can report more accurately on volunteer hours.

### Action Items
- [ ] Add attributes: 
  - start time (time)
  - end time (time)
  - number of hours (calculated from end minus start time)

### Future Development Idea
- Could we use these start/end times to automate when check-in opens/closes? This is just an idea for a future feature, NOT for development in this ticket.

**Comment by kelseylc** [comment]
We decided to take another route on this topic in last week's meeting (2/17). We'll be creating a static # of hours per event_type. For example, hack nights = 3 hours, unconference sessions = 1 hours, and so on. That way we don't need an extra field or calculation step.
