### ISSUE TITLE
Implement a service for operating UserProfile entity

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#407]
The task is blocked by:
- [x] #388
- [x] #410 

### Overview
For the application 3-layered structure implement a service to operate [UserProfile](https://github.com/hackforla/VRMS/blob/development/backend/models/userProfile.model.js) entity

### Action Items

- [x] Add `userProfile.service.js` into `backend/services` folder. 
- [x] Implement `createUser(userProfile, authorEmail)` function that returns the saved entity. Features:
* Minimum required information for creating a user profile is email. Validate this.
* Make a record in ModificationLogs collection.
- [x] Implement `updateUser(userProfile, authorEmail)` function that returns the updated entity. Features:
* Use Mongoose `findOneAndUpdate` with email as a key. 
* Changing the user email is not allowed. 
* Treat undefined values of fields as no-change
* Make a record in ModificationLogs collection.
- [x] Implement `getUser(id)` function that returns unique `userProfile` entity.
- [x] Implement `getUserByEmail(email)` function that returns unique `userProfile` entity.
- [x] Cover implemented functionality with tests.

Extra task: it would be great to wrap create/update actions into one transaction with saving logs but it's not required right now.

### Resources/Instructions
Useful articles about Node.js application architecture and using services:
https://www.coreycleary.me/project-structure-for-an-express-rest-api-when-there-is-no-standard-way
https://www.codementor.io/@evanbechtol/node-service-oriented-architecture-12vjt9zs9i
https://dev.to/santypk4/bulletproof-node-js-project-architecture-4epf#architecture

**Comment by awhig** [comment]
Will get started on this once ModificationLog Service is merged.

**Comment by awhig** [comment]
@alex-anakin I think this requirement for update

Treat empty, null, undefined values of fields as no-change

Should be:

Treat undefined values of fields as no-change

Otherwise if a field is set once, we can never remove it. Additionally, this is how mongoose works. If it's not defined on the update data, it's not changed. If it is set, with empty string or null, it sets this value.

**Comment by awhig** [comment]
@alex-anakin This requirement, 

Make a record in ModificationLogs collection. Use the user email for the author of changes.

You want to use the user email of the userProfile record that is being updated as the author? Shouldn't this be an email, of the user calling the create/update? Which could be anyone who has rights to make these updates. 

Do we have a context User object available somewhere for backend code?

**Comment by awhig** [comment]
@alex-anakin I see in #418 that there is some business logic rules. Should these be in the service instead of the controller?

Validate firstName, lastName as non-empty String. Don't allow the following characters: {, $, :, }. Limit the length by 50 symbols
Validate signupEmail and googleEmail as an email using regexp pattern from email validation https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/validation.js

See https://www.codementor.io/@evanbechtol/node-service-oriented-architecture-12vjt9zs9i
Controller Layer
The controller layer is responsible for handling client requests, and responding to them. Just to reiterate a very important point, this layer should never contain business logic!

**Comment by awhig** [comment]
Also, During creation of User Profile, I've added logic to lower case the email address.

**Comment by alex-anakin** [comment]
> @alex-anakin I think this requirement for update 
> Treat empty, null, undefined values of fields as no-change 
> Should be: 
> Treat undefined values of fields as no-change 
> Otherwise if a field is set once, we can never remove it. Additionally, this is how mongoose works. If it's not defined on the update data, it's not changed. If it is set, with empty string or null, it sets this value.

I agree with that. I fixed the requirement.

**Comment by alex-anakin** [comment]
> @alex-anakin This requirement, 
> Make a record in ModificationLogs collection. Use the user email for the author of changes.
> 
> You want to use the user email of the userProfile record that is being updated as the author? Shouldn't this be an email, of the user calling the create/update? Which could be anyone who has rights to make these updates.
> Do we have a context User object available somewhere for backend code?

We don't have a context User object and probably will not have it in the nearest future.
Let's add a parameter into the methods like the following: `createUser(userProfile, authorEmail)`, `updateUser(userProfile, authorEmail)`. It will be a controller's responsibility to pass the correct author depending on specific API.

**Comment by alex-anakin** [comment]
> @alex-anakin I see in #418 that there is some business logic rules. Should these be in the service instead of the controller?
> 
> Validate firstName, lastName as non-empty String. Don't allow the following characters: {, $, :, }. Limit the length by 50 symbols
> Validate signupEmail and googleEmail as an email using regexp pattern from email validation https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/validation.js

This is a good point but it requires some work from my side. I will add a couple of tasks related to this and we will update the service. We can merge `UserService` without this validation.

**Comment by awhig** [comment]
@alex-anakin I've made the authorEmail change.
