### ISSUE TITLE
Implement authentication by Magic Link in `client-mvp-04`

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#408]
### Overview
Implement authentication using the Magic Link approach in `client-mvp-04`.

### Action Items

- [x] Reuse "Magic link" [implementation](https://github.com/hackforla/VRMS/blob/development/client/src/hooks/useProvideAuth.js) from the current client.
- [x] Implement sending the Magic link to a user after clicking the "Sign In" button on the "Sign In" page.
- [x] Implement a new [page](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25461%3A3453) "The Magic link is sent" that opens after sending a user the link for logging in.
- [x] Redirect the user to the new page "The Magic link is sent" after clicking the "Sign In" button.
- [x] Cover implemented functionality with tests.

### Resources/Instructions
Useful articles about the magic link approach:
https://reallifeprogramming.com/how-to-implement-magic-link-authentication-using-jwt-in-node-8193196bcd78
https://medium.com/one-more-thing-studio/how-to-make-magic-links-with-node-1d164c036e29

**Comment by OlgaBilogurova** [comment]
Progress: 

- Learned resources about the magic link approach and implementation from the current client
- Implemented sending the Magic link to a user after clicking the "Sign In" button

Blocks: None
Availability: Weekdays
ETA: 1 week
