### ISSUE TITLE
Add month/year filter to admin dashboard

### ISSUE THREAD

**Issue by rachelwhaley** [hackforla/VRMS#41]
### Overview
As an admin user, I want to filter the admin dashboard by a range of month/year, so that I can see the metrics limited by a specific time range.

### Action Items
- [ ] Add a filter for dashboard start time (month/year)
- [ ] Add a filter for dashboard end time (month/year)
- [ ] Default filters to show all-time metrics (no filtering)
- [ ] Ensure that all dashboard components react to the filter

**Comment by kelseylc** [comment]
Action items  1 and 2 are essentially asking for a custom date range picker. This is desired but cut from MVP, so I'm moving this to icebox for now. We can pull it out later once we're working on V1 or V2 iterations.
At that time we can update the ticket to reflect newer needs related to custom date ranges.

**Comment by alex-anakin** [comment]
Obsolete
