### ISSUE TITLE
Update Weekly Meeting Time - Civic Opportunity Project.

### ISSUE THREAD

**Issue by rfambro2** [hackforla/VRMS#412]
### Overview
We need to add/change the team meeting time for the Civic Opportunity Project so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (day of week, start time am/pm, duration):
EXAMPLE: Monday, 7:30pm, 2 hours

Sunday, 9am PST, 1 hour
Thursday, 4pm PST, 1 hour

### What is your project page URL?
https://www.hackforla.org/projects/civic-opportunity-project

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #civic-opportunity
Slack @ Ray Fambro
<hr />

### Instructions
We'd like to remove the weekly Wednesday meeting from the schedule, and add a weekly Thursday meeting for 4pm, PST.

**Comment by alex-anakin** [comment]
Done

**Comment by switchzer0** [comment]
I will be corresponding with stakeholder to confirm user acceptance. ETA this week.

**Comment by rfambro2** [comment]
Should the meeting times on the HfLA website indicate timezones?

**Comment by switchzer0** [comment]
requested UAT w/ stakeholder.

@rfambro2 looks like none of them do currently, i think that's a question of how the website calculates/displays times. I believe someone mentioned it displays in local time based on user's browser/system clock? Not sure...we have been entering the data as provided by stakeholders. FYI, a forthcoming Q1 2021 release of VRMS will include a timezone variable in the data model for meetings, and will standardize all time calculations and outputs to UTC

**Comment by rfambro2** [comment]
@switchzer0 - You are correct in that it displays times based on the user's local browser settings/time zones. Thanks for your help! I think we are set.

**Comment by switchzer0** [comment]
approved by user. done.
