### ISSUE TITLE
Add cookie for email address when logging in returning user

### ISSUE THREAD

**Issue by djbowers** [hackforla/VRMS#413]
### Overview
It would be nice if VRMS would store the user's email address so that users don't have to type it in again every time they log in. This could be accomplished with a cookie or any other method of storage. 

### Action Items
Save the user's email address so that it auto-populates on subsequent logins.

**Comment by switchzer0** [comment]
@alex-anakin came as a this user request but aligns 1:1 with our release plan. Please add details per [PRD 1.04](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#heading=h.h4uvf9jro82u) or close as a duplicate.

**Comment by alex-anakin** [comment]
Duplicate
