### ISSUE TITLE
Implement "Main Dashboard" page

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#414]
### Overview
Implement the "Main Dashboard" page as shown on the [mockup](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3386).

### Action Items
Currently, the page doesn't have access to real data.

- [x] The task is blocked by #425. If this task is not implemented, please implement it first.
- [x] Implement the page component `dashboard`. It should be accessible from a browser by direct link `<host>/dashboard`.
- [x] Define in the component object `userProfile` based on [model](https://github.com/hackforla/VRMS/blob/development/backend/models/userProfile.model.js) with the following properties: `firstName, lastName, signupEmail, isAdmin = true`. Use values as specified on the [mockup](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3386).
- [x] Define in the component array `notifications` that contains the following object:
```
{
  projectName: 'VRMS',
  meetingName: 'Weekly Meeting',
  startTime: dateValue1,                          
  endTime: dateValue2
}
```
DateValue1 is 7 pm of the current day, DateValue2 is 8 pm of the current day.
- [x] Follow the comments: 
![VRMS Main dashboard instructions](https://user-images.githubusercontent.com/11644789/99029508-7dd51180-2527-11eb-9b68-63b955c38bf5.png)
- [x] Cover the component with tests.

**Comment by OlgaBilogurova** [comment]
Main Dashboard is implemented.
Additionally added responsiveness, new tests for the footer for authorized users, customizated scroll-bar.
