### ISSUE TITLE
Write proper text for VRMS magic link

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#415]
### Overview
Currently, the Magic link email looks like:
![Login-to-VRMS-email](https://user-images.githubusercontent.com/11644789/99139743-42eae080-25f0-11eb-895f-63ed3acbffcb.png)

We need to improve the email's subject and text.

### Action Items

- [x] Add a comment to the task with improved subject and text.

**Comment by switchzer0** [comment]
@alex-anakin a few Qs:
- Is it burdensome to pull firsttname from user in the DB? (just a nice to have)
- How long until the link expires?
- Will users only have to do magic link 1x per device/browser unless they actively log out, or every single time?
- I think in the interest of time let's do plaintext for now but is this something we could shift to pretty HTML in v0.5+?

**Comment by alex-anakin** [comment]
@switchzer0 
1. We can do that easily.
2. 15 minutes
3. Current implementation requires to log in every single time. [Feature](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#heading=h.a6rvqzgtch6l) will be implemented for the MVP version.
4. We can use HTML right now. But the complex design of the email is time-consuming. So yes, let's stay on a simple design for the moment.

**Comment by switchzer0** [comment]
### Proposed text
**Subject:** Your Hack for LA VRMS Login
**Sender Name:** Hack for LA
**Email copy:**
Hi User-FirstName, here's your magic link to access VRMS. It expires after 15 minutes.

[Click here]() to login or paste this URL into your browser: [https://URL.com](https://URL.com)
