### ISSUE TITLE
Suppress temporarily the test causing GitHub actions failure

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#417]
### Overview
The test https://github.com/hackforla/VRMS/blob/development/backend/config/auth.config.test.js fails on GitHub actions but passes locally. We need to suppress it or ignore programmatically, or just comment out. 

### Action Items

- [ ] Disable the test using any approach
- [ ] Add TODO to turn the test on after fixing GitHub actions.

**Comment by awhig** [comment]
This is done. test.skip() was used.
