### ISSUE TITLE
Cover CreateAccountContainer functionality with tests

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#424]
### Overview
Need to cover implemented CreateAccountContainer functionality with unit tests (mock data, test logic).
It's the next task after finishing #322.

**Comment by ChrxsCrxss** [comment]
**Update:** I've mostly completed this task. I'm dealing with one final stubborn test case, but that should be resolved some time tomorrow. 

Blockers: none
Availability: variable 
ETA: 2 days
