### ISSUE TITLE
Implement "Code of Conduct" page

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#428]
### Overview
Implement the "Code of Conduct" page as shown on the [mockup](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3493).

### Action Items

- [x] The task is blocked by #429. If this task is not implemented, please implement it first.
- [x] Implement the page component `code-of-conduct`. It should be accessible from a browser by direct link `<host>/code-of-conduct`.
- [x] Code of conduct text should be taken from the remote source: [HackForLA code of conduct](https://raw.githubusercontent.com/hackforla/codeofconduct/master/README.md). The text starts with `Hack for LA expects` and ends with `enjoy a harassment-free environment.`.
- [x] Implement reusable component 'Popup' #468
- [x] The “Don’t agree” button displays a [popup](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3505) with the “X” button that makes it disappear. Clicking outside the popup closes it too. 
- [x] The “Agree” button redirects to the dummy page.
- [x] Cover implemented components with tests.
- [x] Add responsiveness.
- [x] Create EmailSetup (1 step of onboarding) page as dummy page. Connect components createAccount => emailSetup => codeOfConduct to show the onboarding flow.

### Resources/Instructions
Dev UI Kit web page (when the application is started locally) http://localhost:3001/dev-ui-kit
Dev UI Kit component https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js
The page [mockup](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3493)
The page with modal window [mockup](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3505)

**Comment by OlgaBilogurova** [comment]
Progress: Started to implement task #429 (create a progress bar)
Blocks: The task is blocked by #429
Availability: Weekdays
ETA: N/A

**Comment by OlgaBilogurova** [comment]
Progress: 

- developed a progress bar as a reusable component
-  created a new component and added route <host>/onboarding/code-of-conduct
-  fetched text from the remote source: HackForLA code of conduct

Blocks: None
Availability: Weekdays
ETA: ~2weeks

**Comment by OlgaBilogurova** [comment]
Progress: 

- handled and displayed markdown data from the remote source: HackForLA code of conduct
- implemented reusable component 'Popup', PR #474
- added behavior when popup should be closed (described above)

Blocks: none
Availability: weekdays
ETA: till next meeting

**Comment by OlgaBilogurova** [comment]
Done
