### ISSUE TITLE
Implement backend validation

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#431]
The task is blocked by:
- [x] #430 

### Action Items

- [x] Add `utils/validator.js` into `backend` folder. 
- [x] Implement `isNotEmpty` static function to check a String value to be defined and not null. Also check that String doesn't consist of the whitespace characters only (space, tab, no-break space, etc.). 
- [x] Implement `isSafe` static function to check a String value doesn't contain the following characters: `{`, `$`, `:`, `}`. 
- [x] Implement `isNoLonger(str, length)` static function to check a String value length to be no longer than the second parameter.
- [x] Implement `isEmail` static function to check a String value using regexp pattern from email validation https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/validation.js

Every function should throw `new ValidationError('message text depending on the function')` if the check did not pass. And return nothing if the check passed.

**Comment by awhig** [comment]
Should finish late this week.

**Comment by awhig** [comment]
still awating pull request review from @alex-anakin
