### ISSUE TITLE
Diagram database schema

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#437]
### Overview
Create a diagram of database schema to support developer understanding.

### Action Items
- [x] create diagram
- [x] review with @switchzer0 
- [x] link to various model.js files in GitHub
- [x] save to google drive as PDF or Google Drawing

### Resources/Instructions
- @alex-anakin for clarifying questions on relationships
- [original draft relationships diagram (not accurately depicted)](https://docs.google.com/presentation/d/17_ucxJ_7uQJwNL8Xc9HimJ73LTTN4Wn_1hYewoOdsLU/edit#slide=id.g952a9bb5bb_1_0)
- [Data models requirements](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#heading=h.hhutmpgbwq8c)
- [Data model.js files](https://github.com/hackforla/VRMS/tree/development/backend/models)

**Comment by awhig** [comment]
Should finish late this week.

**Comment by awhig** [comment]
@switchzer0 Please view initial diagram based off of model document. It was unclear to me in two places.

EventTemplate

templateID		event’s join ID connecting it to recurring instances for future editing

I believe this is the EventTemplateID? The primary key of the EventTemplate record?


Event

templateID		event’s join ID connecting it to recurring instances for future editing


I believe this is the EventTemplateID that the Event is related to?

I made those two assumptions in the diagram I made.

Please review.

[vrms_mvp_model.pdf](https://github.com/hackforla/VRMS/files/5625124/vrms_mvp_model.pdf)

**Comment by switchzer0** [comment]
this looks great overall!
- I believe your interpretation of templateID is correct.
- what's the difference between the dotted and dashed lines?
- i don't see a reason for `event` or `eventTemplate` to see data from `user`; please clarify why you illustrated that way
- @alex-anakin want to chime in with additional comments?

**Comment by awhig** [comment]
Hey @switchzer0 

**what's the difference between the dotted and dashed lines?**

It represents identifying vs non-identifying relationships. For example a ProjectMembership record can't exist without a UserId, or a ProjectId, they are both part of the primary key for the record. On the other hand, an EventTemplate, has its own primary key. The JoinIdProject and HostUserId are not part of the primary key, so technically, this record is not "identified" by those fields. I made in error with the Checkin table. Those relationships to it, should be "dotted", as it has it's own key, and the two relationships are not part of the primary key and don't identify the record. I'm attaching an updated pdf.

**i don't see a reason for event or eventTemplate to see data from user; please clarify why you illustrated that way**

I transcribed the spec doc you created. They both have a HostUserId field, which I believe is an ID from the User table.

[vrms20201218.pdf](https://github.com/hackforla/VRMS/files/5718003/vrms20201218.pdf)

**Comment by switchzer0** [comment]
Thanks for the explainer! Everything you drafted makes sense to me now, only remaining question is:
- should **CheckIn** have an identifying relationship w/ **user** + **event**? CheckIn definitely can't exist without being connected to both an event and user object, although i see checkin has its own primary key in your diagram. I'm ok with that, but want to make sure it makes sense and is useful to do so.

**Comment by awhig** [comment]
@switchzer0 I realize now, that a user should only have 1 checkin per event, so my model is wrong there. We don't need that artificial primary key. The primary key should be the EventID + UserID. I've made this change. FYI, I didn't put all the of the fields in the diagram, just the ones needed to show the relationships. See attached updated pdf.

[vrms4.pdf](https://github.com/hackforla/VRMS/files/5720376/vrms4.pdf)

**Comment by switchzer0** [comment]
@awhig looks great to me now; thank you! would be great to have @alex-anakin second opinion, but I'm all set at this point.

**Comment by alex-anakin** [comment]
Looks good to me. @awhig please fix minor mistakes:
* All IDs are not INT but ObjectId. Or we can skip mentioning of ID type in the diagram.
* ProjectMembership has its own ID.
* There can be multiple EventTemplates for a Project (fix relation mark).

After that it's ready for using in our documentation.

**Comment by awhig** [comment]
@alex-anakin Here is a new version of the doc, with the changes requested.

There is no ObjectId datatype in the sql tool I'm using (Mysql workbench), and I can't leave it empty, so I had to put char(12), which I hope is good enough, as the ObjectIds are 12 byte hex strings, in mongodb.

[vrms5.pdf](https://github.com/hackforla/VRMS/files/5871382/vrms5.pdf)

**Comment by switchzer0** [comment]
approved and saved to appropriate destinations
