### ISSUE TITLE
Deploy the VRMS production instance on AWS

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#440]
### Overview
To set up a stable development/deploying process we need to deploy the VRMS production instance on AWS.
The most complex task here is choosing a powerful enough but not expensive configuration. 

### Resources/Instructions
EC2 spot instances https://aws.amazon.com/ec2/spot/

**Comment by FoxShaunR** [comment]
This is done

**Comment by JackHaeg** [comment]
This has been completed.
