### ISSUE TITLE
Update Record Clearance Project Card - Meeting Times

### ISSUE THREAD

**Issue by abenipa3** [hackforla/VRMS#445]
### Overview
We need to add/change the team meeting time for Record Clearance so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [X] yes
- [ ] no

### List all of your meeting times (day of week, start time am/pm, duration):
Dev meetings Thurs. @ 6 PM PST - 7PM PST
Design & Research meetings Tues. @ 6 PM PST - 7 PM PST
Team meetings Biweekly Mon. @ 6 PM PST - 7 PM PST

### What is your project page URL?
https://www.hackforla.org/projects/record-clearance-project

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name:  #record-clearance
Slack @handle: Daniel Lee
<hr />

**Comment by switchzer0** [comment]
reached out to stakeholder to confirm UAT

**Comment by switchzer0** [comment]
reached out to stakeholder again
