### ISSUE TITLE
Add/edit team meeting time: Hackforla.org Website PM meeting addition

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/VRMS#446]
### Overview
We need to add/change the team meeting time for Hackforla.org Website so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (day of the week, start time am/pm, duration):
Sun, 10:00 am,  2 hours, Team Meeting (Fine as is) 
Tue, 7:00 pm, 1 hour,  Development Team (Fine as is)
Tue, 1:00 pm, 1.5 hours,  PM Meeting (new add) 

### What is your project page URL?
https://www.hackforla.org/projects/website

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: hfla-site
Slack @handle: Ahdithan Uthayakumar
<hr />

**Comment by switchzer0** [comment]
reached out to stakeholder to confirm UAT

**Comment by switchzer0** [comment]
reached out again; user responded saying he will confirm by EOD Monday
