### ISSUE TITLE
Add licence to repo after notifying prior contributors of change

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#448]
### Overview
We need to add a licence to the VRMS repository so that we can make sure it stays open source

### Action Items
- [x] Research Licence types and make recommendation
- [x] Run script to find all prior contributors to notify them
- [ ] AT mention all prior contributors in the new issue (to be created) - don't write anything else in the issue
- [ ] Remove code as required
- [ ] Change licence on date specified (minimum 2 weeks after notification)

### Resources/Instructions
See completed [HfLA website notification example](https://github.com/hackforla/website/issues/699)
See issue from HfLA site for methods on how to [find all the prior contributors](https://github.com/hackforla/website/issues/705)

**Comment by Rankazze** [comment]
@ExperimentsInHonesty @switchzer0 After conducting broad research into the types of open source licenses available I recommend that we use the GNU Affero General Public License.  It is specific to network conveyed applications.   https://www.gnu.org/licenses/agpl-3.0.en.html

**Comment by ExperimentsInHonesty** [comment]
@switchzer0 - here is the issue you asked me to work on.  I got Dean to research the licence types and make a recommendation.  I created this issue and another issue for implementing the notification.  All that remains if for the other action items to be addressed.  I am putting the issue in the prioritized backlog.  But wanted to give you a heads up so you could talk about it with Alex.  It probably needs different labels too.

**Comment by switchzer0** [comment]
I am evaluating GNU vs Affero to ensure we can e.g., monetize to cover costs in the future.

**Comment by peteplass** [comment]
@akibrhast please Look at issue [705](https://github.com/hackforla/website/issues/705) to determine how we found all contribs
[How to notify everyone ](https://github.com/hackforla/website/issues/699)

**Comment by akibrhast** [comment]
- [x] Run script to find all prior contributors to notify them

The script has been run and a list of all prior contributors can be found here -> https://github.com/hackforla/VRMS/issues/524

The automated script can be found here -> https://github.com/akibrhast/website/blob/gh-pages/.github/workflows/contributors.yml

- [x]  AT mention all prior contributors in the issue #449 - don't write anything else in the issue
 @peteplass Please advise on next steps. If any

**Comment by switchzer0** [comment]
I agree that Affero is the right version of GNU — [Handy License Comparison](https://choosealicense.com/licenses/).
I'm not a lawyer, but specifically, it:
- contributors provide express grant of patent rights (to contribute is to agree)
- allows commercialization (we can monetize to cover costs eventually)
- modifications is done to provide service over a network (i.e., the VRMS use case) require disclosure of source code
- modifications must be distributed under the same license

**Comment by peteplass** [comment]
@switchzer0 will add link to exact license type.

**Comment by switchzer0** [comment]
- [License: GNU Affero GPL v3.0](https://www.gnu.org/licenses/agpl-3.0.en.html)
- [Wikipedia entry](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License)
- [Concise "TLDR" explainer](https://choosealicense.com/licenses/)

**Comment by peteplass** [comment]
@akibrhast to instruct Bonnie on how to use the custom contributor tool

**Comment by peteplass** [comment]
license repo added.
