### ISSUE TITLE
VRMS repository wants to change its license type

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#449]
### Overview
The Hack for LA organization is seeking to add the appropriate licences to all projects.  You are receiving this issue because you contributed code to our repository.  If you disagree with the agpl-3.0 being added.  Please let us know what pull request you submitted (provide a link to the pr in the comments of this issue), and we will remove the code.

We will add the licence on Feb 15, 2020

### Resources
[agpl-3.0.en licence](https://www.gnu.org/licenses/agpl-3.0.en.html)

### Contributors
@sarL3y, @OlgaBilogurova, @nickbeaird, @alex-anakin, @shiningjustice, @awhig, @patrickgus, @Jonathanko52, @clockwerkz, @MasterBirdy, @mdPial, @ChrxsCrxss, @rachelwhaley, @JsonRoyJones, @dependabot[bot], @junganthonyy, @ExperimentsInHonesty, @switchzer0, @dae-hyun-kim, @drubgrubby, @rmpcoding, @jafow, @o-anakin

**Comment by switchzer0** [comment]
I believe this is superseded by other tix in progress, and that we have agreed on the GNU Affero v3 license. @ExperimentsInHonesty please confirm that my understanding is correct, and i'll close this out.

**Comment by ExperimentsInHonesty** [comment]
Sorry for the message about changing the licence type.  This message went out erroneously.   We will be sending another message on a new issue when we sort out the licence type change.  Again sorry for the premature message.
