### ISSUE TITLE
Hack Night end of event summary report

### ISSUE THREAD

**Issue by Rankazze** [hackforla/VRMS#45]
### Overview
A summary report for the end of event is needed to be able to do after action analysis.

### Action Items
Report should include at a minimum the following:
  Event location.
  Date of Event.
  Attendee info by member attributes.
  New attendee email list.

**Comment by TanyaWlod** [comment]
I have an Event and Event Detail page mocked. I have light comments that should explain what you're looking at.
Everyone with the link should be able to edit/view. If you have any edits/questions please comment them onto the Figma board.
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=22881%3A2738

**Comment by Jonathanko52** [comment]
Requires Zoom Link information to be somewhere in databases, probably somewhere in the project model.

**Comment by ExperimentsInHonesty** [comment]
Blocker is there is no endpoint for the db to get info from the event model and possibly the event model might

**Comment by alex-anakin** [comment]
Obsolete
