### ISSUE TITLE
Add meeting time for YouthJusticeNav

### ISSUE THREAD

**Issue by nielseny** [hackforla/VRMS#450]
### Overview
We need to add/change the team meeting time for YouthJusticeNav so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (day of week, start time am/pm, duration):
Wednesday, 6PM -7PM PST

### What is your project page URL?
https://www.hackforla.org/projects/youthjusticenav

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #youthjusticenav
Slack @handle: @nielsen
<hr />

**Comment by switchzer0** [comment]
reached out to stakeholder to confirm

**Comment by switchzer0** [comment]
approved by user

**Comment by switchzer0** [comment]
approved by user
