### ISSUE TITLE
Customize scroll-bar

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#452]
### Overview
For pages where inner content longer than container should be applied customized scroll-bar as designed in the [mockup](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25491%3A76).
Support custom scroll in Chrome, Edge, Safari, Firefox.

**Comment by switchzer0** [comment]
how burdensome will it be to also support in Brave browser? Their growth is wild right now and generally among more tech-oriented users i.e. HfLA types. This is also a selfish request :). If trivial, would be great to support Brave, too. If burdensome, just a nice-to-have.

**Comment by OlgaBilogurova** [comment]
Hi @switchzer0,

Yes, we can support Brave as well. Because Brave is a Chromium-based (developed by the Google-sponsored Chromium project) browser as Edge and Opera.

I already checked and the customized scroll-bar looks good in Brave, Edge, Opera, Firefox, and Chrome web browsers.
