### ISSUE TITLE
Create Location data model

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#454]
### Overview
`Location` is a new model for storing predefined locations in the database. We need to create this model to be able to:
* reuse location values across the application
* dynamically change locations without changing the codebase.

Create a Mongoose schema `Location` in `dictionaries` subdirectory of `models` directory containing the following properties:

```
locations: array of strings
```

### Action Items

- [x] Create a schema
- [x] Create the schema test

### Resources/Instructions
https://github.com/hackforla/VRMS/tree/development/backend/models

**Comment by mdPial** [comment]
Hello, I would like to work on that issue.

**Comment by alex-anakin** [comment]
Done
