### ISSUE TITLE
Update & Add Team Meeting Time: 311 Data

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/VRMS#458]
### Overview
We need to add/change the team meeting time for [311 Data] so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (day of week, start time am/pm, duration):
EXAMPLE: Monday, 7:30pm, 2 hours

Team Meeting
1. Delete Tuesday, 7:00 pm, 2 hours, (Team Meeting)  
2. Change Thursday  6:00 pm, 2 hours, Team Meeting with Thursday 6:30 pm, 1 hour, Team Meeting  
3. Replace Thursday 7:00 pm, 1 hour, Management Meeting with Thursday  07:30 pm, 1 hour, Management Meeting

### What is your project page URL?
https://www.hackforla.org/projects/311-data

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: 311 Data  
Slack @handle: Mahmudul
<hr />

**Comment by switchzer0** [comment]
reached out to stakeholder to confirm UAT

**Comment by switchzer0** [comment]
approved by user
