### ISSUE TITLE
Implement a service for operating JobRole entity

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#462]
~The task is blocked by:~
~- [x] #457~

### Overview
Implement a service to operate the JobRole data model.

### Action Items

- [x] Add `jobRole.service.js` into `backend/services` folder. 
- [x] Implement `getAll()` function that returns all `JobRole` values as an array of strings.
- [x] Wrap DB call using `try/catch` with throwing [DatabaseError](https://github.com/hackforla/VRMS/blob/development/backend/errors/database.error.js) in case of any error.
- [x] Cover implemented functionality with tests.

### Resources/Instructions
[Service example](https://github.com/hackforla/VRMS/blob/development/backend/services/modificationLog.service.js)
[Service test example](https://github.com/hackforla/VRMS/blob/development/backend/services/modificationLog.service.test.js)

**Comment by peteplass** [comment]
Is this still a good first issue? Alex to review.

**Comment by alex-anakin** [comment]
> Is this still a good first issue? Alex to review.

Yes, it is.

**Comment by peteplass** [comment]
Alex: When any project is updated, the user can specify the project's roles - list will be shown to user for any project that the user will open. All roles that are used in any project will be accumulated in a dictionary to be reused across applications in the future. 

Projects leads will know what technical skills they need and what roles are open. A dictionary will help them name these roles correctly. 

Bonnie: We want job roles to match real world market roles as much as possible. Volunteers who are performing roles at HfLA should be able to go into the real world with those role titles. As such, these roles should be detailed in their descriptions and thus they should be centrally stored/defined.

**Comment by jasonwong26** [comment]
Pull Request: https://github.com/hackforla/VRMS/pull/586
