### ISSUE TITLE
Implement a service for operating Location entity

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#463]
~The task is blocked by:~
~- [x] #454~

### Overview
Implement a service to operate the `Location` data model.

### Action Items

- [ ] Add `location.service.js` into `backend/services` folder. 
- [ ] Implement `add(locations)` function without returning value. Features:
* `locations` parameter is an array of non-empty strings with at least one element. This should be validated.
* the function adds elements to the `Locations` DB collection skipping duplicates.
- [ ] Implement `getAll()` function that returns all `Location` values as an array of strings.
- [ ] For both functions wrap DB call using `try/catch` with throwing [DatabaseError](https://github.com/hackforla/VRMS/blob/development/backend/errors/database.error.js) in case of any error.
- [ ] Cover implemented functionality with tests.

### Resources/Instructions
[Service example](https://github.com/hackforla/VRMS/blob/development/backend/services/modificationLog.service.js)
[Service test example](https://github.com/hackforla/VRMS/blob/development/backend/services/modificationLog.service.test.js)

**Comment by peteplass** [comment]
@akibrhast Will fix conflict and merge PR. Fix formatting and Alex will approve.

**Comment by akibrhast** [comment]
Based on the mongoose docs - > https://mongoosejs.com/docs/validation.html#built-in-validators

> All SchemaTypes have the built-in required validator. The required validator uses the SchemaType's checkRequired() function to determine if the value satisfies the required validator.

As such I don't think it is necessary to particularly do validation from within the service itself as noted on the issue body:

> locations parameter is an array of non-empty strings with at least one element. This should be validated.

The validation should be, being done by the model, and the service should only be working towards passing validation errors up the chain. The current linked PR implements validation checks from within the `location.service.js`. I don't think it belongs there.

@alex-anakin , @drubgrubby .. Your inputs and thoughts in regards to this please ... ?

**Comment by drubgrubby** [comment]
@akibrhast -> It seems like what you are suggesting makes sense.  I guess I'd try doing it your way, and then try passing some invalid data through the test and see if it catches it.  Just my two cents.
