### ISSUE TITLE
Implement a controller for handling Location API endpoints

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#464]
The task is blocked by:
- [x] #463 

### Overview
Implement a controller for handling `Location` API endpoints.

### Action Items

- [x] Add `location.controller.js` into `backend/controllers` folder. 
- [x] Implement POST `/locations` API endpoint that returns OK 200 in the response in case of an operation success. Call `add` function of `location.service.js`. 
- [x] Implement GET `/locations` API endpoint that returns all `Location` values in the response. Call `getAll` function of location.service.js.
- [x] For all endpoints wrap the call to `location.service.js` function into `try/catch`. In case of an error get the error message and return it with relevant HTTP code (400 for validation error, 503 for database error). To avoid code duplication implement a reusable function for handling errors.
- [x] Cover implemented functionality with tests.

### Resources
The project convention about responses' HTTP codes #357

**Comment by akibrhast** [comment]
@alex-anakin Cannot start on this due to dependency not being resolved yet.

**Comment by akibrhast** [comment]
@alex-anakin Please advise on what to do next?

**Comment by peteplass** [comment]
Pete to assign to Glen once Glen has access to Repo.

**Comment by glenflorendo** [comment]
**Progress:** Actions Items 1-4 completed. Currently working on Action Item 5: writing tests.
**ETA:** End of the week
