### ISSUE TITLE
Create a radio button as a new UI element

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#469]
### Overview

Create a radio button as a new UI element (based on finalized 0.4 Style Guide).

Find mockup here => [Finalized v0.4 Style Guide (Figma), page 2](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25453%3A28)

![radio-btn](https://user-images.githubusercontent.com/11681030/105964406-fb90bf80-6036-11eb-8134-322a612be8cb.png)

### Action Items

- [x] Explore existing implementation for UI elements:
- `src/sass/elements`
- DEV UI KIT web page (run locally) http://localhost:3001/dev-ui-kit 
- DEV UI KIT component https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js

- [x]  Create JSX for radio buttons inside /*** INPUTS ***/ section in src/utils/uiKit
- [x]  Inside `src/sass/elements/_inputs.scss` add styles for radio buttons (2 sizes)
- [x]  Make sure a new UI element looks like in Style Guide

### Resources/Instructions
This issue the part of this epic #374
[Finalized v0.4 Style Guide (Figma)](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25453%3A28)
Dev UI Kit (run locally) http://localhost:3001/dev-ui-kit

**Comment by piall** [comment]
Hello, I would like to work on that issue 😃

**Comment by OlgaBilogurova** [comment]
Hi @mdPial, sounds good.
To work on the VRMS project tasks you have to be a team member.  
Please, open [this link](https://www.hackforla.org/projects/vrms) and start from "Getting Started".

**Comment by piall** [comment]
Okay. Thank you.😃

**Comment by piall** [comment]
Did you wanted point on https://www.hackforla.org/projects/vrms ? because your provided link is invalid

**Comment by OlgaBilogurova** [comment]
@mdPial yes, this is the correct link.
https://www.hackforla.org/projects/vrms

**Comment by piall** [comment]
@OlgaBilogurova  I have become a team member. Could you assign me on this issue?

**Comment by OlgaBilogurova** [comment]
@mdPial assigned. When you will be ready to start, move this task to progress. 
Please, in the future feel free to assign yourself any task that you like to work on. Thanks.

**Comment by piall** [comment]
Thank you for guidelines 😀

**Comment by mdPial** [comment]
Is`src/sass/elements` is the folder of **client-mvp-04**?

**Comment by piall** [comment]
@OlgaBilogurova The color used in Figma as the border of the radio button is`#32373B` which is not in the `_colors.scss` file. Should I use existing dark color  `#000000` or create a new one in the _colors.scss??

**Comment by OlgaBilogurova** [comment]
@mdPial sure, you could create a new color variable for the radio button inside _colors.scss.
I'll add this comment to your PR.

**Comment by piall** [comment]
Okay. I will add the new color variable and make necessary changes. May be you don't need to comment again . I got your message :smile:
