### ISSUE TITLE
Update 311-data meeting time

### ISSUE THREAD

**Issue by captain-nimo** [hackforla/VRMS#470]
### Overview
We need to add/change the team meeting time for 311-data so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes

### List all of your meeting times (day of week, start time am/pm, duration):
- Thursday 6:00 - 6:30 pm (Data science meeting)
- Thursday 6:30 - 7:30 pm (Weekly Team meeting)
- Thursday 7:30 - 8:30 pm (Management meeting)

### What is your project page URL?
https://www.311-data.org

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: 311-data
Slack @handle: Mahmudul
<hr />

**Comment by alex-anakin** [comment]
Added Data science meeting.

**Comment by switchzer0** [comment]
reached to @Mahmudul on slack for UAT

**Comment by switchzer0** [comment]
approved by stakeholder
