### ISSUE TITLE
Add "auth_origin" payload to the Magic Link token

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#471]
### Overview
To determine the originator of sending a Magik Link to a user we need to save this information in the Magic Link token.

### Action Items

- [x] Create a JavaScript util class for string constants.
- [x] Create a constant `['LOG_IN', 'ONBOARDING', 'GOOGLE_ACCOUNT_CHECK']`.
- [x] Send `auth_origin = LOG_IN` when requesting the Magic Link for logging in.
- [x] Send `auth_origin = ONBOARDING` when requesting the Magic Link for checking out if the user email is valid during onboarding.
- [x] Save `auth_origin` into token on the backend.
- [x] Parse `auth_origin` from the Magic Link on the backend when the user opened it.
- [x] Send `auth_origin` back to the frontend in both cases of success or failure.

**Comment by OlgaBilogurova** [comment]
Progress:
- Reworked `auth` logic for `AdminLogin` component for the old client to have login functionality working (for `admin `user role).
- Merged changes from `development `and have 1 backend test failing.

I'm going to refactor and rename this component, and probably extract API requests to a separate file.
Will do it this week.
  
Blocks: PR #492 - 1 backend test failing
Availability: Weekdays
ETA: 1 week
