### ISSUE TITLE
Implement "Collect Google Account" page

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#472]
The task is blocked by:
- [x] #471 

### Overview
Some people don't Gmail as their primary email, but we require having a Gmail account to provide access to project Google Drive.

### Business logic

After checking out user email existence using Magic Link (originated from `ONBOARDING`) validate it against domain:
* If it's 'gmail.com' then go to option 1.
* If it's not 'gmail.com' validate it against [List of popular domains](https://github.com/mailcheck/mailcheck/wiki/List-of-Popular-Domains). If the email is from the list then go to option 2.
* Else go to option 3.

1. Show [we will use your gmail](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25929%3A1979) page. After clicking "OK" make a dummy call to the PATCH `api/userProfiles/<userId>` where `userId` is a value from the previous step. Then redirect the user to the **Code of conduct** page.

2. Show [we need your gmail](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25912%3A1937) page. Validate user input. If the user clicked "SAVE & CONT" but input is not valid then show the [error](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25912%3A1947). If the input is valid then request the Magic Link from the backend with `auth-origin = GOOGLE_ACCOUNT_CHECK` and show [we sent Magic Link page](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25466%3A3522) page.

3. Show the user [we are not sure](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25912%3A1926) page. If the answer is YES then go to option 1. If the answer is NO then go to option 2.

4. Add logic to opening the Magic Ling with `auth-origin = GOOGLE_ACCOUNT_CHECK`. If the token is not valid then show 'the token is not valid' page. If it's valid then go to option 1.

### Resources/Instructions
[List of popular domains](https://github.com/mailcheck/mailcheck/wiki/List-of-Popular-Domains)

**Comment by OlgaBilogurova** [comment]
Progress: 

- On create account page added validation if it's Gmail redirect the user to `Google Drive Setup` page 
- Created a new component `GoogleDriveSetup`, 
- Added a new route `/onboarding/google-drive-setup`

Blocks: PR #492 should be merged
Availability: Weekdays
ETA: 1 week

**Comment by OlgaBilogurova** [comment]
Progress: No progress this week
Blocks: PR #492 should be merged
Availability: Weekdays
ETA: 1 week

**Comment by OlgaBilogurova** [comment]
Progress: Creating UI for the `Google Drive Setup` page
Blocks: PR #492 should be merged
ETA: 1-2 weeks

**Comment by peteplass** [comment]
Please update.

**Comment by OlgaBilogurova** [comment]
Progress: Working on email validation against List of popular domains. 
Blocks: none
ETA: 2-3 weeks

**Comment by OlgaBilogurova** [comment]
Progress: Didn't have enough time to work on the task

**Comment by peteplass** [comment]
unassigned Olga based on time constraints
