### ISSUE TITLE
Update meeting time for YouthJusticeNav

### ISSUE THREAD

**Issue by nielseny** [hackforla/VRMS#475]
### Overview
We need to change the team meeting time for YouthJusticeNav so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

Meeting time: 
* Wednesday 7PM PST (new update)
* Friday 3PM PST (new update)

### What is your project page URL?
https://www.hackforla.org/projects/youthjusticenav

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #youth-justice-nav
Slack @handle: [@nielsen](https://hackforla.slack.com/team/U01G0PX0NJY)
<hr />

**Comment by nielsen** [comment]
Sorry — did you tag me in this CR?

**Comment by nielseny** [comment]
> Sorry — did you tag me in this CR?

@nielsen Sorry didn't mean to tag you! It was meant for me, my slack handle conflicts with your github username, will fix it now

**Comment by alex-anakin** [comment]
Meeting time updated.

**Comment by Olivia-Chiong** [comment]
@alex-anakin thank you for the changes.
