### ISSUE TITLE
Add team meeting time for Open Community Survey.

### ISSUE THREAD

**Issue by danyc23** [hackforla/VRMS#476]
### Overview
We need to add/change the team meeting time for Open Community Survey so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
no

### List all of your meeting times (day of week, start time am/pm, duration):
Mondays 12:00pm - 1:00pm

### What is your project page URL?
https://www.hackforla.org/projects/open-community-survey

### Instructions
The meeting time should be added to the project profile page.

**Comment by drubgrubby** [comment]
Changes have been completed.  I slacked to olivia to either check the times, or to let me know if I should send it to someone else.

**Comment by drubgrubby** [comment]
This was the original ticket that had the meeting times. 

https://github.com/hackforla/community-survey-nc-websites/issues/2

**Comment by drubgrubby** [comment]
Per Bonnie, I have confirmed that these changes have been made correctly.
