### ISSUE TITLE
Home Unite Us meeting times need to change

### ISSUE THREAD

**Issue by thatguyish** [hackforla/VRMS#478]
### Overview
We need to add/change the team meeting time for Home Unite Us so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (day of week, start time am/pm, duration):
Tue 10:00 pm - 11:00 pm (EDT)
Sat 3:30 pm - 5:00 pm (EDT)

### What is your project page URL?
https://www.hackforla.org/projects/home-unite-us

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: Ishmell Ramirez
Slack @handle: thatguyish

**Comment by alex-anakin** [comment]
The meeting time is updated.

**Comment by drubgrubby** [comment]
@alex-anakin -  Per Bonnie I have confirmed that these changes are correct on the HfLA site. I'm moving this do done.
