### ISSUE TITLE
Create input for adding current skills as a new UI element

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#479]
### Overview

Create input for adding current skills as a new UI element (based on finalized 0.4 Style Guide).

Find mockup here => [Finalized v0.4 Style Guide (Figma), page 1](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23471%3A1)

![el-1](https://user-images.githubusercontent.com/11681030/97739745-7f212b80-1a9d-11eb-8c2a-0cef2f182a9d.png)

### Action Items

- [x] Explore existing implementation for UI elements:
- `src/sass/elements`
- DEV UI KIT web page (run locally) http://localhost:3001/dev-ui-kit 
- DEV UI KIT component https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js

- [x]  Create JSX for new UI element inside `/*** INPUTS ***/` section in [`src/utils/uiKit`](https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js)
- [x]  Add styles for new UI element inside `src/sass/elements/_inputs.scss`
- [x] Define in the component data object that simulating JSON data coming from the API:
```
const skills = {
   currentSkills: ["JavaScript", "TypeScript", "React", "Angular", "Java", "Node.js", ...]
 }
```
- [ ]  Add validation for input data using regexp inside `src/utils/validation/validation.js`:
   - make sure input is not empty
   - inputted data should have only letters
Take a look at existing validation: https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/validation/validation.js
- [x] Add functionality to the component:
     - [x] When the user is typing in the input -> show skills that match with expression. Something similar to autocomplete.
   For instance: 
   inputted data: "java"
   show: "JavaScript", "Java"
     - [x]  When the user selected skill from the list and click on '+' button => add wireframing => remove it if user clicks on 'x'. 

- [x]  Make sure a new UI element looks and works like in Style Guide

### Resources/Instructions
[Finalized v0.4 Style Guide (Figma)](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23471%3A1)
Dev UI Kit web page (run locally) http://localhost:3001/dev-ui-kit

**Comment by harshad71** [comment]
hi i m harshad if this issue is not resolve then i would like to work on it

**Comment by peteplass** [comment]
@harshad71 We would love to have you work on this. We meet Mondays 7pm Pacific. Please Join our slack by going to the https://hackforla.org

**Comment by AmyMendelsohn** [comment]
Weekly Update:
I wasn't able to work on this much this week due to unforeseen outside events.

### ETA
Should have a much better update by next week

**Comment by jbubar** [comment]
Question: How would you like the autocomplete to look? Dropdown?

progress: got the dev environment working, did a little research on autocomplete
blockers: not sure about the autocomplete.
availability: during the day erday
ETA: next week monday

Going to meet w david after this meeting

**Comment by peteplass** [comment]
@OlgaBilogurova  to answer Josh this week after review. 

@jbubar  will DM Olga on Slack.

**Comment by jbubar** [comment]
@OlgaBilogurova answered my questions. thanks Olga! 
<details>
    <summary>Here is my progress</summary>

![vrms-input-skills](https://user-images.githubusercontent.com/53061723/120256113-48cda980-c242-11eb-9e95-9fa195140845.gif)


</details>

I still need to do some styling, add icons, do a dropdown, and set up testing for it.

ETA: probably 2 weeks. A bit more complicated than I thought

**Comment by jbubar** [comment]
<details>
    <summary>Styled to look like the figma</summary>

![input-skills-newly-styled](https://user-images.githubusercontent.com/53061723/120406534-f05ce180-c2ff-11eb-9e66-0741d0b5d955.gif)


</details>

Going to work on auto complete next

**Comment by jbubar** [comment]
Here is my update:
<details>
    <summary>a little gif</summary>

![inputskillsshowerrors](https://user-images.githubusercontent.com/53061723/121982127-ca91fc80-cd43-11eb-9b1c-ba833fbe23e2.gif)


</details>

Quite a few things I still need to iron out. I'll be working on it during this meeting. shhh

**Comment by jbubar** [comment]
Almost done, 
<details>
    <summary>still need to check for repeats and add back in the red asterisk in all cases</summary>

![Screen Shot 2021-06-17 at 6 29 05 PM](https://user-images.githubusercontent.com/53061723/122492146-1b029780-cf9a-11eb-9e4e-4465edef3f76.png)


</details>

Need to do the validation also
