### ISSUE TITLE
Add meeting times for Product Management Community of Practice

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/VRMS#481]
### Overview
We need to add/change the team meeting time for Product Management Community of Practice so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (day of week, start time am/pm, duration):
Community of Practice: Product Management, Tuesday, 6 pm for 1 hour
Community of Practice: Product Management, Friday 10 am for 2 hours

### What is your project page URL?
Currently don't have one - here's our repo instead https://github.com/hackforla/product-management

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #product-management
Slack @handle: Olivia Chiong

**Comment by drubgrubby** [comment]
These changes have been made.  I will move them and assign myself when I get github privileges for vrms.

**Comment by drubgrubby** [comment]
@Olivia-Chiong @ExperimentsInHonesty @alex-anakin - There doesn't seem to be any consistency for the naming of the Communities of Practice.  

Should it be: 
- Product Management Community of Practice
- Product Management: Community of Practice
- Community of Practice: Product Management
- Some other thing.

**Comment by drubgrubby** [comment]
per @Olivia-Chiong via slack - We are going to standardize the Communities of Practice to read: 

Community of Practice: Team
for example
Community of Practice: Product Management

**Comment by drubgrubby** [comment]
@Olivia-Chiong - I mentioned in slack that these were ready for user acceptance testing.  I'm just putting it here in the issue to memorialize that.

**Comment by Olivia-Chiong** [comment]
@drubgrubby Thanks David, my apologies, but can you change the meeting on Friday to be 1 hour?

**Comment by drubgrubby** [comment]
@Olivia-Chiong - The Friday meeting has been changed to 1 hour.

**Comment by Olivia-Chiong** [comment]
Thank you. All good now.
