### ISSUE TITLE
Add meeting time for UI/UX Community of Practice

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/VRMS#482]
### Overview
We need to add the team meeting time for UI/UX Community of Practice so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (day of week, start time am/pm, duration):
Monday at 6 pm for 1 hour

### What is your project page URL?
No project page, here's the repo - https://github.com/hackforla/UI-UX

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #ui-ux
Slack @handle: Olivia Chiong or Danielle Nedivi

**Comment by alex-anakin** [comment]
@Olivia-Chiong The even was added. Please check it out.

**Comment by drubgrubby** [comment]
The name on this was changed to "Community of Practice: UI/UX" to standardize the name of all of the Community of Practice listings.

**Comment by Olivia-Chiong** [comment]
Thank you for the updates @drubgrubby
