### ISSUE TITLE
Add meeting time for Marketing Community of Practice

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/VRMS#483]
### Overview
We need to add the team meeting time for Marketing Community of Practice so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (day of week, start time am/pm, duration):
Tuesday, 6 pm for 1 hour

### What is your project page URL?
No project page, here's the repo - https://github.com/hackforla/marketing

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #hfla-marketing
Slack @handle: Olivia Chiong

**Comment by drubgrubby** [comment]
@Olivia-Chiong - The Community of Practice: Marketing times have been added.  Please check them out and confirm that they are correct.  Thanks.

**Comment by Olivia-Chiong** [comment]
@drubgrubby The meeting time has now been changed to Friday at 5 pm. Apologies for the change!

**Comment by drubgrubby** [comment]
@Olivia-Chiong - This has been updated to Friday @ 5pm.

**Comment by Olivia-Chiong** [comment]
Great, thank you. This is good.
