### ISSUE TITLE
Add team meeting times for Civic Tech Index

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/VRMS#484]
### Overview
We need to add/change the team meeting time for Civic Tech Index so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (day of week, start time am/pm, duration):
Developers Meeting - Tuesday, 5:30 pm for 2 hours
Product Managers Meeting - Wednesday, 12:30 pm for 1 hour
Team Meeting - Thursday, 6 pm for 1 hour
Team Meeting - Sunday, 2 pm for 2 hours

### What is your project page URL?
https://www.hackforla.org/projects/civic-tech-index

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #civic-tech-index
Slack @handle: Olivia Chiong

**Comment by drubgrubby** [comment]
These changes have been completed.  I will message Olivia for user acceptance testing. (I'm not on the github yet, so I can't assign or move this issue yet).

**Comment by drubgrubby** [comment]
@Olivia-Chiong - These changes to the Civic Tech Index meeting times. have been completed.  Can you please confirm that these changes are correct (and that the meeting times haven't changed since the original ticket was placed ;-)

**Comment by Olivia-Chiong** [comment]
@drubgrubby confirmed with thanks!
