### ISSUE TITLE
Add meeting time for Record Clearance Project for Check-IN

### ISSUE THREAD

**Issue by khushbooshah-PM** [hackforla/VRMS#486]
### Overview
We need to add/change the team meeting time for Record clearance Project so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (day of week, start time am/pm, duration):
Thursday, 6pm to 7 PM, 1 hours

### What is your project page URL?
https://www.hackforla.org/projects/record-clearance-project

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name:  ##record-clearance
Slack @handle: @Gretchen 
<hr />

**Comment by ggrrettcchhenn** [comment]
Record Clearance Project Meeting times:

Team meeting - every other Monday 6:00 pm - 7:00 pm PST
Design & Research meeting - Tuesdays 6:00 pm - 7:00 pm PST
Dev meeting - Thursdays 6:00 pm PST (typically runs 15 - 30 min)

**Comment by ggrrettcchhenn** [comment]
Slack Channel name: [#record-clearance](https://hackforla.slack.com/archives/record-clearance)
People to contact on Slack: @Myranda Pierce and @Gretchen Howard

**Comment by alex-anakin** [comment]
@ggrrettcchhenn please clarify what should be changed. Mentioned meeting time has no difference with actual values on https://www.hackforla.org/project-meetings

**Comment by ggrrettcchhenn** [comment]
@alex-anakin no need to change the meeting times on the website. I had commented those times in response to them not being listed correctly on this issue so that the Monday & Tuesday weren't taken off the site.

**Comment by alex-anakin** [comment]
@ggrrettcchhenn Meeting time order can't be changed in the nearest time, sorry.
This type of task is for changing meetings' time range or day of the week.

**Comment by drubgrubby** [comment]
@alex-anakin - This ticket appears to be completed.  I am moving it to 'done'.  Let me know if we can close it.
