### ISSUE TITLE
Update EventTemplate data model due to changed requerements

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#487]
### Overview
Update [EventTemplate ](https://github.com/hackforla/VRMS/blob/development/backend/models/eventTemplate.model.js) model due to the [doc](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#heading=h.aui7osumr40e).

### Action items

- [ ] Update the model
- [ ] Fix tests

**Comment by akibrhast** [comment]
@alex-anakin 
1. Am I supposed to only add the fields highlighted in yellow? Or Should I remove the existing `eventTemplateSchema` and recreate it following the fields in the image below?

2. Also during monday meeting there was a picture of the overall database architecture? Where can I find it?

3. Do I need to follow the naming convention highlighted in yellow or just do something that best fits the description?

4. Why the need for the time zone , when that is already available from the starttime and endtime values ?

5.  What is the difference between `eventTemplateSchema` and `eventSchema` purpose? https://github.com/hackforla/VRMS/issues/364#issue-731743379

6. One of the highlighted fields below is `Time zone` . Why do we need the timeZone field? Isn't that information available already via start time and end time values? It seems the timeZone might be related to https://github.com/hackforla/VRMS/issues/455#issue-783055591 . Would you have a moment to discuss/explain that issue?
```json
startTime: "2020-05-12T02:00:00.000Z",
endTime: "2020-05-12T03:00:00.000Z",
```

7. What is the functional difference between the master branch and the development branch? 

![image](https://user-images.githubusercontent.com/32349001/112105672-138e4680-8b83-11eb-8e29-c151adb51104.png)

**Comment by alex-anakin** [comment]
@akibrhast 
1. You need to update the existing schema. Align the code with the doc.
2. https://github.com/hackforla/VRMS/files/5871382/vrms5.pdf
3. Do your best. I will review your pull request anyway.
4. It will simplify the time handling across the application.
5. `Event` is a different data model. `Event` is something that happens ones but `EventTemplate` is a blueprint for events. 
6.  `TimeZone` from #455 is the dictionary. The `timeZone` property can have value from the dictionary only.
