### ISSUE TITLE
Create search input as a new UI element

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#488]
### Overview

Create search input as a new UI element (based on finalized 0.4 Style Guide).

Find mockup here => [Finalized v0.4 Style Guide (Figma), page 2](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25453%3A28)

![search-input](https://user-images.githubusercontent.com/11681030/107314252-173d9200-6a49-11eb-8797-a3a3e6508bf2.png)

### Action Items

- [x] Explore existing implementation for UI elements:
- `src/sass/elements`
- DEV UI KIT web page (run locally) http://localhost:3001/dev-ui-kit, take a look at the element `Input with icon`
- DEV UI KIT component https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js

- [x]  Create JSX for new UI element inside `/*** INPUTS ***/` section in [`src/utils/uiKit`](https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js)
- [x]  Add styles for new UI element inside `src/sass/elements/_inputs.scss`
- [x]  Make sure a new UI element looks and works like in Style Guide

### Resources/Instructions
[Finalized v0.4 Style Guide (Figma)](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25453%3A28)
Dev UI Kit web page (run locally) http://localhost:3001/dev-ui-kit

**Comment by piall** [comment]
I have some doubts about input box width!!
Should  I give 18px margin left for search icon?
![image](https://user-images.githubusercontent.com/43095489/108168938-47a8be80-7122-11eb-9ed6-bbd45c48dcc2.png)
**or**, Should I give 21px margin right for the input box?
![image](https://user-images.githubusercontent.com/43095489/108169118-82125b80-7122-11eb-8bda-4a557606f326.png)
```css
or, just 0px for both search icon and input box?
```

**Comment by OlgaBilogurova** [comment]
Hi @mdPial, regarding mockups please reach out to our UX designer @cicyhou

**Comment by piall** [comment]
Okay. Thank you for the information.

**Comment by piall** [comment]
I have not received any response from her. I sent message two days ago in Slack.

**Comment by OlgaBilogurova** [comment]
Hi @mdPial,

Got it. I've already created a similar element but with the gitHub icon.
Please, check again `Input with icon` http://localhost:3001/dev-ui-kit

Apply these styles for your element:
```
.text-field-icon-container input {
    padding: 6px 45px 7px 21px;
}

.text-field-icon-container .text-field-icon {
    width: 20px;
    height: 20px;
    position: absolute;
    right: 18px;
    top: 7px;
}
```
