### ISSUE TITLE
Fix Scrolling In The DEV UI KIT Web Page

### ISSUE THREAD

**Issue by piall** [hackforla/VRMS#489]
### Overview
Currently, scrolling doesn't work properly if the screen height is small. It doesn't look like having any problem in the beginning. But if we scroll down up to the end it doesn't show all the content (depends on screen height how much content won't show).

![image](https://user-images.githubusercontent.com/43095489/107315698-68896800-6ac1-11eb-9834-a733d95af670.png)

### Steps to reproduce the issue
- run `npm run mvp`
- go to this url: http://localhost:3001/dev-ui-kit
- change the screen height < 825px

**Comment by OlgaBilogurova** [comment]
@mdPial when I developed `dev-ui-kit` I didn't add responsiveness because it's only for developers' needs.😁
Feel free to add responsiveness to `the dev-ui-kit` as well.

**Comment by piall** [comment]
Oh. I see. :sweat_smile:  I thought I am the one with the lowest small screen height in VRMS. So, others didn't notice and made an issue about it. 🤣️
