### ISSUE TITLE
Add UI/UX Community of Practice Meeting

### ISSUE THREAD

**Issue by daniellex0** [hackforla/VRMS#495]
### Overview
We need to add the weekly Community of Practice meeting time for the **UI/UX Community of Practice** so that it will appear on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (PST time ONLY) (day of week, start time am/pm, duration):
Monday, 6:00 pm, 1 hour

### What is your project page URL?
https://github.com/hackforla/UI-UX/blob/main/README.md

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #ui/ux (Hack for LA slack community):
Slack @daniellenedivi
<hr />

**Comment by drubgrubby** [comment]
The meeting time was added on ticket #482 .  

@daniellex0 @Olivia-Chiong 
The two tickets have different project page URLs:
-- This ticket has:  https://github.com/hackforla/UI-UX/blob/main/README.md
-- #482 has: https://github.com/hackforla/UI-UX

Which do you want listed?

**Comment by Olivia-Chiong** [comment]
I will leave it to @daniellex0 for her decision as she is the community lead.

**Comment by daniellex0** [comment]
@drubgrubby Thank you! Please list the second one #482 https://github.com/hackforla/UI-UX )

**Comment by drubgrubby** [comment]
The project page url has been set as requested by danielle.
