### ISSUE TITLE
List of possible location does not match code comments

### ISSUE THREAD

**Issue by akibrhast** [hackforla/VRMS#499]
### Overview
One of the locations returned by the endpoint: https://www.vrms.io/api/projects was 'dtla' whereas the code comments suggested only the following `\\DTLA, Westside, South LA, or Remote (hacknight)`

### Action Items
- [ ] Ensure that data is consistent

### Resources
https://github.com/hackforla/VRMS/blob/2045f382e655d42b55af43533834faf98a1d1084/backend/models/project.model.js#L24

![image](https://user-images.githubusercontent.com/32349001/109271517-a1258300-77dd-11eb-969f-786850668013.png)

**Comment by akibrhast** [comment]
@alex-anakin How do you want this issue to be prioritized?

**Comment by JackHaeg** [comment]
This will be handled by People Depot.
