### ISSUE TITLE
Remove "Hack4LA Happy Hour" and "Hack4LA Onboarding" from schedule

### ISSUE THREAD

**Issue by daniellex0** [hackforla/VRMS#500]
### Overview
We need to remove the meetings "Hack4LA Happy Hour" and "Hack4LA Onboarding"  from Mondays and Tuesdays so that the schedule on hackforla.org will be accurate- because the Happy Hour is no longer happening, and the Onboarding switches every week between Monday and Tuesday.

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
Remove all of these please:
- Hack for LA, Happy Hour, Monday, 6pm, 2 hours
- Hack for LA, Onboarding, Monday, 6pm, 2 hours
- Hack for LA, Happy Hour, Tuesday, 6pm, 2 hours
- Hack for LA, Onboarding, Tuesday, 6pm, 2 hours

### What is your project page URL?
https://www.hackforla.org/projects/website

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel (Hack for LA slack community):
Slack @daniellenedivi
<hr />

**Comment by drubgrubby** [comment]
@daniellex0 - Onboarding and Happy Hour have been removed from the schedule.  Please check and confirm that the changes are correct.

**Comment by daniellex0** [comment]
@drubgrubby These are correct, thank you!
