### ISSUE TITLE
Create dropdown as a new UI element

### ISSUE THREAD

**Issue by OlgaBilogurova** [hackforla/VRMS#501]
### Overview

Create dropdown as a new UI element (based on finalized 0.4 Style Guide).

Find mockup here => [Finalized v0.4 Style Guide (Figma), page 2](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25453%3A28)

![dropdown](https://user-images.githubusercontent.com/11681030/110408409-56f09d00-803a-11eb-8339-182ae5061dd9.png)

### Action Items

- [x] Explore existing implementation for UI elements:
- `src/sass/elements`
- DEV UI KIT web page (run locally) http://localhost:3001/dev-ui-kit 
- DEV UI KIT component https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js

- [x]  Create a new section `/*** DROPDOWN ***/` section in [`src/utils/uiKit`], add JSX for new UI element inside this section (https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js)
- [x] Create a new scss file `_dropdown.scss` inside `src/sass/elements`
- [x] Add styles for new UI element inside `_dropdown.scss`
- [x] Define in the component data object that simulating JSON data coming from the API:
```
const data = {
   timezones : ["HST | Hawaii Standard Time", "AKST | Alaska Standard Time", "PST | Pacific Standard Time", "MST | Mountain Standard Time", "CST | Central Standard Time", "EST | Eastern Standard Time"]
 }
```
Display this data inside the dropdown
- [x]  When the user selects an option from the dropdown, save it to variable

### Resources/Instructions
[Finalized v0.4 Style Guide (Figma)](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25453%3A28)
Dev UI Kit web page (run locally) http://localhost:3001/dev-ui-kit

**Comment by piall** [comment]
I am little bit confused about this step. As data and UI didn't match.
![image](https://user-images.githubusercontent.com/43095489/111403826-e4498680-86f7-11eb-9ee2-2d7d97eafc4b.png)

Could you explain me more about the implementation? 
```
 Define in the component data object that simulating JSON data coming from the API:

const data = {
   timezones : ["HST | Hawaii Standard Time", "AKST | Alaska Standard Time", "PST | Pacific Standard Time", "MST | Mountain Standard Time", "CST | Central Standard Time", "EST | Eastern Standard Time"]
 }
```

**Comment by mdPial** [comment]
I understand that when user will select `Hawaii Standard Time` 
![image](https://user-images.githubusercontent.com/43095489/111404017-37bbd480-86f8-11eb-80e0-6d9eba61ab01.png)
here `HST` will show. Am I thinking right way?. But what about this?
![image](https://user-images.githubusercontent.com/43095489/111404042-4a360e00-86f8-11eb-923b-182fe8f07713.png)

**Comment by piall** [comment]
@OlgaBilogurova in case you have missed it. I am requesting to check the above comments.

**Comment by OlgaBilogurova** [comment]
@mdPial At the mockup you can see data as an example, to show how the dropdown works. I provided in the description the data object that simulating JSON data coming from the API for one of the future dropdowns. But the data could be absolutely different. 

This issue about creating a dropdown as a new UI element. When it would be implemented we could pass any data object using props. That's why the data in the mockup and in the description are different.

**Comment by peteplass** [comment]
Pial is currently taking exams and will return to project in the near future.

**Comment by piall** [comment]
My exam has finished. I have started working again on this issue :smiley:

**Comment by piall** [comment]
@OlgaBilogurova I know you won't be able to work till April. Sorry for mentioning now. You can reply anytime.

I have an issue. I have implemented up to this. ![image](https://user-images.githubusercontent.com/43095489/116216600-9c903300-a76a-11eb-8a2a-f1c9d99d32bb.png)

According to [resource-1](https://stackoverflow.com/questions/31177789/increase-gap-between-select-menu-options) [resource-2](https://stackoverflow.com/questions/12301729/styling-for-option-values-in-a-html-select-drop-down-doesnt-work-in-chrome-sa) [resource-3](https://stackoverflow.com/questions/22681141/select-option-padding-not-working-in-chrome) without making full custom dropdown select option using `JS` or any `JS Plugin` it's not possible to implement below portion like this as `<option>` are OS and browser dependent. 
![image](https://user-images.githubusercontent.com/43095489/116198976-6ea1f300-a758-11eb-93e2-da411afbfb57.png)
I am little bit confused about choosing one over another because our `JSX` element will have dependency of `JS` file or any extra Plugin. What should I do?.

**Comment by peteplass** [comment]
Thanks for giving us an update, Pial!

**Comment by piall** [comment]
> Thanks for giving us an update, Pial!

My Pleasure :smile:

**Comment by peteplass** [comment]
Hey Pial, I reached out to you over Slack - go ahead and use the "#vrms-tech" channel for tech questions.

**Comment by drubgrubby** [comment]
@mdPial -> I've had a chance to look at this issue and I have some thoughts.   Perhaps we can spend a few minutes on zoom at some point to talk about the best approach.  I'll slack you and we'll see if we can find some time.

**Comment by peteplass** [comment]
David reviewed PR - can offer feedback with consultation. Added question. Olga to review PR.

**Comment by OlgaBilogurova** [comment]
Reviewed PR, provided suggestions/comments, and requested changes.
