### ISSUE TITLE
Update user and project models

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#502]
### Overview
For implementing project management UI we need to store managers in projects and projects in users.

### Action Items

- [x] Add field `managedProjects` as an array of Strings into `user` model.
- [x] Add field `managedByUsers` as an array of Strings into `project` model.
- [x] Check out tests don't fail.

### Resources/Instructions
[User model](https://github.com/hackforla/VRMS/blob/development/backend/models/user.model.js)
[Project model](https://github.com/hackforla/VRMS/blob/development/backend/models/project.model.js)

**Comment by drubgrubby** [comment]
I have added the fields to user and project model, and it seems to have passed the tests: 
<img width="309" alt="Screen Shot 2021-03-15 at 10 40 37 AM" src="https://user-images.githubusercontent.com/68244054/111197454-b7706480-857b-11eb-9acb-a7171fff3d67.png">
<img width="235" alt="Screen Shot 2021-03-15 at 10 40 21 AM" src="https://user-images.githubusercontent.com/68244054/111197465-ba6b5500-857b-11eb-9db3-459487b11a90.png">

Question: The test wasn't changed to accommodate the new fields.  Should I update the tests and re-run them?

**Comment by drubgrubby** [comment]
This is probably unrelated, but I am having some additional errors that I think are unrelated.  I'm posting them here to discuss at the meeting.  I can delete this comment if unrelated: 
<details>
<summary>Terminal error 1</summary>
<img width="974" alt="Screen Shot 2021-03-15 at 10 41 28 AM" src="https://user-images.githubusercontent.com/68244054/111201194-c527e900-857f-11eb-93ee-5a0825202702.png">
</details>

<details>
<summary>Terminal error 2</summary>
<img width="605" alt="Screen Shot 2021-03-15 at 10 43 15 AM" src="https://user-images.githubusercontent.com/68244054/111201305-dcff6d00-857f-11eb-8285-7fe99a5382e5.png">
</details>

<details>
<summary>Terminal error 3</summary>
<img width="429" alt="Screen Shot 2021-03-15 at 10 45 32 AM" src="https://user-images.githubusercontent.com/68244054/111201361-ebe61f80-857f-11eb-82aa-755bac1221d5.png">
</details>
