### ISSUE TITLE
Implement a page for managing users

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#504]
### Overview
~1. As a project manager, I want to create a new project.~ (moving to separate issue)
~2. As a project manager, I want to change my existing project details.~ (moving to separate issue)
3. As an Administrator, I want to assign/unassign managers for projects.

### Action Items

1. Login user. If the user is an admin -> it goes to the home page. We need to add a hyperlink to the project management `projects` and user management `users` pages.
2. Login user. If the user has a non-empty array `managedProjects` then redirect him to the project management page.
3. Users page. 
* Get all users. GET /api/users and GET /api/projects
* Show 2 inputs for searching users by email and by name. No users initially on the page. We have a list of users in the client already so we need just to filter it. When the admin inputs a letter we will show a filtered list of users on the page. Columns: First Name, Last Name, email, projects.
* Clicking on any user should expand an additional section with the following elements: dropdown with all projects and the "Save changes" button. The admin can choose any project and then save changes.

### Resources/Instructions
Directory for the new page https://github.com/hackforla/VRMS/tree/development/client/src/pages
https://github.com/hackforla/VRMS/blob/59ebef0b72948530ad22e572d706a2b2df4c5568/client/src/components/Navbar.js

**Comment by drubgrubby** [comment]
@alex-anakin -> On the Admin Nav there is now an option to "Add Event".  Is that functionality going to be moved into the "Projects" area that is only accessible to the Project Managers for that project?

It seems like the PM should log into one of the projects that they are allowed to manage, and from there they will be able to create and edit events.

But maybe this add event is something else. 

I'm trying to figure out if the Admin nav should show: 

Option 1 -> Home Events Add Event Projects Users
or
Option 2 -> Home Events Projects Users

**Comment by drubgrubby** [comment]
### Progress:
I'm about a week away from finishing the admin part where users are assigned projects that they can manage.  

### Blockers:
I have not yet bent Ract to my will and instead spend much of my day cursing it.  I'm assuming that as I solve some of the puzzles about hope to pass things to and through components that this process will go more quickly. 

### Availability:
All of the time that I'm not working on my taxes. 

### ETA:
Let's say this component will be done next Monday.

**Comment by drubgrubby** [comment]
### Progress:
I made lots of progress, but some of that was proceeded by regress - I had to tear some parts of the component back and build them back more React.  I need to complete the add to database functionality, and then style and tidy. 

### Blockers:
All of the things I don't know. 

### Availability:
Hopefully I'll finish by the weekend.  Driving down to the desert on Sunday.

### ETA:
6:58pm one week from today.

**Comment by drubgrubby** [comment]
### Progress:
Almost done with this feature. 

### Blockers:
misbehaving multi-level arrays and React confusion.

### Availability:
When awake. 

### ETA:

Thursday before noon.

**Comment by drubgrubby** [comment]
### Progress:
Part one of this - adding projects to users so that they can manage them - is working, and I am very happy about that.  I still need to do some rudimentary styling, and then I'll do a PR. 

### Blockers:
My eyes hurt from staring at a computer so much. 

### Availability:
Yes

### ETA:
Thursday

**Comment by peteplass** [comment]
Please update when you get a chance.

**Comment by drubgrubby** [comment]
There is an outstanding pull request on this issue.

**Comment by drubgrubby** [comment]
### Progress:
There are just a couple of minor code changes and this will be done. 

### Blockers:
I am currently at this meeting. 

### Availability:
I will finish this tomorrow. 

### ETA:
Tomorrow, the day I finish it.
