### ISSUE TITLE
add onboarding session3/16/2021

### ISSUE THREAD

**Issue by peteplass** [hackforla/VRMS#505]
### Overview
We need to add/change the team meeting time for [YOUR PROJECT NAME HERE] so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- New participant onboarding 6:00pm Alternating Mondays and Tuesdays

### What is your project page URL?
https://www.hackforla.org/projects/vrms

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #new-joiner-orientation: 
Slack @handle: @Pete Plass
<hr />
### Instructions
this is requested by @ExperimentsInHonesty

**Comment by drubgrubby** [comment]
@peteplass @ExperimentsInHonesty -> I'm assuming that "Alternating Mondays and Tuesdays" means that one week it's on Monday, and the following week it's on Tuesday.  The challenge is that the meeting display isn't really a calendar, so there's not really a way to make it show up one week under Mondays, and the next under Tuesdays.  

I can put it in on both Monday and Tuesday, and have the 'eventType' field say something like "alternate weeks".   In the following image, eventType is what is displaying "Team meeting", "Weekly meeting", etc.

<details>
<summary>How eventType shows</summary>
<img width="725" alt="image" src="https://user-images.githubusercontent.com/68244054/111523111-2387cf80-8718-11eb-9c77-ebcbe27a50a4.png">

</details>

However, since there are no dates listed, only days of the week, it seems like that would be confusing.  

Let me know your thoughts on how to proceed with this.

**Comment by drubgrubby** [comment]
@peteplass - You listed "https://www.hackforla.org/projects/vrms" as the Project Page URL.  This is the place that the person is redirected to when they click the link in the schedule.  I don't think that the vrms page is where people should get redirected to if they are interested in onboarding.  Is it?  If not, what is the url that people should be sent to when you they click the "onboarding" link?

**Comment by peteplass** [comment]
@drubgrubby ah, gotcha. I think what we're looking at here is two events that occur every other week. One on Tuesdays and one on Mondays. As for an onboarding link, It's likely going to be the onboarding site for zoom registration: https://us02web.zoom.us/meeting/register/tZUtdeGvrTMoHtKkRwm7R8Kl8r9TXL73-UY9?_x_zm_rtaid=TNHnsFXoTF2IZlf-TUfrPw.1616083598988.a1e0d0f77cffa24ca0d6e75e25e23695&_x_zm_rhtaid=832

**Comment by drubgrubby** [comment]
@alex-anakin -> 
Question background: Bonnie wants to add Onboarding to the recurring event schedule.  The onboardings are held on alternating Mondays and Tuesdays: one week it's on Monday, the next week it's on Tuesday.  She's okay listing it on both days, and making a note (probably using 'eventType") that it's alternating, and to check meetup.

However, she wants to make sure that vrms only gives the option to check in to the onboarding on the week when it's happening.  For example, on the week that onboarding is happening on Monday, the option to check-in to a meeting should only happen on Monday, and not on both Monday and Tuesday. The following week, it would only show up on Tuesday. 

**The question: Is it possible to have the onboarding check-in option show up only on the day and week that the onboarding is taking place, on Monday one week and on Tuesday the next week?**  

My guess is that it is not, and that if we put it on the calendar on both days, it will show up as a check-in option on both days. 

(Let me know if this question is not clear).

**Comment by drubgrubby** [comment]
@peteplass @ExperimentsInHonesty 

Onboarding has been added to the calendar on both Monday and Tuesday with a note "Alternating Mon/Tue. Click for schedule".  

<details>
<summary>HfLA Meetings Page</summary>

![screencapture-hackforla-org-project-meetings-2021-03-25-21_07_52](https://user-images.githubusercontent.com/68244054/112575787-3fd9db00-8dae-11eb-8bcc-4a00a872f864.png)

</details>

Please confirm that this is correct and/or leave the wording that you would prefer.

**Comment by peteplass** [comment]
Checked on Monday 4/4, was working for onboarding

**Comment by peteplass** [comment]
Will check again on Tuesday 4/ 13. Issue will be closed if working.

**Comment by drubgrubby** [comment]
@peteplass -> Can we close this?
