### ISSUE TITLE
Add to events: Software Engineering Community of Practice

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#507]
### Overview
We need to add/change the team meeting time for Software Engineering Community of Practice so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Community of Practice: Engineering, Wednesday 6pm, 1 hour

### What is your project page URL?
https://github.com/hackforla/engineering/blob/main/README.md

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #engineering
Slack @handle: Greg Pawin
<hr />

**Comment by drubgrubby** [comment]
<img width="432" alt="Screen Shot 2021-03-21 at 9 30 01 AM" src="https://user-images.githubusercontent.com/68244054/111913325-e0d13a80-8a2a-11eb-9b8b-77308537ac33.png">

This has been added to the calendar.  Please confirm that these changes are correct.

**Comment by drubgrubby** [comment]
Per Greg Pawin via slack, this is correct.
