### ISSUE TITLE
Correct Lucky Parking Meeting Time

### ISSUE THREAD

**Issue by gregpawin** [hackforla/VRMS#508]
### Overview
We need to add/change the team meeting time for [YOUR PROJECT NAME HERE] so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [X] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Lucky Parking, General Meeting, Monday 7pm, 1 hour

### What is your project page URL?
https://www.hackforla.org/projects/lucky-parking

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #lucky-parking
Slack @handle: Greg Pawin
<hr />
### Instructions

Website events page: https://www.hackforla.org/events/, is showing Lucky Parking Meeting time as 5:30 to 10:30pm. It should be 7PM - 8PM on Monday evenings.

**Comment by drubgrubby** [comment]
This change has been completed: 

<img width="412" alt="Screen Shot 2021-03-22 at 6 07 58 PM" src="https://user-images.githubusercontent.com/68244054/112077386-9ee2ea00-8b39-11eb-9eb1-22e15265bba9.png">

**Comment by gregpawin** [comment]
Looks great! Thanks!
