### ISSUE TITLE
Ballot Nav check-in does not appear at designated time in check-in dropdown each week

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#509]
desired behavior. on all Tuesdays around 5pm, in line with [schedule](https://www.hackforla.org/events/), ballotnav meeting should appear as a clickable checkin option in the dropdown at vrms.io

**Comment by drubgrubby** [comment]
@switchzer0 -> BallotNav seems to be showing up in the drop-down now.  Was this a consistent thing, or was BallotNav not showing up intermittently? 

Please let us know (reopen this issue) if you notice that it doesn't show up in the future.  I'm guessing this is solved, but it's possible it's some weird intermittent thing.    

<img width="574" alt="Screen Shot 2021-03-30 at 6 22 48 PM" src="https://user-images.githubusercontent.com/68244054/113207993-28737580-9226-11eb-9fe9-967513b44d73.png">

**Comment by switchzer0** [comment]
was a request from user. guess it's resolved itself!

**Comment by alex-anakin** [comment]
Closing as duplicate of #522
