### ISSUE TITLE
README.md updates for easier onboarding

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#511]
### Overview
Edit README.md to make onboarding easier for new VRMS team members. 

### Action Items
Updates will include: 

- [x] Clarify the "configure your database" section to remove references to setting up a local MongoDB server.
- [x] Remove the docker setup information. (It seems (from my experience) that the docker setup is currently unreliable.  If we choose not to remove the docker component, then perhaps the suggestion to try the local configuration if you are having trouble with the docker configuration. 
- [x] Clarify the section on Incorporating changes from upstream.  Because of the branch names (master instead of development) and the fact that this is different than the way at least the website team does it, I think this would benefit from some additional explanation. 
- [x] Clarify the section about using 'touch' for environmental variables.  The paths don't work as is, and Windows machines don't have touch. 
- [x] Remove "(locally)" from "Get up and running". (If we're removing docker). 
- [x] Change references to "Hack nights" to "team meetings" (or something like that) as I do not think the website refers to hacknights any more. 
- [x] Make the Slack references into hyperlinks
- [x] Misc. other language changes to improve clarity. 

### Resources/Instructions
https://github.com/hackforla/VRMS/blob/development/README.md

**Comment by peteplass** [comment]
@drubgrubby Rewrote readme files to help onboard people more easily. pull request awaiting review. Akib has reviewed. Waiting on Alex to sign off.
