### ISSUE TITLE
Update Food Oasis Meeting Times

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/VRMS#514]
### Overview
We need to add/change the team meeting time for Food Oasis so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Food Oasis, Management, Monday 3:00pm, 1 hour
- Food Oasis, Development, Tuesday 6:30pm, 1 hour
- Food Oasis, Management, Thursday 6:00pm, 1 hour

### What is your project page URL?
https://www.hackforla.org/projects/food-oasis

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #FOLA
Slack @handle: Katie Jensen (U01JKTLQGBF)
<hr />

**Comment by drubgrubby** [comment]
@ktjnyc -> I've updated the Food Oasis meeting times.  Can you please check them and confirm that they are correct?  

https://www.hackforla.org/project-meetings

**Comment by ktjnyc** [comment]
@drubgrubby - I made a mistake. Thursday should be: 

Food Oasis, Team, Thursday 6:00pm, 1 hour

Could you update that? Thanks

**Comment by drubgrubby** [comment]
@ktjnyc -> I've made the update.  Please confirm that it is correct.  Thanks.

**Comment by ktjnyc** [comment]
Looks good now! Thanks.

**Comment by ktjnyc** [comment]
The meetings don't seem to be showing up on the VRMS website at meeting time.  Is it possible to get that updated too?
