### ISSUE TITLE
Add Accesss The Data Project to the project database

### ISSUE THREAD

**Issue by snooravi** [hackforla/VRMS#516]
### Overview
We need to add/change the team meeting time for Access the Data so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Access the Data, Team Meeting, Tuesday 2:00pm, 1 hour

### What is your project page URL?
http://accessthedata.org/

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #access-the-data
Slack @handle: @snabelsi
<hr />

**Comment by drubgrubby** [comment]
@snooravi -> The Access the Data team meeting has been added to the website calendar.  Please check it and confirm that it is correct.  Thanks. 

https://www.hackforla.org/project-meetings

**Comment by snooravi** [comment]
Looks great! thank you
