### ISSUE TITLE
Change Lucky Parking Meeting Time

### ISSUE THREAD

**Issue by gregpawin** [hackforla/VRMS#530]
### Overview
We need to add/change the team meeting time for Lucky Parking so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [X] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Lucky Parking, Team meeting, Monday 6pm, 1 hour

### What is your project page URL?
https://www.hackforla.org/projects/lucky-parking

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #lucky-parking
Slack @handle: @ Greg Pawin
<hr />
### Instructions
Please change the meeting time from Monday at 7pm to Monday at 6pm

**Comment by drubgrubby** [comment]
@gregpawin -> I've made the change as you requested.  Please confirm that this change is correct.  

<img width="851" alt="Screen Shot 2021-04-20 at 9 38 28 AM" src="https://user-images.githubusercontent.com/68244054/115433414-65df7900-a1bc-11eb-9fc5-a232a8a633f3.png">

**Comment by gregpawin** [comment]
Looks good! Thanks!
