### ISSUE TITLE
Change the meetings time for BOP to Civic Tech Structure meeting times

### ISSUE THREAD

**Issue by akibrhast** [hackforla/VRMS#531]
### Overview
As requested on sunday meeting by @ExperimentsInHonesty . 

- The meeting times for the card project card -> [Brigard Organizers Playbook Card](https://www.hackforla.org/projects/brigade-organizers-playbook) should have the meeting times from the [CTS Card](https://www.hackforla.org/projects/civic-tech-structure)  moved to it

- Remove those meetings times from CTS  [CTS Card](https://www.hackforla.org/projects/civic-tech-structure)
### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
![image](https://user-images.githubusercontent.com/32349001/116129747-7601c780-a698-11eb-8a0d-0fe21063be73.png)

### What is your project page URL?
https://www.hackforla.org/projects/brigade-organizers-playbook

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name:  unknown
Slack `@handle`: `@Bonnie`  , `@Olivia Chiong` , `@Serena B`
Github `@handle`: @ExperimentsInHonesty , @Olivia-Chiong , @s
<hr />

### Instructions

Please add the above listed times for the BOP project in VRMS

**Comment by drubgrubby** [comment]
@akibrhast -> I don't understand what's being asked for here.  Do you?  There are three different projects mentioned on this issue: Brigade Organizers Playbook, Civic Tech Structure, and Home Unite Us.  

Civic Tech Structure has meetings at: Sat 11:00 am - 1:00 pm, Tue 9:00 am - 11:00 am and Thu 9:00 am - 11:00 am 

From the issue title I would guess that I should add those same meeting times for BOP.  Am I deleting the Civic Tech Structure meeting times?  Do they just have all of their meetings at the same time?  

I'm assuming that the Home Unite Us meetings are just the times that you didn't delete from the template where it says to list the meeting times. Correct? 

Can you give me some clarity on this, or point me to a person or an issue that can clarify this?  Thanks!

**Comment by akibrhast** [comment]
Hey @drubgrubby ,
My apologies, the initial issue created was incomplete and messy. I have just edited it.

> Am I deleting the Civic Tech Structure meeting times? 

- No I do not think so. Since no comment was made about deleting the Civic Tech Structure meeting times. @ExperimentsInHonesty Please confirm.

> Do they just have all of their meetings at the same time?

- This is not known. @ExperimentsInHonesty Please confirm.

> I'm assuming that the Home Unite Us meetings are just the times that you didn't delete from the template where it says to list the meeting times. Correct?

- That is indeed correct. My apologies. I have edited it out.

> Can you give me some clarity on this, or point me to a person or an issue that can clarify this?

- I would possibly check/confirm with @ExperimentsInHonesty or @Olivia-Chiong in regards to final details

**Comment by akibrhast** [comment]
@baleja please confirm the meeting times for BOP

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty @Olivia-Chiong ->  I have added Brigade Organizers Playbook meetings  to the calendar. 

Please confirm that this is correct...or that it is not.  

<img width="517" alt="Screen Shot 2021-04-26 at 11 23 06 AM" src="https://user-images.githubusercontent.com/68244054/116131988-e05b3d80-a681-11eb-9854-23974bc42b8e.png">

<img width="628" alt="Screen Shot 2021-04-26 at 11 23 15 AM" src="https://user-images.githubusercontent.com/68244054/116132017-e81ae200-a681-11eb-8b7c-3bfa9be273a0.png">

<img width="653" alt="Screen Shot 2021-04-26 at 11 23 22 AM" src="https://user-images.githubusercontent.com/68244054/116132041-ee10c300-a681-11eb-8d1a-78b99864a2e9.png">

**Comment by Olivia-Chiong** [comment]
@drubgrubby We will actually be removing the times from Civic Tech Structure once they have been moved to BOP. Require @baleja to confirm the meeting times. I've sent this to her on Slack as well.

**Comment by Baleja** [comment]
Hello there, BOP core meeting time on tuesday is at 10am PST not 9 anymore.
We also do not have the meetings on Thursday anymore as per Bonnies request.

**Comment by drubgrubby** [comment]
Hi @Baleja - Just to confirm.  There are two meetings: 

Tuesday, 10am -11am - Core Team
Saturday, 11am - 1pm - Core Team

Please confirm.  Thanks.

**Comment by Baleja** [comment]
Yes confirmed

**Comment by drubgrubby** [comment]
@Baleja (@Olivia-Chiong @ExperimentsInHonesty ) -> I have added the two BOP meetings to the calendar, and removed the Civic Tech Structure meetings.  

https://www.hackforla.org/project-meetings

Please confirm that it has been done correctly.  Thanks.
