### ISSUE TITLE
Try to deploy VRMS v0.3 current code on Heroku as a development instance.

### ISSUE THREAD

**Issue by peteplass** [hackforla/VRMS#533]
### Overview
Deploy the VRMS application on Heroku from [prod](https://github.com/hackforla/VRMS/tree/prod) branch. It's a copy of the `development` branch.

### Action Items
1. Don't create Heroku-specific Procfile.

2. Don't run `client-mvp-04` on Heroku, just `backend` and `client`.

3. Pull VRMS code on the Heroku (I'm not sure about Heroku's way of delivering the code to the instance).

4. Create `.env` files with the same values as for the [local deployment](https://docs.google.com/document/d/1yDF6UmyO-MPNrl3y_Mw0mkm_WaixlSkXzWbudCzHXDY/edit).

5. Heroku will run the `start` script by default from [package.json](https://github.com/hackforla/VRMS/blob/prod/package.json)

6. If that doesn't work take a look at the old [package.json](https://github.com/hackforla/VRMS/blob/master/package.json). There was a two-step Heroku deployment:
```
"start": "node server.js",
"heroku-postbuild": "cd client && npm install && npm run build"
```
  If needed fix the `package.json` in the development branch then make a pull request to `prod`.

7. We don't need a domain for the dev instance because Heroku provides some URL like `http://vrms-8408.herokuapp.com` (where `8408` is a random number).

**Comment by peteplass** [comment]
Alex assigned for task definition

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty -> Can you share whatever account information/credentials we need for Heroku so we can work on this?

**Comment by drubgrubby** [comment]
### Progress:
I just got added to Heroku today, so I am able to work on the vrms Heroku app.  So that feels like progress.

### Blockers:
I've never worked with Heroku, and there are many things that I don't know about many things. 

### Availability:
Yes

### ETA:
Hahahahaha.  Which is to say, I just got the login info, and I haven't started, so I can't even make an estimate.

**Comment by peteplass** [comment]
Currently moot while we switch to AWS
