### ISSUE TITLE
Check out that the application works in the new development instance on AWS incubator

### ISSUE THREAD

**Issue by peteplass** [hackforla/VRMS#534]
### Overview
Check out basic functionality after deploying the DEV instance on Heroku.

### Action Items
1. Register 2 new users in the DEV instance using existing and accessible emails.
2. Make one of the new users an admin directly in test DB using MongoDB Compass. MongoDB connection string is in [env variables](https://docs.google.com/document/d/1yDF6UmyO-MPNrl3y_Mw0mkm_WaixlSkXzWbudCzHXDY/edit).
3. Login by every user in the app.
4. Make check-in by non-admin user.
5. Check out the check-in record in the DB.

### Resources/Instructions
[How to create unlimited testing accounts with the Gmail+](https://www.eringibson.co/how-to-create-unlimited-testing-accounts-with-the-gmail-hack/)

**Comment by peteplass** [comment]
Alex assigned for task definition

**Comment by akibrhast** [comment]
It's broken in call kinds of weird ways, and I don't even know where to begin

**Comment by peteplass** [comment]
Currently moot.
