### ISSUE TITLE
Edit team meeting times for Engage

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/VRMS#539]
### Overview
We need to add/change the team meeting time for Engage so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Engage, All Team Members, Sunday 4pm, 1 hour
- Engage, All Team Members, Wednesday 6pm, 1 hour
- Engage, Product Manager Meeting, Wednesday 5pm, 1 hour

### What is your project page URL?
https://www.hackforla.org/projects/engage

### Who should we contact on your team (via Slack) for user acceptance testing
Slack @handle: Glen Florendo
<hr />

**Comment by drubgrubby** [comment]
@glenflorendo -> The changes to the Engage meeting times have been made.  Can you please check them out and confirm (in this issue) that they are correct?  Thanks. 

https://www.hackforla.org/project-meetings

**Comment by glenflorendo** [comment]
> @glenflorendo -> The changes to the Engage meeting times have been made. Can you please check them out and confirm (in this issue) that they are correct? Thanks.
> 
> https://www.hackforla.org/project-meetings

@drubgrubby The changes look great! Thank you so much!
