### ISSUE TITLE
Clarification on AWS account access/creation from Admin

### ISSUE THREAD

**Issue by peteplass** [hackforla/VRMS#549]
Admin is Olivia while Bonnie is out. 

Alex and Mohith to reach out to Olivia to schedule conversation this week.

**Comment by peteplass** [comment]
Currently waiting on Olivia regarding payment should project exceed MongoDB free tier.

**Comment by peteplass** [comment]
Mohith to update. @mrao2

**Comment by mrao2** [comment]
No reply from Olivia yet.

**Comment by peteplass** [comment]
Discussion w/ Alex on Thursday: We need access to vrms@hackforla.org in order to get access to the MongoDB account.
Bonnie notes: this may create a lot of paperwork because all separate clouds accounts need to be tracked separately and balloons admin overhead. 

Mohith: We can set up MongoDB on an EC2 instance on AWS. There may be scaling issues? 
AWS Fargate may save resources by containerizing the instance. 

This is an ongoing discussion. Mohith will reach out to Darren on Ops regarding next steps.

**Comment by peteplass** [comment]
@mrao2 Please update.

**Comment by peteplass** [comment]
Please checkout 1Password VRMS access through vrms@hackforla.org.

**Comment by peteplass** [comment]
We need to see if we can host a MangoDB instance within the current dev instance. 

Alex: do we have access to the vrms@hackforla.org account? 
We do not currently need an additional account for this - Mohith. 

Alex - we need to create an additional task for the Ops team regarding this.

**Comment by peteplass** [comment]
Closing due to duplicate.
