### ISSUE TITLE
Fix VRMS Dockerization 

### ISSUE THREAD

**Issue by peteplass** [hackforla/VRMS#551]
We need to focus on VRMS 0.3 Docker setup.

Backend docker file: https://github.com/hackforla/VRMS/blob/development/backend/Dockerfile.api
Client v 0.3 docker file: https://github.com/hackforla/VRMS/blob/development/client/Dockerfile.client
Docker-compose configs (we need to have the first only):
https://github.com/hackforla/VRMS/blob/development/docker-compose.yml
https://github.com/hackforla/VRMS/blob/development/docker-compose-ci.yaml

1. Remove `docker-compose-ci.yaml` config.
2. Fix the remaining Docker-compose config to be able to run the project from CLI using the following commands:
- `docker-compose build`
- `docker-compose up`

**Comment by akibrhast** [comment]
As discussed on 5/62021 
I am first going to work on fixing dockerization for v0.3 .

**Comment by akibrhast** [comment]
Not sure if I am supposed to :
1.  Figure out how to containerize the existing production vrms-03 ? That is currently running on heroku and is based on this [repo](https://github.com/sarL3y/VRMS-prototype)
OR
2. Figure out how to containerize the development vrms-03 that is connected to nothing atm

@alex-anakin @peteplass

**Comment by peteplass** [comment]
Alex to answer to move project along.

**Comment by alex-anakin** [comment]
@akibrhast we don't work with any other repositories than https://github.com/hackforla/VRMS 

The current state of VRMS 0.3 code in the repository is pretty far ahead of the Heroku deployed application state. Let's say, 500 commits ago the code was prepared for Heroku deployment. But now it's dockerized and all Heroku configs are gone.

Backend docker file: https://github.com/hackforla/VRMS/blob/development/backend/Dockerfile.api
Client v 0.3 docker file: https://github.com/hackforla/VRMS/blob/development/client/Dockerfile.client
For docker-compose I found 2 files:
https://github.com/hackforla/VRMS/blob/development/docker-compose.yml
https://github.com/hackforla/VRMS/blob/development/docker-compose-ci.yaml
But I'm not sure which one is actual and which one can be removed. Try to figure it out.

P.S. I updated the task description a little bit.

**Comment by akibrhast** [comment]
## Progress
The docker compose and the docker files are working and running the application. However I have not yet thoroughly tested out the entire application in all its details as was discussed/requested on last Thursday. Last week I was celebrating Eid. So did not spend any time working on anything. I should have a more detailed report in regards to how everything is working by this thursday or earlier.

## Blockers
None

## Availability
Evenings Everyday

## ETA
Upcoming Thursday

**Comment by peteplass** [comment]
Please update.

**Comment by akibrhast** [comment]
### Progress
Docker compose works as expected, all the routes and pages are working fine. We can delete docker-compose.ci
- Edited the docker-compose.yml file and removed the 0.4 client stuff

### Blockers
Please advise on what to do next.

### Availability
evenings


### ETA
I think this is done? Please advise.

**Comment by peteplass** [comment]
Alex states that we need to prepare PR then we need to communicate with ops team. For the ops team, this needs to run "out of the box".

**Comment by akibrhast** [comment]
Unfortunately I was not able to resolve this issue. I am self-unassigning myself from this. So that I won't cause a blocker and someone else can take over.

**Comment by jasonwong26** [comment]
## Status

Added [PR 591](https://github.com/hackforla/VRMS/pull/591) to address the proxy issue.

Akib tested it in his environment and the fix works.

## Next Steps

1. Have someone review both PRs linked to this ticket (#585 and #591)
   NOTE: PRs fail the ` test-mvp-unit` check due to removing the docker-elements related to client v0.4.
2. Merge the changes of both PRs
3. Update the google doc containing the application .ENV values to reference the new BACKEND_HOST variable created in #591

**Comment by akibrhast** [comment]
Merged in PR #591
