### ISSUE TITLE
Split 0.3 and 0.4 Backend/Frontend Code

### ISSUE THREAD

**Issue by peteplass** [hackforla/VRMS#553]
We need to use separate branches for 0.3 and 0.4. 

This must happen before Docker fix.

**Comment by alex-anakin** [comment]
I was blocked by #492. It's merged now.
ETA - end of the week.

**Comment by peteplass** [comment]
Github is very good at finding vulnerabilities in main branches.  Since there can't be two main branches, some of the dependency checks could go missed with two active branches, as the second one will need to be checked manually with every update. 

To get around this, we will have one single active branch and Alex will create two backend folders derived from the existing one.

**Comment by peteplass** [comment]
Alex moved some files, didn't have time to finish last week. Estimated time to complete: end of week of May 24.

**Comment by alex-anakin** [comment]
Didn't have time to finish it.
ETA: the next meeting (6/14/2021)

**Comment by alex-anakin** [comment]
Didn't feel well the last week.
No additional progress.
ETA: 6/21/2021

**Comment by peteplass** [comment]
Alex worked on documentation - not complete for this week 6/21 - 

ETA: 6/28

**Comment by alex-anakin** [comment]
Almost done, will create a PR tonight.

**Comment by alex-anakin** [comment]
Merged the development branch, got conflict. Resolved conflict then got failed checks.
