### ISSUE TITLE
Create issues to Implement page so project managers can mange the projects they are assigned

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#555]
[This is a placeholder issue that will be expanded into multiple issues and closed when issues have been created].

### Overview
Project managers are currently unable to add and change meeting times, and make other changes to their projects in VRMS.  This feature will allow them to make changes themselves. 

### Action Items

~0) Allow creation of new projects (add to admin section)~

~1) Create manage projects page and add things to React so it shows up at vrms.io/manageprojects~
 

<everything below dependent on that>

~-Set login so someone who has projects associated with them has access to the project editing~
~-Create select project component // This is where you select the project to edit if you have multiples~
~- Create functionality to read from and write to db~

~-Create editSpecificProject component // This is where you make changes to specific project. This page will show the current values of the different fields and give you the option to edit them individually by clicking a button. Each feature will be a separate component.~

<below dependent on above>

~- Add/remove/change meeting times, descriptions, etc~
~- Edit All other project fields~

Required components: 
~- Parent ManageProjects~
~- Select project~
~- EditSpecificProject~
~- EditMeetings~
~- EditProjectFields~

**Comment by averdin2** [comment]
I worked on this with @drubgrubby

**Comment by drubgrubby** [comment]
### Progress:
Moving right along.  Have the issues listed, about halfway done with creating them. 

### Blockers:
None. 

### Availability:
Yes

### ETA:
Wednesday

**Comment by drubgrubby** [comment]
Issues have been created for the edit projects feature.
