### ISSUE TITLE
Allow admin to create new projects

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#560]
### Overview
Create a feature so that admins can create new projects

### Action Items

- [x] Add a button to the useradmin page that will open a create new projects component
- [x] Add CreateNewProject component that will allow admin to create a new project
- [x] This will only take the name of the new project.  (Additional info will be added in project management section)
- [x] Test new project name against current names, both active and inactive.

### Resources/Instructions
vrms.io/useradmin
projects collection in the db  // This is where you will see all of the fields that need to be added on new project creation.

**Comment by drubgrubby** [comment]
### Progress:
Moving right along.  I have the form done.  Working on the validation

### Blockers:
None that I know of.

### Availability:
Yes

### ETA:
Thursday

**Comment by peteplass** [comment]
David will respond to Alex Review

**Comment by drubgrubby** [comment]
### Progress:
Waiting for PR review

### Blockers:
None

### Availability:
Yes

### ETA:
3 hours ago
