### ISSUE TITLE
Create basic manage projects page and component

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#561]
### Overview
Create a page for project managers (or other authorized individuals) to make changes to the pages that they are authorized to edit. 

### Action Items

- [x] Create ManageProjects.js with empty ManageProjects component
- [x] Create ManageProjects.scss
- [x] Link to the "Projects" link in the navbar

### Resources/Instructions
https://github.com/hackforla/VRMS/blob/development/client/src/App.js
https://github.com/hackforla/VRMS/tree/development/client/src/pages
https://github.com/hackforla/VRMS/blob/development/client/src/components/Navbar.js

**Comment by peteplass** [comment]
Please update.

**Comment by averdin2** [comment]
I made a new empty component and SCSS file to be used for managing user's projects. The current path is /projects. Below is a screenshot of the page. Once PR #556 is merged, this can be merged after and more work on this Manage Projects page can be done.

![image](https://user-images.githubusercontent.com/10714770/118724903-15236600-b7e4-11eb-8fe2-dcbbce2fe2b4.png)

**Comment by peteplass** [comment]
currently blocked by #556 

Otherwise PR is ready
