### ISSUE TITLE
Create 'select project' functionality for project management

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#563]
### Overview
Some users will be authorized to edit multiple projects.  The ManageProjects page should display links to the projects that the logged in user is authorized to edit. 

They will be able to click the link to the project that they want to edit and go to the manage project component. 

If the person logged in is 'admin' they should see all of the projects. 

### Action Items
Create a SelectProject component .  This will display the projects that a user is authorized to edit.  When the user clicks on a link it will place the selected project ID in state for use with other components. 

### Resources/Instructions
tbd

**Comment by jbubar** [comment]
I got started on this today. Should be quick. Almost done
David has been great and answering all my questions.
ETA: by thursday
Availability: all day tomorrow

**Comment by jbubar** [comment]
I am going to have a busy next few weeks. So I will remove myself from this issue. Please feel free to grab my minuscule progress from [my branch](https://github.com/jbubar/VRMS/tree/563-manage-projects)

feel free to use these commands to pull it
```bash
git checkout -b joshs-manage-projects development # or name it what ever you want to name the branch
git pull https://github.com/jbubar/VRMS.git 563-manage-projects
```

taken from this formula
```bash
git checkout -b <branch-name> <main-branch>
git pull https://github.com/<person’s GitHub username>/<repo-name>.git <branch-name>
```

**Comment by drubgrubby** [comment]
### Progress:
I am taking this over from Josh as this is technically the next issue in line. Just getting started. 

### Blockers:
None

### Availability:
Most of the week. 

### ETA:
Haven't gotten into it yet, so not sure.  Nonetheless, let's say Thursday.

**Comment by drubgrubby** [comment]
### Progress:
~This is done, I just haven't had time to create a PR.  I will do that after the meeting tonight. ~
I lied.  I did a PR. 

### Blockers:
None

### Availability:
N/A

### ETA:
Now!
