### ISSUE TITLE
Edit project fields

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#571]
### Dependencies
~#563~ 

### Overview
Create the functionality to edit all of the fields associated with the selected project. (This will not include meeting times). 

### Action Items
Display all fields related to selected project in editable text boxes
Write changed fields to the db

### Resources/Instructions
db.projects
vrms.io/projects
https://github.com/hackforla/VRMS/blob/development/client/src/pages/ManageProjects.js

**Comment by drubgrubby** [comment]
### Progress:
Have the basic structure done.  

### Blockers:
None. 

### Availability:
Good this week. 

### ETA:
Next Monday

**Comment by drubgrubby** [comment]
### Progress:
Funtionality is functioning, just needs some CSS touchups. 

### Blockers:
I hate doing CSS touchups. 

### Availability:
Enough

### ETA:
Tomorrow

**Comment by peteplass** [comment]
Alex will review PR this week.
