### ISSUE TITLE
Copy the current production database to the newly created MongoDB on AWS

### ISSUE THREAD

**Issue by alex-anakin** [hackforla/VRMS#574]
### Overview
After finishing #550 copy the current production database to the newly created MongoDB on AWS.

### Action Items
1. Make DB dump locally.
2. Upload the dump to the newly created MongoDB on AWS.

### Resources/Instructions
https://docs.mongodb.com/database-tools/mongodump/
https://docs.mongodb.com/database-tools/mongorestore/

**Comment by peteplass** [comment]
Closing because moot.
