### ISSUE TITLE
Switching DNS of vrms.io from existing prod instance to the new one.

### ISSUE THREAD

**Issue by peteplass** [hackforla/VRMS#580]
### Overview
Switching DNS of vrms.io from existing prod instance to the new one.

### Action Items

- [x]  add custom domain of VRMS.io to the AWS instance. 
- [x]  Close the Heroku account with previous VRMS production instance. 

### Resources/Instructions

https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html

**Comment by FoxShaunR** [comment]
Prod has been deployed to aws. Prod and dev heroku dynos have been shut down.
