### ISSUE TITLE
Add LocalStorage Service to loginContainer.js

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#593]
## Story
Relates to feature: 1.05 - Landing/Login Page - Text Field Memory

> As a returning user, I want VRMS to remember previous inputs in the landing page text field so I don’t have to retype my email address repeatedly.

## Dependencies
~#592~

## Instructions

- [x] Review the storage service created for #592
- [x] Add a reference to the storage service to the `components/login/loginContainer.js` file.
- [x] Choose a key to use for storing the prior input to the landing page (you get to pick this!)
- [x] Add an internal function that uses the new service to check for an existing value in local storage for the key you chose
- [x] Add a `useEffect` call on Component Mount to call the function and set the `userEmail` state variable to this.
- [x] Modify the return section to add the `userEmail` state variable to the parameters for the `LoginView` component
- [x] Add logic to the `handleSubmitForm()` method to update the value stored in localStorage, setting it to the last submitted value.  (alternatively, only set this when the user is successfully authenticated).

**Comment by peteplass** [comment]
Please update

**Comment by Aveline-art** [comment]
I am removing my assignment and moving this back into the backlog since I lack the time to commit to this project.
