### ISSUE TITLE
Meeting time changes for Civic Tech Index

### ISSUE THREAD

**Issue by connie-yu-dotcom** [hackforla/VRMS#597]
### Overview
Civic Tech Index requires some updates on our meeting times on the Hack for LA site. 

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
Civic Tech Index meeting times

Thu 6:00 pm - 8:00 pm
Team Meeting
Mon 6:00 pm - 8:00 pm
Team Meeting
Wed 12:30 pm - 2:30 pm
Product Managers Meeting

### What is your project page URL?
https://www.hackforla.org/projects/civic-tech-index

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: hack for la
Slack @handle: Connie Yu
<hr />
### Instructions
Please remove the Tuesday Dev meeting. Sunday team meeting has been changed to Monday.

**Comment by DrIffathsultana** [comment]
@connie-yu-dotcom 
- [ ] Please change the timing to PST 
- [ ] 24 hr change request

**Comment by connie-yu-dotcom** [comment]
@DrIffathsultana  updated the issue, sorry for the confusion.

**Comment by DrIffathsultana** [comment]
@connie-yu-dotcom Can you please select Project.

**Comment by connie-yu-dotcom** [comment]
@DrIffathsultana  I am not able to add or select anything for the Project

**Comment by drubgrubby** [comment]
@connie-yu-dotcom -> I have changed the meetings to reflect the above changes.  Can you please confirm that the changes are correct ( https://www.hackforla.org/events/ ) . 

Also, in case you see it here first rather than slack, can you please confirm that the developers' meeting that is currently listed on the calendar is no longer happening and should be deleted.  (Or confirm the opposite, if that is the case).

**Comment by DrIffathsultana** [comment]
@drubgrubby Hi David, Thanks for the update. 

Below is the list of Civic Tech Index project new meeting times.
- [x] Team meeting
1. Monday 6-8 pm PST
2. Thursday 6-7 pm PST
 - [x] Product manager
 Wednesday 12.30 -1.30 pm PST

- [x] Please remove Tuesday Developers meeting.

**Comment by drubgrubby** [comment]
@DrIffathsultana - I believe these are correct now. Please confirm. Thanks.

**Comment by DrIffathsultana** [comment]
@drubgrubby Yes, They are correct. Thanks
