### ISSUE TITLE
Fix Links on Events Page for CoP Meetings

### ISSUE THREAD

**Issue by aliibsin** [hackforla/VRMS#605]
### Overview
All the CoP meeting links are pointing to the wrong url. This is requested by https://github.com/hackforla/website/issues/1836

### Action Items
 - [ ] Ensure they are pointing to https://www.hackforla.org/communities-of-practice

### Resources/Instructions
Image below is an example. All CoP links should point to link above.

![image](https://user-images.githubusercontent.com/77088922/123556210-b9cb8880-d73e-11eb-8629-b237c36ba03c.png)

**Comment by drubgrubby** [comment]
@aliibsin -> Just to be clear, the field `hflaWebsiteUrl`, that is currently pointed to `hackforla.org` should be changed to the URL you listed for all of the Community of Practice meetings.  Is that correct?

**Comment by drubgrubby** [comment]
@aliibsin -> I have updated all of the community of practice meetings to point to the URL you listed above.  Can you please check them and confirm in this issue that everything is correct?  Thanks.

**Comment by aliibsin** [comment]
Looks good to me! Closing the issue.
