### ISSUE TITLE
Create Logout Page & Implement Workflow

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#609]
## Story
Relates to feature: 2.03 Main Dashboard - Logout

> As a general user I want to log out of the product so I can keep my account secure.

## Instructions

- [x] Edit the **Action Types** file: 
  - [x] Add a new string constant named `AUTH_LOGOUT`.
- [x] Edit the **Auth Actions** file: 
  - [x] Add a new action method without parameters (you can use `authStart()` as a template), named `authLogout()` and referencing the action type you created.
  - [x] Add the new method to the exports 
- [x] Edit the **Auth Reducer** file:
  - [x] Add a new case clause to handle the new action type.
  - [x] Add logic to leave state values other than those listed below unchanged (e.g. `...state`)
  - [x] Add logic to set the following state values:
  ```
  authToken: null,
  authOrigin: null,
  loggedIn: false,
  user: null,
  userProfile: null
  ```
- [x] Add a new page component named `logout.js`
   - [x] Import the `useEffect` method from React
   - [x] Import the `useDispatch` and `useSelector` methods from react-redux
   - [x] import `allActions` from the store/actions folder
   - [x] use the useEffect method run the following on mount  (refer to the first example component as a starting point)
         - call the `dispatch()` method to trigger the logout action created above.
   - [x] add a message to the page to the effect of 'you have been logged out.' (refer to second example component for a starting point)
   - [x] create a new related test file
   - [x] add a test to confirm that the page renders the message as expected (you can use the second example page's `Should render with text content` test as an example
   - [ ] OPTIONAL: add a test to confirm that the page triggers the correct redux action on mount (see documentation on Redux testing for example)
- [x] Add the new logout page component to the Routes Collection, with the path `/logout`
- [x] Edit the Menu Component
    - [x] altering the logout link to point to the new page path
    - [x] Add a new test to confirm that clicking the Logout link redirects the user to the new logout page (use the `Should redirect to dummy page if click on "Profile" menu item` test as a template)

### Files
- **Action Types**: `/store/actions/types.js`
- **Auth Actions**: `/store/actions/authActions.js`
- **Auth Reducer**: `/store/reducers/authReducer.js`
- **Example Component with store methods**: `/components/auth/handleAuth.js`
- **Example Component for layout**: `/components/dummy/dummy.js`
- **Routes Collection**: `/routes/index.js`
- **Menu Component**: `/components/menu/menu.js`

### Libraries
- [Using the Effect Hook](https://reactjs.org/docs/hooks-effect.html)
- [Writing Redux Tests](https://redux.js.org/usage/writing-tests)

**Comment by piall** [comment]
Hi @jasonwong26 ! Is this issue ready to work?. I see no label added here.
