### ISSUE TITLE
Change Meeting Time for Product Management & UI/UX Community of Practice

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/VRMS#613]
### Overview
We need to add/change the team meeting time for Community of Practice - Product Management & UI/UX so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Community of Practice: UI/UX, Wednesday 6:00 pm, 1 hour
- Community of Practice: Product Management, Wednesday 6:00 pm, 1 hour
- Community of Practice: Product Management, Friday 10:00 am, 1 hour

### What is your project page URL?
https://www.hackforla.org/communities-of-practice

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #product-management #ui-ux
Slack @handle: Olivia Chiong or Danielle Nevidi
<hr />

**Comment by drubgrubby** [comment]
@Olivia-Chiong -> Can you please confirm that these times are now correct?  https://www.hackforla.org/events/

**Comment by Olivia-Chiong** [comment]
confirmed, thank you.
