### ISSUE TITLE
Engage Meeting Time Change 

### ISSUE THREAD

**Issue by BryonPm** [hackforla/VRMS#620]
### Overview
We need to add/change the team meeting time for Engage so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
- Engage, Team, Tuesday 6:00pm, PDT, 1 hour
- Engage, Team, Sunday 4:00pm, PDT, 1 hour

### What is your project page URL?
https://www.hackforla.org/projects/engage

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #engage
Slack @handle: @bryon
<hr />

**Comment by drubgrubby** [comment]
@BryonPm -> Can you please confirm that the times are now correct?  Also, can you please confirm that the Wednesday Product Manager meeting should be deleted (which I have not yet done)?

Thanks.

**Comment by BryonPm** [comment]
@drubgrubby could you please reflect the times as pacific (local) to California?

**Comment by drubgrubby** [comment]
@BryonPm -> Times are displayed based on the local time of the person viewing the website.  Are you seeing something else?   (That coding is on the website itself; I don't have any control over that. 

<img width="466" alt="Screen Shot 2021-07-19 at 4 05 59 PM" src="https://user-images.githubusercontent.com/68244054/126238560-44324d32-1e41-4380-83ed-852c74ecf9b9.png">

Should I delete the Wednesday Project Managers' meeting, or leave it?

**Comment by BryonPm** [comment]
@drubgrubby The update looks good! Thanks for taking care of us! You can close the issue when you get time.
