### ISSUE TITLE
Restrict access to new admin dashboard for non-admin users (0.3)

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#621]
### Overview
We have implemented new login functionality to allow users who have projects assigned to them to log in.  However, if they know it's there, they can still access the admin dashboard. We would like to disallow that access. 

### Action Items

The following should happen on login. 
Case 1: Person with accesslevel 'admin' logs in.  They should initially be directed to `/admin`.  

<img width="809" alt="Screen Shot 2021-08-05 at 4 22 46 PM" src="https://user-images.githubusercontent.com/68244054/128433982-ea56f17c-fabf-4b69-96e6-eabb0077688f.png">

This person should have full access to everything. 

Case 2: Person with accesslevel 'user' who has managedprojects associated with their id should be able to log in and be directed to `/projects`

<img width="913" alt="Screen Shot 2021-08-05 at 4 29 47 PM" src="https://user-images.githubusercontent.com/68244054/128434114-6dc1ea24-3fd4-47d6-90bf-bf0983553c5e.png">

This person should ideally only have access to the `/projects` page. But, since .3 doesn't really have very robust user level authorization, they should at a minimum not have access to `/adminuser'.  

Only someone with user level 'admin' should be able to view this page: 

<img width="817" alt="Screen Shot 2021-08-05 at 4 16 57 PM" src="https://user-images.githubusercontent.com/68244054/128434327-a8cc6ce9-48f9-40d6-863e-240ce54b5ac9.png">

The functionality to allow 'user' with managed projects to log in already exists.  Completion of this issue should restrict access of someone with accesslevel 'user'.

**Comment by peteplass** [comment]
Alex will review PR this week.

**Comment by drubgrubby** [comment]
This issue is in play once again.

**Comment by WalterT-MK** [comment]
Progress: From the looks of the requirement, it should be implemented with my last ticket. 
Blockers: When logging in using user email, still give me all the admin options.
Availability: N/A
ETA: N/A

**Comment by WalterT-MK** [comment]
Progress: Have an idea on how to fix the problem
Blockers: Unable to get login email for some reason
Availability: should be able to finish by end of the week
ETA: End of the week

**Comment by WalterT-MK** [comment]
Progress: Identified the problem, actively try to figure out any workaround;
Blockers: try to come up with another way to store user access level, webpage unable read auth.user at first render causing redirection on user with admin or user access level. 
Availability: N/A
ETA: N/A
