### ISSUE TITLE
Add/edit team meeting time for Food Oasis

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#626]
### Overview
We need to add/change the team meeting time for Food Oasis so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
**Keep the following meetings**
Food Oasis, Development, Tue 6:30 pm, 1 hour
Food Oasis, All Team meeting, Thu 6:00 pm, 1 hour  (there is a problem with this, see screen shot where during the meeting - happening now- its not showing up, even though the time is appearing on the page for the project
https://www.hackforla.org/projects/food-oasis

**Remove** 
Food Oasis, Management, Mon 3:00 pm , 1 hour

### What is your project page URL?
https://www.hackforla.org/projects/food-oasis

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #fola
Slack @handle: Sameer
<hr />

**Comment by gigicobos** [comment]
![Screen Shot 2021-07-22 at 9 12 24 PM](https://user-images.githubusercontent.com/66035169/126727228-fb180d0b-c216-421e-81f7-afc101ba7958.png)

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty -> I believe that this bug has been fixed.  But until we have the live vrms site moved and can update it with the current code, the fix is useless.  Sad, but true.

**Comment by maburke09** [comment]
@drubgrubby what role should go on this type of issue? the roles we have now are: back-end, front-end, product, devops. Do we need another role or are one of these appropriate? Based on your answer, Product will add the appropriate label to the template

**Comment by drubgrubby** [comment]
@maburke09 -> This particular issue is a bit of an outlier.  It was opened as a request for making a change to the database, but it was actually a request to fix a bug.  This particular issue I would label `role: backend` - the fix changed the frequency with which code is run to make requests to the database.

However, for the other tickets that look like this - for example #672 and #681 - I would probably add a new role `role: Database`. (or something like that).  These are direct changes that I make to the database. Hopefully, when I finish the updates I'm making on v 0.3, we won't have these tickets anymore as team members will be able to log in and make their own changes.  Let me know if you have any further questions about this.
