### ISSUE TITLE
Epic: Onboarding Phase 1

### ISSUE THREAD

**Issue by mrao2** [hackforla/VRMS#630]
### Overview
REPLACE THIS TEXT - Text here that clearly states the purpose of this issue in 2 sentences or less.

### Stories

- [x] [3.01](https://github.com/hackforla/VRMS/issues/322)
- [x] #631
- [ ] 3.03
- [x] [3.04](https://github.com/hackforla/VRMS/issues/428)
- [ ] 3.05
- [ ] 3.08
- [ ] 3.10
- [ ] 3.15
- [ ] 3.16
- [ ] 4.01
- [ ] 4.02

### Resources/Instructions
REPLACE THIS TEXT - If there is a website that has documentation that helps with this issue provide the link(s) here.

**Comment by ExperimentsInHonesty** [comment]
Part of a prior dev management structure - depreciated
