### ISSUE TITLE
Make an authenticated request to the API for a logged in user

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#644]
# Epic: Integrate with AWS Cognito for Authorization
This ticket sets up the AWS Cognito resource in AWS for us to utilize with the VRMS website.

Finally we get to put it all together!  Create a test endpoint (or modify an existing endpoint) to require authentication and then access that data as an authenticated user.

# Dependencies
- #637
- #640
- #641
- #643
- #638 
- #639
- #642

# Instructions
- [x] Review the work done in the prior tickets.
- [x] Create a test API endpoint and secure it with the authorization middleware created in #642.  The endpoint should return a simple string that includes the user's email address.
- [x] Modify the test page created for #641 to make a call to the new API endpoint.  This should be done using the helper method created in #643.

**Comment by ExperimentsInHonesty** [comment]
This issue is closed by PR #762 - it is also a sub issue of #636
