### ISSUE TITLE
Update folder structure to make v0.4 the primary environment

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#645]
# v0.4 Setup Infrastructure

# Instructions
- [ ] Create a new folder named `reference` or something similar.
- [ ] Move the current `/client/` and `/backend/` folders (representing work done for v0.3) inside the new folder
- [ ] Rename the v0.4 folders to `/client/` and `/backend/` folders respectively
- [ ] Update the root `package.json` file to point the `start` script to the v0.4
- [ ] Confirm that the script runs as expected and the solution can be run.

**Comment by peteplass** [comment]
Completed this week.
