### ISSUE TITLE
Address failing tests in Backend

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#649]
# v0.4 Setup Infrastructure

This ticket prepares us to implement the PR Validation actions by ensuring we have a clean environment - with passing tests and linting rules.

# Dependencies
- #645

# Instructions
- [ ] Run the `npm run test` command on the backend folder.
- [ ] Address each failing test

# Acceptance Criteria
Running the `npm run test` command should not return any errors.

**Comment by peteplass** [comment]
closing for cleanup.
