### ISSUE TITLE
Add 100 Automation Best Practice Documents

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#655]
# Summary
Per discussion on 08/05/2021 with Bonnie, the documents outlined in the 100 Automation repository should be added to the VRMS project.

### Action Items

- [x] 1. Review the documentation here: https://github.com/100Automations/Website/blob/gh-pages/_guides/community-support-for-automations.md
- [x] 2. Add any documents listed in in the above that are missing from VRMS
- [x] 3. Update any documents in the above that exist in VRMS but do not match the standards defined.
- [x] 4. Create Code of Conduct file in VRMS using this file as a reference: https://github.com/100Automations/true-github-contributors/blob/mixin/CODE_OF_CONDUCT.md
  - [x] Find and replace text: "100 Automations" with: "VRMS" 
  - [x] Replace Code of Conduct link with: https://www.hackforla.org/code-of-conduct/

**Comment by JackHaeg** [comment]
Per @jbubar recommends discussing with @ExperimentsInHonesty to see if feature is still relevant.

**Comment by JackHaeg** [comment]
Reviewed documentation with Bonnie. Only the code of conduct file was missing from VRMS. As such, I created a code of conduct file as described in action item 4, and have linked the PR above.
