### ISSUE TITLE
100 Automation Best Practice Documents

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#656]
# Summary

Per discussion on 08/05/2021 with Bonnie, the documents outlined in the 100 Automation repository should be added to the VRMS project.  This will largely be completed with the ticket referenced below, however we need to ensure the same documents exist for v0.4 and that they reflect any differences between the environments.

# Dependencies

- #655

# Instructions

1. Review the documentation here: https://github.com/100Automations/Website/blob/gh-pages/_guides/community-support-for-automations.md
1. Review the documentation created in the v0.3 branch for the ticket referenced above.
1. Ensure that the documentation created in the v0.3 branch exists in the v0.4 branch, following the guidelines defined in step 1.
1. Modify the documentation to reflect any differences in the v0.4 branch

**Comment by JackHaeg** [comment]
Per @jbubar recommends discussing with @ExperimentsInHonesty to see if feature is still relevant.

**Comment by JackHaeg** [comment]
Closing issue as no longer relevant
