### ISSUE TITLE
Meeting time change request for GreenEarthOS

### ISSUE THREAD

**Issue by PLoiya** [hackforla/VRMS#658]
### Overview
We need to add/change the team meeting time for GreenEarthOS so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
- GreenEarthOS, Team meeting, Wednesday 7pm, 1 hour

### What is your project page URL?
[] TBD

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: GreenEarthOS-Climate 
Slack @handle: Puneet Loiya

<hr />
### Instructions

name: GreenEarthOS

description: The GreenEarthOS project seeks to create and publish a map of the current climate project support landscape including gaps. Once the landscape has been created the project will work to create visible guidance for open source projects and project ideators on how to navigate the landscape and connect with players at every appropriate stage (recruiting, mentoring, partnerships, packaging and funding); thereby reducing barriers to currently under represented communities.

 githubIdentifier: GreenEarthOS

 githubUrl: https://github.com/hackforla/GreenEarthOS

 slackUrl : https://hackforla.slack.com/archives/C01C2P7D413

googleDriveUrl : https://drive.google.com/drive/u/0/folders/1N2GN3SHSXBpO_Q6dgfOp7EzbDVUz-6HO

googleDriveId: 

 hflaWebsiteUrl : Not yet

videoConferenceLink: https://us02web.zoom.us/j/87137723460?pwd=RFIyalV2L0F2UWVWLzNlRlNaekNkQT09

**Comment by ExperimentsInHonesty** [comment]
@drubgrubby I added this issue to the prioritized backlog

**Comment by drubgrubby** [comment]
@PLoiya -> I have added GreenEarthOS to the VRMS database, and added the team meeting as you requested. 

Please confirm that the meeting time is correct. 

https://www.hackforla.org/events/

<img width="419" alt="Screen Shot 2021-08-06 at 3 41 50 PM" src="https://user-images.githubusercontent.com/68244054/128577661-5edbf56f-2a34-4cc1-98e5-96b2331bda63.png">

**Comment by PLoiya** [comment]
@drubgrubby Yes, The meeting time is correct. Thanks. I have verified the same. After reviewing with Bonnie, I will update the comments and let you know.
