### ISSUE TITLE
Work with Ops team to set up v0.3 Staging Environment

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#661]
# Summary

Hi Bonnie,

Below is a summary of where we are with the VRMS project in terms of hosting a specific ask for the Ops team:

- VRMS is a NodeJS application with React frontend that runs within Docker
- The current main branch (named `development`) contains version 0.3, which is ready for staging release
- We expect to take version 0.3 to Production in the next couple of weeks
- Version 0.3 is composed of 4 resources:
  - client - serves the React front end
  - backend - serves the NodeJS backend application
  - nginx - serves as a reverse proxy to route traffic directed to `{domain}/api` to the backend. 
     - NOTE: for development environment only, not for Production release.
   - mailhog - serves as the SMTP server for email delivery.  
     - NOTE: for development environment only, not for Production release.
- Development environment secret values are stored in this [Google Document](https://docs.google.com/document/d/1yDF6UmyO-MPNrl3y_Mw0mkm_WaixlSkXzWbudCzHXDY/edit)

Ask for the Ops team:

1. Set up a staging environment domain (production domain is: https://www.vrms.io/)
2. Set up hosting for the backend and client docker images
    1. Add environment variables as specified in Google Document
    1. Set `NODE_ENV` environment variable to: `NODE_ENV=production` to set email delivery to Gmail SMTP service
3. Route default traffic for staging domain to client instance
4. Add Routing rule to route traffic to `{domain}/api` to the backend instance.

If at all possible, it would be great for us to set up a CI/CD pipeline so that the Dev team can trigger a new build of the Staging environment - either manually or via automation.

**Comment by peteplass** [comment]
Meeting originally scheduled for 8/7. Did not take place. In the meantime, other movement in this area has been made and can be seen on #673 . Docker env has deployed and team is working out the bugs. Closing for tidiness.
