### ISSUE TITLE
Add secret values to project OnePassword

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#666]
# v0.4 Setup Infrastructure

This ticket is part of the transition to us having individual dev environments and to facilitate our CI/CD pipeline.

# Instructions
- [x] Review the secret values stored in the Google doc referenced below.
- [ ] Review best practices for storing secrets in 1 Password (how to track differing values for Production Dev environments).
- [x] Add each value in the Google doc to the VRMS Password vault.

# Reference
[.env Values Documentation](https://docs.google.com/document/d/1yDF6UmyO-MPNrl3y_Mw0mkm_WaixlSkXzWbudCzHXDY/edit)
[1Password Vault](https://hackforla-team.1password.com/vaults/qtxg3aercbhlvcapm6ifama474/allitems/o3nqmdo7bne6zkosj2rbsxpgky)

**Comment by ExperimentsInHonesty** [comment]
Added the name/value pairs to our VRMS vault in 2 separate secure notes.  And created a new empty vault called VRMS -prod
