### ISSUE TITLE
Update VRMS DNS

### ISSUE THREAD

**Issue by darpham** [hackforla/VRMS#668]
### Overview
Transffering DNS management from Google DNS to AWS Route53

### Action Items
- provide current dns records in google
- transfer google dns to aws route53
- update NS records in Google to point to AWS Route53

**Comment by darpham** [comment]
New NS records to be updated in Google DNS
```
ns-1937.awsdns-50.co.uk.
ns-620.awsdns-13.net.
ns-1177.awsdns-19.org.
ns-185.awsdns-23.com.
```

**Comment by ExperimentsInHonesty** [comment]
![screencapture-domains-google-registrar-vrms-io-dns-2021-08-12-19_38_45](https://user-images.githubusercontent.com/37763229/129298715-a1bf4ab7-837e-410d-b4cb-2a026dd97578.png)

**Comment by ExperimentsInHonesty** [comment]
Host name: www.vrms.io
Type: CNAME
TTLL: 1 hour
Data: afternoon-tortoise-tdhdm6hlcqp30pxdm5kx88cq.herokudns.com.

Host name: vrms.io
Type: A
TTLL: 1 hour
Data: 
216.239.32.21
216.239.34.21
216.239.36.21
216.239.38.21

Host name: vrms.io
Type: AAAA
TTL: 1 hour
Data:
2001:4860:4802:32::15
2001:4860:4802:34::15
2001:4860:4802:36::15
2001:4860:4802:38::15

**Comment by ExperimentsInHonesty** [comment]
DNS for VRMS 
![dns for vrms](https://user-images.githubusercontent.com/37763229/129298573-6d4e1cbf-0014-4835-8c60-d42d796fa627.PNG)

**Comment by juliagab56** [comment]
Closing for QA
