### ISSUE TITLE
Meeting time change request for 100 Automations

### ISSUE THREAD

**Issue by henlatourrette** [hackforla/VRMS#672]
### Overview
We need to add/change the team meeting time for 100 Automations so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- 100 Automations Thursday at 5 pm (changed) we changed the day and time from Wednesdays to thursdays
- 100 Automations Saturdays from 2-4 pm (stays the same)

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

### What is your project page URL?
https://www.hackforla.org/projects/100-automations

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name:  Henry Latourrette
Slack @handle: Henry Latourrette
<hr />

**Comment by drubgrubby** [comment]
@henlatourrette -> I have made the changes to the meeting time.  Please confirm that the changes are correct. 

https://www.hackforla.org/events/

**Comment by drubgrubby** [comment]
Henri confirmed via slack that the changes are correct.  Closing issue.
