### ISSUE TITLE
v0.3 Env Variables Need to Deploy Correctly

### ISSUE THREAD

**Issue by peteplass** [hackforla/VRMS#673]
### Overview
v0.3 Has been deployed but not all environment variables are reading correctly
### Action Items
The production version of the docker container is running NGINX. NGINX runs multiple threads, env variables are not making it to the appropriate thread. 

- [ ] current working theory: replace the docker image that's running NGINX with one that's running a standard REACT hosting app. 

- [ ] Alternative: continue using NGINX, Darren will be sought out for guidance in how to fix this. 

### Resources/Instructions
There is a lot of existing documentation on converting NGINX docker file to standard REACT. 
Check link [here](https://mherman.org/blog/dockerizing-a-react-app/)
Darren will provide more info on pushing through NGINX image - he says this is the optimal option.

**Comment by peteplass** [comment]
There will be a call on Wed. 8/18/21 at 6pm PT. With Darren to discuss this issue.

**Comment by peteplass** [comment]
Had a conversation with Darren one 8/19. Were not able to close the issue. 

Jason will reach out to Darren to try to get a follow up meeting to close this issue.

**Comment by jasonwong26** [comment]
This issue was resolved with the merge of PR: https://github.com/hackforla/VRMS/pull/683
