### ISSUE TITLE
Meeting time change request for Hackforla.org Website

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/VRMS#681]
### Overview
We need to add/change the team meeting time for [hackforla/website ](https://www.hackforla.org/projects/website) so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

#### Meeting times

- Hackforla.org Website, Development Team, Tuesday 7:00 pm, 1 hour
- Hackforla.org Website, PM Meeting, Wednesday 12:00 pm, 1 hour
- Hackforla.org Website, UI-UX Meeting, Thursday 5:00 pm, 1 hours
- Hackforla.org Website, Back End Meeting, Thursday 7:00 pm, 1 hour
- Hackforla.org Website, All Team Meeting, Sunday 10:00 am, 2 hours

#### Delete

For all the meeting times currently on the [Hackforla.org Website's project page](https://www.hackforla.org/projects/website), delete all of them, as none are correct. Only the five above should be listed.

### What is your project page's URL?
[hackforla/website ](https://www.hackforla.org/projects/website)

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: Ava Li
Slack @handle: @avali
<hr />
### Instructions

Please update the meeting times for the website project as the above. 

#### Resources
[hackforla/website ](https://www.hackforla.org/projects/website)

**Comment by drubgrubby** [comment]
@Aveline-art -> I have made the changes you requested to the meeting times.  Please confirm that they are correct: 

<img width="294" alt="Screen Shot 2021-08-25 at 2 46 33 PM" src="https://user-images.githubusercontent.com/68244054/130869077-052b6968-f3a8-4c41-8833-baaa0c39bfbe.png">

**Comment by drubgrubby** [comment]
Ava confirmed via slack that these times are correct.  Closing ticket.
