### ISSUE TITLE
Fix URL for Expunge Assist on Hfla Events Page

### ISSUE THREAD

**Issue by sheltoG** [hackforla/VRMS#684]
### Overview
We need to fix the URL under the Expunge Assist event for Monday's from 6-7 PM. Currently the URL link resolves to a 404 error. The correct URL it should point to is: https://www.hackforla.org/projects/expunge-assist

### Action Items
[ ] Replace current href URL (https://www.hackforla.org/projects/record-clearance-project) with the following URL: https://www.hackforla.org/projects/expunge-assist
[ ] Test to make sure it is working correctly

### Resources/Instructions
[Hack for LA Events Page](https://www.hackforla.org/events/)
Parent Issue: https://github.com/hackforla/website/issues/950

**Comment by adam-abundis** [comment]
@sheltoG @ExperimentsInHonesty This information is being pulled from a VRMS API (https://www.vrms.io/api/recurringevents). The front-end javascript just fetches this data and dumps it into the page. How do we request updates for VRMS data?

**Comment by drubgrubby** [comment]
@sheltoG -> I have changed the website URL as requested.  Please confirm that the change is correct.  Thanks.
