### ISSUE TITLE
Remove URL for Community of Practice: Software Developers/Front-end Weekly meeting link on Hfla Events Page

### ISSUE THREAD

**Issue by sheltoG** [hackforla/VRMS#685]
### Overview
We need to remove the Name, Time and URL under the Community of Practice: Software Developers/Front-end Weekly meeting event for Monday's from 8-9 PM. This meeting time is not valid since the CofP meeting for engineering is on Wednesdays.

### Action Items
[ ] Remove the Name, Time and URL under the Community of Practice: Software Developers/Front-end Weekly meeting event for Monday's from 8-9 PM
[ ] Test to make sure it is removed in prod

### Resources/Instructions
Parent Issue: https://github.com/hackforla/website/issues/950

**Comment by adam-abundis** [comment]
@sheltoG @ExperimentsInHonesty This information is being pulled from a VRMS API (https://www.vrms.io/api/recurringevents). The front-end javascript just fetches this data and dumps it into the page. How do we request updates for VRMS data?

**Comment by drubgrubby** [comment]
@sheltoG -> I have removed this meeting as requested.  Please confirm that it has been removed correctly.  Thanks.

**Comment by sheltoG** [comment]
Thanks @drubgrubby it has been removed correctly.
