### ISSUE TITLE
Add global location filter: Date Range

### ISSUE THREAD

**Issue by kelseylc** [hackforla/VRMS#69]
As an admin user, I want to be able to update all charts on the dashboard page to filter for a certain date range at once.

Task:

- [ ] Add a global location filter to the dashboard page
- [ ] This global location filter should be a dropdown of preset date ranges:

Date Range
*** Last 7 Days
*** Last 30 Days
*** Last 90 Days
*** Last 6 months
*** Last 12 months
*** All Time

- [ ] Ensure that all dashboard components (data tables, data points & charts) react to the filter

Date range filter will filter the user's view of the data by calculating from CURRENT day's date (-7 days), (-30 days), and so on.

**Comment by sarL3y** [comment]
This will require a refactor of the data flow in the dashboard, so I'm removing it from pre Summit.

**Comment by OlgaBilogurova** [comment]
This task is blocked by #213

**Comment by alex-anakin** [comment]
Obsolete
