### ISSUE TITLE
Create new user - needs to redirect on success

### ISSUE THREAD

**Issue by maburke09** [hackforla/VRMS#693]
### Overview
As a new user when I signup for VRMS I need to receive a response so that I (and my browser) know my signup has been completed

### Action Items

- [x] Review user input chain to determine why no response is given.
- [x] Fix it. 

(Functional on live site, not working on dev)

### Resources/Instructions
[Dev site](https://dev.vrms.io)
[Live site](https://vrms.io)

**Comment by glenflorendo** [comment]
> * [ ]  Review user input chain to determine why no response is given.

There's an error in handling the form submission when a new user signs up.

```js
TypeError: responseId.includes is not a function at CheckInForm.js:161
```

I'll fix this soon.
