### ISSUE TITLE
Login: browser does not remember email

### ISSUE THREAD

**Issue by maburke09** [hackforla/VRMS#694]
### Overview
As a returning user, when I login, I want the email I used previously to be remembered in the browser.

### Action Items

- [ ] Once #693 has been completed, check to see if the issue has been resolved. 
- [ ] If not, determine why the previously used email is not being remembered in the browser, or if it is remembered in some cases and not others.

**Comment by jbubar** [comment]
Are we talking about Autocomplete?
https://www.w3schools.com/jsref/prop_email_autocomplete.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by chukalicious** [comment]
changed the autocomplete attribute in the returningUserForm.js from 'off' to 'on' and below is a capture of the result:

![image](https://user-images.githubusercontent.com/19879362/142752497-f4e0c6cc-4b92-44eb-ac13-9fd61c090ee3.png)

**Comment by chukalicious** [comment]
Hi team! As discussed during today's meeting, the recommendation is to merge this PR and open another that address the issue specifically with the Safari browser. @drubgrubby if, you'd do the honors 😁
