### ISSUE TITLE
Meeting check-in: no user response

### ISSUE THREAD

**Issue by maburke09** [hackforla/VRMS#696]
### Overview
As a new or returning user, when I check into a meeting, I need to receive a response that it has been successful or not

### Action Items

- [x] Once #693 has been completed, check to see if the issue has been resolved. 
- [x] If not, determine why the previously used email is not being remembered in the browser, or if it is remembered in some cases and not others.

**Comment by drubgrubby** [comment]
This issue was resolved by one of the recently completed issues.  Closing.  Go Team Go!
