### ISSUE TITLE
Navigation: home link sends user to login screen (without logging them out)

### ISSUE THREAD

**Issue by maburke09** [hackforla/VRMS#697]
### Overview
We need to identify what behavior is desired when clicking the home button for a more rational user experience

### Detail
Right now, when you are logged in and you click the home navigation item inside the application you are taken back to the outside of the app where you normally would login into a meeting. What do we want this to do?

### Action Items
1. Look at Figma to see what screen is supposed to be there
2. Ask Adam what is supposed to happen

### Resources/Instructions
[Figma link](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23726%3A2254)

**Comment by drubgrubby** [comment]
@jbubar 's work on PR #774 will also fix this, a double-play, if you will.

**Comment by drubgrubby** [comment]
This was closed by PR #774
