### ISSUE TITLE
Add Github API Integrations

### ISSUE THREAD

**Issue by disregardfiat** [hackforla/VRMS#70]
### Overview
Adding GitHub API Allows the VRMS system to perform any action accessible via github.com. This will allow the system to see if a person is registered on github with the same address they used to sign up(if public on profile). Add that user to HackForLA. Future Development will include additional actions such as  assignment to projects/teams, admin roles... and dynamically generating welcome emails that contain instructions on how to set up 2FA, or how to get a github account as appropriate. 

### Action Items
Build reusable promise based functions for interaction with githubs API. This includes additional environment variables for the admin token.

### Resources/Instructions
[Github API Docs](https://developer.github.com/v3/)

**Comment by disregardfiat** [comment]
A token with the following rights from an Admin of the HackForLA Org on Github needs to generate a Dev Token with the following permissions:
* admin:org - Full control of orgs and teams, read and write org projects 
* read:user - Read all user profile data 
* user:email - Access user email addresses (read-only)

Additional Repo rights may be needed in the future

**Comment by alex-anakin** [comment]
@alex-anakin check the project codebase out for any mentions of implementetion

**Comment by alex-anakin** [comment]
Obsolete
