### ISSUE TITLE
Board Cleanup

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#760]
### Overview
We need to clean up the project boards so that we can manage the project effectively

### Action Items
- [x] Meet with team and address the following areas
- [x] Issues not assigned to project boards
- [x] Issues missing Roles
- [x] Issues missing Size
- [x] Issues missing Feature
- [x] Issues missing milestones

### Resources/Instructions
- [Issues missing Size](https://github.com/hackforla/VRMS/issues?q=is%3Aopen+is%3Aissue+label%3A%22size%3A+missing%22)
- [Issues missing Feature](https://github.com/hackforla/VRMS/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+missing%22)
- [Issues missing Milestone](https://github.com/hackforla/VRMS/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone)
- [Issues missing Roles](https://github.com/hackforla/VRMS/issues?q=is%3Aopen+is%3Aissue+label%3A%22role%3A+Missing%22)
- [Issues not assigned to project boards](https://github.com/hackforla/VRMS/issues?q=is%3Aissue+is%3Aopen+no%3Aproject+)

- See Weekly label check for progress: https://github.com/hackforla/VRMS/issues/1168

**Comment by juliagab56** [comment]
Looks like we can resuse this for Monday (6/26) and as we continue working on cleaning the board once more
