### ISSUE TITLE
Event model changes discussion

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#761]
### Overview
We need to update the event model to contain more data so that it can accommodate people filtering events

### Action Items
- [ ] See hackforla/civictechjobs#13 for details on the models that CTJ requires (see [here](https://github.com/hackforla/CivicTechJobs/issues/13#issuecomment-886323790))
- [ ] Implement the models within VRMS
- [ ] Release dependency on hackforla/civictechjobs#40

### Resources/Instructions
[VRMS Event Model](https://github.com/hackforla/VRMS/blob/development/backend/models/event.model.js)
[VRMS Recurring Event Model](https://github.com/hackforla/VRMS/blob/development/backend/models/recurringEvent.model.js)
[engineering open roles](https://github.com/hackforla/engineering/projects/2)

#### Places that are currently using the Event model data via VRMS api
https://www.hackforla.org/project-meetings
https://www.hackforla.org/events/
project pages (e.g. https://www.hackforla.org/projects/100-automations)

#### Places that we intend to use the api
Civic tech jobs site [Figma mockup]
Issue from Civic Tech Jobs with data model requirements https://github.com/hackforla/CivicTechJobs/issues/13#issuecomment-886323790

**Comment by ExperimentsInHonesty** [comment]
the following images display meeting time check boxes and the roles checkboxes which will both be necessary inputs for users to find project open roles with meeting times that they can make.  

Although its worth noting that it says 3 but under meeting time but it only shows one meeting time above.

![Meeting Times image](https://user-images.githubusercontent.com/37763229/133940768-83e0aaa8-12c5-4b28-b455-1a411e07790d.png)

![image](https://user-images.githubusercontent.com/37763229/133910865-1cf2f9b0-c41d-406d-9238-eebef3222787.png)

**Comment by ExperimentsInHonesty** [comment]
Current meeting details for hackforla.org team
Date, Start Time, Duration, Name of Meeting
Sun, 10:00 am, 2 hr, All Team Meeting
Tue, 12:00 pm, 1 hr, UI/UX Lead & PM meeting (not currently on the calendar)
Tue, 7:00 pm, 1 hr, Development Team
Wed, 12:00 pm, 1 hr, PM Meeting
Thu 5:00 pm, 1 hr, UI-UX Meeting
Thu 7:00 pm, 1 hr, Back-end Meeting

**Comment by ExperimentsInHonesty** [comment]
Current meeting details for hackforla.org team, annotated with who should attend
- [ ] Date, Start Time, Duration, Name of Meeting, Must Attend, Should, Can Attend
- [ ] Sun, 10:00 am, 2 hr, All Team Meeting, [PM & All Leads], All, All 
- [ ] Tue, 12:00 pm, 1 hr, UI/UX Lead & PM meeting, [Research Lead, Design Lead, PMs], , 
- [ ] Tue, 7:00 pm, 1 hr, Development Team, [Font End Lead, Back End Lead], [Back end developers, Front end developer], All
- [ ] Wed, 12:00 pm, 1 hr, PM Meeting, PMs, , 
- [ ] Thu 5:00 pm, 1 hr, UI-UX Meeting, [Research Lead. Design Lead], [Researchers, Designers], ???
- [ ] Thu 7:00 pm, 1 hr, Back-end Meeting. Back End Lead, [Back End Developers, Front End Leads], All

**Comment by ExperimentsInHonesty** [comment]
Current meeting details epungeassist (who Must, Should and Can attend are assumptions to be validated)
- [ ] Date, Start Time, Duration, Name of Meeting, Must Attend, Should, Can Attend
- [ ] Mon, 6:00 pm, 1 hr, Team meeting on 1st & 3rd Mondays, [PM & All Leads], All, All 
- [ ] Mon, 6:00 pm, 1 hr, PM meeting on alternate Mondays, PM, PM, , 
- [ ] Tue 6:00 pm, 1 hr, Research & Design meeting, [Research Lead. Design Lead], [Researchers, Designers], ???
- [ ] Thu, 6:00 pm, 1 hr, Development Team, [Font End Lead, Back End Lead], [Back end developers, Front end developer], All

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty

Quick question on the meeting time check boxes: 
https://github.com/hackforla/VRMS/issues/761#issuecomment-922387185

Are these choices going to be displayed in the user's local time?  If yes, do we need to account for people who live abroad but are willing to attend meetings that, for them, are in the middle of the night?  We've had a number of people who have attended meetings that are outside of those distinctions of morning, afternoon, and evening in their local time.

**Comment by drubgrubby** [comment]
This issue was created before People Depot was born.  As the database and api functionality is now in the hands of people depot, I am closing this ticket.
