### ISSUE TITLE
Meeting time change request for [Access the Data]

### ISSUE THREAD

**Issue by lrchang2** [hackforla/VRMS#764]
### Overview
We need to add/change the team meeting time for [Access the Data] so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
- Access the Data, Workshop Working Meeting, Monday 5pm, 1 hour
- Access the Data, PM Meeting, Tuesday 2pm, 1 hour
- Access the Data, UX/UI Meeting, Tuesday 5pm, 1 hour
- Access the Data, Team Meeting, Wednesday 5pm, 1 hour
- Access the Data, Website Working Meeting, Thursday 4pm, 1 hour

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

### What is your project page URL?
https://www.hackforla.org/projects/access-the-data

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #access-the-data
Slack @handle: @Lucy Chang
<hr />

**Comment by drubgrubby** [comment]
@lrchang2 -> I have made the changes and added these meetings to the calendar.  Please confirm that they are correct (assuming they are).  

https://www.hackforla.org/events/

**Comment by lrchang2** [comment]
@drubgrubby I made a time zone error, the meeting on Tuesday for "Access the Data, PM Meeting" should be 2pm PST, not 4pm. thanks!

**Comment by drubgrubby** [comment]
@lrchang2 -> I made the change.  Please confirm.

**Comment by lrchang2** [comment]
@drubgrubby yes, perfect everything looks to be in order! thanks!
