### ISSUE TITLE
Document VRMS team meeting times and who Must/Should/Can attend

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#768]
### Overview 
The Civic Tech Jobs team needs accurate meeting time information from the VRMS team to help match your project with available volunteers.

### Action Items
- [ ] provide details about the each meeting in a comment by using a copy of the check boxes below
- [ ] post a link to this issue on https://github.com/hackforla/CivicTechJobs/issues/35 in a comment letting the civic tech jobs team know you are done.
```
  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
```
### Resources
- URL of the project's homepage on the HfLA website:  https://www.hackforla.org/projects/vrms
- Times that VRMS shows for your meetings: 
Mon 7:00 pm, 2 hour
Thu 6:30 pm , 1 hour, Developers' Meeting

**Comment by drubgrubby** [comment]
Full Team Meeting
Mondays, 7pm Pacific
2 hours  

- [x] day: Monday
   - [x] start_time: 7 pm pacific
      - [ ] AM
      - [x] PM
   - [x] duration_in_min: 120
   - [x] name_of_meeting: VRMS Team Meeting
   - [x] who_must_attend
      - [x] pm
      - [x] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [x] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [x] design
      - [x] research
      - [x] frontend
      - [x] backend
      - [x] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by drubgrubby** [comment]
VRMS Tech Meeting
Thursday, 6:30pm Pacific
1 Hour 

 - [x] day: Thursday
   - [x] start_time: 6:30
      - [ ] AM
      - [x] PM
   - [x] duration_in_min: 60
   - [x] name_of_meeting: VRMS Tech meeting
   - [x] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [x] frontend_lead
      - [x] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [x] frontend
      - [x] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_can_attend
      - [x] pm
      - [ ] all_leads
      - [x] design_lead
      - [x] research_lead
      - [ ] frontend lead
      - [x] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [x] other: Anyone with a technical (feasibility, API, etc) question for the developers.
