### ISSUE TITLE
Upload video of Bonnie and Jason talking about Cognito integration

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#771]
### Overview
Upload video of Bonnie and Jason talking about Cognito integration

### Action Items

- [x] Upload video of Bonnie and Jason talking about Cognito integration
- [x] Tell @drubgrubby and other team members where it's been uploaded to. 

### Resources/Instructions
Video of Bonnie and Jason talking about Cognito integration.
[Folder with recordings and transcript](https://drive.google.com/drive/folders/143wFtbhzXtXhICZYUBkdiDi_HKxtVGEi)

**Comment by jbubar** [comment]
https://drive.google.com/drive/folders/11EXZDResUVRMXosUIXpXnu3SrV3f0Z7b?usp=sharing
