### ISSUE TITLE
Meeting time change request for Access the Data

### ISSUE THREAD

**Issue by lrchang2** [hackforla/VRMS#776]
### Overview
We need to add/change the team meeting time for Access the Data so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Access the Data, Data Science Workshop Meeting, Monday 5:00pm, 1 hour
- Access the Data, PM meeting, Tuesday 2:00pm, 1 hour
- Access the Data, Team Meeting, Wednesday 5:00pm, 1 hour
- Access the Data, UX/UI Website Meeting, Thursday 4:00pm, 1 hour

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

### What is your project page URL?
https://www.hackforla.org/projects/access-the-data

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #access-the-data
Slack @handle: lrchang2
<hr />

**Comment by drubgrubby** [comment]
@lrchang2 -> I have made the requested changes to the meeting times.  Can you please confirm that they are now correct?  Thanks.

https://www.hackforla.org/events/

**Comment by lrchang2** [comment]
@drubgrubby yes, everything looks correct, thank you
