### ISSUE TITLE
New Dashboard Chart: Avg. Hours per Volunteer

### ISSUE THREAD

**Issue by kelseylc** [hackforla/VRMS#78]
As an admin user, I want the dashboard to show key metrics in a chart visualization, so that I can easily see the Average volunteer hours per volunteer across brigades, and per each location if using the global location filter.

**Link to Wireframes:**
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=22881%3A2738

**Action Items:**
- [ ] Build a BAR chart called "Avg. Hours per Volunteer" that shows the AVERAGE (n) of total volunteer hours across brigades as a numerical value to the right of the chart title. Show to the 100th decimal.
--- Chart Title: **Avg. Hours per Volunteer**
--- n = (SUM of volunteer hours) / (COUNT of unique volunteers)
--- Include a legend below the donut chart with the average by location for each hacknight location.

- [x] This chart should display a color split across the 3 Hack for LA brigades. Use the color scheme determined from #76 & #77 

- [x]  This chart needs to react to the 2 global data filters (Location & Date Range picker)

**Acceptance Criteria:**
As a user I should now see a bar chart beneath the global location filters like so: 
![image](https://user-images.githubusercontent.com/17465075/75739488-d75b2000-5cb9-11ea-8777-0a35fca2f357.png)

**Comment by sarL3y** [comment]
Current implementation is using a donut chart. Will refactor to bar chart post-Summit.

**Comment by kelseylc** [comment]
I see that this was deployed as a Donut chart in production. A donut chart doesn't make sense for an Average stat, since an average is not part of a whole. A bar chart would make more sense for something like tracking Avg. Hours per location. This can wait until after Summit, but it should get fixed.
