### ISSUE TITLE
Add/edit team meeting time for Product Management Community of Practice

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/VRMS#781]
### Overview
We need to add/change the team meeting time for [Product Management, Community of Practice] so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [ x] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
- Product Management, Community of Practice, Wednesday 6 pm, 1 hour
- Product Management Community of Practice, Team meeting, Friday 10 am, 1 hour

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: #product-management
Slack @handle: priyankatalwar
<hr />

**Comment by drubgrubby** [comment]
The times are correct per Priyanka
