### ISSUE TITLE
Meeting time change request for UX Research Meeting

### ISSUE THREAD

**Issue by sacamp** [hackforla/VRMS#789]
### Overview
We need to add/change the team meeting time for the HackforLA website UX research team  so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [x] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
EXAMPLE: 
- Hack for LA Website UX Research Wednesday 2:00pm, 1 hour

Note: Please explicitly state if a meeting time that is currently displayed is to be deleted.

### What is your project page URL?
https://www.hackforla.org/projects/vrms

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #hfla-site-ux
Slack @ Simone Campbell:
<hr />

**Comment by drubgrubby** [comment]
@sacamp -> I've made the change as you requested.  Please confirm that the change is correct. 

https://www.hackforla.org/events/

**Comment by sacamp** [comment]
The changes are correct.
