### ISSUE TITLE
New Dashboard Chart: Most hours volunteered Leaderboard

### ISSUE THREAD

**Issue by kelseylc** [hackforla/VRMS#79]
As an admin user, I want the dashboard to show key metrics, one of which is a Volunteer Leaderboard. This is a list of the Top Volunteers sorted DESC by Sum of Volunteer Hours. I'll want to see the Top Volunteers across all locations, and per each location (when using the global location filter).

**Link to Wireframes:**
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=22881%3A2738

**Action Items:**
- [ ] Build a table called "**Volunteer Leaderboard**" that shows a distinct (deduplicated) list of HackforLA Volunteers sorted in **descending** order by Volunteer Hours. 

This table should contain the following 3 columns:
--- **Name** | Display Name = (users.name__firstName) + (users.name__lastName)
--- **Events** | Events = COUNT(eventId) by user
--- **Hours** | Hours = SUM(events.hours) by user

- [ ] LIMIT the default view of this table to the top 5 in the list (by SUM of volunteer hours)

- [ ] Include a button, right-align in the table header, that says **View All**. Clicking this button should display all rows of the Volunteer list in the table.
_** Note: this step can be CUT if needed for timing._

- [ ]  This chart needs to react to the 2 global data filters (Location & Date Range picker)

**Acceptance Criteria:**
As a user I should now see the **Volunteer Leaderboard** table beneath the "Avg. Hours per Volunteer" chart, like so:
![image](https://user-images.githubusercontent.com/17465075/75741952-06c15b00-5cc1-11ea-977f-89d12e8b8961.png)

**Comment by kelseylc** [comment]
Note: In the future we should consider a "View More" paginated view instead of the "View All" button, that would shows 10-20 more at a time, to prevent a massive list appearing in in the mobile dashboard. This would improve the user experience on mobile, but will require some more UX considerations, so we can discuss further later.

**Comment by ExperimentsInHonesty** [comment]
@sarL3y says update is
1. Progress - paused for project roadmp
2. Blocks - hello!  covid19!
3. Availability - this week is better
4. ETA - paused

**Comment by ExperimentsInHonesty** [comment]
Matt's tentative 
- estimate of hours: 4 hours
- complexity points: 2
@shiningjustice  - matt will talk to you about this.

**Comment by alex-anakin** [comment]
Obsolete
