### ISSUE TITLE
Meeting time change request for TDM Calculator

### ISSUE THREAD

**Issue by KPHowley** [hackforla/VRMS#792]
### Overview
We need to add/change the team meeting time for TDM Calculator so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [ ] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

- TDM Calculator, Weekly Team Check In, Wednesday 7:00-8:00pm, 1 hour
- TDM Calculator, Management Meeting, Saturday  10:00-11:00AM , 1 hour

*This is an update to existing meetings

### What is your project page URL?
https://www.hackforla.org/projects/tdm-calculator

**Comment by drubgrubby** [comment]
@KPHowley - I have made the changes you requested to the meetings.  Can you please confirm that they are correct? 

https://www.hackforla.org/events/

**Comment by drubgrubby** [comment]
Hearing no objections I pronounce this issue closed.
