### ISSUE TITLE
API Requirements for VRMS

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#798]
### Overview
VRMS will transition from using a database to using the PeopleDepot api. We need to have documentation on how and where the application interacts with the db in both v 0.3 and v 0.4

### Action Items
- [x] List all api calls that are used currently in the app
- [x] look through v0.4 and create a list of probable api calls

### Resources/Instructions
- use RESTFUL api structure
- [article on restful api's](https://www.redhat.com/en/topics/api/what-is-a-rest-api)
- [v0.4 google doc](https://docs.google.com/document/d/16VvC0fbaXsvEQkQaVSj8dG3wFEHgErbjJ6H3akSUoVM/edit#heading=h.1wzlazx41h42)

**Comment by jbubar** [comment]
Started working on this in the meeting

//app.js
app.use('/api/auth', authRouter);
* POST /signup
* POST /login
* POST /verify-signin
* POST /me
* POST /logout

app.use("/api/events", eventsRouter);
* GET /api/events
* GET /api/events/:eventId
* POST /api/events
* PATCH /api/events/:eventId
* DELETE /api/events/:eventId

	Possibly deletable routes
* GET api/events/nexteventbyproject/:id

app.use('/api/checkins', checkInsRouter);
app.use("/api/users", usersRouter);
app.use("/api/questions", questionsRouter);
app.use("/api/checkuser", checkUserRouter);
app.use("/api/grantpermission", grantPermissionRouter);
app.use("/api/projects", projectsRouter);
app.use("/api/recurringevents", recurringEventsRouter);
app.use("/api/projectteammembers", projectTeamMembersRouter);
app.use('/api/slack', slackRouter);
app.use('/api/healthcheck', healthCheckRouter);

**Comment by drubgrubby** [comment]
First draft of basic API calls for vrms more or less based on existing functionality

**Users**
GET - Get all users - /api/users/
GET - Get one user by _id - /api/users/:user_id
GET - Get one user by email - /api/users/:user_email
POST - Create new user - /api/users
PATCH - Update one user by _id - /api/users/:user_id
DELETE - Delete one user by _id - /api/users/:user_id

**Recurring Events**
GET - Get all recurring events - /api/recurringevents
GET - Get one recurring event by id - /api/recurringevents/:recurringevent_id
POST - Create new recurring event - /api/recurringevents
PATCH - Update one recurring event by id- /api/recurringevents/:recurringevent_id
DELETE - Delete recurring event by id - /api/recurringevents/:recurringevent_id

**Events**
GET - Get all events - /api/events
GET - Get one event by id - /api/events/:event_id
POST - Create new event - /api/events
PATCH - Update one user by id - /api/events/
DELETE - Delete one event by id - /api/events/:event_id

**Checkins**
GET - Get all checkins - /api/checkins
GET - Get all checkins by event - /api/checkins/:event_id
GET - Get all checkins by project_id - /api/checkins/:project_id (needs a join)
GET - Get all checking by user_id - /api/checkins/:user_id
GET - Get one checkin by id - /api/checkins/:checkin_id
POST - Create new checkin - /api/checkins

**Projects**
GET - Get all projects - /api/projects
GET - Get one project by id - /api/projects/:project_id
POST - Create new project - /api/projects
PATCH - Update one project by id - /api/projects
DELETE - Delete one project by id - /api/projects/:project_id

**Questions**
GET - Get all questions - /api/questions
GET - One question by id - /api/questions/:question_id
POST -  Create a question - /api/questions
PATCH - Update a question by id- /api/questions/:question_id
DELETE - Delete a question by id - /api/question/:question_id

**Comment by drubgrubby** [comment]
This was posted to a new issue at people depot: 
https://github.com/hackforla/peopledepot/issues/10
