### ISSUE TITLE
Build flowchart of work flow

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#8]
### Overview
Create VRMS check-in user flow with cookie detection in a flowchart.

### Action Items
* [x] Convert hand drawn images in comments to Whimsical flowchart.
* [x] Get sign-off on flowchart accuracy
* [x] Create deck-ready version of flow chart with screenshots

### Resources/Instruction
See comments for flows

**Comment by sarL3y** [comment]
**Current below (need updating)**

[VRMS.User.Flow.Admin.v2.pdf](https://github.com/hackforla/VRMS/files/3942906/VRMS.User.Flow.Admin.v2.pdf)
[VRMS.User.Flow.Attendee.v2.pdf](https://github.com/hackforla/VRMS/files/3942907/VRMS.User.Flow.Attendee.v2.pdf)

**Comment by ExperimentsInHonesty** [comment]
![volunteer_use_cases](https://user-images.githubusercontent.com/37763229/72212784-c818dc80-3497-11ea-9713-860c596898cc.png)
![volunteer_use_case_1_flow](https://user-images.githubusercontent.com/37763229/72212786-d1a24480-3497-11ea-8c66-bba173531daf.png)
![volunteer_use_case_2_flow](https://user-images.githubusercontent.com/37763229/72212787-d49d3500-3497-11ea-9175-04a7056c9cb8.png)
![volunteer_use_case_3_flow](https://user-images.githubusercontent.com/37763229/72212788-d666f880-3497-11ea-8f0b-ef7cff01a9aa.png)

![volunteer_use_case_1-3_flow](https://user-images.githubusercontent.com/37763229/72212817-e7fcd000-3498-11ea-8bf4-64d12caa0111.png)

**Comment by kelseylc** [comment]
@ExperimentsInHonesty please review if this flow looks correct. If so, I'll add some screenshots of the steps to make it look nicer and then include it in the deck.
![VRMS Flowchart](https://user-images.githubusercontent.com/17465075/75749585-f916d000-5cd6-11ea-9f11-d76612cae2cf.png)
