### ISSUE TITLE
Admin Events Page: Past Events

### ISSUE THREAD

**Issue by kelseylc** [hackforla/VRMS#80]
As an admin user, I want to be able to look up past HackforLA events in the VRMS admin dashboard.

This view should live in the "Events" tab, in the header menu of the dashboard (rather than the "Home" tab).

**Link to Wireframes:**
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=22881%3A2738
--- See screen titled "Events-Past Events"

**Action Items:**
- [ ] In the global location filter section, replace the "HackforLA Overview" header text with 2 clickable tabs:
* Past Events [**default view**]
* Upcoming Events
![image](https://user-images.githubusercontent.com/17465075/75742653-2194cf00-5cc3-11ea-96eb-701df930aca9.png)

- [ ] In the "**Past Events**" view, show a list of HackforLA events as a series of tiles with the following repeatable components for every event tile:
* **Event Name** (events.name)
--- e.g. HackforLA Westside
* **Event Date** (events.date) -- format should be [Day of week, Month Day Year] 
--- e.g. Monday, Feb. 4 2020
* **Location** (events.location__city)
--- e.g. Santa Monica
* "**View Details**" button (right-align & vertically centered in the tile). This button will click through to an "Event Details" view (requirements here: #82 )

- [ ]  This list needs to react to the 2 global data filters (Location & Date Range picker)

**Acceptance Criteria:**
As a user, when I click on the "Events" header menu tab, I should now see two new tabs in the global location filter section, called **Past Events** and **Upcoming Events**.

The "Events" view should default to "Past Events", which shows me a list of past HackforLA events like so:
![image](https://user-images.githubusercontent.com/17465075/75743253-370af880-5cc5-11ea-92a6-27b73890209a.png)

If I use the Location global filter, I should now only see a list of past events for that Hacknight location. If i use the Date Range filter, I should now only see past events within the date range selected.

**Comment by juliagab56** [comment]
Outdated issue
