### ISSUE TITLE
Admin Events Page: Upcoming Events

### ISSUE THREAD

**Issue by kelseylc** [hackforla/VRMS#81]
As an admin user, I want to be able to look up **upcoming** HackforLA events in the VRMS admin dashboard.

This view should live in the "Events" tab, in the header menu of the dashboard.

**Link to Wireframes:**
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=22881%3A2738
--- See screen titled "Events-Upcoming Events"

**Dependency**
* This ticket assumes that the "Upcoming Events" tab was already added in ticket #80, like so:
![image](https://user-images.githubusercontent.com/17465075/75743469-f364be80-5cc5-11ea-93ed-063fd5b979d0.png)

**Action Items:**
- [ ] When user is in the "Upcoming Events" view, change the global filter "Date Range" drop down options to:
*** **Next** 7 Days
*** **Next** 30 Days [**default**]
*** **Next** 90 Days
*** **Next** 6 months
*** **Next** 12 months
*** All Time

- [ ] In the "**Upcoming Events**" view, show a list of HackforLA events as a series of tiles with the following repeatable components for every event tile:

* **Event Name** (events.name)
--- e.g. HackforLA Westside
* **Event Date** (events.date) -- format should be [Day of week, Month Day Year] 
--- e.g. Monday, Feb. 4 2020
* **Location** (events.location__city)
--- e.g. Santa Monica
* "**View Details**" button (right-align & vertically centered in the tile). This button will click through to an "Event Details" view (requirements here: #83)

- [ ]  This list needs to react to the 2 global data filters (Location & Date Range picker)

**Acceptance Criteria:**
As a user, when I click on the "Events" header menu tab, I should now see two new tabs in the global location filter section, called **Past Events** and **Upcoming Events**.

When I click on the "Upcoming Events" link, I should see a list of any upcoming events created by admins in the next 30 days (default view), like so:
![image](https://user-images.githubusercontent.com/17465075/75743929-936f1780-5cc7-11ea-99cf-4e98d20642f1.png)

If I use the Location global filter, I should now only see a list of past events for that Hacknight location. If i use the Date Range filter, I should now only see upcoming events within the date range selected.

**Comment by juliagab56** [comment]
Outdated issue
