### ISSUE TITLE
Past Events: Event Details page

### ISSUE THREAD

**Issue by kelseylc** [hackforla/VRMS#82]
As a user, when I click on the "View Details" button for either a Past Event or Upcoming event, I want to see the details of that event. 

For a **Past Event**, I want to see an overview of that event's details & attendance.

#### Link to Wireframes:
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=22881%3A2738
--- See screen titled "Events-Past Events-Details"

## Action Items

- [ ] On the Event Details page for a Past Event, show the following information:
* **Event Name** = events.name
* **Event Date & Time** = events.date @  [hardcoded Start & End time]
  * e.g. Monday, Mar. 2 2020 @ 6PM - 9PM
* **City, State** = events.location__city, events.location__state
* **Status: [Open/Closed]**
  * Open = (events.checkInReady = TRUE)
  * Closed = (events.checkInReady = FALSE)
* **Total Volunteers: (n)** WHERE n = COUNT(checkins.userid) for selected event

- [ ] Underneath the "Total Volunteers" header, add a donut chart (with legend) showing a breakdown of that event's volunteers by New vs. Returning.
* New vs Returning value can be found here: 
  * **New:** users.newMember = TRUE
  * **Returning:** users.newMember = FALSE
* The legend should display the COUNT of New volunteers vs. Returning volunteers at that event

## Acceptance Criteria

As an admin user, when I click on the Events tab, then on "View Details" for a Past Event, I should now see an Event Details page like so:
![image](https://user-images.githubusercontent.com/17465075/75746834-46dc0a00-5cd0-11ea-8c64-e81966a31d72.png)

**Comment by kelseylc** [comment]
**CUT:** 
Total Volunteer Hours: (Sum)
Attendees: (list of check-ins, display first_name last_name)

**Comment by kelseylc** [comment]
Matt, I'm not sure what kind of asset library you're using for the dashboard. If you have something like a closed lock/open lock symbol, I think that would be great to show open/closed status. Otherwise, a basic Check mark vs. Close symbol (X) will suffice.

**Comment by juliagab56** [comment]
Outdated issue
