### ISSUE TITLE
Create new events error

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#878]
### Overview
It appears that new checkin events are not being created from recurring events and an error is being console logged every time it tries. 

### Action Items
Fix the error in create event.

<details>
<summary>Create Event Error</summary>
Running createEvent:  {"name":"Not Today Team Meeting","hacknight":"Online","eventType":"Team Meeting","project":{"recruitingCategories":[],"partners":["Seeking"],"managedByUsers":[],"_id":"5edeb5c9ce228b001778fad3","name":"Not Today","description":"Not Today is an app intended to help people wait out periods of suicidal thinking without acting on their thoughts.","githubIdentifier":"202051333","projectStatus":"Active","location":"Westside","githubUrl":"https://github.com/hackforla/not-today","slackUrl":"https://hackforla.slack.com/archives/CMDEH9478","googleDriveUrl":"https://drive.google.com/drive/folders/1dRIYWa_JiBhKOVNKLJG-t7_8s_LjtKDC","googleDriveId":"1dRIYWa_JiBhKOVNKLJG-t7_8s_LjtKDC","hflaWebsiteUrl":"https://www.hackforla.org/projects/not-today","videoConferenceLink":"","lookingDescription":"- Flutter \n - Mobile Development UI/UX \n - Empathy and sensitivity with subject material and end users","createdDate":"2020-06-08T22:03:53.063Z","__v":0},"date":"2022-01-19T03:00:00.730Z","startTime":"2022-01-19T03:00:00.730Z","endTime":"2022-01-19T04:00:00.730Z","hours":1,"location":{"city":"Los Angeles","state":"CA","country":"USA"}}

REQUEST SHOULD CONTAIN CUSTOM HEADER BUT IT ISN'T FOUND

POST /api/events/ 401 0.194 ms - 12

FetchError: invalid json response body at http://localhost:4000/api/events/ reason: Unexpected token U in JSON at position 0
    at /Users/davidrubinstein/DigitalProjects/HfLA/VRMS/backend/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createEvent (/Users/davidrubinstein/DigitalProjects/HfLA/VRMS/backend/workers/createRecurringEvents.js:146:33)
    at async filterAndCreateEvents (/Users/davidrubinstein/DigitalProjects/HfLA/VRMS/backend/workers/createRecurringEvents.js:102:37)
    at async runTask (/Users/davidrubinstein/DigitalProjects/HfLA/VRMS/backend/workers/createRecurringEvents.js:159:9) {
  type: 'invalid-json'
}
undefined
Today's events are created
</details>

### Resources/Instructions
I believe that this is the relevant file: 
/backend/workers/createRecurringEvents.js

This may be related to issue #273 , so check that out.

**Comment by WalterT-MK** [comment]
### Progress:
still cannot reproduce the error. Able to create new events using postman.  
### Blockers:
Unable to identify the problem and reproduce the error. 
### Availability:
N/A
### ETA:
cannot determine

**Comment by WalterT-MK** [comment]
### Progress:
the error occurs when making get request to `/api/events`, when the response code 401, and when using Postman, the response is `401 Unauthorized`. The custom header is not what causes the problem. 
### Blockers: 
Maybe it is causedd by the database?
### Availability:
N/A
### ETA:
hopefully finished by end of this week

**Comment by WalterT-MK** [comment]
### Progress:
The error occurs due to unable to read from `.env` file. 
`headerToSend` from `createRecurringEvens.js` is reading `.env` file locate at `vrms/client/`'s `.env`. 
Change `process.env.REACT_APP_CUSTOM_REQUEST_HEADER` to `process.env.CUSTOM_REQUEST_HEADER` solved the problem. 
### Blockers:
When running frontend and backend together using `npm run dev` at `vrms/`, `process.env.REACT_APP_CUSTOM_REQUEST_HEADER` is using the correct value, this is due to `REACT_APP_CUSTOM_REQUEST_HEADER` and `CUSTOM_REQUEST_HEADER` sharing the same value at different `.env` files. Thus, the problem will not occur when running the frontend & backend together. 
When using `npm run dev` at `vrms/backend/`, the problem occurs.  
### Availability: 
ready to accept another ticket.
### ETA: 
finished

**Comment by jbubar** [comment]
Can we search through the entire backend and see if there are any similar mistakes? - Shaun's idea
