### ISSUE TITLE
Create issues for addditions and subtractions to Create Events module

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/VRMS#879]
### Overview
This is a placeholder for brainstorming fixes.  I will then create issues for each of these items.  These will all have a dependency of #570 

### Action Items

- [ ] Think of things to fix, add or subtract
- [ ] Fix, add or subtract them

### Resources/Instructions
Issue #570 
PR #859 

This issue will at some point be involved in how to name events
https://github.com/hackforla/VRMS/issues/768

Also, let's be sure to check out the plans for people depot so that whatever we do here will be in alignment

And here are the vrms mockups:
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23726%3A2254

**Comment by drubgrubby** [comment]
- [x] When creating a new event it should focus on the event after it's been created, along with some feedback like "new recurring event created". 
- [x] When you update a meeting give feedback like "You have successfully updated this event", or maybe "success". 
- [x] Give feedback when an item is deleted.

**Comment by ExperimentsInHonesty** [comment]
Project list should differentiate between CoP meetings and Project Meetings

    311 Data
    Access the Data
    BallotNav
    Brigade Organizers Playbook
    Civic Tech Index
    Civic Tech Structure
    Community of Practice: Marketing
    Community of Practice: Product Management
    Community of Practice: Software Engineering
    Community of Practice: UI/UX
    Data Science Team
    Design Systems
    Engage
    Expunge Assist
    GreenEarthOS
    Hack for LA Marketing Team
    Hackforla.org Website
    HelloGOV
    Home Unite Us
    LA TDM Calculator
    Lucky Parking
    New Schools Today
    Not Today
    Onboarding
    Open Community Survey
    Operations Group
    Undebate
    VRMS
    Write for All™
    Youth Justice Nav

**Comment by drubgrubby** [comment]
List existing meetings. Click to edit specific meeting.

**Comment by drubgrubby** [comment]
On project edit page, show a list of current meetings with an edit link.  When the edit link is clicked it will open the project for editing. 

https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23726%3A2254

**Comment by ExperimentsInHonesty** [comment]
Initial meeting type dropdown with:
Team meeting
Onboarding

That would trigger a secondary list with the following: 
All Team 
Data Science
UI/UX Design
UI/UX Design & Research
UI/UX Research
Engineering All
Engineering Front End
Engineering Back End
PM
PM & Org
Other

From this we will create logic for meeting name in the future. 

Ex:
Team Meeting -> All Team = VRMS All Team meeting (or something like that)

**Comment by drubgrubby** [comment]
No longer able to edit the meeting name.  It will be created from above comment.  Remove 'meeting' from the meeting name

**Comment by drubgrubby** [comment]
Validation

Meeting Name: other - 30 characters
Description: Optional. (this is the place to say: (examples) - limit 60 characters
Require videoconference link
