### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#9]
### Overview
Update the project wiki to include anything required for the current milestone

### Dependency
When we get to the end of MVP and have something to document, or when we get more clarity on the code

### Action Items

- [x] Use hackforla website wiki as an example to build out our wiki
   - [x] Gather info
- [ ] Update the project wiki per findings
   ~- [ ] Review with Bonnie~

### Resources
[Hack for LA website wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

**Comment by switchzer0** [comment]
Update: have made non-technical updates to wiki to ensure information is useful, current. Next steps to track down technical updates from various team members as needed
Blocks: time from @alex-anakin to identify additional technical areas for improvement
Availability: most days
ETA: December 1

**Comment by switchzer0** [comment]
superseded and completed via other tix
