### ISSUE TITLE
Build "Add Event"  page

### ISSUE THREAD

**Issue by kelseylc** [hackforla/VRMS#92]
## Description
As an Admin user, I want to be able to create a new Event on the fly, regardless of event type (hack night, conference, summit, weekend meetup, etc.). I should be able to add a new event to the DB from the VRMS admin dashboard so that we can check-in users, track volunteer hours (custom to the event), and so on. 

A new event may or may not be a hacknight, and may include "sessions" which is why there is the below dependency.

## Dependency
#64 - add new fields to the "events" table (event_type, session)
Needs User Access Levels in system to be able to identify who can add an event

## Acceptance Criteria

**Comment by kelseylc** [comment]
Ticket not complete, still need to hash out requirements before moving to prioritized backlog.

**Comment by ExperimentsInHonesty** [comment]
Progress: Created reusable UI components for the forms, next steps are debugging, and getting the USER ID for the owner of the event
Blocks: none
Availability: Thurs-weekend
ETA: 4/6

**Comment by ExperimentsInHonesty** [comment]
Progress: got all the UI components created, and CSS done.  Next steps are: Linking it up to the backend 
Blocks:  Prepping for an interview
Availability: unkown.  Assigning Matt to help
ETA: 4/13

**Comment by sarL3y** [comment]
Progress 4/13: Need to create the proper routes for adding both events and recurring events. 
Blocks: None
ETA: This week

**Comment by ExperimentsInHonesty** [comment]
@Jonathanko52 working on routes.  we will get update from matt next week.

**Comment by sarL3y** [comment]
Progress 4/27: Jonathan removed CSS package 'classnames', still needs routes in backend
Blocks: None
ETA: This week

**Comment by shiningjustice** [comment]
Progress: Everything should be ready, just need to test the connection  
Blocks: Need to be added as an admin to test that events are added correctly. Will talk to Matt about this.
ETA: Early this week

**Comment by shiningjustice** [comment]
Progress: Ready after PR #155 is merged
- Added new fields per changes to event model (`videoConferenceLink`, `projectId` and some date fields) and per the added recurringEvents model 
- Tested connection, works! Bug that prevented redirecting after success delayed this a bit

**Comment by shiningjustice** [comment]
Progress: Made revisions per Matt's review (see comments in PR #155 for details)
Blocks: Pending general authentication being worked out for front end (admin must "own" projects before we can create events for it). Auth pending db migration/finalization
ETA: See blocks

**Comment by juliagab56** [comment]
Outdated issue
