### ISSUE TITLE
Refactor Admin Dashboard

### ISSUE THREAD

**Issue by sarL3y** [hackforla/VRMS#94]
### Overview
The admin dashboard needs to be compartmentalized and future-proofed. 

### Action Items
* [x] Research and propose requirements needed to refactor the admin dashboard
* [x] Modularize components

**Comment by ExperimentsInHonesty** [comment]
Progress: updated 2 of 3 components to make them more modular.  Still need to update functions.
Block: Data being pushed into the donut chart container component not being updated
Availability: plenty
ETA: next meeting - Monday 4/6
