### ISSUE TITLE
Research Curated User Journeys

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/VRMS#95]
### Overview
Identify features for a curated user journey.

### Action Items
Look at all personas on the personas board
Look at the VRM board

**Comment by ExperimentsInHonesty** [comment]
Progress: Reviewed the personas
Blocks: none
Availability: after work all week
ETA: 4/6

**Comment by Rankazze** [comment]
Progress:  Reviewed the user stories and added some cards.  Added cards to VRMS Research too.
Blocks: none
Availability: n/a
ETA: done
