### ISSUE TITLE
Meeting time change request for Design Systems All team meeting

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/VRMS#964]
### Overview
We need to change the team meeting time for Design Systems **team weekly meeting and the UX/UI meeting** so it will appear correctly on hackforla.org

### Is your team meeting team already displayed on hackforla.org?
- [x] yes
- [ ] no

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):

- [x] **Design System, Team meeting, Monday 5:30pm, 1 hour.** (this is the time that needs to be updated)

- [x] **Design System, UX/UI meeting, Tuesday 6pm, 1 hour.** (this is the time that needs to be updated)

Our other meeting is correct:
- Design System, Research meeting, Tuesday 11am, 1 hour.

### What is your project page URL?
https://www.hackforla.org/projects/design-systems

### Who should we contact on your team (via Slack) for user acceptance testing
Slack Channel #name: Design-System
Slack @handle: hanastevenson
<hr />

**Comment by drubgrubby** [comment]
@Hanastevenson : I have updated the Design System meetings in the database.  Please confirm that the time are correct. 

https://www.hackforla.org/events/
